### ISSUE TITLE
Missing libgnutls30 causing problems for some Proton games

### ISSUE THREAD

**Issue by dreamer** [ValveSoftware/steam-runtime#101]
For reference, see latest comments in ValveSoftware/Proton#225

At the moment, steam runtime provides only libgnutls 2.12.14 with soname 26. It's very, very old - causing connectivity issues in some titles (some reports indicate, that it's SSL-related [[1]](https://www.reddit.com/r/SteamPlay/comments/9m5bbd/ssl_error_with_truckersmp_and_proton/)).

Replacing binary with newer version with soname 30 resolves connectivity issues (and probably avoids some security problems), at the risk of introducing crashes due to newer ABI version.

Because only this old version is provided by Steam Runtime, and Proton is compiled with access to soname 26 only, old version is preferred even if newer gnutls is provided by host OS (you can verify this by starting game in Proton and running `lsof -p <pid> | grep gnutls`). Therefore completely fixing this issue will probably require releasing update to runtime and rebuilding Proton.

I tried to prepare PR for either libgnutls28 or libgnutls30 to accompany this issue, but building runtime reports error:

> ERROR: Package libgnutls30 not found in Packages file http://repo.steampowered.com/steamrt/dists/scout/main/binary-amd64/Packages

So someone with access to repo.steampowered.com needs to work on this.

**Comment by smcv** [comment]
gnutls28 is a separate source package, so the two can probably coexist, as long as one or the other is patched to not produce libgnutls-openssl27 and gnutls-bin.

**Comment by nanonyme** [comment]
Might not be that simple. It also breaks on systems where system has gnutls30 with prefer system libraries enabled

**Comment by nanonyme** [comment]
This seems to me to be a bug in Proton or its packaging of Wine. You cannot just replace gnutls28 with gnutls30 in runtime without excessive amounts of regressions

**Comment by dreamer** [comment]
@nanonyme no-one suggested replacing it and pretending it's different ABI in this issue? It's only about adding gnutls with ABI version 30 in steam runtime. .26 can still be there alongside. .2**8** is not part of steam runtime either - I only tried to add it to packages.txt (because I saw, that it exists in Ubuntu version serving as basis for steam runtime), but it didn't work.

@smcv I *think* libgnutls-openssl27 and gnutls-bin are not part of steam runtime.

**Comment by nanonyme** [comment]
@dreamer I'm *still* being sceptical here since as said, it's still broken if host has gnutls30. What *actually* fixed things was when people made a symlink gnutls.so.26->gnutls.so (which effectively is a symlink to gnutls.so.30) based on the original linked issue.

**Comment by nanonyme** [comment]
This workaround "sudo ln -s /usr/lib/libgnutls.so.30.14.11 /usr/lib/libgnutls.so.26" explicitly is about lying that you have libgnutls26 when you in reality have libgnutls30. You can easily find it in the original linked issue. I don't understand at all why that would make things better instead of worse.

**Comment by Zeioth** [comment]
I can confirm this issue. This is the workaround I'm using right now:
https://github.com/ValveSoftware/Proton/issues/225#issuecomment-425778539

**Comment by dreamer** [comment]
@nanonyme again, no-one is suggesting implementation of workaround here. We want real gnutls.so.30 to be built and included in steam runtime.

**Comment by nanonyme** [comment]
Again you're missing the point. It doesn't want gnutls30 but gnutls26. Yes, you could probably add the gnutls devel packages for gnutls30 into runtime to fix along with libraries

**Comment by dreamer** [comment]
@nanonyme maybe I am miscommunicating here somehow:

Problem is fixed by libgnutls.so.30 but Wine bundled with Proton prefers to load libgnutls.so.26. At the moment it loads libgnutls.so.26 provided by steam runtime (as @aeikum confirmed and you can verify it by running `lsof` on running process), but it prefers to use libs provided by host, if they are available (sensible). Version .26 is usually NOT available on any modern distro, so simply creating symbolic link named .26 pointing to .30 forces Wine to use .30. My intention with this issue is that both .26 and .30 will be provided by steam runtime - preferrably with .30 as default one, so Proton and future native linux games won't be affected by this problem.

> It doesn't want gnutls30 but gnutls26

By "it" I presume Wine. Wine doesn't "want" .26 nor .30 (it doesn't care), it just loads the version pointed by configure at compile time.

If my understanding here is incorrect at any point, then point it out, please (maybe I am wrong and don't realize it).

Also, what we didn't verify yet - we don't know if the problem keeps occuring with the last version supporting soname .26. Steam runtime provides 2.12.14 (released in 2011) while the last version is 2.12.23 (released in 2013) ([source](https://www.gnutls.org/abi-tracker/timeline/gnutls/)).

**Comment by dreamer** [comment]
Just discovered, that this issue affects all of Uplay titles - they need both 32 bit and 64 bit version of newer gnutls (plus corefonts). According to [pcgamingwiki](https://pcgamingwiki.com/wiki/The_Big_List_of_3rd_Party_DRM_on_Steam#Uplay) there are 69 Uplay titles on Steam at the moment.

**Comment by h1z1** [comment]
Somewhere I have a bug report about it.  This is going to continue being more of a problem as sites knowingly or not (ie CDN frontend), deprecate older security.  TLS 1.1/1.2 and SSLv3 for example.

**Comment by ronlaws86** [comment]
Why not just fix proton to use an up to date version of TLS instead of packaging an old version that is slowly becoming incompatible and gets ignored anyway? the workaround mentioned about linking the host version 30 to 26 works for some aforementioned games but as stated may break others. Short term fixes are nice, but this is only ignoring the core issue as it becomes more of a problem with time.

**Comment by dreamer** [comment]
@ronlaws86 Read issue description. This issue is **NOT** about linking - it's exactly about updating steam runtime to provide current version of gnutls. Symbolic links are only hacks that users can deploy on their own until the issue is fixed.

Steam runtime will need to provide both old and new version: old for existing native linux games and new for Proton and future native linux games.

**Comment by Leopard1907** [comment]
I want to play Quake Champions via native Linux Client before that game dies :(

**Comment by Leopard1907** [comment]
Well , i think Bethesda did something good for us. It works oob now. I'm playing it for five days in a row.

**Comment by Bleuzen** [comment]
Is this fixed / implemented now?
https://github.com/ValveSoftware/steam-runtime/commit/ca34a8df9db1c3c0ce71aa96c64cd5606135f693

**Comment by TTimo** [comment]
@Bleuzen the work is still in progress and being tested internally. expect some news soon

**Comment by TTimo** [comment]
This is fixed in the latest steam beta runtime.
