### ISSUE TITLE
Vulkan includes/libs not installed when the steam-runtime chroot is created?

### ISSUE THREAD

**Issue by izoprene** [ValveSoftware/steam-runtime#105]
Hi, I'm currently building a Vulkan based game on Ubuntu 16.04.1 with the 16.04 repo libvulkan-dev & libvulkan1 packages. I've also downloaded SDL2.0.8 and compiled that into my source tree instead of using the Ubuntu 16.04 SDL2 packages because Vulkan SDL2 support is [disabled in that release](https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1740517) at the moment, but it will apparently be [fixed in 18.10](https://phoronix.com/scan.php?page=news_item&px=Ubuntu-18.10-SDL2-Build-Vulkan). All this is compiling and running fine.

Now, today I cloned the steam runtime from github, created the amd64 version of the steamrt chroot and tried to run my makefile in that steamrt chrooted environment like this: ~/myprojectpath/src$ schroot --chroot steamrt_scout_amd64 -- make -f my-makefile, but I'm getting an include error on '#include <SDL_vulkan.h>'.

So I entered the chrooted steamrt environment (schroot --chroot steamrt_scout_amd64) and I cannot see any vulkan include files. But the strange thing is, the Git clone references **libvulkan1 libvulkan-dev** in steam-runtime/packages.txt, and **vulkan install** in steam-runtime/sourcepkgs.list. So it looks like the vulkan includes/libraries should have been installed but they haven't.

Am I missing something here???

**Update:**
I deleted the steam-runtime git local repo and steam-rt chroot environment and started over by re-cloning the steam-runtime Git repo again.

Then I chose the vebose option when running the build script: sudo ./build-runtime.py -verbose like this:
symbols :  False
verbose :  True
repo :  http://repo.steampowered.com/steamrt
source :  False
beta :  False
debug :  False
runtime :  */*/*/steam-runtime/runtime
Creating Steam Runtime in */*/*/steam-runtime/runtime
Downloading amd64 binaries from http://repo.steampowered.com/steamrt/dists/scout/main/binary-amd64/Packages

The terminal output only shows libvulkan1 being downloaded, with the deb in the steam-runtime/newpkg/binary/amd64/libvulkan1_1.03...

But this non-beta repo (http://repo.steampowered.com/steamrt/dists/scout/main/binary-amd64/Packages) only lists libvulkan1, so fair enough, libvulkan-dev isn't going to be installed.

So, I erased everything and did the entire thing again with the --beta switch activated: sudo ./build-runtime.py --beta --verbose like this:
symbols :  False
verbose :  True
repo :  http://repo.steampowered.com/steamrt
source :  False
beta :  True
debug :  False
runtime :   */*/*/steam-runtime/runtime
Creating Steam Runtime in */*/*/steam-runtime/runtime
Downloading amd64 binaries from http://repo.steampowered.com/steamrt/dists/scout_beta/main/binary-amd64/Packages

... with exactly the same results in the terminal, just libvulkan1 being downloaded.

But the strange thing is, this scout_beta repo (as above - http://repo.steampowered.com/steamrt/dists/scout_beta/main/binary-amd64/Packages) DOES list libvulkan-dev, vulkan-utils and libvulkan1, yet it still isn't being downloaded with the build-runtime.py --beta script.

As a last resort I uninstalled everything again, ie the steam-runtime git local repo and steam-rt chroot environment and even the ubuntu libvulkan-dev, libvulkan1 and vulkan-utils that I previously installed from the Ubuntu 16.04 repos, just to be sure there were no conflicts.

I re-cloned the steam-runtime Git repo again, rebuilt the runtime with --beta --verbose (sudo ./build-runtime.py --beta --verbose), and libvulkan-dev wasn't downloaded as checked in the terminal output, then I set up a new steam-rt chroot (sudo ./setup_chroot.sh --amd64) and confirmed that libvulkan-dev was not installed to that chroot.

It says in the steam-runtime readme.md 'This chroot environment contains development libraries and tools that match the Steam Runtime.', and libSDL2-dev is being installed so it's half way there.

Any thoughts on why libvulkan-dev is not being installed into the steam-runtime chroot would be very much appreciated. :-)

**Comment by TTimo** [comment]
Hello @izoprene

I'm checking some of the internal reports we have about package versions, and the steam clients report having 1.1.73+dfsg-1+steamosc2 of the vulkan source package in their runtime (which means libvulkan-dev, libvulkan1 and vulkan-utils binary packages).

This also matches what is in our scout and scout_beta apt repositories.

Have you tried explicitly installing the needed packages via apt in your chroot?

**Comment by izoprene** [comment]
Hi TTimo,
I've tried building a non-beta and beta steam-runtime then their chroot counterparts. But when I enter either chroot, I can 'apt-get install libvulkan1' (connects to http://repo.steampowered.com/steamrt/ scout/main libvulkan1 amd64 1.0.3~git20160215-0.1+steamos5+srt1 [55.0 kB]). But libvulkan-dev fails to install with 'Unable to locate package libvulkan-dev'. This is also after a 'sudo apt-get update' too.

It looks like libvulkan-dev is not available to the build chroot through the steam repo?

**Comment by kisak-valve** [comment]
Hello @TTimo, @izoprene  looks like a little confusion happened here between http://repo.steampowered.com/steamrt/pool/main/v/vulkan/ and http://repo.steampowered.com/steamos/pool/main/v/vulkan/ and scout vs scout_beta.

Looks like http://repo.steampowered.com/steamrt/dists/scout/main/binary-amd64/Packages is being picked which would match this behavior. Please try using the Scout_beta again and let's go from there.

**Comment by izoprene** [comment]
Hi kisak, I'm confused too! lol

So first I create a local copy of the steam-runtime using Git...
'git clone https://github.com/ValveSoftware/steam-runtime.git'
This creates the steam-runtime directory in my home directory.

Now, previously, I've tried running 'sudo ./build-runtime.py --beta' which outputs this on the terminal...
```
Creating Steam Runtime in /home/matt/steam-runtime/runtime
Downloading amd64 binaries from http://repo.steampowered.com/steamrt/dists/scout_beta/main/binary-amd64/Packages
```
...which also creates 'newpkg' in the steam-runtime directory. I presume I can now test applications in the scout-beta runtime environment. But I first need to build my application in the steam runtime schroot.

Also previously, I would then run 'sudo ./setup_chroot.sh --amd64' which creates the chroot, but as per my last post, I was unable to install libvulkan-dev inside this chroot.

Today I've skipped 'sudo ./build-runtime.py --beta' entirely and just run 'sudo ./setup_chroot.sh --amd64' straight after the git clone because I thought the 'sudo ./build-runtime.py --beta' HAD to be run first? Is this correct?

So anyway, today I've just run 'sudo ./setup_chroot.sh --amd64' and got this terminal output... 
```
Creating /var/chroots/steamrt_scout_amd64...
Creating /etc/schroot/chroot.d/steamrt_scout_amd64.conf...
[steamrt_scout_amd64]
```
also I see the scout repos being referenced...
```
Get:2 http://repo.steampowered.com scout InRelease [8188 B]
Get:5 http://repo.steampowered.com scout/main Sources [80.5 kB]
Get:7 http://repo.steampowered.com scout/main amd64 Packages [237 kB] 
Get:8 http://repo.steampowered.com scout/main i386 Packages [236 kB]
Ign http://repo.steampowered.com scout/main TranslationIndex                   
Ign http://repo.steampowered.com scout/main Translation-en
``` 
etc etc

Notice the 'setup_chroot.sh --amd64' is  referencing scout not scout-beta. Is there a switch or something to force setup_chroot.sh to create the scout-beta version (with lib-vulkan installed or the ability to apt-get install libvulkan-dev)?

Also could you tell me what 'scout' actually is? I can't find any explanation of 'scout' anywhere.

Thanks.

**Comment by izoprene** [comment]
**### Issue solved:**
Using a fully updated Ubuntu 18.10 (which has the [18.04 SDL2.0.8 Vulkan support not enabled ](https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1740517) problem fixed):

1) Clone a local copy of Steam runtime repo:
`git clone https://github.com/ValveSoftware/steam-runtime.git`

2) In the local repo, build the Steam beta runtime:
`./build-runtime.py --beta --verbose`
(Python script created: /steam-runtime/runtime, and downloaded amd64 binaries from http://repo.steampowered.com/steamrt/dists/scout_beta/main/binary-amd64/Packages)

3) Setup steam runtime chroot:
`bash ./setup_chroot.sh --beta --amd64`
**Note:** readme.md says setup-chroot.sh, it should be setup_chroot.sh, ie change hyphen to an underscore.
(bash script created: /var/chroots/steamrt_scout_beta_amd64)
But **no Vulkan dev libraries** were installed.

4) Enter chroot environment:
`schroot --chroot steamrt_scout_beta_amd64`

5) Inside the chroot environemt, update and upgrade package lists:
```
sudo apt-get update
sudo apt-get upgrade
```
But **still no** libvulkan-dev!

8) Inside the chroot, install libvulkan-dev manually via apt:
`sudo apt-get install libvulkan-dev`
libvulkan-dev & libvulkan1 installed.
**Note:** Apt uses the steam beta repos: http://repo.steampowered.com/steamrt/scout_beta/
libvulkan1 amd64 1.0.54.0+dfsg1-1+steamos1+srt1 [83.2 kB]
libvulkan-dev amd64 1.0.54.0+dfsg1-1+steamos1+srt1 [136 kB]

9) Back outside the chroot environment, compile Vulkanised SDL2 application source in the chroot via schroot:
`schroot --chroot steamrt_scout_beta_amd64 -- make -f mymakefile`

Success!

**Comment by TTimo** [comment]
Great! So no problem on the steam-runtime side then, just usage questions.

FYI - the steam beta client for linux just updated with a new runtime, we are going to propagate the matching packages to apt for scout and scout_beta, which will include an update to the vulkan headers.

**Comment by izoprene** [comment]
Hi TTimo,
That's great thanks, I'll look forward to that as I'm totally focused on _native_ Linux game dev, not just relying on Proton/DXVK etc.

I do have a issue with using the steam runtime's run.sh script though which I've opened as [issue 107.](https://github.com/ValveSoftware/steam-runtime/issues/107)

Thanks again.
