### ISSUE TITLE
Possible problem running the steam runtime's run.sh script

### ISSUE THREAD

**Issue by izoprene** [ValveSoftware/steam-runtime#107]
I have a problem using the run.sh in the runtime directory in steam runtime. I'm using Ubuntu 18.10 64bit.

I can compile using the steamrt chroot no problem, and when I execute the resulting binary in a normal terminal I can see that it was compiled with SDL2.0.6 (the chroot's SDL2 version) and is linking to Ubuntu 18.10's SDL2.0.8 shared libraries. My app generates a logfile showing SDL2 compilation and version information via SDL_VERSION() & SDL_GetVersion().

```
SDL version, compiling, linking & revision info
Compiled with SDL version - Major: 2
Compiled with SDL version - Minor: 0
Compiled with SDL version - Patch: 6
Linked with SDL version - Major: 2
Linked with SDL version - Minor: 0
Linked with SDL version - Patch: 8
Revision: hg-11914:f1084c419f33
Revision number: 11914
```

As the point of the steam runtime is an isolated environment for game development, I'm trying to run my application in the steam runtime by copying the same chroot compiled binary to the /steam-runtime/runtime directory where run.sh lives. Then I open a terminal inside /steam-runtime/runtime and run this command:
`bash ./run.sh ./linuxgame`

But I get the same result where my logfile says that the binary is compiled with SDL2.0.6 (correct) & Linked with SDL2.0.8. This makes me think that my binary is using the Ubuntu 18.10 SDL2 libs and not the runtime versions.

Running the following command does show that the load library path is indeed the path where I installed built the steam runtime:
`bash ./run.sh --print-steam-runtime-library-paths`

I can't seem to find a command that can tell me what SDL version the dynamic libraries are in the the steam runtime.

Am I doing something wrong or is the steam runtime using SDL2.0.8 runtime libs and the chroot using SDL2.0.6 dev libs?

**Comment by TTimo** [comment]
the beta client runtime was just updated and uses SDL2 2.0.8
the scout and scout_beta apt repositories have updated as well

the main steam client will still be on 2.0.6 for a while until beta is promoted.

you have several options:

- Continue using your current chroot and produce binaries that were compile time linked against 2.0.6. They will work and continue to work moving forward.

- apt update your chroot and get 2.0.8. Note that you can't go back. And if you rely on specific features that are in 2.0.8 and not 2.0.6 you'll have to use the steam beta client until it is promoted. There is not much reason to do this unless you are waiting on a specific bug fix in the new version.
