### ISSUE TITLE
provided x11 libs have been useless for ages

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#108]
(did not check for the installer) the steam runtime provided x11 libs have not been able to run the client for ages because it depends on non compatible underlying lib (mesa GL).

**Comment by h1z1** [comment]
Where are you seeing this?

**Comment by sylware** [comment]
Did a clean re-install: the installer without libs pinning, runs into the DRI3 symbol issue unless using the DRI3 disable env variable.
Once the steam client was downloaded by the installer, if no lib pinning is done, the client crashes, which means the provided libs are useless, and that has been the case for ages.

**Comment by TTimo** [comment]
Not enough actionable information. Feel free to re-open with test case and reproduction information (including affected distributions, observed vs expected results etc.)

**Comment by sylware** [comment]
I did figure out what's wrong: in my humble opinion, valve is not the culprit.
That said, the steamruntime libs are really useless on many distros without
pinning. They will work only on distros where the package integrators did hack
the build system kludges of libs from the gfx stack (or the products of
linking).

Because: In many gfx stack lib packages, the elf rpath will be added by many
"build system kludges", then when steamui.so loads, there are several
mismatches of libs between system libs and steamruntime libs, mainly because of
libGL, but also because of some other dependencies.

Then the real culprits are those "build system kludges", which in many build
scenarios, will add the elf rpath option.

That's why, for proprietary binaries on gnu/linux distros, the line between
"system libs" and "distributed libs" is blury which makes things tricky.
To make things rock solid: except the glibc, everything should either be
statically linked, or dynamically loaded with associated symbol lookup.

For gnu/linux users, a warning should be added to tell that if some system
libs, which happen to be used by steam, were linked with the rpath option,
steam may not run without proper lib pinning.
