### ISSUE TITLE
run.sh usage

### ISSUE THREAD

**Issue by izoprene** [ValveSoftware/steam-runtime#122]
Hi, I'm trying out the new steam-runtime repo and I think I may have a problem using run.sh to run my game in the steam runtime. I'm using Ubuntu 18.10 64bit.

Steps taken:

- git clone https://github.com/ValveSoftware/steam-runtime.git

- ./build-runtime.py  --verbose

- bash ./setup_chroot.sh --amd64

- **schroot --chroot steamrt_scout_amd64 -- make -f makefile** to create a build of my game using the schroot (I had to go into the chroot and apt install libvulkan-dev first though as I'm using Vulkan).

- I copied the resulting binary 'mygame' into the steam-runtime/runtime directory and opened a Terminal there.

**Note:** The binary created with the chroot is a different byte size to the binary created in the normal way using my system libs and build environment.

Then in the Terminal I execute the command **./run.sh ./mygame** and my game starts up and closes cleanly and produces a log.txt file of all activities (SDL2 version, changelogs etc, SDL2 window info, system RAM, Vulkan Instance, layers, extensions, devices etc).

The problem is that logfile output is identical to the log created by a normal make in my home/username/projects directory (same size in bytes and I checked manually). It's like as if run.sh isn't actually executing my game in the runtime at all, and instead executing it using the normal system libs.

Is this correct?

**Comment by Plagman** [comment]
I've not used the run.sh script from the SDK in a while; you can try running it from Steam's run.sh, should be in 
~/.steam/root/ubuntu12_32/steam-runtime/run.sh by default.

**Comment by izoprene** [comment]
Hi Plagman, I copied the mygame binary (built with the Steam chroot) to ~/.steam/root/ubuntu12_32/steam-runtime and opened up a Terminal there. Executing the command ./run.sh ./mygame does produce a different log.txt where the difference is the SDL2 HG Revision and Revision Number. Everything else is identical.

Thank you for the tip, just one more thing, does this mean that the steam-runtime/runtime run.sh which is created with build-runtime.py is of less use than using the run.sh that gets installed with the Steam client?

(I assume that files pulled into steam-runtime/runtime by build-runtime.py are used to create the chroot, which of course is needed for building Steam apps with known (SteamRT) dependencies.)

**Comment by Plagman** [comment]
The runtime has support for using system libraries if they're newer than the ones provided by the runtime, so maybe you're seeing the same behavior because the libraries you're checking are newer on the host? Once your game is running through run.sh, you can look at `/proc/$gamePid/environ` with `strings` to see if LD_LIBRARY_PATH is properly set up to use the runtime.

You can't build with the runtime Steam ships, just run stuff, so the one you bootstrap is still needed for building. But if you're just testing, using the Steam copy is sufficient.

Note that you didn't have to copy your game around to test this, you can use run.sh from any working directory.

**Comment by izoprene** [comment]
> The runtime has support for using system libraries if they're newer than the ones provided by the runtime, so maybe you're seeing the same behavior because the libraries you're checking are newer on the host? 

That's probably true because I'm running a fully updated Ubuntu 18.10.

> Note that you didn't have to copy your game around to test this, you can use run.sh from any working directory.

I just tried executing the Steam client run.sh (~/.steam/root/ubuntu12_32/steam-runtime/run.sh) from my project build directory and it produced a log.txt file which is different to the log.txt from a normal build, as above in my previous comment, which is correct.

Thanks again!
