### ISSUE TITLE
Cannot enable VK_LAYER_LUNARG_standard_validation in Steam runtime

### ISSUE THREAD

**Issue by izoprene** [ValveSoftware/steam-runtime#123]
Hi all,
I have a work-in-progress SDL2 & Vulkan game engine which I'm developing on Ubuntu 16.04.5 LTS with the latest Steam runtime. I'm using the non-beta runtime with schroot for building my game, no problems. I can then run the game in the runtime using run.sh.

I did have to enter the amd64 chroot and install libvulkan-dev (with libvulkan1) to get the vulkan.h header etc.

Note: There are no SDL2 or Vulkan, runtime or dev libraries installed on my OS except in the Steam runtime,

The problem is that if I disable validation layers in my code, everything works fine: Create an instance, select a physical device, enumerate extensions, queue families, logical device etc.

If I enable validation layers at runtime using vkEnumerateInstanceLayerProperties() for VK_LAYER_LUNARG_standard_validation, there are zero layers found.

Looking into the Steam runtime file structure I can see:
~/gamedev/steam-runtime/runtime/amd64/usr/share/vulkan/explicit_layer.d/ has validation layers.
~/gamedev/steam-runtime/runtime/amd64/usr/share/vulkan/implicit_layer.d/ has none.

I've even tried copying the layer definitions from explicit_layer.d to implicit_layer.d but that made no difference. 

I know there is a way of changing the layer path using VK_LAYER_PATH env variable but I don't know how to make this work with run.sh or if it would help?

I suspect that if I were to install the lunarG sdk package [[https://packages.lunarg.com/](https://packages.lunarg.com/)] for Ubuntu 16.04 then it would fix this problem but I want to keep this OS clean and only use the Steam runtime to build and run my game against.

One more thing, my game's validation functions work perfectly if I install the LunarG Ubuntu packages into the main OS libraries and build as normal.

Thanks for any help!

**Comment by TTimo** [comment]
You can export a value for VK_LAYER_PATH before calling run.sh, it will be carried through.

**Comment by izoprene** [comment]
Hi TTimo, I did that before the executing run.sh and it worked, thanks.
