### ISSUE TITLE
Another lib incompatibility (Steam crashing after updating LLVM)

### ISSUE THREAD

**Issue by aladar42** [ValveSoftware/steam-runtime#135]
Steam now crashes because of LLVM update to version 8. Updating Mesa will update lib32-llvm to version 8, which crashes Steam on startup.

~ % LIBGL_DEBUG=verbose steam                              :(
/home/aladar/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
/home/aladar/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
Running Steam on arch  64-bit
/home/aladar/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/aladar/.local/share/Steam/steam.sh: line 823: /home/aladar/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
Installing breakpad exception handler for appid(steam)/version(0)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/aladar/.drirc: No such file or directory.
libGL: pci id for fd 8: 1002:67ff, driver radeonsi
libGL: OpenDriver: trying /usr/lib32/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib32/dri/radeonsi_dri.so
libGL: dlopen /usr/lib32/dri/radeonsi_dri.so failed (libLLVM-7.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL: pci id for fd 8: 1002:67ff, driver radeonsi
libGL: OpenDriver: trying /usr/lib32/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib32/dri/radeonsi_dri.so
libGL: dlopen /usr/lib32/dri/radeonsi_dri.so failed (libLLVM-7.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL: OpenDriver: trying /usr/lib32/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib32/dri/swrast_dri.so
libGL: dlopen /usr/lib32/dri/swrast_dri.so failed (libLLVM-7.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

**Comment by TTimo** [comment]
Do other OpenGL programs work? This log suggests your OpenGL drivers are broken at the OS level. Try glxgears / glxinfo etc.

**Comment by aladar42** [comment]
Yeah, right, my bad. Glxgears32 quits with the same error (libLLVM-7.so: cannot open shared object file: No such file or directory). So I guess thats a Mesa problem? llvm and llvm-libs are both installed.

**Comment by TTimo** [comment]
not familiar with arch sorry. closing - not a steam client issue
