### ISSUE TITLE
setup_chroot failed w/o clear error

### ISSUE THREAD

**Issue by codecat** [ValveSoftware/steam-runtime#139]
I get the following error when trying to run setup_chroot on Ubuntu 18.04:

```
ERROR: setup_chroot.sh just hit error handler.
  BASH_COMMAND is "sudo tee ${CHROOT_DIR}/${CHROOT_NAME}/etc/profile.d/steamrtproj.sh"
  BASH_VERSION is 4.4.19(1)-release
  pwd is "/home/nimble/dev/steam-runtime"
  PATH is "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/home/nimble/apps"

A command returned error. See the logfile: /tmp/steam-runtime-setup-chroot-XuX.log
```

Not sure what the exact error is, it doesn't tell me. Plus, the logfile mentioned is empty:

```
~/dev/steam-runtime (master ✔) ᐅ l /tmp/steam-runtime-setup-chroot-XuX.log
-rw------- 1 nimble nimble 0 dec 17 16:15 /tmp/steam-runtime-setup-chroot-XuX.log
```

The command I run is `./setup_chroot.sh --amd64` which used to always work properly before.

The file referenced (`/var/chroots/steamrt_scout_amd64/etc/profile.d/steamrtproj.sh`) does exist, is empty, and is owned by root:root.

**Comment by TTimo** [comment]
Thank you for your report. Issue should be addressed now, please test master again.

**Comment by codecat** [comment]
That fixed it, thanks! <3
