### ISSUE TITLE
build-runtime.py fails with Package not found on Ubunut 18.10

### ISSUE THREAD

**Issue by ewmailing** [ValveSoftware/steam-runtime#144]
I am trying to create a steam-runtime environment so I can build/test my games in it. I've been doing this for a couple of years now, but I haven't had to build a new steam-runtime environment in maybe 6 months to a year, and it appears some things have changed (specifically, the required --output switch requirement is new to me). Additionally, I have moved to a more recent version of Ubuntu (18.10).

The result is that I cannot get build-runtime.py to successfully finish. I get package not found for 4 packages:

./build-runtime.py --output=~/steam-runtime/runtime 

ERROR: Package libtasn1-6 not found in Packages files
ERROR: Package libgnutls30 not found in Packages files
ERROR: Package libnettle6 not found in Packages files
ERROR: Package libhogweed4 not found in Packages files

I tried using apt-get install to install packages with those names, but they seem to already be installed. So I'm not sure what to try next. Any ideas on how to get this built?

**Comment by TTimo** [comment]
Nevermind the log for `build-runtime.py`, I can reproduce.

If you use `--beta` you won't run into this issue. It will build a steam runtime for the current steam beta client though. The beta will be promoted to general availability in a few days so you should be fine.

There's still a bug though - paging @smcv who will probably know what's happening.

**Comment by smcv** [comment]
```
ERROR: Package libtasn1-6 not found in Packages files
ERROR: Package libgnutls30 not found in Packages files
ERROR: Package libnettle6 not found in Packages files
ERROR: Package libhogweed4 not found in Packages files
```

If you are not running with the `--strict` option (which is used when producing the official runtimes), then those error messages are not actually fatal, and the script should finish successfully. The test runtime will be incomplete (those libraries will be missing) but there's no way around that: whenever new libraries are added, we can't have a `packages.txt` that is correct for both the beta and the production version at the same time.

If you want to test with the production Steam Runtime, please get it from the production Steam client: that's the only way to guarantee that you are using exactly the same libraries that the Steam client would install for your users. The only reason to run `build-runtime.py` yourself should be if you want to use the beta libraries (in which case you need the `--beta` option), or if you are developing/testing modifications to the Steam Runtime.

In recent Steam Runtime versions you can unpack `manifest.txt` from the tarball, and use that with your favourite diff tool to compare what's in each version.

**Comment by ewmailing** [comment]
Thank you both. The --beta option did work.
But TTimo was correct that I was really after setup_chroot.sh instead. I thought I tried it before and it failed, but it worked now.

**Comment by ewmailing** [comment]
@TTimo, you mentioned the beta will become general release soon. I've read elsewhere it was possible to get newer compiler versions in the beta. Will updated versions of the compilers become available with the release?
