### ISSUE TITLE
Regression in setup_docker.sh, --extra-bootstrap argument broken

### ISSUE THREAD

**Issue by boltronics** [ValveSoftware/steam-runtime#147]
https://github.com/ValveSoftware/steam-runtime/commit/a7c6d17206d6e5f62d3fbb002fd43c3b85bb5bda#diff-528f7dc318b35dc8650e449b5d31e70fR140

@smcv shouldn't that be `--extra-bootstrap`?

The proton build system can no longer automatically be provisioned at the moment.
```
~/proton$ vagrant up
...
==> default: Running provisioner: shell...
    default: Running: inline script
    default: Cloning into 'steam-runtime'...
    default: !! Unknown option --extra-bootstrap
    default: !! Usage: ./steam-runtime/setup_docker.sh [--beta] [--extra-bootstrap FILE] -- {amd64|i386} [IMAGE]
    default: !! Unknown option --extra-bootstrap
    default: !! Usage: ./steam-runtime/setup_docker.sh [--beta] [--extra-bootstrap FILE] -- {amd64|i386} [IMAGE]
...
```

**Comment by smcv** [comment]
Yes, probably. I'll check.

**Comment by smcv** [comment]
Can I find the script that sets up the Proton build system somewhere? It would be good to run it in CI as a way to check that future changes haven't made it regress (it presumably exercises more of the code than my usual test setup does).

**Comment by boltronics** [comment]
Yes, it can be found [here](https://raw.githubusercontent.com/ValveSoftware/Proton/proton_3.16/vagrant-user-setup.sh). Thanks.
