### ISSUE TITLE
setup script is a bash only script

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#176]

**Comment by sylware** [comment]
In the new steam runtime, the setup script doing lib pinning is a bash only script. Please rename is setup.bash.
.sh is appropriate for posix shell script, which could run with a light and conservative sh interpreter like dash.
A middle ground approach: distribute your bash binary (statically linked if possible to make it robust). The clean way: .sh script with some binary helpers (usually coded using simple C)

**Comment by kisak-valve** [comment]
Hello @sylware, using `.sh` as a file extension is standard practice across all shell scripts. The interpreter needed for the script is determined by the shebang on the first line of the script. This is no different than any other project.

All major distros support Bash and it's not really worth the time to make sure that this script remains posix-compatible.

**Comment by sylware** [comment]
I don't agree: It hurts light distros working without bash (like mine), and
shut the door to any distros trying to drop obvious kludges and still would like to
play games.

With this reasoning, gnu/linux would not be worth the time and we should all run
windows. Not acceptable reason.

Technical steering should reduce pressure on gnu/linux distros by
avoiding to rely as much as possible on non video game core API/ABIs/software.

The only thing you should rely on is: 
	- elf loader, unfortunately with a glibc (libcs are not binary
	  compatible).
	- running x11/wayland "servers" (dynamically discovered).
	- video game core stuff: GL/vulkan/alsa/linux input (dynamically
	  discovered, not statically loaded).
	- a basic shell (for instance dash).
	- a conservative and as minimal as possible set of basic shell
	  commands.
	- don't hesitate to code helper binaries.

Expecting host installed massive kludge is slapping the door at alternative
gnu/linux distros, and forcing the use of massive and huge gnu/linux distros
down upon user throat.
	
I think I already wrote you that.

Not fair, but who said the world was a fair place.
