### ISSUE TITLE
latest lib pinning ignores system LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#177]

**Comment by sylware** [comment]
It seems the new setup.bash/sh which does lib pinning does only consider the output of /sbin/ldconfig which seems to ignore the user/system LD_LIBRARY_PATH

**Comment by kisak-valve** [comment]
Hello @sylware, this is a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5455. If you want that issue tracked over here, let me know and I'll transfer it over. There's no value in fragmenting the discussion.

Closing as a duplicate.
