### ISSUE TITLE
SteamOS big picture and desktop mode

### ISSUE THREAD

**Issue by noncopyable** [ValveSoftware/steam-runtime#188]
Hello again!

I am afraid this may not be the best place to ask this, feel free to close the issue.
Using steam-runtime prebuilt libraries and steamworks/.../ContentBuilder i was able to build for Linux but SteamOS desktop-mode and big-picture-mode gives this error:

`
"error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory"`

As far as i understand SteamOS and Linux use same build path.
https://partner.steamgames.com/doc/store/application/platforms/linux (Developing for SteamOS and Linux) has no extra steps for SteamOS.

What am i missing?

Thanks

**Comment by TTimo** [comment]
We would need more details, but it sounds like you need to be running your title in the Steam Runtime, and you are running it on the host directly instead.

Find the run.sh script (under ~/.steam) and run your title through it?

**Comment by noncopyable** [comment]
@TTimo this error is from build review, complete form is:

```
Failure:
Your build has failed our review because it fails to launch on SteamOS through Big Picture mode and Desktop mode. This may be due to a missing dependency. The Steam installation is expected to resolve all dependencies.

The app launches as intended on Ubuntu 18.04.1 LTS. If you need time to implement this fix, please update the SteamOS+Linux system requirements, making it clear the game currently only works on Ubuntu.

The following error can be found in the terminal:
"error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory"
```
As the review states same build runs on Ubuntu without issues. i can also debug the application on steam without issues but i do not know how to run in SteamOS locally.

**Comment by TTimo** [comment]
I suspect a missing `libsteam_api.so` is just a red herring.

We are building some tools that will help verify that a binary's dependencies are fully covered by the steam runtime. Can you DM me on Twitter or reach me directly some other way, we can have a closer look.

In the meantime, you can try using run.sh + ldd against your binary and see what dynamic dependencies may not be covered by the steam runtime. For instance here I'm doing this for TF2:

```
timo@phoenix ~/.l/s/S/s/c/Team Fortress 2> ~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ldd -r ./hl2_linux 
        linux-gate.so.1 (0xf7fce000)
        libtcmalloc_minimal.so.4 => not found
        libdl.so.2 => /usr/lib32/libdl.so.2 (0xf7f84000)
        libpthread.so.0 => /usr/lib32/libpthread.so.0 (0xf7f61000)
        libc.so.6 => /usr/lib32/libc.so.6 (0xf7d7a000)
        /lib/ld-linux.so.2 => /usr/lib/ld-linux.so.2 (0xf7fd0000)
```

(this test may not find anything wrong, but that's a step)

**Comment by noncopyable** [comment]
I do not have a twitter account, i sent you a mail @TTimo
