### ISSUE TITLE
Don't Starve Together (322330) doesn't launch with the NVIDIA proprietary driver

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#192]
Don't Starve Together (322330) does not launch whatsoever with Pressure Vessel enabled. A black window appears for a brief moment which then closes and Steam no longer says you are playing the game. Without Pressure Vessel the game works perfectly. 

System information: https://gist.github.com/Newbytee/c4a4142c60e9be6dddbb52ee8c03b4a4

**Comment by kisak-valve** [comment]
In a quick activation test, this game starts up on my Fedora 31 / r600 test box, but CURL has a hard time resolving addresses and can't play online. Possibly a compatibility issue with nVidia on Fedora.

**Comment by Newbytee** [comment]
> In a quick activation test, this game starts up on my Fedora 31 / r600 test box, but CURL has a hard time resolving addresses and can't play online. Possibly a compatibility issue with nVidia on Fedora.

Is there any log I could provide that might interest you? Tested again and still no dice.

**Comment by TTimo** [comment]
Thank you for your report. Could you update your system information once the container runtime has been installed? The one you provided was pulled before the depot was installed, so it reports `The Steam Linux Runtime container tool is not installed.`

**Comment by Newbytee** [comment]
> Thank you for your report. Could you update your system information once the container runtime has been installed? The one you provided was pulled before the depot was installed, so it reports `The Steam Linux Runtime container tool is not installed.`

![image](https://user-images.githubusercontent.com/4428753/68623974-057fde80-04d6-11ea-874d-02acc6814eb4.png)
It appears as installed here, however ...
![image](https://user-images.githubusercontent.com/4428753/68623986-0d3f8300-04d6-11ea-8e96-e956095b0cb7.png)
Not sure what's up with this. I've restarted Steam and checked for updates. Aside from this some games did work (such as Terraria and CS:GO), so unless they somehow reverted to using my system libraries it seems Pressure Vessel is working. 

Is there something else I need to do? I didn't install the Steam Linux Runtime manually for what it's worth, it seems it did this by itself.

**Comment by TTimo** [comment]
Thanks, others are running into the same problem, something's breaking the diagnostic tool from running in the container. Will fix.

**Comment by Newbytee** [comment]
Gave Don't Starve Together a spin inside Pressure Vessel on my laptop. My experience here mirrors kisak's, game launches successfully but is unable to connect to servers. 

Laptop system info: https://gist.github.com/Newbytee/e514631db8a86fe1e3714c1831366f98

**Comment by TTimo** [comment]
Thanks. In the meantime you can run the diagnostic tool by hand in the container with a command like this:

`~/.steam/steam/SteamApps/common/SteamLinuxRuntime/run-in-scout -- steam-runtime-system-info`

**Comment by Newbytee** [comment]
Here's the output from that command on my desktop (the PC where the game won't launch): [runtime-info.txt](https://github.com/ValveSoftware/steam-runtime/files/3833446/runtime-info.txt)

**Comment by TTimo** [comment]
See https://github.com/ValveSoftware/steam-runtime/issues/204 for "container tool is not installed" problems.

**Comment by soredake** [comment]
After the latest update game works now.

**Comment by soredake** [comment]
But without internet connection and sound.

log:
[dst-slr.log](https://github.com/ValveSoftware/steam-runtime/files/4585731/dst-slr.log)

**Comment by Newbytee** [comment]
> After the latest update game works now.

Are you by chance not using the proprietary NVIDIA driver?

**Comment by soredake** [comment]
@Newbytee https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae****

**Comment by Newbytee** [comment]
> @Newbytee https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae

Yeah, definitely seems that the game not launching is exclusive to the proprietary NVIDIA driver. Going by this you seem to be using an RX 560 with amdgpu?

**Comment by soredake** [comment]
Yes.

**Comment by soredake** [comment]
Maybe https://github.com/ValveSoftware/steam-runtime/issues/226

**Comment by smcv** [comment]
> without internet connection

This is probably the same issue as #264 and #258, and quite possibly also #226.

**Comment by smcv** [comment]
Address resolution problems are hopefully fixed by the latest beta versions. Please try with the "Steam Linux Runtime" set to the public beta branch `client_beta`, and the latest Steam client beta (Sep 10 2020 or newer). `SteamLinuxRuntime/VERSIONS.txt` should identify it as pressure-vessel 0.20200909.0+srt1 and scout 0.20200910.0.

If that version works, then we can consider the name-resolution parts of this issue to be the same thing as #226.

Note that the beta Steam Linux Runtime is not expected to work with Steam client versions older than the current beta. This is not considered to be a bug.

Issues that are specific to the NVIDIA proprietary driver might still affect those new versions.

**Comment by Newbytee** [comment]
Surprisingly both the proprietary NVIDIA driver issue and the networking issue are gone at least on my end now. :+1:

**Comment by smcv** [comment]
We've changed a lot since November, so it's entirely possible that the NVIDIA issue was fixed along the way!
