### ISSUE TITLE
CS: GO No fonts in chat in the beta container

### ISSUE THREAD

**Issue by fredoche** [ValveSoftware/steam-runtime#196]
Using the container feature in beta:
Nothing appears in the chat windows during the game.
Host: Linux Fedora 31
Cheers

**Comment by TTimo** [comment]
Hello @fredoche, can you provide the output of Help > System Information to help diagnose this?

**Comment by kvbev** [comment]
I have this issue also but there are more details. here is my [system information.](https://gist.github.com/kvbev/4eaf7eda2e234658cc3503f7b892de77)

the only text that will appear in the chat is when someone in the game opens a case or completes a trade. the chat is also functional in that you can type and send something but you cannot see what you are typing nor what you sent or is being said.

this bug also breaks the console, anything you type in the console will show as a blank line once entered. repeatedly pressing the the tilde key to open and close the console will add that character to the console prompt. net_graph will also not appear on the game screen.

tooltips that include a key binding will not show said key binding, instead blank brackets, [].

**Comment by TTimo** [comment]
@kvbev can you refresh with the "Steam Linux Runtime Information" output? That was disabled in the version you used for the report, but it's enabled again in latest.

**Comment by kvbev** [comment]
[System information](https://gist.github.com/kvbev/4eaf7eda2e234658cc3503f7b892de77) updated from steam beta. also all issues still present when using steam beta.

**Comment by Newbytee** [comment]
This seems to be fixed for me with version 0.20200417.0 of the Steam Runtime.

**Comment by kvbev** [comment]
this is also fixed for me on the latest steam beta with runtime 0.20200417.0

chat and console all work now.

**Comment by TTimo** [comment]
While we didn't work specifically on this problem, the latest steam runtime improved compatibility with non-debian distribution, I suspect some changes made there fixed this.

**Comment by fredoche** [comment]
it's fixed for me afaics, thanks
