### ISSUE TITLE
Game Dev Tycoon (239820) crashes instantly

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#198]
Game crashes instantly when launching it in Pressure Vessel. No window. 

System info: https://gist.github.com/Newbytee/c4a4142c60e9be6dddbb52ee8c03b4a4

Log: [game-dev-tycoon-stdout-stderr-log.txt](https://github.com/ValveSoftware/steam-runtime/files/4723093/game-dev-tycoon-stdout-stderr-log.txt)

**Comment by smcv** [comment]
> ./gamedevtycoon64-bin: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory

This game seems to be assuming that it has access to a newer libudev version from the host system. This would usually work OK with the LD_LIBRARY_PATH runtime (but not always - it depends on the host OS). It is unlikely to ever be compatible with a strict Steam Runtime 1 environment, which is what the SteamLinuxRuntime compat tool provides.

**Comment by smcv** [comment]
With the new version of the "Steam Linux Runtime" container, identified as `depot 0.20210630.32` or later in `SteamLinuxRuntime/VERSIONS.txt`, this game fails to launch for different reasons: the container now provides `libudev.so.1`, but the game's startup script is not compatible with how the container works.

Specifically, the game's startup script completely replaces the `LD_LIBRARY_PATH` from the Steam Runtime, instead of prepending or appending, similar to what we see in #224. We might be able to work around this with future Steam Linux Runtime enhancements (tracked internally as T14481), but that's going to be relatively complicated to get right

**Comment by smcv** [comment]
> Specifically, the game's startup script completely replaces the LD_LIBRARY_PATH from the Steam Runtime, instead of prepending or appending, similar to what we see in #224. We might be able to work around this with future Steam Linux Runtime enhancements (tracked internally as T14481)

Unfortunately, this is not sufficient. In addition to having this LD_LIBRARY_PATH issue, Game Dev Tycoon requires `libnss3.so`. That library is not part of the Steam Runtime 2 'soldier' runtime (at least, not at the moment), and Game Dev Tycoon can't see the version of `libnss3.so` that comes with Steam Runtime 1 'scout' either, because it removes the LD_LIBRARY_PATH that would let it see that version.

**Comment by smcv** [comment]
> In addition to having this LD_LIBRARY_PATH issue, Game Dev Tycoon requires `libnss3.so`. That library is not part of the Steam Runtime 2 'soldier' runtime (at least, not at the moment), and Game Dev Tycoon can't see the version of `libnss3.so` that comes with Steam Runtime 1 'scout' either, because it removes the LD_LIBRARY_PATH that would let it see that version.

The latest build of **Steam Linux Runtime - Soldier** works around this by adding `libnss3.so`, `libnspr4.so` and related libraries.

You need at least **Steam Linux Runtime** depot 0.20210809.34 or later, and **Steam Linux Runtime - Soldier** depot 0.20210818.24 or later (see `SteamLinuxRuntime*/VERSIONS.txt`). As of today, both of these are only available in the `client_beta` branches, but they will be promoted to the default branches when they've had more testing.

I've confirmed that Game Dev Tycoon launches successfully with these versions.

**Comment by Newbytee** [comment]
Curious, for me it still crashes. Log: [gdt-log.txt](https://github.com/ValveSoftware/steam-runtime/files/7017019/gdt-log.txt)

And yes, I have verified I'm using the aforementioned versions of the Steam Linux Runtimes and I'm using the Steam client beta.

**Comment by smcv** [comment]
That's weird, my copy loaded successfully without that. I'm not delighted about the idea of adding `dbus-glib` to the soldier runtime (it's unmaintained, I'm the unmaintainer!) but it might be pragmatic to do so.

**Comment by Newbytee** [comment]
Could it be something wrong on my end?

**Comment by RyuzakiKK** [comment]
> Could it be something wrong on my end? (I know Pressure Vessel is supposed to isolate the games from system differences, but still)

FYI this doesn't seem to be a problem on your end. The game is complaining about `libdbus-glib-1.so.2` also on my system.

**Comment by smcv** [comment]
I think I must have been doing something wrong when I re-tested. I can now reproduce the same failure mode on at least Ubuntu 20.04 and Debian 11.

**Comment by smcv** [comment]
The next soldier beta will probably add `libdbus-glib-1.so.2`, which should resolve this.

**Comment by Newbytee** [comment]
> The next soldier beta will probably add libdbus-glib-1.so.2, which should resolve this.

Do you have an ETA for that so I know when to test it?

**Comment by smcv** [comment]
No ETA, I'll comment here when it's available.

**Comment by smcv** [comment]
Today's beta update for "Steam Linux Runtime - soldier" also adds dbus-glib, which should be enough to make this game work.

To check which version you have, look at `SteamLinuxRuntime_soldier/VERSIONS.txt`. The version you want is `depot 0.20210907.26` or later.

**Comment by Newbytee** [comment]
Game works now :+1:.

I have a really weird issue with it where I need to toggle fullscreen to actually see it, but that happens without Pressure Vessel too. I don't recall having this before, so that's strange. Either way, I think this can be closed now.
