### ISSUE TITLE
Stellaris (281990)

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-runtime#201]
#### Your system information

* Steam client version (build number or date): Nov 7 2019, at 23:57:46
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Steps for reproducing this issue:

1. Install stellaris
2. Go to properties, set steam play override to steam linux container
3. Start game
4. Nothing happens

System information: https://gist.github.com/XakepSDK/3c3b0796e37bb94aa1585bf7f2b6035c

**Comment by RyuzakiKK** [comment]
I enabled the Steam Linux Runtime container and tried Stellaris right now. It seems to be working without any problem.

@XakepSDK Can you please try it again? A lot has changed in the past couple of years since you first reported this issue.

**Comment by XakepSDK** [comment]
Looks like it's working
