### ISSUE TITLE
Steam Linux Runtime container tool installation detection

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-runtime#204]
#### Your system information

* Steam client version (build number or date): Nov 7 2019, at 23:57:46
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* System information: https://gist.github.com/XakepSDK/134d38db5bc6d7bfea6b499cba5382e0
* Steam output: https://gist.github.com/XakepSDK/3397a9c88da03e09e2338e47db75af24

#### Please describe your issue in as much detail as possible:
Steam does not detect steam linux runtime installation.

#### Steps for reproducing this issue:

1. Install Steam Linux Runtime
2. Restart steam
3. Look at system information, it has `The Steam Linux Runtime container tool is not installed.`

Steam Linux Runtime installed on separate disk.

**Comment by TTimo** [comment]
Hello - do you have the home isolation feature enabled? Do you mind trying without it?

I can confirm that the System Information output for container is not working if home isolation is enabled. This will be fixed in next Steam client beta (> Nov 11).

**Comment by XakepSDK** [comment]
1. Started regular steam
2. Installed Steam Linux Runtime
3. Checked if it's present in system info
4. Restarted steam and checked again

Home isolation was not enabled.

`cat /proc/15990/environ| tr '\0' '\n'` of `/usr/lib/steam/steam` process: https://gist.github.com/XakepSDK/48eb4e47e0bb32b0ae83665d7c82088e

**Comment by TTimo** [comment]
Intriguing. Can you provide this log file: `~/.steam/root/logs/compat_log.txt`

**Comment by TTimo** [comment]
Nov 14 beta client update received some fixes to the container diagnostic, but maybe this is a different problem.

**Comment by XakepSDK** [comment]
Nov 14 2019, at 01:54:29, same issue
https://gist.github.com/XakepSDK/d1ab692781f3bbda7418eda8bd17a4be

**Comment by Newbytee** [comment]
Issue persists for me too.

**Comment by Newbytee** [comment]
Never mind! Works for me today.

**Comment by XakepSDK** [comment]
Nov 14 2019, at 18:30:46
same issue

ls output in `~/.steam` https://gist.github.com/XakepSDK/6a1edce139efd4a81883ce9473113a20
Steam terminal output https://gist.github.com/XakepSDK/b7921cd6e6745a35871921dd3845f5ad

**Comment by XakepSDK** [comment]
Nov 19 2019, at 00:20:39
Same issue

**Comment by Vash63** [comment]
I can duplicate this as well on my [System Information](https://gist.github.com/Vash63/de8cfef4e4abcbfe884d1163fdb3c2bb) page. It's installed and Steam verifies the files successfully.

**Comment by soredake** [comment]
Same with archlinux, installed in default folder (~/.local/share/steam)

**Comment by gitvalds** [comment]
Also for me "System information says "The Steam Linux Runtime container tool is not installed."
Any game that I set to run in it do not start.
The "Play" button for a moment becomes "Stop" and then "Play" again.
If I search in the Steam client for "Steam linux runtime" it appears with a green button which says "Launch".
If I click on it, then it shows:
"An error has occurred while updating Steam linux runtime (invalid app configuration)

I don't remember enabling "home isolation" and "isolation" does not appear in the output of:
cat /proc/6217/environ
where 6217 is the process:
6217    1223  0 03:03 ?        00:00:00 /usr/bin/bash /usr/bin/steam

I am on Fedora 31.
If I can do something, please let me know.
[compat_log.txt](https://github.com/ValveSoftware/steam-runtime/files/3907762/compat_log.txt)

**Comment by gitvalds** [comment]
Operating System Version:
    Unknown (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.3.12-300.fc31.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  12006000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20191024.0

**Comment by kisak-valve** [comment]
Hello @gitvalds, for clarity, did you test a native linux game with pressure-vessel? The initial deployment of the Steam Linux Runtime container does not support Proton.

**Comment by gitvalds** [comment]
@kisak-valve 
Hi. No, actually.
I did not know about pressure-vessel until I read your comment.
Then I suppose that my comments should be ignored :)

**Comment by XakepSDK** [comment]
Dec 11 2019, at 01:10:38, bug still present
https://gist.github.com/XakepSDK/53bb8d40578047a5ad7a4f1451d233da

**Comment by XakepSDK** [comment]
Dec 11 2019, at 01:10:38 with new SLR:
```
./run-in-scout -- pressure-vessel/bin/pressure-vessel-wrap --version
pressure-vessel-locale-gen: No locales need to be generated
pressure-vessel version 0.20190927.0+4+gb7ad27a+srt1
```
Still same issue

**Comment by TTimo** [comment]
What filesystem is /media on? What are the mount options?
We'll assume that "Verify Integrity of Tool Files" does not find any errors?

#190 suggests that you may be using Arch's steam runtime modifications, can you confirm that the problem exists when using Valve's official steam runtime?

Can you provide your latest `content_log.txt`, `steam_api_log.txt` and `compat_log.txt` from `~/.steam/steam/logs`

**Comment by XakepSDK** [comment]
1. ext4
```
findmnt | grep /media/data
├─/media/data                         /dev/sda2   ext4        rw,relatime
```
2. "Verify Integrity of Tool Files" - all files passed check
3. I'm using steam runtime, `Steam Runtime Version:  steam-runtime_0.20191210.1`

[content_log.txt](https://github.com/ValveSoftware/steam-runtime/files/3954336/content_log.txt)
[compat_log.txt](https://github.com/ValveSoftware/steam-runtime/files/3954337/compat_log.txt)
[steam_api_log.txt](https://github.com/ValveSoftware/steam-runtime/files/3954338/steam_api_log.txt)

**Comment by XakepSDK** [comment]
`find SteamLinuxRuntime/ -type f -exec sha1sum {} \; > SLR_sha1.log`
[SLR_sha1.log](https://github.com/ValveSoftware/steam-runtime/files/3954396/SLR_sha1.log)

**Comment by TTimo** [comment]
Any other folks having this problem using third party Proton builds, such as https://github.com/GloriousEggroll/proton-ge-custom ?

**Comment by TTimo** [comment]
@XakepSDK can you rename/move `/home/user/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/compatibilitytool.vdf` and see if that fixes your problem?

**Comment by XakepSDK** [comment]
No.
`STEAM_RUNTIME_CONTAINER_TEST=1 PRESSURE_VESSEL_WRAP_GUI=1 steam > out.log 2>&1`
[out.log](https://github.com/ValveSoftware/steam-runtime/files/3956957/out.log)

What i did:
1. Run CS 1.6 with `None (use host system)`
2. Run CS 1.6 with `Steam Runtime 1 (scout) Platform build 0.20191210.1`

`/home/user/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/compatibilitytool.vdf`
renamed to `compatibilitytool.vdf__`

Why CS 1.6? It 100% worked with first publicly announced release.

I noticed that i have set custom launch options for a game, removing them does not fix issue.

**Comment by Vash63** [comment]
I do have a third party Proton build installed (compiled from [this script](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/proton-tkg) )

**Comment by Newbytee** [comment]
> Any other folks having this problem using third party Proton builds, such as https://github.com/GloriousEggroll/proton-ge-custom ?

I have 4.14-GE-1 and one "Proton" I put together myself and I **do not** have this problem.

**Comment by TTimo** [comment]
Thanks everyone. Next beta update (> 2019-12-11) will have a fix for this.

**Comment by XakepSDK** [comment]
Dec 12 2019, at 22:37:09

I have `CClientJobGatherRuntimeInformation: container read output failed` instead of `The Steam Linux Runtime container tool is not installed.`
Is this ok?

**Comment by XakepSDK** [comment]
Maybe this can be useful:
```
user@arch ~ % /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime/run-in-scout -- steam-runtime-system-info    
pressure-vessel-locale-gen: No locales need to be generated
bwrap: execvp /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime/pressure-vessel/bin/pressure-vessel-with-lock: No such file or directory
1 user@arch ~ % /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime/pressure-vessel/bin/pressure-vessel-with-lock                                                                                                                                                    :(
pressure-vessel-with-lock: Usage: pressure-vessel-with-lock [OPTIONS] COMMAND [ARG...]
64 user@arch ~ %                                                                                                                                                                                                                                                             
```

**Comment by XakepSDK** [comment]
I think i found issue! If i CD to `/media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime` and execute first command, it shows me some JSON.

**Comment by XakepSDK** [comment]
```
user@arch ~ % /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime/run-in-scout -- steam-runtime-system-info                           
pressure-vessel-locale-gen: No locales need to be generated
bwrap: execvp /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime/pressure-vessel/bin/pressure-vessel-with-lock: No such file or directory
1 user@arch ~ % cd /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime                                                                                                                                                                                               :(
user@arch ..ary/steamapps/common/SteamLinuxRuntime % ls
README.md  com.valvesoftware.SteamRuntime.Platform-amd64,i386-scout-buildid.txt  com.valvesoftware.SteamRuntime.Platform-amd64,i386-scout-runtime.tar.gz  deploy-runtime  pressure-vessel  run-in-scout  scout  scout_0.20191210.1  scout_sdk  toolmanifest.vdf
user@arch ..ary/steamapps/common/SteamLinuxRuntime % /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime/run-in-scout -- steam-runtime-system-info
pressure-vessel-locale-gen: No locales need to be generated
{
  "can-write-uinput" : true,
  "steam-installation" : {
```

**Comment by TTimo** [comment]
@XakepSDK is /usr/bin not in your PATH maybe? This lastest round of problems is likely specific to your unusual host configuration, but I'll update the logic to explicitly execute `/usr/bin/steam-runtime-system-info`

**Comment by smcv** [comment]
```
bwrap: execvp /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime/pressure-vessel/bin/pressure-vessel-with-lock: No such file or directory
```

Does the path quoted there exist?

Does its ELF interpreter `/lib64/ld-linux-x86-64.so.2` exist?

**Comment by TTimo** [comment]
@smcv the path quote does exist yes (@XakepSDK provided a tree output of the depot)

**Comment by smcv** [comment]
Oh, I think I see the problem here. pressure-vessel makes the main Steam Library directory available in the container, and it makes the current working directory available too; but it doesn't know what secondary Steam Library directories there are, so if SteamLinuxRuntime is itself installed in a secondary Steam Library directory, it can't find itself inside the container.

Workaround: migrate SteamLinuxRuntime from the secondary Steam Library to `~/.local/share/Steam/steamapps/common`.

**Comment by smcv** [comment]
> it makes the current working directory (which contains the game) available too

This is why cd'ing to the SteamLinuxRuntime directory makes `run-in-scout -- steam-runtime-system-info` work (but that isn't an option for running actual games, because for those, the current working directory needs to be the game).

**Comment by XakepSDK** [comment]
```
user@arch ~ % echo $PATH                    
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```
`/usr/bin` exists in PATH, `/usr/bin` is directory, not symlink.

**Comment by XakepSDK** [comment]
Moving Steam Linux Runtime to default library fixes:
1. SLR info appears in system info https://gist.github.com/XakepSDK/65986578bd9ad1cf047d05d471cb768b
2. I can start game using SLR scout
Both issues are in this ticket

3. Host libraries does not work, ticket #190, still not fixed

**Comment by TTimo** [comment]
The container runtime depot was updated to `0.20191217.0` - this version supports launching from a non-default library install.

**Comment by XakepSDK** [comment]
Can confirm, it's fixed
