### ISSUE TITLE
Supplied gcc-5 is missing some C++11 symbols in libstdc++

### ISSUE THREAD

**Issue by ewmailing** [ValveSoftware/steam-runtime#207]
Hello. I am trying to use the gcc-5 you now supply with Steam Runtime, which appears to be gcc 5.4. I need C++11, but fortunately, gcc 5.4 is supposed to have everything I need. However, when I actually try using your supplied gcc-5, I hit some build errors complaining of unfound things.

To give you a little more context, I am hoping to build the Swift compiler and libraries for Steam Runtime so I can try to write games using Swift. But to build Swift, it needs to build more recent versions of LLVM and Clang as a bootstrap. They have checks for C++11, including the capabilities in the standard C++ library.

So the very first error I hit is a check in CMake in llvm-project/cmake/modules/CheckCompilerVersion.cmake

I know gcc 5.4.0 should pass this check, but when it test builds on on steam runtime, it fails with an undefined refernce to std::iostream_category(), which is part of C++11 and I know if I build gcc 5.4 myself, it can pass this check.

To distill down the CMake check so you can understand it, it basically reduces to creating the following gcc_soft_version.cpp file and trying to build it:

```
#include <iosfwd>
#if __GLIBCXX__ < 20150422
#error Unsupported libstdc++ version
#endif
#include <ios>
void foo(void) { (void) std::iostream_category(); }
int main() { return 0; }
```

If I compile this by hand using gcc-5 on Steam Runtime via:
`g++-5 -std=gnu++11 gcc_soft_version.cpp
`
I get the error:
```
gcc_soft_version.cpp:(.text+0x5): undefined reference to `std::iostream_category()'
collect2: error: ld returned 1 exit status
```

The value of __GLIBCXX__ is 20160803 on Steam Runtime, so it passes the first check.

I tried working around this by building my own gcc 5.4 on Steam Runtime with libstdc++ as only static, but I hit a lot of problems of the form "relocation R_X86_64_32S against `a local symbol' can not be used when making a shared object; recompile with -fPIC", starting with this one just trying to build gcc.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66955

Going down a deep rabbit hole, I finally worked around enough things to try to build Clang/LLVM next, but then I hit a very similar error and am currently blocked.

But at the end of the day, I know I am playing with fire working with my own libstdc++ instead of the system one.

I'm hoping you guys might be able to fix this in Steam Runtime itself since it seems like a bug, as I know gcc 5.4 should not have this problem. I'm hoping this might just be a minor build switch bug in your scripts to build gcc-5. Then I hope I could just use your stock gcc-5 to build Swift.

**Comment by TTimo** [comment]
We are not likely to update compilers in scout any further at this time. As you have noticed, it's an increasingle difficult process to backport new compilers to scout.

However, we will make newer compilers available in newer runtimes, based on the work outlined in https://steamcommunity.com/app/221410/discussions/0/1638675549018366706/

I can't give you a precise timeline but I'm hoping that will help resolve your problem.
