### ISSUE TITLE
Game Files Don't Get Downloaded with Steam Linux Runtime

### ISSUE THREAD

**Issue by ertancanatik** [ValveSoftware/steam-runtime#208]
I have selected Steam Linux Runtime for Steam Play, but when I hit download for Assetto Corsa, only content file got downloaded. When I try to download iRacing, it doesn't download anything and gives the message of finishing download like it downloaded. When I browse for files of the game, there is nothing in the steamapps/common/iRacing folder. 
https://gist.github.com/ertancanatik/774f33918f44a8acd566751d3cdd06ba

**Comment by kisak-valve** [comment]
Hello @ertancanatik, by selecting Steam Linux Runtime, you've told Steam to not use Proton with the Windows game on Linux. This is a known limitation with the initial deployment of the tool and is being tracked at #200.

Closing as a duplicate.
