### ISSUE TITLE
Cities: Skylines not running with the container.

### ISSUE THREAD

**Issue by matheusreich** [ValveSoftware/steam-runtime#209]
If Steam Linux Runtime is enabled, C:S will execute, but only present a black screen. It does not load at all, but it does change the mouse to the custom mouse that the game has. When reverted to the standard option (without the container), it runs perfectly fine.

**Comment by RyuzakiKK** [comment]
I just tried to launch it with the SLR container enabled and it worked just fine.

@matheusreich Can you please try it again? A lot has changed in the past couple of years since you first reported this issue, and apparently this should not be an problem anymore.

**Comment by kisak-valve** [comment]
Closing pending feedback.
