### ISSUE TITLE
PRESSURE_VESSEL_SHARE_HOME=0 not compatible with cloud saves yet

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-runtime#214]
With `PRESSURE_VESSEL_SHARE_HOME=0` set steam downloads saves to incorrect location `.local/share/feral-interactive/Life Is Strange/VFS/Local/My Games/Life Is Strange/Saves/`,  the correct location is `.var/app/com.steampowered.App319630/.local/share/feral-interactive/Life Is Strange/VFS/Local/My Games/Life Is Strange/Saves/`

**Comment by TTimo** [comment]
Correct, the cloud saves system isn't compatible with home isolation yet. Thanks for the report.

**Comment by smcv** [comment]
Please could someone with the right permissions retitle this to `PRESSURE_VESSEL_SHARE_HOME=0 not compatible with cloud saves yet` to flag it as a known-missing feature that affects multiple games?

**Comment by soredake** [comment]
Retested, saves are still not saved in correct location.
