### ISSUE TITLE
Danger Gazer doesn't launch

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-runtime#216]
When trying to run [Danger Gazers](https://store.steampowered.com/app/1043150/Danger_Gazers/) with the runtime container, it dies with this:

> /media/storage/SteamLibrary/steamapps/common/Danger Gazers/Danger_Gazers: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

Trying the container, since it's a Game Maker title which bugs-out normally with:

> /media/storage/SteamLibrary/steamapps/common/Danger Gazers/Danger_Gazers: /home/liam/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /media/storage/SteamLibrary/steamapps/common/Danger Gazers/Danger_Gazers)

(I really wish Game Maker would sort that out already...)

If you need other details/want me to try something else do let me know. System info: https://gist.github.com/LiamDawe/ea58011b3231eb14c5c04657d19e6e3d

**Comment by smcv** [comment]
It looks like Danger Gazers (and presumably other Game Maker titles?) has been built on a more recent Debian/Ubuntu derivative, and is not compatible with the "pure" Steam Runtime system provided by the presure-vessel container.

`CURL_OPENSSL_4` is specific to the Debian/Ubuntu versions of libcurl, and won't be available when the Steam Runtime copy of libcurl.so.4 is overridden by the host OS copy. What host OS are you running on?

`libcrypto.so.1.1` is part of OpenSSL 1.1, which is in Debian 9+ and Ubuntu 18.04+, but not in older versions (and the Steam Runtime is based on Ubuntu 12.04, which is much older).

**Comment by LiamDawe** [comment]
Sorry, forgot to mention and leave details.

This is Manjaro, latest. I've added system info into the OP.

**Comment by smcv** [comment]
On #235 I wrote:
> We have some ideas for a less strict container environment where games like this are more likely to work

We now have a prototype of this available. If you [go into the list of SLR betas](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#using-a-beta-or-an-older-version) and choose the `scout_layered_slim` branch, you'll get the Steam Runtime v1 'scout' `LD_LIBRARY_PATH` runtime, running inside the same Steam Runtime v2 'soldier' container that Proton uses.

I don't have Danger Gazers, but I tried this with the demo version of Demetrios (451570) which is another GameMaker title. It segfaults when I use the default or `client_beta` branch of SLR, but runs successfully when I use `scout_layered_slim`. So, that's promising! Please try it and see how you get on?

If the `scout_layered_slim` branch breaks any of your *other* games, please report that as a separate issue, and make it as obvious as possible that you're using the `scout_layered_slim` branch.

If this approach is successful, then it will eventually replace the current approach to running native scout games in SLR.

(This is an implementation of https://github.com/ValveSoftware/steam-runtime/blob/master/doc/possible-designs.md#steam-runtime-2-container-with-ld_library_path-runtime-inside from the design document I wrote a while ago.)

**Comment by smcv** [comment]
Sorry, I should have mentioned: if launching games in `scout_layered_slim` doesn't work immediately, try exiting from Steam completely, and starting Steam again. Similarly, if you go back from `scout_layered_slim` to the default or `client_beta` branch, you might need to exit from Steam and restart it.

**Comment by LiamDawe** [comment]
Great, can confirm it launches just fine using the scout_layered_slim Beta for SLR. As suggested, I did need to close and reload Steam for it to work, as the initial launch did not. Great stuff!

**Comment by smcv** [comment]
> Great, can confirm it launches just fine using the scout_layered_slim Beta for SLR

Unfortunately, I think this is going to regress in newer versions of `scout_layered_slim`: it only worked because of a bug, which has now been fixed.

This game (and other GameMaker games) would probably work better in a Steam Runtime 2 'soldier' environment, but Steam doesn't currently support running native Linux games in a soldier container.

**Comment by smcv** [comment]
The equivalent of `scout_layered_slim` is now in the `client_beta` branch too.

**Comment by smcv** [comment]
> Unfortunately, I think this is going to regress in newer versions of `scout_layered_slim`: it only worked because of a bug, which has now been fixed.

Looks like I was too pessimistic. This game is actually launching fine for me, using SteamLinuxRuntime depot 0.20210630.32, soldier depot 0.20210630.17 and scout runtime 0.20210630.0 (which are all available in stable/general-availability branches). @LiamDawe, please could you try this again?

```
$ cat ~/SteamLibrary/steamapps/common/SteamLinuxRuntime/VERSIONS.txt 
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20210630.32			# Overall version number
LD_LIBRARY_PATH	-	scout	-	# see ~/.steam/root/ubuntu12_32/steam-runtime/version.txt
scripts	v0.20210623.0-0-ga389036			# Entry point scripts, etc.
$ cat ~/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20210630.17			# Overall version number
pressure-vessel	0.20210630.0			
scripts	v0.20210623.0-0-ga389036			# Entry point scripts, etc.
soldier	0.20210629.0	soldier	0.20210629.0	# soldier_platform_0.20210629.0/
$ cat ~/.steam/root/ubuntu12_32/steam-runtime/version.txt 
steam-runtime_0.20210630.0
```

**Comment by LiamDawe** [comment]
Can confirm the current Steam Linux Runtime option picked in the Compatibility menu allows it to load just fine.

**Comment by smcv** [comment]
Great! I think this issue can be closed, then. (You or @kisak-valve can close it, but I can't.)

**Comment by kisak-valve** [comment]
Thanks for retesting @LiamDawe. It sounds like we're done here. Closing as fixed.
