### ISSUE TITLE
Back to Bed (308040) crashes instantly on startup 

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#218]
When attempting to run the game inside of Pressure Vessel it crashes instantly on startup, no window visibly appears.

[System information](https://github.com/ValveSoftware/steam-runtime/files/4029958/sysinfo.txt)

**Comment by smcv** [comment]
Is this on the same system as in #222?

Does this game work normally when you are **not** using pressure-vessel?

If you run Steam from a terminal, do you get any error or warning messages logged when you run this game? (You should get at least a few, even for a game that is working correctly.)

**Comment by Newbytee** [comment]
> Is this on the same system as in #222? If not, please provide the **Help -> System Information** from the system where you see this bug, as a link to a [gist](https://gist.github.com/).

Yes. Same system.

> Does this game work normally when you are **not** using pressure-vessel?

Yes. Game works perfectly without Pressure Vessel, I'm testing for fun.

> If you run Steam from a terminal, do you get any error or warning messages logged when you run this game? (You should get at least a few, even for a game that is working correctly.)

I will try this in about a week. Currently I'm not able to.

**Comment by Newbytee** [comment]
Game works now. No apparent issues.
