### ISSUE TITLE
POSTAL 2 (223470) crashes after content warning 

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#222]
POSTAL 2 singleplayer crashes after the content warning (mature content, etc., not an error), whereas the unsupported multiplayer instantly crashes. To be clear, this is when running it in Pressure Vessel.

[System Information](https://github.com/ValveSoftware/steam-runtime/files/4029958/sysinfo.txt)

**Comment by TTimo** [comment]
CNR on Manjaro, tested both single player and coop.

The 'chat' dialog (accessed via t) seems broken though. I can type some dialog but nothing scrolls in the box?

@Newbytee - can you provide the output of Help > System Information?

**Comment by Newbytee** [comment]
> CNR on Manjaro, tested both single player and coop.
> 
> The 'chat' dialog (accessed via t) seems broken though. I can type some dialog but nothing scrolls in the box?
> 
> @Newbytee - can you provide the output of Help > System Information?

All right, see the original post.

**Comment by TTimo** [comment]
Can you locate a crash ID upload in stderr/stdout? It will look something like this:

```
assert_20200103200500_1.dmp[60610]: Finished uploading minidump (out-of-process): success = yes
assert_20200103200500_1.dmp[60610]: response: CrashID=bp-289f5a6e-4f0f-486f-9cc4-8a23d2200103
assert_20200103200500_1.dmp[60610]: file ''/tmp/dumps/assert_20200103200500_1.dmp'', upload yes: ''CrashID=bp-289f5a6e-4f0f-486f-9cc4-8a23d2200103''
```

**Comment by Newbytee** [comment]
> Can you locate a crash ID upload in stderr/stdout? It will look something like this:
> 
> ```
> assert_20200103200500_1.dmp[60610]: Finished uploading minidump (out-of-process): success = yes
> assert_20200103200500_1.dmp[60610]: response: CrashID=bp-289f5a6e-4f0f-486f-9cc4-8a23d2200103
> assert_20200103200500_1.dmp[60610]: file ''/tmp/dumps/assert_20200103200500_1.dmp'', upload yes: ''CrashID=bp-289f5a6e-4f0f-486f-9cc4-8a23d2200103''
> ```

Where should I be looking for this exactly? I redirected stdout and stderr from POSTAL 2 to a file, but it only gave me this: [postal2.log](https://github.com/ValveSoftware/steam-runtime/files/4031086/postal2.log).

I had a look inside /tmp/dumps, however there I only find <my username>_stdout.txt which seems to contain the stdout and stderr from Steam, however I see nothing that looks like what you showed above. Launching Steam via terminal does not seem to reveal any additional information. 

Closest thing I see to what you wrote is: `[0107/154631.934036:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer`

Here's /tmp/dumps/neboula_stdout.txt if it's any helpful: [neboula_stdout.txt](https://github.com/ValveSoftware/steam-runtime/files/4031114/neboula_stdout.txt)

**Comment by TTimo** [comment]
Ok. I'm not very familiar with portal 2 - it doesn't look like it's setup to capture and send crash reports via breakpad like some of the other Valve products.

**Comment by TTimo** [comment]
Ok my brain completely crossed the wires here and was thinking 'Portal 2' this whole time and not 'Postal 2'.

**Comment by Newbytee** [comment]
> Ok my brain completely crossed the wires here and was thinking 'Portal 2' this whole time and not 'Postal 2'.

All right :'). Understandable. Portal 2 works in Pressure Vessel here too, but with some issues, though that's a matter for another issue.

**Comment by smcv** [comment]
@Newbytee Does Postal 2 work normally when you are **not** using pressure-vessel? (No crashes, etc.)

**Comment by Newbytee** [comment]
> @Newbytee Does Postal 2 work normally when you are **not** using pressure-vessel? (No crashes, etc.)

Yes, it does work when running the game "normally". There are (very) occasional crashes when entering a new zone, however aside from that the game works just as it should. The unsupported multiplayer did not quite work though, characters had no textures and if I recall correctly the menu didn't really load, but it did not instantly crash.

**Comment by Newbytee** [comment]
Steam's log from launching the game in Pressure Vessel: https://gist.github.com/Newbytee/1af7fd5d27edc8e725391235aca21aa5

**Comment by Newbytee** [comment]
Game gets past the content warning now and into the menu. Didn't try out loading a save but I imagine it should work and regardless the problem this issue details has been fixed.
