### ISSUE TITLE
HL2DM and possibly other Source Engine games have MOTD/Download issues

### ISSUE THREAD

**Issue by henk717** [ValveSoftware/steam-runtime#225]
**Observed behavior**
Ingame MOTD renders pink, downloads do not actually download anything and instead rapidly run trough the download list with no files being downloaded.

**Expected Behavior (Observed using the native method instead of the steam runtime)**
The ingame MOTD renders a HTML page using the Steam proccess for web rendering.
Server downloads complete succesfully.

**Reproduction steps**
Join any server with custom content, the download will fail.
Create a local server or join a server without custom content, the MOTD will display pink.

**System Tested**
Manjaro Stable, updated to the latest packages as off 2-2-2020 on multiple systems and GPU's.

**Comment by smcv** [comment]
This might be the same thing as #226. Please try with the latest beta versions: see https://github.com/ValveSoftware/steam-runtime/issues/226#issuecomment-691550054 for details.

**Comment by kisak-valve** [comment]
Closing pending feedback.
