### ISSUE TITLE
DNS resolution not working inside pressure-vessel

### ISSUE THREAD

**Issue by kadogo** [ValveSoftware/steam-runtime#226]
Hello, while launching Kind Words with Steam Linux Runtime it look like it has no internet access. I think it can be related with https://github.com/ValveSoftware/steam-runtime/issues/225 maybe.

![Capture d’écran_2020-02-03_00-25-41](https://user-images.githubusercontent.com/5759396/73617169-31fe4f00-461c-11ea-8593-0dbadeed9057.png)

I saw this part that can be usefull in the Player.log from the game

```
(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

Curl error 6: Could not resolve host: config.uca.cloud.unity3d.com
Curl error 6: Could not resolve host: lofichillbeats.com
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64.so
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/steam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64.so
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
Setting up 2 worker threads for Enlighten.
  Thread -> id: 7f565298b700 -> priority: 1 
  Thread -> id: 7f565218a700 -> priority: 1 
Cannot resolve destination host
 
(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

Cannot resolve destination host
 
(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

Curl error 6: Could not resolve host: cdp.cloud.unity3d.com
Curl error 6: Could not resolve host: cdp.cloud.unity3d.com
Curl error 6: Could not resolve host: cdp.cloud.unity3d.com
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64.so
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/steam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64.so
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64.so
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/steam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64.so
Fallback handler could not load library /home/user/.steam/steam/steamapps/common/Kind Words/Kind Words_Data/Mono/libsteam_api64
```

Cheers

**Comment by smcv** [comment]
Please paste the report from **Help -> System Information** into a [Github Gist](https://gist.github.com/) and put a link here.

If you use the test UI (`PRESSURE_VESSEL_WRAP_GUI=1`) and run a shell instead of the game, then run `getent ahosts example.com`, what happens?

If you use the test UI and run `curl http://93.184.216.34`, what happens? (Hopefully you should get some HTML that says "404 - Not Found".)

Is your `/etc/resolv.conf` a symbolic link to a different file?

What are the contents of your `/etc/resolv.conf`?

Is there anything else unusual about how your host system resolves names or accesses the internet?

**Comment by smcv** [comment]
If you have or can install [Flatpak](https://flatpak.org/), it would also be interesting to know whether a Flatpak app that needs internet access can resolve hostnames and access internet resources. pressure-vessel reuses a lot of the container setup code from Flatpak, so if there's a limitation in how pressure-vessel does this, Flatpak might have the same issue.

**Comment by kadogo** [comment]
Hello @smcv 

My system information link is https://gist.github.com/kadogo/a72b612e48ede28a5bd7495b268de99d

I tried the command in a shell and in my normal terminal

![Capture d’écran_2020-02-17_20-57-31](https://user-images.githubusercontent.com/5759396/74683135-428bf900-51c8-11ea-83c1-3e01f1a45ce4.png)

```bash
$ getent ahosts example.com
93.184.216.34   STREAM example.com
93.184.216.34   DGRAM  
93.184.216.34   RAW    
2606:2800:220:1:248:1893:25c8:1946 STREAM 
2606:2800:220:1:248:1893:25c8:1946 DGRAM  
2606:2800:220:1:248:1893:25c8:1946 RAW  
```

```bash
$ curl http://93.184.216.34
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>404 - Not Found</title>
	</head>
	<body>
		<h1>404 - Not Found</h1>
	</body>
</html>
```

My resolv.conf is a fixed file with +i attribute because I not want my networkmanager to change it

```bash
~$ ls -lash /etc/resolv.conf 
4,0K -rw-r--r-- 1 root root 51 oct 18 00:59 /etc/resolv.conf
```

```bash
$ lsattr /etc/resolv.conf 
----i---------e---- /etc/resolv.conf
```

```bash
$ cat /etc/resolv.conf 
nameserver 195.10.195.195
nameserver 94.247.43.254
```

I have Flatpak installed if you have any command or test I can run I would be glad to do them and write the results here.

Cheers.

**Comment by smcv** [comment]
Looks like networking works fine inside the container, but hostname (DNS) resolution is broken.

If you `cat /etc/resolv.conf` in the container, do you get the same result as on the host system?

> I have Flatpak installed if you have any command or test I can run I would be glad to do them and write the results here.

If you install the org.freedesktop.Platform//19.08 runtime from Flathub and then run

```
$ flatpak run --command=bash --share=network org.freedesktop.Platform//19.08
```

you should get a shell where you can try the same `getent ahosts example.com` and `cat /etc/resolv.conf` commands as on the host system and inside the pressure-vessel container.

> My resolv.conf is a fixed file with +i attribute

The immutable flag could perhaps be interfering with pressure-vessel making it available in the container?

Configuring `/etc/NetworkManager/NetworkManager.conf` with

```
[main]
dns=none
```

should be enough to stop it rewriting `/etc/resolv.conf` without needing to make anything immutable (see NetworkManager.conf(5) for more details and to check whether your version has that option).

**Comment by kadogo** [comment]
> Looks like networking works fine inside the container, but hostname (DNS) resolution is broken.
> 
> If you `cat /etc/resolv.conf` in the container, do you get the same result as on the host system?
> 
The result is the same of my local resolv.conf

![Capture d’écran_2020-02-17_23-04-10](https://user-images.githubusercontent.com/5759396/74689031-e631d500-51d9-11ea-908c-033c0730450f.png)

> > I have Flatpak installed if you have any command or test I can run I would be glad to do them and write the results here.
> 
> If you install the org.freedesktop.Platform//19.08 runtime from Flathub and then run
> 
> ```
> $ flatpak run --command=bash --share=network org.freedesktop.Platform//19.08
> ```
I did the install with `flatpak install org.freedesktop.Platform//19.08`

```bash

> 
> you should get a shell where you can try the same `getent ahosts example.com` and `cat /etc/resolv.conf` commands as on the host system and inside the pressure-vessel container.
> 
> > My resolv.conf is a fixed file with +i attribute
> 
> The immutable flag could perhaps be interfering with pressure-vessel making it available in the container?
> 
> Configuring `/etc/NetworkManager/NetworkManager.conf` with
> 
> ```
> [main]
> dns=none
> ```
> 
> should be enough to stop it rewriting `/etc/resolv.conf` without needing to make anything immutable (see NetworkManager.conf(5) for more details and to check whether your version has that option).

**Comment by smcv** [comment]
Huh, weird.

@kisak-valve, please could you change the title of this issue to "DNS resolution not working inside pressure-vessel" or something like that?

**Comment by smcv** [comment]
I have a new idea for why this might be failing. @kadogo, please try this in an interactive shell inside the container:

```
LD_DEBUG=files getent ahosts example.com 2>&1 | tee getent-ahosts.log
```

and then send `getent-ahosts.log` as a gist.

I think you might see an error in that log, something like this:

```
/lib/x86_64-linux-gnu/libnss_dns.so.2: error: symbol lookup error: undefined symbol: (something) (fatal)
```

If you do, then I think I know how we can solve this in a future pressure-vessel release.

**Comment by dennis1248** [comment]
Hey @smcv 

Here is the gist https://gist.github.com/dennis1248/9489524cf7813d8ef6f80c31ce35f333

And you are correct, the log indeed contains that error.
```
14524:	/lib/x86_64-linux-gnu/libnss_dns.so.2: error: symbol lookup error: undefined symbol: h_errno, version GLIBC_PRIVATE (fatal)
```

**Comment by smcv** [comment]
Great! In that case, a future SteamLinuxRuntime update will probably fix this.

**Comment by kadogo** [comment]
Hello @smcv sorry for my late reply.

I just did the command but I think I have another error

```
/lib/x86_64-linux-gnu/libnss_dns.so.2: error: relocation error: symbol h_errno version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference (fatal)
```

https://gist.github.com/kadogo/f27e55b7b16ca1fce12e82410959426d

**Comment by smcv** [comment]
That's basically the same error. The fixed version is making its way through the system and will hopefully resolve this.

**Comment by TTimo** [comment]
@kadogo you can test with latest Steam client beta (Sep 10 2020 or newer), and the "Steam Linux Runtime" set to branch `client_beta` (which I updated just now - I forgot to do this when we pushed the new beta yesterday).

**Comment by kadogo** [comment]
Hello @TTimo 

It look like I not have an error now (https://gist.github.com/kadogo/cba0689ad560539e8d7b6ec53c573680)

**Comment by TTimo** [comment]
right - looks to me like you did get a good DNS response in that last one

**Comment by kadogo** [comment]
Yes, I did a fast test and the game looked like working correctly.

I let you decide if the issue need to be closed or if it's better to wait that the others issues are tested if they are related.

Anyway thanks everyone for making it work ^^

**Comment by Newbytee** [comment]
This seems to be fixed with the latest Pressure Vessel beta. :tada:

**Comment by smcv** [comment]
@kisak-valve, please could you close this issue? Everyone seems to agree that betas >= Sep 10 2020 resolved this.
