### ISSUE TITLE
Estranged: Act II (582890) will not run under slr

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-runtime#237]
[estranged-p2.log](https://github.com/ValveSoftware/steam-runtime/files/4244494/estranged-p2.log)

**Comment by smcv** [comment]
It's crashing with a segmentation fault. Either something is wrong in the container environment that pressure-vessel has set up, or the game is making assumptions about your system that aren't true any more in the container.

Please upload the *Help -> System Information* report as a [gist](https://gist.github.com/) and drop a link here. You can use the same link for all your issue reports if it's current and the same issue is still happening.

**Comment by soredake** [comment]
https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae

**Comment by soredake** [comment]
Moved to ubuntu, game works now with slr.

**Comment by soredake** [comment]
@smcv sure, https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae/revisions
