### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/libresolv.so uses unversioned private symbols from libc

### ISSUE THREAD

**Issue by gtalent** [ValveSoftware/steam-runtime#238]
/usr/lib/x86_64-linux-gnu/libresolv.so uses unversioned private symbols, which causes problems because /usr/lib/x86_64-linux-gnu/libc.so actually redirects the linker to the host environment's libc. libresolv and libc appear to be developed together and in some ways are the same package, so libresolv uses h_errno@GLIBC_PRIVATE assuming its libc version will match.

I'm thinking the right solution is to make libresolv also redirect to the host environment's version of the library, the only other solution would be to ship a later version of libresolv and break the Steam Runtime's compatibility guarantee.

**Comment by smcv** [comment]
@kisak-valve, please could you label this as a pressure-vessel issue? (I don't think we have a libresolv.so anywhere else.)

> I'm thinking the right solution is to make libresolv also redirect to the host environment's version of the library

Yes. pressure-vessel (the container-runner for the SteamLinuxRuntime) is already meant to be "capturing" `libresolv.so.2` and other libraries that are part of glibc, and including them in the library search path, whenever the host system's `libc.so.6` is in use. They should end up in `/overrides/lib/x86_64-linux-gnu` inside the container.

If that isn't working for you, or if it isn't sufficient, please provide enough information to reproduce and debug the issue, such as the host OS you're running this on, `steam-runtime-system-info` output inside and outside the container (you can get this from *Help -> System Information* in Steam), and details of whatever practical problem this bug causes (for example a particular game not working, and any messages that are produced when it doesn't work).

**Comment by smcv** [comment]
> the only other solution would be to ship a later version of libresolv

We can't do that. The Steam Runtime is designed to work on anything >= Ubuntu 12.04, so it has to be based on Ubuntu 12.04's glibc.

pressure-vessel is meant to detect when your host system's glibc is newer (which in practice it always will be, because Steam doesn't actually work on Ubuntu 12.04 any more), and "capture" all the libraries that are part of glibc from your host system.

**Comment by gtalent** [comment]
Do you mean there should be a /overrides directory in the schroot? I'm not seeing that.

**Comment by smcv** [comment]
Oh, are you talking about the schroot? Please be clear about which of the various modes and features you're reporting bugs in.

The schroot (or Docker) environment for compiling games should be purely scout: scout's libc.so.6, scout's libresolv.so.2, scout's /lib64/ld-linux-x86-64.so.2 and so on. How is anything from your host system getting into it?

**Comment by gtalent** [comment]
OK, so you guys intend for us to actually build in the schroot. We have more of a cross compile setup going. We'll have to adjust our dev environment accordingly then, thanks.

**Comment by smcv** [comment]
The recommended setup is now a Docker container; please see the README, section <https://github.com/ValveSoftware/steam-runtime/#building-in-the-runtime>. If you're more familiar with schroot than Docker, schroot can also work. The way we recommend setting up the schroot has changed in the last few months, so please check the README.

In principle the same `-sysroot` tarball should be possible to use with something like `gcc -sysroot /path/to/unpacked/directory` - is that what you mean by a cross-compile setup? - but I haven't tried it, and the details might be a bit murky. You'd need to make sure your compiler is configured to look for libraries to link with in both `lib/x86_64-linux-gnu` and `usr/lib/x86_64-linux-gnu` in the sysroot.

If you are using a compiler not provided by the Steam Runtime, make sure it doesn't add dependencies on the libraries that came with it: bundling copies of core libraries like libstdc++ with a game frequently breaks newer graphics drivers, either immediately or a few months or years later. Options like `-static-libgcc` and `-static-libstdc++` might help.
