### ISSUE TITLE
The Stanley Parable (221910) doesn't launch at all with slr

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-runtime#239]
[stanley.log](https://github.com/ValveSoftware/steam-runtime/files/4301940/stanley.log)

**Comment by kisak-valve** [comment]
Hello @soredake, this is https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#The_Stanley_Parable. Not a runtime issue.

**Comment by soredake** [comment]
Is there anything can be done from steam-runtime side to make game work out of the box?

**Comment by smcv** [comment]
Using the SteamLinuxRuntime container runtime for scout games is still considered to be experimental, so the workaround for any game-specific error that only happens in SteamLinuxRuntime is "don't". For historical reasons, scout games were never tested in a "pure" scout environment (SLR gets closer to this than previous runtime implementations), so if their developer was not sufficiently careful, they are likely to have non-scout dependencies.

If a game's developer has bundled a shared library with their game that also exists in the runtime and is depended on by the graphics stack, then that is never going to work reliably. That's really the developer's issue to solve, not Steam's; Valve has a policy of not modifying games' content depots.

The Steam Flatpak app on Flathub (which is considered unofficial from Valve's perspective) has a workaround for this, involving a `LD_AUDIT` plugin that declines to load these bundled libraries. However, this requires per-game configuration (to declare which bundled libraries shouldn't have been included) and a patched glibc (to make `LD_AUDIT` not trigger a significant performance regression).

**Comment by soredake** [comment]
It happens with or without SLR, so i suppose it's unfixable.
