### ISSUE TITLE
Company of Heroes 2 (231430) doesn't launch: missing libatomic.so.1

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-runtime#240]
[ch2.log](https://github.com/ValveSoftware/steam-runtime/files/4303659/ch2.log)

**Comment by kisak-valve** [comment]
From the log: `/media/disk1/Steam/steamapps/common/Company of Heroes 2/bin/CompanyOfHeroes2: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

**Comment by smcv** [comment]
`libatomic.so.1` was new with gcc 4.8. We didn't traditionally include it in the `LD_LIBRARY_PATH` Steam Runtime, which means games like this one were assuming the host system was going to provide it.

We should probably add it (and perhaps other gcc libraries?) to the container, and perhaps to the `LD_LIBRARY_PATH` runtime too.

@kisak-valve, please could you retitle this to capture the class of bugs it represents? `Company of Heroes 2 (231430) doesn't launch: missing libatomic.so.1` or something similar.

**Comment by TTimo** [comment]
Agreed, we support gcc 4.8 in the build schroot/docker image, it makes sense that we should distribute the implied libraries in the runtime too.

**Comment by smcv** [comment]
Any libraries that changed SONAME between our supported compilers (gcc 4.6, 4.8, 5) might as well all be included.

**Comment by smcv** [comment]
Please re-test with the Steam client update from 26 March (after exiting and re-launching Steam, `~/.steam/steam/ubuntu12_32/steam-runtime/version.txt` should say `steam-runtime_0.20200318.2`). We've added `libatomic.so.1`, `libitm.so.1` and `libquadmath.so.0` which hopefully solve this bug.

**Comment by soredake** [comment]
Game works now, thanks!
