### ISSUE TITLE
Add global SLR gui option to steam

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-runtime#243]
#### Your system information

* Steam Runtime Version: latest
* Distribution (e.g. Ubuntu 18.04):  ArchLinux
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae
  
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Add global gui options to steam:
`PRESSURE_VESSEL_SHARE_HOME` -> "Unshare home when using SLR"
`STEAM_RUNTIME_CONTAINER_ALWAYS` -> "Always use SLR for all games'

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @soredake, at this point those env variables are experimental. If you want them globally set, make a launcher script that sets them before calling Steam.
