### ISSUE TITLE
Docker images for steamrt version 0.20200318.2

### ISSUE THREAD

**Issue by rbernon** [ValveSoftware/steam-runtime#244]
Steam beta client ships runtime version 0.20200318.2 but the corresponding docker images aren't available on http://repo.steampowered.com/steamrt-images-scout/snapshots/

I'm not sure if it's an oversight or just some delay, or if the docker images are not the preferred way to build anymore?

**Comment by TTimo** [comment]
They are, we are rebuilding out CDN setup and image distribution setup so there's a delay.

**Comment by rbernon** [comment]
Great thanks, I'll wait!
