### ISSUE TITLE
steamoverlayvulkanlayer.so: wrong ELF class

### ISSUE THREAD

**Issue by FreeSlave** [ValveSoftware/steam-runtime#245]
#### My system information

* Steam Runtime Version: 0.20200318.2
* Distribution: Debian 9.12
* Link to your full system information: https://gist.github.com/FreeSlave/a19292a6624a0c3a52acdde537c57a6c
* Have you checked for system updates?: No. I can upgrade to Debian 10, but I don't think it's essential.
* Are you using the Steam Linux Runtime compatibility tool?: No

Seems like `steamoverlayvulkanlayer.so` loading is mixed up for different bit capacities. When retrieving info for i386-linux-gnu it tries to load `ubuntu12_64/steamoverlayvulkanlayer.so`, and for x86_64-linux-gnu on other hand it reads `ubuntu12_32/steamoverlayvulkanlayer.so`, therefore wrong ELF class. The error can be seen in the gist.

I don't know if it affects anything for me as I did not test anything vulkan-related on steam. Is there any simple way to test vulkan in steam? I can install The Talos Principle and try setting Vulkan renderer there.

**Comment by kisak-valve** [comment]
Hello @FreeSlave, this is the same as https://github.com/ValveSoftware/steam-for-linux/issues/6718. Steam LD_PRELOAD's 32 bit and 64 bit variants of some libraries when starting all games. One variant will silently work while the other harmlessly fails.

Look for `x11/vulkan` in your system information, which indicates that you do have a working vulkan driver stack for 32 bit and 64 bit, albeit a bit dated for your video card.
