### ISSUE TITLE
Cannot run Torchlight II (200710) with Steam Linux Runtime (libbz2.so.1 missing)

### ISSUE THREAD

**Issue by sonnyp** [ValveSoftware/steam-runtime#246]
#### Your system information

* Steam Runtime Version: 0.20200318.2
* Distribution (e.g. Ubuntu 18.04): Fedora 31
* [Link to your full system information](https://gist.github.com/sonnyp/41101f73b26de952aaba4ad961fe8565)

* Have you checked for system updates?: [Yes/No] Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

```
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 200710, ActionID 5] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 200710, ActionID 5] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 200710 "", ProcID 13637, IP 0.0.0.0:0
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 200710
>>> Adding process 13637 for game ID 200710
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to Completed with ""
>>> Adding process 13638 for game ID 200710
>>> Adding process 13639 for game ID 200710
>>> Adding process 13640 for game ID 200710
>>> Adding process 13641 for game ID 200710
>>> Adding process 13642 for game ID 200710
pressure-vessel-locale-gen: No locales need to be generated
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sonny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/mnt/8fd9d800-5d5d-4fb2-881c-aeaf60cbc813/SteamLibrary/steamapps/common/Torchlight II/ModLauncher.bin.x86_64: error while loading shared libraries: libbz2.so.1: cannot open shared object file: No such file or directory
>>> Adding process 13750 for game ID 200710
Game removed: AppID 200710 "", ProcID 13637 
Uploaded AppInterfaceStats to Steam
Exiting app 200710
No cached sticky mapping in ActivateActionSet.
```

**Comment by smcv** [comment]
> libbz2.so.1: cannot open shared object file: No such file or directory

It's probably significant that this is one of the few libraries where the canonical SONAME of the library (libbz2.so.1.0) is not the same as the name that the game is looking for (libbz2.so.1).

**Comment by riebimite** [comment]
I had this same problem and managed to get around it by copying the libbz2.so.1 library to ~/.local/share/Steam/steamapps/common/'Torchlight II'/lib64/.

**Comment by TTimo** [comment]
I believe we have other reports that detail how Torchlight II binaries are not correctly setup for steam linux runtime compatibility.

**Comment by smcv** [comment]
I think this particular report is orthogonal to the other Torchlight II brokenness.

We do have a machine-readable list of all the libraries in the runtime, including "aliases" like `libbz2.so.1.0` vs. `libbz2.so.1`, so it might be possible to teach pressure-vessel to take into account both the canonical SONAME and the alias when it populates `/overrides`.

**Comment by smcv** [comment]
> We do have a machine-readable list of all the libraries in the runtime, including "aliases" like libbz2.so.1.0 vs. libbz2.so.1, so it might be possible to teach pressure-vessel to take into account both the canonical SONAME and the alias when it populates /overrides.

This is now implemented and should be in the next beta, versioned >= 0.20210317.0; check for `pressure-vessel 0.20210317.0+srt1` or later in `SteamLinuxRuntime/VERSIONS.txt` if you are not sure whether you have this version.

With that version, the workaround of copying `libbz2.so.1` into the game's directory should not be necessary any more.

> I believe we have other reports that detail how Torchlight II binaries are not correctly setup for steam linux runtime compatibility

This change does not fix any other issues that might affect Torchlight II.

**Comment by kisak-valve** [comment]
Closing per the last comment.
