### ISSUE TITLE
Update CMake version within the runtime to 3.0

### ISSUE THREAD

**Issue by mdiluz** [ValveSoftware/steam-runtime#25]
Currently many CMake projects, configuration modules and scripts are dependent on CMake versions after 2.8.7.

While it's easy enough to compile the latest from source, would it be possible to upgrade to this version within the runtime repositories?

**Comment by baszalmstra** [comment]
+1 yes please

**Comment by PaulDana** [comment]
+1 yes please I need this as well

**Comment by computerquip** [comment]
Okay, why the fuck has this not happened yet? The issue is almost 3 years old.

**Comment by yaakov-h** [comment]
Way to exaggerate, its only a year and a half.

**Comment by computerquip** [comment]
Well, actually, the version of Cmake (2.8.7) packaged is from 2011, I looked at the incorrect version when checking: https://cmake.org/Wiki/CMake_Released_Versions

So, it's actually close to 5 years old.

**Comment by computerquip** [comment]
> Way to exaggerate, its only a year and a half.
Only a year and a half huh?

**Comment by yaakov-h** [comment]
Well actually,

> The issue is almost 3 years old.

Look up.
> mdiluz opened this issue on Dec 9, 2014

**Comment by computerquip** [comment]
I was referring to how old cmake is.

**Comment by timon37** [comment]
+1 it's getting worse with every passing month... and the issue is now (kinda) 3 years old!

**Comment by dos1** [comment]
This would be a huge QoL update, and shouldn't be hard to do - CMake 3.13.2 builds just fine in the steam-runtime environment.

**Comment by TTimo** [comment]
Yes, `--beta` should have `3.0.2-1+steamos1` at the moment, but I will look into adding a more recent version.

Btw don't use `--beta` atm for anything you plan on releasing immediately, it is ahead of the runtime available in the steam client. We are using it for some internal testing.

**Comment by TTimo** [comment]
Unfortunately, while compiling latest cmake in the runtime is trivially easy, the debian repackaging has a number of issues, so I don't have a good ETA to give on this.

**Comment by smcv** [comment]
The `--beta` SDK now has CMake 3.13.2-1+steamrt1.1 (backported from the latest in Debian unstable) instead of 3.0.2. Again, don't use `--beta` for anything you intend to release soon, because it's still ahead of the runtime available in the Steam client.

**Comment by TTimo** [comment]
Latest cmake is now available in `--beta` SDK. Matching steam beta client runtime was released today.
