### ISSUE TITLE
Some in-game text doesn't show up in CS:GO

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#252]
#### Your system information

* Steam Runtime Version: 0.20200318.2
* Distribution (e.g. Ubuntu 18.04): Fedora 31
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/Newbytee/e96a349d26ef4e999529ae8a5fb068e9
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:
The text that appears on the bomb when you plant it and the in-game (in-match) chat does not contain any text. The main menu chat works like it should however. 

#### Steps for reproducing this issue:

1. Start a match as terrorist
2. Attempt to write something into the chat
3. Plant a bomb at site and watch the display on the bomb

**Comment by kisak-valve** [comment]
Hello @Newbytee, this issue is already being tracked at #196. Closing as a duplicate.
