### ISSUE TITLE
[beta] steam-runtime freetype misses a symbol and breaks cs:go

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#253]
I did pin a 64bits recent fontconfig lib, but while loading cs:go it breaks because it is looking for a symbol missing in the  steam-runtime freetype:
failed to dlopen vguimatsurface_client.so error=/mnt/128/home/user/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
(following the issue ValveSoftware/steam-for-linux#7059)

**Comment by TTimo** [comment]
libfontconfig and libfreetype go together, matching incompatible versions together will cause problems. For a similar issue, see https://github.com/ValveSoftware/steam-for-linux/issues/6234

for reference, cs:go runs fine in container runtime, where it uses the matching pair of fontconfig and freetype from the steam runtime.
