### ISSUE TITLE
Counter-Strike: Global Offensive (730) takes significantly longer to start in Pressure Vessel

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#258]
#### Your system information

* Steam Runtime Version: 0.20200417.0
* Distribution (e.g. Ubuntu 18.04): Fedora 31
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/Newbytee/24732fd267eb69effeb00feb1e182232
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:
When launching CS:GO outside of Pressure Vessel, it takes 30 seconds — give or take — to launch and be usable. The game is also generally able to be played instantly, no waiting for connecting to CS:GO servers. 

The story is different when running the game inside of Pressure Vessel however. The game takes around 2 minutes to launch, and when it has launched, it spends an extra few seconds connecting to the CS:GO servers. One might imagine the latter is due to temporary networking issues, but it has been very consistent in my testing (and playing). 

I have CS:GO installed on a HDD with the filesystem ext4. This HDD is mounted at `/mnt/storage` and thus does not contain my root filesystem. 

#### Steps for reproducing this issue:

1. Start CS:GO in Pressure Vessel and measure the time 
2. Start CS:GO outside of Pressure Vessel and measure the time
3. Notice that CS:GO takes significantly longer to start in Pressure Vessel

**Comment by smcv** [comment]
I wonder whether this might be a problem with pressure-vessel's container interfering with name resolution or networking - similar to #226 and #264, but with the symptom being slowness rather than complete failure.

Please try the steps from https://github.com/ValveSoftware/steam-runtime/issues/226#issuecomment-587125941 and report back? That would provide useful information. The contents of your `/etc/nsswitch.conf` would also be interesting.

**Comment by Newbytee** [comment]
> Please try the steps from [#226 (comment)](https://github.com/ValveSoftware/steam-runtime/issues/226#issuecomment-587125941) and report back?

Done on the Geneshift issue, see https://github.com/ValveSoftware/steam-runtime/issues/264#issuecomment-664397269

**Comment by smcv** [comment]
Please try with the "Steam Linux Runtime" set to the public beta branch `client_beta`, and the latest Steam client beta (Sep 10 2020 or newer). `SteamLinuxRuntime/VERSIONS.txt` should identify it as pressure-vessel 0.20200909.0+srt1 and scout 0.20200910.0.

If that version works, then we can consider this issue to be a duplicate of #226.

Note that the beta Steam Linux Runtime is not expected to work with Steam client versions older than the current beta. This is not considered to be a bug.

**Comment by Newbytee** [comment]
This does indeed seem to be a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/226. I cannot reproduce it any more, the game starts up in around 30 seconds now (which is about what it takes to start when not using "Steam Linux Runtime").
