### ISSUE TITLE
Strange thing with at-spi library in Steam Runtime Heavy

### ISSUE THREAD

**Issue by Zenitur** [ValveSoftware/steam-runtime#263]
`STEAM_RUNTIME=1 STEAM_RUNTIME_HEAVY=1 steam` shows:

`./steamwebhelper: symbol lookup error: ./steam-runtime-heavy/libatspi.so.0: undefined symbol: g_type_class_adjust_private_offset`

**Edit:** the reason is not in at-spi library as I said before. The reason is that at-spi lib from the bundle was built with a newer version of Glib that presents in the bundle. I found that this function is replacing the `g_type_class_add_private()` function that  [becomes legacy](https://gitlab.gnome.org/GNOME/glib/commit/7e5db31d36532274c2b2428ef9bace796928785e) in Glib 2.58. So we need compile at-spi library with the older version of Glib or upgrade the Glib in the Steam Runtime Heavy too.

**Comment by TTimo** [comment]
'heavy' is based on Debian Jessie, not Ubuntu 12

I assume you mean to report that steamwebhelper fails to start. Please provide the complete output from Help > System Information (wait for the "Steam Linux Runtime Information" section to complete).

**Comment by Zenitur** [comment]
Hello **TTimo**! Thank you for a lot of native Linux games!
I did not expect such a quick response. So I'd edit my initial post before somebody will see that. But I didn't get in time.
My operation system is unsupported by Steam. It's SLES 11. It was made in the same time with the Ubuntu 10.04 and Debian 6, but the SLES is still having updates. I'd upgraded Glibc from 2.11 to 2.17 (and lose warranty) and then can start Steam. All dependencies (except of libc6) are in Steam Runtime.
Trying to fix some problem, I'd switched STEAM_RUNTIME_PREFER_HOST_LIBRARIES, STEAM_RUNTIME and STEAM_RUNTIME_HEAVY boolean variables. Then I was found that at-spi library cannot find some new function in glib2 from the runtime. So I decided to inform you.

**Comment by Zenitur** [comment]
> I assume you mean to report that steamwebhelper fails to start.
At this moment I cannot start all the Steam client, not only the steamwebhelper. I'm searching for the library in my system that I need to update.
> Please provide the complete output from Help > System Information (wait for the "Steam Linux Runtime Information" section to complete).
Currently I can't do that. I can use another `~/.local/share/Steam` prefix with a lot of pinned libs. It works. But the data of Steam Linux Runtime can be different.

**Comment by TTimo** [comment]
Pretty sure your glibc is too old, I think our min spec matches the glibc version that was in ubuntu 14.

The heavy runtime is only relevant to steamwebhelper, a 64 bit process launched by the steam client. It doesn't make much sense that you are showing me steamwebhelper errors if the steam client fails to start. The steam client binary is 32 bit and only uses scout though.

**Comment by Zenitur** [comment]
I think I'd opened the issue for nought. It might be than `libatspi.so.0` from the Steam Runtime Heavy is hating the **my** glib2.0 library, not the bundled copy. It seems that I did some LD_PRELOAD's of glib 2.34 libraries when I searched for the library that need an update.

So you can close the issue.

Anyway its strange that `./steam-runtime-heavy/libatspi.so.0` need `g_type_class_adjust_private_offset` that was appeared in Glib 2.58. Because Glib version is lower that 2.58 in Ubuntu 12.04 (the base of Steam Runtime) and Debian 8 "Jessie" (the base of Steam Runtime Heavy)
