### ISSUE TITLE
Geneshift (308600) fails to connect to servers

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#264]
#### Your system information

* Steam Runtime Version: 0.20200505.0
* Distribution (e.g. Ubuntu 18.04): Fedora 31
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/Newbytee/1a74ab85c5d0831cf44a0bcaca51ddc4
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:
When not running the game in Pressure Vessel, it starts up and connects as it should. In Pressure Vessel, however, it fails to connect to servers and attempting to reconnect does not help.

Possibly related: https://github.com/ValveSoftware/steam-runtime/issues/226, https://github.com/ValveSoftware/steam-runtime/issues/227, https://github.com/ValveSoftware/steam-runtime/issues/192, https://github.com/ValveSoftware/steam-runtime/issues/262

Log created from `> /tmp/geneshift-log 2>&1` as launch option: [geneshift-log.txt](https://github.com/ValveSoftware/steam-runtime/files/4750746/geneshift-log.txt)

#### Steps for reproducing this issue:

1. Start game in Pressure Vessel
2. Observe that it fails to connect

**Comment by smcv** [comment]
Something is going wrong with either name resolution (DNS) or other Internet communication.

The steps from https://github.com/ValveSoftware/steam-runtime/issues/226#issuecomment-587125941 might help to pin down what is wrong. It would also be interesting to see what is in your `/etc/nsswitch.conf`.

**Comment by Newbytee** [comment]
> If you use the test UI (PRESSURE_VESSEL_WRAP_GUI=1) and run a shell instead of the game, then run getent ahosts example.com, what happens?

![image](https://user-images.githubusercontent.com/4428753/88547263-c5d63400-d01d-11ea-9896-7c7f54564f1b.png)

> If you use the test UI and run curl http://93.184.216.34, what happens? (Hopefully you should get some HTML that says "404 - Not Found".)

![image](https://user-images.githubusercontent.com/4428753/88547358-e605f300-d01d-11ea-9736-42e8db302ab4.png)

> Is your /etc/resolv.conf a symbolic link to a different file?

```
[neboula@shock ~]$ file /etc/resolv.conf 
/etc/resolv.conf: ASCII text
```

> What are the contents of your /etc/resolv.conf?

[resolv.conf.txt](https://github.com/ValveSoftware/steam-runtime/files/4982246/resolv.conf.txt)

> Is there anything else unusual about how your host system resolves names or accesses the internet?

Not that I'm aware of.

**Comment by smcv** [comment]
As I suspected, name resolution is broken but networking works fine, the same as in #226. I'm not sure why.

Your `resolv.conf` looks normal: the only odd thing about it is that it has a large number of upstream DNS servers listed, some of which are IPv6.

The relevant line from your `nsswitch.conf`:

```
hosts:      files mdns4_minimal [NOTFOUND=return] dns myhostname
```

also seems normal.

Here is something you could try:

* Download the SDK runtime that matches the Platform you're using, from https://repo.steampowered.com/steamrt-images-scout/snapshots/0.20200505.0/com.valvesoftware.SteamRuntime.Sdk-amd64,i386-scout-runtime.tar.gz
* Create a `scout_sdk` directory inside `SteamLinuxRuntime` if it doesn't already exist
* Unpack the SDK runtime into that directory, so you have files like `scout_sdk/metadata` and `scout_sdk/files/bin/bash` inside your `SteamLinuxRuntime` directory
* Use the debug GUI to select the SDK runtime instead of the default Platform runtime, and run a shell instead of the game like you did before
* Inside that shell, try:

```
busybox nslookup example.com 2606:4700:4700::1111
busybox nslookup example.com 2606:4700:4700::1001
busybox nslookup example.com 1.1.1.1
busybox nslookup example.com 1.0.0.1
busybox nslookup example.com 8.8.8.8
```

**Comment by Newbytee** [comment]
> Your `resolv.conf` looks normal: the only odd thing about it is that it has a large number of upstream DNS servers listed, some of which are IPv6.

Both my ISP and router have IPv6 support for what it's worth.

> ```
> busybox nslookup example.com 2606:4700:4700::1111
> busybox nslookup example.com 2606:4700:4700::1001
> busybox nslookup example.com 1.1.1.1
> busybox nslookup example.com 1.0.0.1
> busybox nslookup example.com 8.8.8.8
> ```

I was initially going to paste the output of all of these commands, however I soon realised that it was identical (yes, 100% identical, regardless of whether it was with an IPv6 DNS or IPv4 DNS) with all of them. Here's the output:

```
(steamrt scout 0.20200505.0)neboula@shock:/mnt/storage/SteamLibrary/steamapps/common/Geneshift$ busybox nslookup example.com 8.8.8.8
ERROR: ld.so: object '/home/neboula/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Server:    2606:4700:4700::1111
Address 1: 2606:4700:4700::1111

nslookup: can't resolve 'example.com'
```

**Comment by smcv** [comment]
... what?! That's *really* strange. You're explicitly asking nslookup to use 8.8.8.8, and it's ignoring you and using the first server from `/etc/resolv.conf` instead...

**Comment by smcv** [comment]
I have a possible explanation, but I'll need to add some code to pressure-vessel before we can test it. I'll come back to this.

**Comment by smcv** [comment]
I have a new idea for why this might be failing. Please try this in an interactive shell inside the container:

```
LD_DEBUG=files getent ahosts example.com 2>&1 | tee getent-ahosts.log
```

and then send `getent-ahosts.log` as a gist.

I think you might see an error in that log, something like this:

```
/lib/x86_64-linux-gnu/libnss_dns.so.2: error: symbol lookup error: undefined symbol: (something) (fatal)
```

If you do, then I think I know how we can solve this in a future pressure-vessel release.

**Comment by Newbytee** [comment]
> I have a new idea for why this might be failing. Please try this in an interactive shell inside the container:
> 
> ```
> LD_DEBUG=files getent ahosts example.com 2>&1 | tee getent-ahosts.log
> ```
> 
> and then send `getent-ahosts.log` as a gist.
> 
> I think you might see an error in that log, something like this:
> 
> ```
> /lib/x86_64-linux-gnu/libnss_dns.so.2: error: symbol lookup error: undefined symbol: (something) (fatal)
> ```
> 
> If you do, then I think I know how we can solve this in a future pressure-vessel release.

I can confirm that there is a such error. Log: https://gist.github.com/Newbytee/9cabc38c515c6713b7574de6bfb0107c

**Comment by smcv** [comment]
OK, I think a fix will be in the next pressure-vessel release.

**Comment by smcv** [comment]
Please try with the "Steam Linux Runtime" set to the public beta branch `client_beta`, and the latest Steam client beta (Sep 10 2020 or newer). `SteamLinuxRuntime/VERSIONS.txt` should identify it as pressure-vessel 0.20200909.0+srt1 and scout 0.20200910.0.

Note that the beta Steam Linux Runtime is not expected to work with Steam client versions older than the current beta. This is not considered to be a bug.

**Comment by Newbytee** [comment]
The game is able to connect! Great job. :+1:
