### ISSUE TITLE
ETS2 doesn't start

### ISSUE THREAD

**Issue by nachfuellbar** [ValveSoftware/steam-runtime#269]
#### Your system information

* Steam Runtime Version: don't know how to find
* Distribution:  Fedora 32
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
https://gist.github.com/nachfuellbar/5941b6a2bc570519a61901036dc3669a
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes (why asking this in the runtime repo?)

#### Please describe your issue in as much detail as possible:
Euro Truck Simulator 2 should start

#### Steps for reproducing this issue:

1. Start Euro Truck Simulator 2 with Steam Linux Runtime enabled for the game

**Comment by smcv** [comment]
> why asking this in the runtime repo?

This git repo is used for bug reporting for both the old `LD_LIBRARY_PATH` version of the Steam Runtime (used if you do not enable the Steam Linux Runtime compatibility tool), and the new Steam Linux Runtime compatibility tool. We need to know which one an issue reporter is using :-)

**Comment by smcv** [comment]
> Steam Runtime Version: don't know how to find

From the Gist, it's:

```
Steam Linux Runtime Container Information:
{
...
  "runtime" : {
    "path" : "/",
    "version" : "0.20200505.0",
```

**Comment by smcv** [comment]
Does ETS2 work as expected when you are *not* using the Steam Linux Runtime?

**Comment by nachfuellbar** [comment]
Thanks for the explanation :)

Yes it runs pretty good without the Steam Linux Runtime - some sound issues but that's it
Pretty much tried using it to test if the sound issue is there when using the runtime

**Comment by RyuzakiKK** [comment]
I tries ETS2 with the Steam Linux Runtime container enabled and it worked without any particular problem.

@nachfuellbar can you please try it again?  Recently Steam Linux Runtime got a major update that changed how the container is created and probably this fixed the issue that you reported.

**Comment by nachfuellbar** [comment]
@RyuzakiKK just tried with a short game and seems to work - didn't confirm with a long session but the game starts now at least ;)

**Comment by smcv** [comment]
If it starts, that's usually good enough! Thanks for re-testing.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing per the last couple comments.
