### ISSUE TITLE
Wrong library category

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-runtime#281]
This tool, `Steam Linux Runtime - Soldier`, appears in our game library as a game we can run, when **Proton 5.13** is selected globally in Steam Settings.
It should appear in the **Tools** category instead of the Games category.

**Comment by kisak-valve** [comment]
Hello @Zorrototo, please don't intentionally open duplicate issue reports. Closing as a duplicate of #280.

**Comment by Zorrototo** [comment]
I got a 404 Github error page when I tried the first time what are you talking about.
