### ISSUE TITLE
pressure-vessel fails with could not find libnvidia-fatbinaryloader.so

### ISSUE THREAD

**Issue by zfigura** [ValveSoftware/steam-runtime#282]
#### Your system information

* Steam Runtime Version: 2
* Distribution (e.g. Ubuntu 18.04): Manjaro 20.1
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/zfigura/b4510259f8307e4bab2307589ea908b8
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: No

#### Please describe your issue in as much detail as possible:

Launch Steam, select the application Undertale (391540), click "play". Nothing happens, and in a couple seconds "stop" reverts back into "play". From all indications the application is never launched.

Full console output of such actions, with PRESSURE_VESSEL_VERBOSE=1, is here: https://gist.github.com/zfigura/d94f72a2e49bd6c45f0c8279bccb6563

In particular I notice the line

i386-linux-gnu-capsule-capture-libs: code 2: Missing dependencies: Could not find "libnvidia-fatbinaryloader.so.430.40" in LD_LIBRARY_PATH "", ld.so.cache, /lib or /usr/lib

which appears (among other things) every time I try to launch a game which uses soldier. I'm using nouveau, which leads me to believe that nouveau was not accounted for.

A game using Proton 5.0 still works, and one using 5.13 fails with the same symptoms, so I'm inclined to blame soldier.

**Comment by kisak-valve** [comment]
Hello @zfigura, please see #275 and the discussion around https://github.com/ValveSoftware/Proton/issues/4278#issuecomment-711439731 https://github.com/ValveSoftware/Proton/issues/4278#issuecomment-711443063

Looks like pressure-vessel is having a hard time with broken left over files from an nVidia 430.40 install in the past.

**Comment by zfigura** [comment]
Oops, you're quite right. Somehow I still had lib32-opencl-nvidia still installed despite removing the rest of the blob.

Sorry I didn't see the other issues, I guess I forgot to check for *closed* issues as well as open ones.
