### ISSUE TITLE
SLR - Soldier - launch_args[@]: unbound variable

### ISSUE THREAD

**Issue by MurdoMaclachlan** [ValveSoftware/steam-runtime#284]
I'm tentatively placing this in a separate report from ValveSoftware/Proton#4266 and ValveSoftware/Proton#4278 since I can't confirm if it's either of those issues, as no logs are created. I've so far tested ten games/software, all of which run with 5.0-9 (unless otherwise noted) and none of which run with 5.13.

The extra problem comes in when I try to create logs. I've added the PROTON_LOG=1 command to all their launch options, and can confirm logs are being created with earlier versions, but no logs are created when I run them with 5.13.

[System information](https://gist.github.com/MurdoMaclachlan/9bc9a0f0d251bfe981ec054aa3ca6364)

**Games/software tested:**

- Bloons TD5
- Campfire Pro ("runs" with 5.0-9, but no window appears; runs perfectly with 4.11-13)
- Dark Souls Remastered
- Dark Souls II
- Elder Scrolls III: Morrowind
- Elder Scrolls IV: Oblivion
- Elder Scrolls V: Skyrim
- Pharaoh + Cleopatra
- Thief Gold
- Witcher 3: Wild Hunt

**Comment by kisak-valve** [comment]
Thanks, `/home/murdo/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point: line 179: XDG_RUNTIME_DIR: unbound variable` tells us you've encountered a pressure vessel issue that was previously mentioned at https://github.com/ValveSoftware/Proton/issues/4278#issuecomment-710712973.

**Comment by CSahajdacny** [comment]
I have a similar problem: 
None of my games works with Proton 5.13 and Proton logs are not even created.

[My system](https://gist.github.com/CSahajdacny/07a4c2e835804bb7368673bd8035d8f4)
[
The steam console output](https://gist.github.com/CSahajdacny/261d51ce2f47ed757d98a261ed0e0e4b)

**Comment by kisak-valve** [comment]
Hello @CSahajdacny, no, your log does not have an issue with XDG_RUNTIME_DIR, and reads more like #230. Please open a separate issue report.

**Comment by CSahajdacny** [comment]
> Hello @CSahajdacny, no, your log does not have an issue with XDG_RUNTIME_DIR, and reads more like #230. Please open a separate issue report.

How must I call it?...

**Comment by kisak-valve** [comment]
Maybe something like pressure-vessel-wrap: no supported CPU architectures on Ubuntu?

**Comment by kisak-valve** [comment]
@MurdoMaclachlan, per "Fixed Proton 5.13 on systems that do not define XDG_RUNTIME_DIR (steam-runtime#284)" in the [2020-10-23 Steam client update](https://store.steampowered.com/news/76967/) and corresponding Steam Linux Runtime - Soldier update, please retest this issue.

**Comment by MurdoMaclachlan** [comment]
It still doesn't work with the new update, unfortunately, but I'm not sure the error is the same. The new log is [here](https://gist.github.com/MurdoMaclachlan/32b4b7aca0c69e688f9c3236f3c0be0d).

On a side note, since the update, starting Steam has always resulted in a console popping up with

> Steam needs to install these additional packages: 
        curl, python-apt, xterm, xz-utils, zenity, libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386

followed by a password prompt that doesn't accept my root password and complains that my non-root login isn't a sudoer (which I keep that way so I don't accidentally break something). However, Steam runs fine regardless of what happens on this console (also, curl, xterm and zenity are definitely all installed, others might be), and I can even close the console and nothing seems to go wrong.

**Comment by kisak-valve** [comment]
> Steam needs to install these additional packages: 
        curl, python-apt, xterm, xz-utils, zenity, libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386

This sounds unrelated to the issue being tracked here, and also not tailored for Slackware's package management. This is something that Slackware's package maintainer for Steam should take a look at if there is one.

**Comment by smcv** [comment]
`launch_args[@]: unbound variable` is triggered by an older version of bash on the host system (older than 4.4, I think). Newer versions have a more helpful interpretation of what counts as "unset" for `set -u` when using arrays.

I think we know how to fix this; it'll probably be in the next update.

**Comment by smcv** [comment]
> I think we know how to fix this

This is reproducible on SteamOS 2 (which is based on Debian 8, so its bash version is quite old), and the fix I had in mind works there. It'll probably be in the next SteamLinuxRuntime update for both scout and soldier.

If you want to try it out "early", you can edit the script in the depot like this: https://gist.github.com/smcv/88f59d07057301e539bbf97e0d238d3c

**Comment by smcv** [comment]
`launch_args[@]: unbound variable` should be fixed in the public beta versions of SteamLinuxRuntime and SteamLinuxRuntime_soldier.

If you look in `SteamLinuxRuntime_soldier/VERSIONS.txt`, to have this fix, the line starting with `SteamLinuxRuntime` should say `v0.20201124.0-0-gd107701` (or later, if there's a new beta by the time you read this).

**Comment by MurdoMaclachlan** [comment]
Might seem like a silly question, but how I go about updating the runtime? I don't have much experience with using it.

**Comment by kisak-valve** [comment]
Hello @MurdoMaclachlan, you can opt into the beta release by going to Library in Steam, then searching for Steam Linux Runtime - Soldier, then go to the Properties by either right clicking on it or the gear icon. After that go to the Betas tab and you can select the beta marked `use with Steam beta`.

**Comment by MurdoMaclachlan** [comment]
Thanks!

Just tested it with Dark Souls Remastered, and it seems like everything is working with no issues!

**Comment by kisak-valve** [comment]
Closing per the last comment.
