### ISSUE TITLE
Bad RIP value from gtk3-nocsd package

### ISSUE THREAD

**Issue by marekmarecki** [ValveSoftware/steam-runtime#286]
Proton version: **5.13-1**
Ubuntu 20.04.1, nvidia

Games affected (all non-native games that I have installed are affected):

- Age of Empires II: Definitive Edition (id 813780)
- Age of Empires II (2013) (id 221380)
- Fallout: New Vegas (id 22380)
- Grand Theft Auto IV: The Complete Edition (id 12210)

With proton 5.0-9 everything above was launching ok.

I can see some strange things in syslog:
`Oct 22 20:53:38 ubuntu-pc kernel: [  593.762926] pressure-vessel[12294]: segfault at 0 ip 0000000000000000 sp 00007fffaeee1eb8 error 14 in pressure-vessel-launch[400000+14000]
Oct 22 20:53:38 ubuntu-pc kernel: [  593.762933] Code: Bad RIP value.`

Logs that I collected:

- Steam's [stdout](https://gist.github.com/marekmarecki/91a4a303f7a0b981ff366bc39b06997e) from launching steam client and trying running AoE2:DE. Not much info here.
- [stdout with more info](https://gist.github.com/marekmarecki/a81484d359f657a75325e1abdcb38a8e) (~/.steam/errror.log)
- [System information](https://gist.github.com/marekmarecki/229dadbf07d4bfad8db04de2a7a3250b)
- I think here is most valuable info: [syslog](https://gist.github.com/marekmarecki/55f8f43b64e9e7bd9d191447127c9740) when trying to launch AoE2:DE

Putting PROTON_LOG=1 %command% in launch options **is not** creating any logs (it was creating logs with proton 5.0-9).

Where should I look to get to the bottom of the problem?

Thanks

---
Small update:
I have the exact same problem (the same errors in logs) on another machine (also Ubuntu 20.04.1
 but steam installed from package provided by Steam's site, not provided by distro - if that makes any difference anyway)

**Comment by kisak-valve** [comment]
Hello @marekmarecki, this reads like a pressure vessel issue, which Proton 5.13 runs on top of. I suspect that the debian-provided Steam package is stealing any useful hints from the terminal spew and putting it in `~/.steam/error.log`. Can you check if that exists and if there's any hints in it?

**Comment by marekmarecki** [comment]
Hi @kisak-valve. My bad. When I last checked this file, there was nothing interesting inside. Now it is generating more info. I updated the problem description with another gist. There are some errors there, like this for example:

`ERROR: ld.so: object '/home/marek/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Segmentation fault

`

**Comment by marekmarecki** [comment]
I can confirm that removing gtk3-nocsd package from system and rebooting OS **solves** the problem: [log from game running on 5.13-1](https://gist.github.com/marekmarecki/893f24007ddab0caa1a8becbb75e52ad). Confirmed on two machines. Big thanks to [aib's comment](https://github.com/ValveSoftware/Proton/issues/4278#issuecomment-715843927).

**Comment by smcv** [comment]
The `libgtk3-nocsd.so.0` preload library is known to break non-Steam programs quite regularly, too, and the GTK maintainers consider it to be a problem. I would recommend not using it.

If we do anything to solve this crash, it will probably be the brute-force approach: when we are adjusting `LD_PRELOAD` to work inside the container, remove any entry that looks like it might be `libgtk3-nocsd`.

**Comment by marekmarecki** [comment]
I removed the package, no problem. It was not installed directly, just as some dependency at some  point in the past, I do not need it. But some folks may also have it and not know what to do, especially if it don't come up in logs that easily (in my attached logs there is no mention of this lib; would need to dig deeper to find it).
Cheers and keep up the good work :+1:

**Comment by aib** [comment]
Indeed; I used gdb to trace the segfault to nocsd. And there's no direct connection to Steam or Proton, so it would be hard to stumble upon the solution. That's why I commented; glad to see it helped!

**Comment by smcv** [comment]
pressure-vessel versions >= 0.20210105.0 automatically disable gtk3-nocsd for the container.

These versions are available in the beta branch of SteamLinuxRuntime and SteamLinuxRuntime_scout starting from today (check `VERSIONS.txt`). They are not in the normal/stable branch yet, but probably will be soon.

**Comment by kisak-valve** [comment]
Closing per the last comment.
