### ISSUE TITLE
Cannot find Steam instance under Proton 5.13 when .steam is a symlink

### ISSUE THREAD

**Issue by giomasce** [ValveSoftware/steam-runtime#291]
#### Your system information

* Steam client version (build number or date): built Oct 28 2020
* Distribution (e.g. Ubuntu): Debian unstable
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Proton 5.13 doesn't start when `.steam` is a symlink (in my configuration this is done do move that whole directory in another partition where there is more space). More specifically, if you enable Steam Play and then launch any title requiring Proton, a dialog appears saying that the game is launching, but a few seconds later the dialog disappears and the game doesn't launch. The launch button quickly return from blue "Stop" to green "Launch".

Many messages are written on the console log, the two meaningful ones appearing to be:
```
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
```

Further investigation leads to noting that Proton calls `steam.exe`, which is is hardcoded in the Proton Wine build. `steam.exe` acutally calls `SteamAPI_Init` and then aborts when it fails. The source for `SteamAPI_Init` is not available, so I can only guess at the reasons for its failure. However, I noticed that setting `DBG_PATHMATCH` environment variable to a non empty value enables some debug logging, from which it can be interred that the library tries to manually walk the path to `$HOME/.steam/steam.pid`, failing to detect the appropriate entries from `readdir` results. I suspect that the walking procedure only tests for directories and files, ignoring symlinks.

#### Steps for reproducing this issue:

1. Make sure that `.steam` is a symlink to a directory that exists and is empty.
2. Install Steam on Linux, enable Beta and enable Steam Play with Proton 5.13. Update the client, and download a Windows-only title.
3. Run the title. Notice that it doesn't work as described above.

**Comment by kisak-valve** [comment]
Hello @giomasce, starting with Proton 5.13-1, Proton now runs on top of Steam Linux Runtime - Soldier.  This container environment does not have unlimited access to the host system and it sounds like the folder your .steam symlink points to isn't getting mounted into the container.

**Comment by giomasce** [comment]
That's possible, it is in another partition (my home is on a SDD disk, but there is not a lot of space there, so I moved `.steam` on another partition on an HDD). This is not a completely uncommon setup, I believe, so it might be sensible to try to support it.

**Comment by giomasce** [comment]
Yes, bind mounting seems to work. Thanks!

**Comment by smcv** [comment]
A `.steam` symlink should work in the latest beta (VERSIONS.txt should say pressure-vessel is version 0.20201124.0+srt1). Bind-mounting or having a separate Steam library on a larger disk is a better long-term answer to this, though: symlinks are always going to be a bit fragile in situations like this.

**Comment by smcv** [comment]
I believe this is fixed in the current stable version.

**Comment by kisak-valve** [comment]
Closing per the last comment.
