### ISSUE TITLE
Spaces in Proton path (all versions) break games started from Launch Options' bash script

### ISSUE THREAD

**Issue by Saroumane** [ValveSoftware/steam-runtime#299]
#### Your system information

* Steam client version (build number or date): Oct 28 2020
* Distribution : Ubuntu 20.04.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Problem description
When I use a script in (in a game's Launch Options) to start a Proton game, this game fails to start because of spaces in Proton's path.

Example for Proton game Mushihimesama :
My Launch Options : `/home/user/steamCRT.sh %command%`

steamCRT.sh is used to switch video output to a TV before game is started, then switch back to PC Monitor after game has ended :

```
#!/bin/bash
xrandr --output DisplayPort-0 --off --output VGA-2-1 --mode "640x480i"

eval $@

xrandr --output DisplayPort-0 --primary --auto 
sleep 6
xrandr --output VGA-2-1 --off

```

Why it does not work ? Let's look at the %command% which is passed to the script as $@ :
`/home/user/.steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --deploy=soldier --suite=soldier --verb=waitforexitandrun -- /home/user/.steam/steamapps/common/Proton 5.13/proton waitforexitandrun /home/user/.steam/steamapps/common/Mushihimesama/default.exe`

If I copy-paste this line to command line, it fails because the space in Proton path is not escaped :
`/home/user/.steam/steamapps/common/Proton 5.13/proton ` 
should be 
`/home/user/.steam/steamapps/common/Proton\ 5.13/proton`

#### Workaround
Let's hardcode the escape in the script :
```
lnch=$(echo $@ | sed 's/Proton /Proton\\ /g')
eval $lnch
```

#### What I expect 
Universal solution : please don't put spaces in Proton path. (space in paths are too ambiguous, that's why underscores are available)
You can rename them as Proton_x.y or Protonx.y

**Comment by kisak-valve** [comment]
Hello @Saroumane, this reads like an issue with how Proton gets called by Steam Linux Runtime - Soldier. Even if the space wasn't in Proton 5.13, the user can have spaces in the path to their Steam Library. Let's treat this as a Pressure Vessel issue until there's a stronger indication the issue the issue is elsewhere.

**Comment by Saroumane** [comment]
That's funny this issue got transferred : I initially created this issue in steam-runtime repo (that's I used their template), but at the last moment I remembered that there is a separate repo for Proton

**Comment by kisak-valve** [comment]
I suspect this is a bug in your script from your use of `eval $@` which splits arguments on white space. You might get better behavior with `eval $*`. From https://stackoverflow.com/questions/12314451/accessing-bash-command-line-args-vs/12316565.

**Comment by Saroumane** [comment]
Oh nice find ! I was not aware of this subtle differences.
I tried all 4 options mentioned : 
```
eval $* 
eval $@ 
eval "$*"  
eval "$@"
```
=> same result, game can't start.

But the solution is just :
**`"$@"`**
(eval command must be avoided and quotes are mandatory. No other combination works)

Thanks again for your input, very helpful.
