### ISSUE TITLE
Mount&Blade Warband (48700) doesn't work with runtime

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-runtime#301]
#### Your system information

* Steam Runtime Version: pressure-vessel
* Distribution : Linux Mint 20 (Ubuntu 20.04 based)
* Link to your full system information (Help -> System Information) in a [Gist]: 
  https://gist.github.com/Leopard1907/234879515a98a92d5f9c93507192460a
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:
Game and configuration menu doesn't work with runtime. Configuration menu works without runtime but game doesn't work due to some weirdly missing deps like libfmode. Used to work on Ubuntu 18.04 base , not sure what is changed here. 

What is a configuration menu:

![Ekran Görüntüsü - 2020-11-17 10-13-17](https://user-images.githubusercontent.com/24878978/99358238-47e4b400-28be-11eb-8ee6-c495836778a6.png)

pressure-vessel log:

[pressure-vessel.log](https://github.com/ValveSoftware/steam-runtime/files/5551826/pressure-vessel.log)

#### Steps for reproducing this issue:

1. Trying to run mentioned game with Steam Linux Runtime from compatibility options menu
2. Observing

**Comment by kisak-valve** [comment]
Hello @Leopard1907, `/home/asus/.local/share/Steam/steamapps/common/MountBlade Warband/mb_warband_linux: error while loading shared libraries: libGLEW.so.2.1: cannot open shared object file: No such file or directory` looks like a line of interest from the log. Looks like this is a game-bundled dependency that it can't find for some reason.

**Comment by smcv** [comment]
Steam Runtime version 1 does not include GLEW 2.1 (Steam Runtime version 2, as used for Proton 5.13, does - but there's currently no support for compiling games against that).

According to https://steamdb.info/depot/48703/ this game bundles its own copy. Either that copy is not found for some reason, or maybe it's found but its dependencies are missing?

**Comment by smcv** [comment]
> Configuration menu works without runtime but game doesn't work due to some weirdly missing deps like libfmode

Do you perhaps mean that without using SteamLinuxRuntime, you get an error message involving `libfmodex64.so`?

I think something might be wrong with the way this game arranges for its bundled libraries to be used.

Does `mb_warband.sh` add the game directory to `LD_LIBRARY_PATH`?

Does `mbw_config.sh` add the game directory to `LD_LIBRARY_PATH`?

It looks as though this game is set up to run `mb_warband_linux` instead of `mb_warband.sh`, which is perhaps a mistake... unless the executable has its `DT_RUNPATH` set to `${ORIGIN}` or something?

**Comment by Leopard1907** [comment]
@smcv Sorry for late reply. Yes , without SLR i get `/home/asus/.local/share/Steam/steamapps/common/MountBlade Warband/mb_warband_linux: error while loading shared libraries: libfmodex64.so: cannot open shared object file: No such file or directory` which is odd i was able to play this very game just fine on Ubuntu 18.04 based system like 2 years ago.

Content of `mb_warband.sh`:

#!/bin/sh

PROGRAM_DIRECTORY="`dirname "$0"`"
export LD_LIBRARY_PATH="$PROGRAM_DIRECTORY"

"$PROGRAM_DIRECTORY/mb_warband_linux" "$@"

Content of `mbw_config.sh:

#!/bin/sh

PROGRAM_DIRECTORY="`dirname "$0"`"
export LD_LIBRARY_PATH="$PROGRAM_DIRECTORY"

"$PROGRAM_DIRECTORY/mbw_config_linux" "$@"

As for what executable is doing , i have no idea.

**Comment by Leopard1907** [comment]
Hi again. At least without SLR native version works now with `LD_LIBRARY_PATH="." %command%`

**Comment by smcv** [comment]
> native version works now with `LD_LIBRARY_PATH="." %command%`

The fact that you need to do that is a game-specific bug. I suspect the game's developer had intended to set the Steam metadata so that Steam would run `mb_warband.sh`, instead of running `mb_warband_linux` directly.

`LD_LIBRARY_PATH="$(pwd):${LD_LIBRARY_PATH}" %command%` would be a somewhat cleaner workaround. Does that work, when running it without SLR?

Setting the `LD_LIBRARY_PATH`, as in your workaround, is probably not going to work when going through SLR, because it's difficult to piece together what the search path *should* be - we have to derive it from several sources of information.

If you set the launch command to `./mb_warband.sh # instead of %command%`, then that might work with or without the SLR container. Again, that's a workaround, which you shouldn't need to do... but checking whether it works would be a useful way to check that my understanding of what's happening is correct.

**Comment by smcv** [comment]
> export LD_LIBRARY_PATH="$PROGRAM_DIRECTORY"

This is *also* a bug in the game: to use the Steam Runtime correctly, it should be using something like `export LD_LIBRARY_PATH="$PROGRAM_DIRECTORY${LD_LIBRARY_PATH+":${LD_LIBRARY_PATH}"}"`.

**Comment by Leopard1907** [comment]
> LD_LIBRARY_PATH="$(pwd):${LD_LIBRARY_PATH}" %command% would be a somewhat cleaner workaround. Does that work, when running it without SLR?

Yes , it works.

**Comment by smcv** [comment]
> > native version works now with `LD_LIBRARY_PATH="." %command%`
>
> The fact that you need to do that is a game-specific bug. I suspect the game's developer had intended to set the Steam metadata so that Steam would run `mb_warband.sh`, instead of running `mb_warband_linux` directly.

I think the reason this got through the developer's QA might be that older versions of `run.sh` had a bug where they would usually leave an unwanted `:` at the end of the `LD_LIBRARY_PATH`, which meant "... and then try the current working directory". We recently fixed that bug, which seems to have made a few games regress: #317 is another.

That would explain how this game ever worked...

I think this is really a game bug, but we might be able to work around it.

**Comment by xrogaan** [comment]
> I think this is really a game bug, but we might be able to work around it.

I did notice taleworlds people of the problem regarding warband and seems to have been [acknowledged](https://forums.taleworlds.com/index.php?threads/warband-launch-option-is-misconfigured-on-linux.435710/). Warband being an old game, and them being busy with their newer titles, it may take some time before anything is done on their end.

**Comment by smcv** [comment]
Thanks - it's always best when game-specific issues can be fixed in the game, rather than being worked around in the runtime.

**Comment by smcv** [comment]
The changes in the beta client described in #317 should be fixing this for games run *without* the SteamLinuxRuntime (but only those games, right now).

Resolving https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/46 and updating to a newer Steam client (not yet released) will fix this for games run *with* the SteamLinuxRuntime.

**Comment by xrogaan** [comment]
Did the said Steam client update happened yet? Can this issue be closed?

**Comment by RyuzakiKK** [comment]
I just tested this game with the latest stable version of SLR and it seems to work as expected.

@Leopard1907 can you please try it again with SLR enabled, and without any custom launch options, and report back if it works?

**Comment by Leopard1907** [comment]
@RyuzakiKK Hi there, i was able to test it just now. 

- First of all game doesn't need this anymore it seems. So it works without SLR without resorting to this workaround:

  https://github.com/ValveSoftware/steam-runtime/issues/301#issuecomment-734214116

- Game now works with SLR too, but config menu doesn't work with SLR. Config menu:

  https://user-images.githubusercontent.com/24878978/99358238-47e4b400-28be-11eb-8ee6-c495836778a6.png

- With SLR Mangohud OpenGL doesn't seem to work out of the box , with either `mangohud %command` or `mangohud --dlsym %command%`. 

  It needs ```LD_PRELOAD=$LD_PRELOAD:/usr/lib/mangohud/lib/libMangoHud_dlsym.so:/usr/lib/mangohud/lib/libMangoHud.so %command%``` which is not exclusive to native apps but rather exclusive to any OpenGL apps ( Proton and native ) within runtime. Such as mentioned here. 

  https://github.com/flightlessmango/MangoHud/issues/560

- Here is the log of all happenings i listed above, grabbed with ```__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only STEAM_LINUX_RUNTIME_LOG=1 steam```
[slr-app48700-t20210722T182510.log](https://github.com/ValveSoftware/steam-runtime/files/6863471/slr-app48700-t20210722T182510.log)

```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20210630.17			# Overall version number
pressure-vessel	0.20210630.0			
scripts	v0.20210623.0-0-ga389036			# Entry point scripts, etc.
soldier	0.20210629.0	soldier	0.20210629.0	# soldier_platform_0.20210629.0/
```

**Comment by smcv** [comment]
I think we can consider the original issue you reported - the game not working - to be fixed.

> Game now works with SLR too, but config menu doesn't work with SLR

Please could you open a separate issue for this, and describe more precisely what "doesn't work" means here?

> With SLR Mangohud OpenGL doesn't seem to work out of the box , with either mangohud %command or mangohud --dlsym %command%.
>
> It needs LD_PRELOAD=$LD_PRELOAD:/usr/lib/mangohud/lib/libMangoHud_dlsym.so:/usr/lib/mangohud/lib/libMangoHud.so %command% which is not exclusive to native apps but rather exclusive to any OpenGL apps ( Proton and native ) within runtime.

Please could you open a separate issue for this, and give more details there? It would be particularly useful to know what exact environment variables and values get set by `mangohud` on your system.

If this is not game-specific, then it would be useful if you could check whether a small free-to-play OpenGL game like https://store.steampowered.com/app/302380/Floating_Point/ has the same problem - if it does, then that'll mean everyone experiencing a similar problem can easily be testing the same thing.

**Comment by Leopard1907** [comment]
Config menu doesn't work means; clicking on it doesn't do anything with SLR. So since it is still a part of the game ( a config menu where you set resolution,language, other graphical features, key assignment ) i thought it is still not a full fix. 

I can try that game and couple of other GL games too, will open a seperate issue for that then.

**Comment by smcv** [comment]
> So since it is still a part of the game ( a config menu where you set resolution,language, other graphical features, key assignment ) i thought it is still not a full fix.

Sure, there's still something wrong with the combination of SLR and this particular game, but that doesn't mean it's the same issue: we've fixed the library search path issue that was causing the game itself not to start, and whatever problem you're having with the config menu is still happening. So it would be useful to have a matching set of Help -> System Information + steps to reproduce + log, so we can start the debugging process again for the config menu issue, and the easiest way to keep that debugging process separate, and not get it mixed up with different/outdated info about the issue that we already fixed, is a separate issue report.

**Comment by Leopard1907** [comment]
Sure, closing as fixed then. Will open new reports about those seperate issues.
