### ISSUE TITLE
Some combination of amd.com driver and AMDVLK driver messes up Proton 5.13-2

### ISSUE THREAD

**Issue by TheAquabat** [ValveSoftware/steam-runtime#310]
#### Your system information

* Steam Runtime Version: soldier_0.20201203.0
* Distribution (e.g. Ubuntu 18.04):  Kde Neon 20.04 (Ubuntu Like)
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
https://gist.github.com/TheAquabat/9ab48978c5666dd5e17688efcc5f78c6
* Have you checked for system updates?: [Yes]
* Are you using the Steam Linux Runtime compatibility tool?: [YES]

#### Please describe your issue in as much detail as possible:
Can't get Proton 5.13-2 (or 5.12-3rc2) to work don't know what the problem is really at some point it worked with this same setup and the same installed libraries, first I thought it was the gtk nocsd package, but after removing that I thought I was hitting this bug https://github.com/ValveSoftware/steam-runtime/issues/309#
but removing the headless libs driver that I downloaded amd.com for the OpenCL driver ( I installed it like this sudo ./amdgpu-pro-install --opencl=legacy,pal --headless ) doesn't seem to do much difference. But what it makes me doubt if it is a library problem is that removing the amdvlk driver, makes Proton Ge 5.21 work (also uses pressure vessel) . So this is probably a library problem.

container log 
https://gist.github.com/TheAquabat/68ad6d803d39170afdc18bb2e75b3f4f

#### Steps for reproducing this issue:

1. Install amdvlk https://github.com/GPUOpen-Drivers/AMDVLK deb package, and amd.com driver in headless mode https://www.amd.com/es/support/graphics/amd-radeon-5600-series/amd-radeon-rx-5600-series/amd-radeon-rx-5600-xt
2. Try running Proton 5.13-2
3. (not sure of all this steps might be correct , could be another different bug)

**Comment by kisak-valve** [comment]
Hello @TheAquabat, your system information is incomplete, please let it finish gathering the extended diagnostics information and update your gist.

**Comment by TheAquabat** [comment]
Ok I updated it I could try running the previous version to discard if it is not a regression, might be the reason why it worked at some point with the same setup.
I tried soldier previous version and Proton previous version (I'm running 5.13-3-rc2) none of that fixed the issue. 
What I said, it's what I suppose the problem is because removing amdvlk has some effect, but I could be a completely different issue because I tried many thing to discard what the issue was.
here's a Proton log
https://gist.github.com/TheAquabat/31b4bebe5625df19a6ca79831fcefb30

**Comment by TheAquabat** [comment]
Ok more info some games work some doesn't .

**Comment by TheAquabat** [comment]
I don't know I'm closing this for now because I only have vague affirmations to the issue, maybe what I'm seeing it's just that a handfull of games have regressed on Proton and this is not a steam runtime bug, because I tried other games like Dirt Rally 2.0 and Witcher 3 and they worked. It looked similar to https://github.com/ValveSoftware/steam-runtime/issues/309 but it might be not the same thing.
