### ISSUE TITLE
Steam Linux Runtime does not display system cursor

### ISSUE THREAD

**Issue by nervyalloy51** [ValveSoftware/steam-runtime#311]
#### System Information
 
* Distribution: Arch Linux x86_64 
* System Information: [System-info](https://gist.github.com/nervyalloy51/c3554cd69f3ef3db2da1b0d3c5333f10)
* Checked for system update: Yes
* using the Steam Linux Runtime: Yes

#### Issue Description:

Games ran with `Steam Linux Runtime` compatibility tool display generic cursor rather than the default system cursor.
also affecting games ran with `Proton 5.13` see [Proton #4317](https://github.com/ValveSoftware/Proton/issues/4317)

#### Steps for reproducing this issue:

1. Install Linux native game on steam
2. Set compatibility tool option to `Steam Linux Runtime`

**Comment by smcv** [comment]
> does not display system cursor

Yes, a non-default system-wide configured cursor is one of the many aspects of the host system that the container doesn't have.

https://github.com/flatpak/flatpak/issues/114 and https://github.com/flatpak/flatpak/issues/709 cover similar ground, but Flatpak has user-installable "runtime extensions" for particular themes, which we don't.

pressure-vessel picks up host system fonts (like Flatpak does, and in fact using basically the same code), but does not pick up host system icons or cursors (like Flatpak doesn't).

**Comment by zaps166** [comment]
@smcv Any chance to fix it? Cursor theme is system-wide, it should be set in all apps (if app doesn't use its own).

**Comment by smcv** [comment]
The latest beta version of pressure-vessel attempts to share the cursor theme (and the icon theme) with the host system. (This is harder to achieve than it sounds!)

To check which version you have, look at `SteamLinuxRuntime_soldier/VERSIONS.txt`. The version that fixes this issue is `depot 0.20210907.26` or later.

**Comment by Ammako** [comment]
This is live, and on my end it works well.

**Comment by kisak-valve** [comment]
A Steam Linux Runtime - Soldier release with this has been promoted to the mainline update channel. Closing as fixed.

**Comment by YellowOnion** [comment]
Is there anyway to figure out why cursors aren't working inside of steam-runtime the patch linked only lets the container find the cursor, I suspect it's either NixOS own steam wrapper not building the theme directories correctly, or something weird with the way I have sway setup.

**Comment by kisak-valve** [comment]
Hello @YellowOnion, please open a new issue report so that your issue can be tracked properly.

**Comment by dnkmmr69420** [comment]
I have this issue on steam proton games. Any way to fix it?

**Comment by smcv** [comment]
> I have this issue on steam proton games. Any way to fix it?

Those two sentences are not enough information for a developer to understand what is happening on your system or why. Please open a separate issue with full details.

**Comment by dnkmmr69420** [comment]
check this https://github.com/NixOS/nixpkgs/issues/245234 It is a NixOS Related issue
