### ISSUE TITLE
mesa can not find radeonsi_dri.so inside Steam Linux Runtime on Slackware 14.2

### ISSUE THREAD

**Issue by 414n** [ValveSoftware/steam-runtime#318]
#### Your system information

* Steam Runtime Version: soldier_0.20201203.0
* Distribution (e.g. Ubuntu 18.04): Slacware64 14.2
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/):  [steam_info](https://gist.github.com/414n/34891616266f2d4e4489173e8bbee632)
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Similar to what is reported in #309, when using Proton-5.13 in Steam, some games that worked flawlessly with Proton-5.0 fail to start, while others run successfully.
Those that fail seem to fail in a similar manner, printing out libGL errors before throwing a number of seh exceptions, culminating in what seems like a crash.
Do note that the system is running on mesa, so no drivers are installed in `/opt` or other locations.
Here is a summary (i used `LIBGL_DEBUG=verbose` to print some more information):

Games that won't start:
 - Killer Instinct [steam-577940.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5668868/steam-577940.log.gz)
 - Witcher 3 [steam-292030.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5668894/steam-292030.log.gz)
 - Ghostrunner demo [steam-1249200.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5668954/steam-1249200.log.gz)
 - Alien swarm [steam-563560.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5669003/steam-563560.log.gz)

Games that do start:
 - Ultra Street Fighter IV [steam-45760.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5668963/steam-45760.log.gz)

I performed some standalone tests by launching an xterm instance like this:
```sh
PRESSURE_VESSEL_VERBOSE=1 \
LC_ALL=en_US \
/path/to/SteamLinuxRuntime_soldier/_v2-entry-point \
  --deploy=soldier \
  --suite=soldier \
  --verb=run  &> /tmp/pressure.log -- xterm -e bash --norc
```

Inside this environment, I then tried launching the host `glxgears` or `glxinfo` binaries (which are mapped to `/run/host/usr/bin/glx{gears,info}`) and the output I got is this: [glxinfo_srt.log](https://github.com/ValveSoftware/steam-runtime/files/5669022/glxinfo_srt.log). This seems to confirm that the `radeonsi_dri.so` library is nowhere to be found inside the container `/overrides`:
```sh
/overrides/lib/i386-linux-gnu/dri/:
total 0
drwxr-xr-x 2 alan users 60 Dec  9 22:33 0
drwxr-xr-x 2 alan users 60 Dec  9 22:33 1
drwxr-xr-x 2 alan users 60 Dec  9 22:33 2
drwxr-xr-x 2 alan users 60 Dec  9 22:33 3
lrwxrwxrwx 1 alan users 39 Dec  9 22:33 i965_drv_video.la -> /run/host/usr/lib/dri/i965_drv_video.la
lrwxrwxrwx 1 alan users 39 Dec  9 22:33 i965_drv_video.so -> /run/host/usr/lib/dri/i965_drv_video.so
lrwxrwxrwx 1 alan users 42 Dec  9 22:33 nouveau_drv_video.so -> /run/host/usr/lib/dri/nouveau_drv_video.so
lrwxrwxrwx 1 alan users 39 Dec  9 22:33 r600_drv_video.so -> /run/host/usr/lib/dri/r600_drv_video.so
lrwxrwxrwx 1 alan users 43 Dec  9 22:33 radeonsi_drv_video.so -> /run/host/usr/lib/dri/radeonsi_drv_video.so

/overrides/lib/x86_64-linux-gnu/dri/:
total 0
drwxr-xr-x 2 alan users 60 Dec  9 22:33 0
drwxr-xr-x 2 alan users 60 Dec  9 22:33 1
drwxr-xr-x 2 alan users 60 Dec  9 22:33 2
drwxr-xr-x 2 alan users 60 Dec  9 22:33 3
lrwxrwxrwx 1 alan users 41 Dec  9 22:33 i965_drv_video.la -> /run/host/usr/lib64/dri/i965_drv_video.la
lrwxrwxrwx 1 alan users 41 Dec  9 22:33 i965_drv_video.so -> /run/host/usr/lib64/dri/i965_drv_video.so
lrwxrwxrwx 1 alan users 44 Dec  9 22:33 nouveau_drv_video.so -> /run/host/usr/lib64/dri/nouveau_drv_video.so
lrwxrwxrwx 1 alan users 41 Dec  9 22:33 r600_drv_video.so -> /run/host/usr/lib64/dri/r600_drv_video.so
lrwxrwxrwx 1 alan users 45 Dec  9 22:33 radeonsi_drv_video.so -> /run/host/usr/lib64/dri/radeonsi_drv_video.so
```

I believe this is due to Slackware having the DRI drivers installed by the mesa package under `/usr/lib{,64}/xorg/modules/dri` instead of `/usr/lib/{i386,x86_64}-linux-gnu/dri/` (Debian) or `usr/lib/dri/radeonsi_dri.so` (Arch), meaning that they probably won't get picked up and mapped accordingly when launching the container.

I also tried adding these following overrides (found [here](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/master/pressure-vessel/wrap.1.md)) when launching the test environment or the games, but to no avail: `PRESSURE_VESSEL_RUNTIME=soldier PRESSURE_VESSEL_HOST_GRAPHICS=1 LIBGL_DRIVERS_PATH=/usr/lib64/xorg/modules/dri:/usr/lib/xorg/modules/dri`. Maybe I did not correctly understand how they should be used.

This is the output from Steam with `PRESSURE_VESSEL_VERBOSE=1`: [steam.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5668971/steam.log.gz)

#### Steps for reproducing this issue:

1. use a distro with DRI drivers under `/usr/lib64/xorg/modules/dri`;
2. select Proton 5.13 for any of the games on the "don't work" list;
3. launch the game

**Comment by smcv** [comment]
> I believe this is due to Slackware having the DRI drivers installed by the mesa package under `/usr/lib{,64}/xorg/modules/dri`

The location of the DRI drivers for Mesa is something that we have to "just know", so if distributions move them into arbitrary places, we have to specifically hard-code those arbitrary places.

At the moment we look for DRI drivers in `${libdir}/dri`, where `${libdir}` is any of these:

* Debian-style multiarch (`lib/x86_64-linux-gnu` and `lib/i386-linux-gnu`)
* Red Hat-style multilib (`lib64` and `lib`)
* Arch-style multilib (`lib` and `lib32`)

If it would be possible to persuade Slackware packagers to put the Mesa DRI modules in `/usr/lib{,64}/dri/` (the same as the VA-API `*_drv_video.so` modules), then that would be the same layout as Red Hat, which would solve this permanently. You can see that this is already partially working for Slackware: we find your VA-API modules, but not your Mesa DRI modules.

Or, we can hard-code more paths in pressure-vessel...

> I also tried adding these following overrides when launching the test environment or the games, but to no avail: PRESSURE_VESSEL_RUNTIME=soldier PRESSURE_VESSEL_HOST_GRAPHICS=1 LIBGL_DRIVERS_PATH=/usr/lib64/xorg/modules/dri:/usr/lib/xorg/modules/dri. Maybe I did not correctly understand how they should be used.

`PRESSURE_VESSEL_RUNTIME=soldier` is set automatically by `SteamLinuxRuntime_soldier`, so you don't need to override that.

`PRESSURE_VESSEL_HOST_GRAPHICS=1` is the default so you don't need to override that.

Setting `LIBGL_DRIVERS_PATH=/usr/lib64/xorg/modules/dri:/usr/lib/xorg/modules/dri` *should* work as a workaround for this, but for historical reasons we don't currently check `LIBGL_DRIVERS_PATH`.

**Comment by 414n** [comment]
>If it would be possible to persuade Slackware packagers to put the Mesa DRI modules in /usr/lib{,64}/dri/ (the same as the VA-API *_drv_video.so modules), then that would be the same layout as Red Hat, which would solve this permanently. You can see that this is already partially working for Slackware: we find your VA-API modules, but not your Mesa DRI modules.
>Or, we can hard-code more paths in pressure-vessel...

I can try to ask other slackers on LQ if there's a motivation for having the DRI modules in the current path and not in a layout a-la Red Hat.
In the meantime, may I suggest another, perhaps more generic way to look for that path?
On my system, the pkgconfig file for dri (`dri.pc`) has the following contents:
```
prefix=/usr
libdir=${prefix}/lib64
includedir=${prefix}/include

dridriverdir=/usr/lib64/xorg/modules/dri

Name: dri
Description: Direct Rendering Infrastructure
Version: 20.2.3
Requires.private: libdrm >=  2.4.102
Cflags: -I${includedir}
```
So, pkg-config queries like `PKG_CONFIG_PATH=${libdir} pkg-config dri --variable=dridriverdir` -- where `${libdir}` points first to 64-bit libdir and then to 32-bit libdir in a multilib setup -- return the exact path that is currently needed.
Obviously, this requires the `pkg-config` utility installed and the `${libdir}/pkgconfig/dri.pc` file to be present on the system, but it could solve the problem in a generic way for currently "unmanaged distros", providing a fallback after searching in the current known paths has returned nothing.

>Setting LIBGL_DRIVERS_PATH=/usr/lib64/xorg/modules/dri:/usr/lib/xorg/modules/dri _should_ work as a workaround for this, but for historical reasons we don't currently check LIBGL_DRIVERS_PATH.

Please, do correct me if I'm wrong: does this mean that the value inside that variable, while it could solve this issue, is silently ignored by the runtime at the moment?

**Comment by smcv** [comment]
> Obviously, this requires the pkg-config utility installed and the ${libdir}/pkgconfig/dri.pc file to be present on the system

This typically won't be available on non-developer systems, and querying it on the offchance that it might work will slow down container setup for everyone.

> does this mean that the value inside [LIBGL_DRIVERS_PATH], while it could solve this issue, is silently ignored by the runtime at the moment?

It would be more a workaround than a solution, but yes.

For most graphics drivers (Vulkan, EGL, ...) we use the same code paths as for the steam-runtime-system-info diagnostic tool, which does understand LIBGL_DRIVERS_PATH; but because the DRI drivers were the first ones implemented, they go through different code that doesn't check the environment variable. I'm looking into fixing that, but some refactoring is needed before we can get there.

**Comment by 414n** [comment]
Small update: I tried compiling custom mesa packages overriding DRI drivers path, but that resulted in AIGLX not finding them anymore, so I guess that, without recompiling X too, it won't work.
Back to the original situation, I manually copied the DRI driver files from `${libdir}/xorg/modules/dri` to `${libdir}/dri` (symlinking them was not enough) and, finally, some titles successfully started working with Proton-5.13.
I will perform more through tests tomorrow.

**Comment by smcv** [comment]
> I tried compiling custom mesa packages overriding DRI drivers path, but that resulted in AIGLX not finding them anymore, so I guess that, without recompiling X too, it won't work.

Right, this is something that would have to be done as a coordinated transition by the distro.

> I manually copied the DRI driver files from ${libdir}/xorg/modules/dri to ${libdir}/dri (symlinking them was not enough)

That's a reasonable workaround.

Symlinking should work *if* the symbolic links are *relative* (`/usr/lib/dri/radeonsi_dri.so -> ../xorg/modules/dri/radeonsi_dri.so`). It's unlikely to work if the symbolic links are absolute (`/usr/lib/dri/radeonsi_dri.so -> /usr/lib/xorg/modules/dri/radeonsi_dri.so`), because `/usr` means something different in the container (making that happen is the whole purpose of using the container).

**Comment by smcv** [comment]
I think https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/200 will fix this.

**Comment by 414n** [comment]
> This typically won't be available on non-developer systems, and querying it on the offchance that it might work will slow down container setup for everyone.

You're right. It's a pity though, as that would be the exact required information...

> > I manually copied the DRI driver files from ${libdir}/xorg/modules/dri to ${libdir}/dri (symlinking them was not enough)
> 
> That's a reasonable workaround.
> 
> Symlinking should work _if_ the symbolic links are _relative_ (`/usr/lib/dri/radeonsi_dri.so -> ../xorg/modules/dri/radeonsi_dri.so`). It's unlikely to work if the symbolic links are absolute (`/usr/lib/dri/radeonsi_dri.so -> /usr/lib/xorg/modules/dri/radeonsi_dri.so`), because `/usr` means something different in the container (making that happen is the whole purpose of using the container).

I can confirm that relative symlinks work too, and are an easy-enough workaround for now.

> I think https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/200 will fix this.

Wow, thanks for already trying to upstream support for Slackware!
BTW, I [did open a thread on LQ](https://www.linuxquestions.org/questions/showthread.php?p=6194136) inquiring for information on this matter.
Here's an updated list of working/non-working titles after applying the symlink/copy workaround:

**Games that do start now on Proton-5.13**:
 - Killer Instinct
 - Alien Swarm

**Games that still do not start on Proton-5.13**:
 - The Witcher 3 (fails opening an ALSA audio device just after loading `XAudio2_7.dll`, see https://github.com/ValveSoftware/Proton/issues/607#issuecomment-743436942)
 - Ghostrunner demo - same ALSA issue as The Witcher 3

Given that the remaining issues on the tested titles do not seem to be mesa-related anymore, I guess those should be dealt with elsewhere. I'd keep this open to test the changes in https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/200, if/when they get accepted.

**Comment by smcv** [comment]
If audio works in Killer Instinct and Alien Swarm, then pressure-vessel is probably working correctly and any further issues are probably Proton.

If audio doesn't work anywhere, then that might be a separate pressure-vessel issue, or it might be Proton.

From your mentions of ALSA dmix, do I assume correctly that you're not using PulseAudio? Using PulseAudio is the code path that has been tested more; there is some setup code borrowed from Flatpak, to make the host system's PulseAudio AF_UNIX socket available in the container. Plain ALSA without dmix should in principle also work (we're not deliberately doing anything to make it *not* work, and the whole host `/dev` is visible in the container, including `/dev/snd`) but is not routinely tested.

For ALSA with dmix, I have no idea. If it needs some sort of daemon or assumes that everything is using the same version of the ALSA libraries, then it's unlikely to work (because the container is using its own libraries, mostly from Debian 10, so that Proton and future native Linux games can be run even on older or incompatible host OSs). In general, pressure-vessel is going to be in the same situation as Flatpak, whatever that means.

**Comment by 414n** [comment]
> If audio works in Killer Instinct and Alien Swarm, then pressure-vessel is probably working correctly and any further issues are probably Proton.
> If audio doesn't work anywhere, then that might be a separate pressure-vessel issue, or it might be Proton.

I agree, this is definitely on Proton/wine side. See below.

> From your mentions of ALSA dmix, do I assume correctly that you're not using PulseAudio? Using PulseAudio is the code path that has been tested more; there is some setup code borrowed from Flatpak, to make the host system's PulseAudio AF_UNIX socket available in the container. Plain ALSA without dmix should in principle also work (we're not deliberately doing anything to make it _not_ work, and the whole host `/dev` is visible in the container, including `/dev/snd`) but is not routinely tested.
> 
> For ALSA with dmix, I have no idea. If it needs some sort of daemon or assumes that everything is using the same version of the ALSA libraries, then it's unlikely to work (because the container is using its own libraries, mostly from Debian 10, so that Proton and future native Linux games can be run even on older or incompatible host OSs). In general, pressure-vessel is going to be in the same situation as Flatpak, whatever that means.

No, I'm currently on PulseAudio, so ALSA dmix issues should not be in the picture right now.
A Proton user pointed me to install the XACT Engine via winetricks inside the prefix and that indeed solved the crash at start for Witcher 3 (still have to test Ghostrunnner demo), so I believe there's nothing to blame on the runtime, for now. :wink: 

Anyway, thanks for the information!

**Comment by 414n** [comment]
Ok, Ghostrunner works too by just forcing `WINEDLLOVERRIDES="xaudio2_7=n,b"`. :+1:

**Comment by smcv** [comment]
Today's `SteamLinuxRuntime_soldier` beta should be able to find DRI drivers in `${libdir}/xorg/modules/dri`, without needing your workaround. To check whether you have this version, look for pressure-vessel 0.20210105.0 or later in VERSIONS.txt.

Let's treat the PulseAudio issues as separate (#343).

**Comment by 414n** [comment]
Yes, I can confirm that DRI drivers are correctly loaded now on 0.20210105.0 after removing the symlinks that I previously created as a workaround.
Here's a steam log with `PRESSURE_VESSEL_VERBOSE=1` when launching Killer Instinct, for comparison: [steam.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5778322/steam.log.gz).

Thank you everyone
