### ISSUE TITLE
Libcairo 1.17.4 from Arch gets pinned due to lower .so version

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-runtime#330]
#### Your system information

* Steam Runtime Version: Latest in the Steam Beta Client as of today, also tested on the Steam Stable Client as of today, same issue on both.
* Distribution: Arch Linux (EndeavorOS)
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/LiamDawe/4d125f0b20159003ac6d38cfa36a1e36
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes and No, tried with and without.

#### Please describe your issue in as much detail as possible:

The game fails to run, with this error:

> symbol lookup error: /usr/lib/libgdk-3.so.0: undefined symbol: cairo_surface_unmap_image

However, it runs perfectly when launched outside of Steam. So I assume this is a runtime error somewhere?

#### Steps for reproducing this issue:

1. Download [APICO Demo](https://store.steampowered.com/app/1390190/APICO/)
2. Try to run
3. Fail and cry
4. Run it perfectly outside of Steam

**Comment by kisak-valve** [comment]
Missing symbol issue also seen recently in https://github.com/ValveSoftware/SteamVR-for-Linux/issues/410.

**Comment by kisak-valve** [comment]
Hello @LiamDawe, can you test if removing the `libcairo.so.2` symlinks in the `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs*` folders has an effect. It looks like the steam runtime `libcairo.so.2.11000.2` library is getting evaluated as newer than `libcairo.so.2.1174.0` from the Arch package.

**Comment by LiamDawe** [comment]
Yep, that's the issue exactly. Launches without a fuss now.

**Comment by kisak-valve** [comment]
I suspect that there's a libcairo bug here which got exposed by Arch's transition to a meson build 2 weeks ago (https://github.com/archlinux/svntogit-packages/commit/2e6a027d5026edf1c708c100167b719d0a6f83fc).

**Comment by LiamDawe** [comment]
Rightyo, what's the best way to get this properly reported?

**Comment by kisak-valve** [comment]
Looks like the project is hosted on gitlab.freedesktop.org, so https://gitlab.freedesktop.org/cairo/cairo/-/issues, possibly in coordination with Arch's package maintainer(s) for Cairo.

**Comment by LiamDawe** [comment]
Right, [here goes then](https://gitlab.freedesktop.org/cairo/cairo/-/issues/442).

**Comment by smcv** [comment]
Fix merged in cairo and will hopefully arrive in your distro soon.

**Comment by RyuzakiKK** [comment]
FYI I tried Arch's `cairo-git` and I confirm that `libcairo` doesn't get pinned anymore. So we just need to wait for the new release of cairo to land.

**Comment by psychon** [comment]
If you want to speed up the process (no idea when the next cairo release / snapshot comes out), you could open an issue with Arch's issue tracker and ask them to apply https://gitlab.freedesktop.org/cairo/cairo/-/commit/e9ccb1d8d095482e4139da658e679d5aad56b184 to their version.

**Comment by tingvarsson** [comment]
Reported on Arch: https://bugs.archlinux.org/task/69012

**Comment by tingvarsson** [comment]
And now in the Arch repos as well, 1.17.4-3!

**Comment by LiamDawe** [comment]
Looking good now, all fixed.
