### ISSUE TITLE
Paradox Launcher (ALL modern PDS titles) broken - native

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-runtime#331]
#### Your system information

* Steam Runtime Version: Latest Stable
* Distribution: Arch Linux (EndeavorOS)
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
https://gist.github.com/LiamDawe/8cf345fddfb0d9da9515edd708baef2d
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes and No, tried with both, broken with both.

#### Please describe your issue in as much detail as possible:
The Paradox Launcher (native titles) no longer works with the Steam Runtime. It does, however, work perfectly fine with [steam-native](https://www.archlinux.org/packages/multilib/x86_64/steam-native-runtime/) on Arch Linux so it seems something has made it incompatible somewhere with the Steam Runtime so this will affect more and more people as distributions upgrade.

Don't know if it's related but Proton 5.13-3 mentions how it had a fix for the Paradox Launcher, so perhaps a similar fix can be used here since it's a lib issue somewhere.

#### Steps for reproducing this issue:

1. Run an up to date Arch Linux install
2. Try to run Prison Arcitect, Stellaris, Crusader Kings III and so on... 
3. Watch as nothing happens.
4. Launch the game directly outside of Steam / or / run with steam-native and it's fine

**Comment by smcv** [comment]
> Steam Runtime Version: Latest Stable

That's not a version number, but from your System Information dump, you're using version 0.20201203.1.

Which version of the Steam client are you using? Please look for "Steam package versions" followed by a large integer in Help -> About Steam - unfortunately this information is not currently shown in the System Information window. To give you an idea of what to look for, 1607650432 is a recent beta.

> Try to run Prison Arcitect, Stellaris, Crusader Kings III and so on

To be clear, are these the native Linux versions of these games?

> Watch as nothing happens

If you run Steam from a terminal emulator (gnome-terminal, Konsole, xterm or similar), what output does it produce when you try to run one of these games?

Please try with the ordinary `LD_LIBRARY_PATH`-based Steam Runtime (not Steam Linux Runtime) first - that's the simplest situation.

After sending the error output to this issue, if you are currently using the stable version of the Steam client, it might help to try switching to the public beta: Steam -> Settings -> Account -> Beta Participation -> Change... -> Steam Beta Update. There was a regression fixed recently that could be causing this (but to confirm, I'd need to see the error messages you currently get, *before* you try switching to the beta).

If this is the issue that I think it might be, then this will not immediately fix running these games through the Steam Linux Runtime - but showing us the error output will help us to fix it for the Steam Linux Runtime mode, too.

> Don't know if it's related but Proton 5.13-3 mentions how it had a fix for the Paradox Launcher

If you're running the native Linux versions of the affected games, then changes in Proton to make the Windows version of the Paradox Launcher work in Proton/Wine are unlikely to be directly relevant.

**Comment by LiamDawe** [comment]
> That's not a version number, but from your System Information dump, you're using version 0.20201203.1.

Sidenote then, the Steam client having that listed in the About Steam menu would probably help? Just a thought.

> Which version of the Steam client are you using? Please look for "Steam package versions" followed by a large integer in Help -> About Steam - unfortunately this information is not currently shown in the System Information window. To give you an idea of what to look for, 1607650432 is a recent beta.

Oh right, okay. December 7, Steam package version 1607372145

> To be clear, are these the native Linux versions of these games?

Yes. Sorry, I guess I should be explicitly clear now with Proton being a thing. WIll try to remember for future reports.

> If you run Steam from a terminal emulator (gnome-terminal, Konsole, xterm or similar), what output does it produce when you try to run one of these games?

Here's the full output of trying to launch Stellaris for example:

https://gist.github.com/LiamDawe/8adca8775342b1da22016b044163697f

> Please try with the ordinary LD_LIBRARY_PATH-based Steam Runtime (not Steam Linux Runtime) first - that's the simplest situation.

That is what I have been doing. As noted in the OP I tried both normal and the container runtime. Both have the same issue.

Trying it with the latest Steam Client Beta, December 11 package version 1607650432 here's what happens when trying to run Stellaris:

https://gist.github.com/LiamDawe/9e3f4571df07d4d9bb8d6112981546a6

> If you're running the native Linux versions of the affected games, then changes in Proton to make the Windows version of the Paradox Launcher work in Proton/Wine are unlikely to be directly relevant.

No worries, thought it might be worth noting anyway just in case! :+1:

**Comment by smcv** [comment]
I don't see anything useful in the output you provided, unfortunately. I was hoping for error messages from the game or from the dynamic linker.

**Comment by LiamDawe** [comment]
Okay, I'm open to any and all suggestions on what to try to find the issue :+1:

**Comment by RyuzakiKK** [comment]
I reproduced it with Prison Architect and it seems like the issue is caused by Scout's libcairo. I'm checking if it's because the game assumes to have a symbol that is missing or if it's something else.

**Comment by smcv** [comment]
> it seems like the issue is caused by Scout's libcairo

libcairo. Arch Linux. #330?

**Comment by LiamDawe** [comment]
@RyuzakiKK fantastic, how did you find that out with no errors showing? Because you're right. I tested the same fix as in #330 from @kisak-valve and yup sure enough Stellaris launcher now works as does Crusader Kings II.

Fantastic find!

**Comment by RyuzakiKK** [comment]
@LiamDawe I tried `gdb` first but the game was not crashing with a backtrace, so I went with `strace` and there I found a `symbol lookup error` related to cairo.

**Comment by LiamDawe** [comment]
Fixed as of latest Arch updates.
