### ISSUE TITLE
Skyrim SE stopped running

### ISSUE THREAD

**Issue by vhda** [ValveSoftware/steam-runtime#333]
#### Your system information

* Steam Runtime Version: soldier_0.20201203.0
* Distribution (e.g. Ubuntu 18.04): Debian Sid
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/vhda/1707da2df165598076ae6d5668021aa7
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Typically I see two instances of the virtual desktop: the first before Vulkan Shader compilation and a second after. The game then launches in the latter.
Now no virtual desktop shows even though I see the wineserver and wine coming up.
Obviously, I overrode the setting to force wine virtual desktops.

Note 1: I updated my packages on Sunday 13th, played the game again on Monday 14th, on Tuesday 15th I was no longer able to play it. At this point I've updated my packages again trying to see if it was something that was wrong there, but with no avail. Nonetheless, I still think the problem is specific to Steam, since I did not update packages and game stopped launching.
Note 2: Tried to run Breathedge and it runs successfully.

pressure-vessel.log: https://gist.github.com/vhda/0e7c207fc04572ba7f97ef717d90562b

#### Steps for reproducing this issue:

1. Launch game

**Comment by vhda** [comment]
Resetting compatdata appears to work.

**Comment by kisak-valve** [comment]
Hello @vhda, that would indicate a Proton issue instead of a Pressure Vessel issue. If you figure out what happened there, feel free to add a note to https://github.com/ValveSoftware/Proton/issues/4.

Closing as not-a-runtime-issue.
