### ISSUE TITLE
Red Dead Redemption 2 currently can not run if it sees duplicate vulkan icds.

### ISSUE THREAD

**Issue by dylandn** [ValveSoftware/steam-runtime#336]
#### Your system information

* Steam Runtime Version: steam-runtime_0.20201203.1
* Distribution (e.g. Ubuntu 18.04): Gentoo 17.1
* https://gist.github.com/dylandn/2a98381b1b1a854119d6139e16da706a
* Have you checked for system updates?: yes
* Are you using the Steam Linux Runtime compatibility tool?: beats me

#### Please describe your issue in as much detail as possible:
As per this post here, https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-748537235
I am starting a new issue based on this person's suggestion. Please see his comment for details. To quote them: " there's a Pressure Vessel issue happening there. Pressure Vessel is finding the 32 bit and 64 bit radv vulkan icds twice and then putting it in the container environment twice for each bit-ness which is why the game is seeing two devices."

I only have one AMDGPU, but that turns into 2 for some reason.

**Comment by kisak-valve** [comment]
For clarity, this doesn't usually matter, but if Red Dead Redemption 2 sees multiple video cards, then it tries to use child window rendering and falls over starting with a `fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!` in the Proton log and goes downhill from there. With a single 64 bit Vulkan icd, this doesn't happen.

**Comment by dylandn** [comment]
> rezk ~ # ls -l /usr/share/vulkan/icd.d/
> total 1
> -rw-r--r-- 1 root root 147 Dec 19 11:04 radeon_icd.i686.json
> -rw-r--r-- 1 root root 149 Dec 19 11:05 radeon_icd.x86_64.json
no symlinks or something silly.

**Comment by RyuzakiKK** [comment]
@dylandn Can you try to launch Steam with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam` and check if this is enough to solve it?

**Comment by dylandn** [comment]
> @dylandn Can you try to launch Steam with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam` and check if this is enough to solve it?

I seem to be getting three different results every time I try this:

"Uknown error FFFFFFFF", the two fixme lines still show up in the log. 

"ERR_GFX_INIT Failed to initialize graphics device. Please reboot or reinstall latest drivers."

Of it goes further and I'm greeted with a "Social Club Error Social Club failed to initialize. Error code: 15". This is an error I've gotten before and never managed to get past either but that's another issue. At this error, the game is hung and I must xkill it.

**Comment by smcv** [comment]
> Can you try to launch Steam with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam` and check if this is enough to solve it?

This workaround should not be necessary in pressure-vessel versions >= 0.20210105.0, which partially solves this issue.

These versions are available in the beta branch of SteamLinuxRuntime and SteamLinuxRuntime_soldier starting from today (check VERSIONS.txt). They are not in the normal/stable branch yet, but probably will be soon.

**Comment by smcv** [comment]
> "Uknown error FFFFFFFF"
> "ERR_GFX_INIT Failed to initialize graphics device. Please reboot or reinstall latest drivers."
> Or it goes further and I'm greeted with a "Social Club Error Social Club failed to initialize. Error code: 15".

It's difficult to tell whether these remaining issues are bugs in the container framework, or in Proton. It might be useful to try these:

```
cd /path/to/SteamLinuxRuntime_soldier
PRESSURE_VESSEL_VERBOSE=1 ./run -- steam-runtime-system-info --verbose 2>&1 | tee srsi.log

cd /path/to/SteamLinuxRuntime_soldier
PRESSURE_VESSEL_VERBOSE=1 ./run -- vulkaninfo 2>&1 | tee vulkaninfo.log
```

and see what's in `vulkaninfo.log` and `srsi.log`.

**Comment by dylandn** [comment]
Both log files here: https://gist.github.com/dylandn/eaceee43ab82441ce0b518a5f5230e4d

**Comment by smcv** [comment]
That's without the VK_ICD_FILENAMES workaround, and also without using the SteamLinuxRuntime_soldier beta, correct?

If you try again with the SteamLinuxRuntime_soldier beta, does that help?

**Comment by dylandn** [comment]
Correct, without the VK_ICD_FILENAMES set. 

I'm not entirely sure how to tell if it's the beta or not. Under the Steam settings, under Account, "Beta Participation:" is set to "Steam Beta Update" so I guess so?

I just relaunched Steam 5 mins ago and there were two Runtime updates queued up, including the Soldier one. 

Here are both log files after the updates, again without ICD workaround:
https://gist.github.com/dylandn/1636a138d1c0b7d6edc59a1f45d3d50f

**Comment by kisak-valve** [comment]
Hello @dylandn, you can go to the Library section of the Steam client, search for Steam Linux Runtime on the left sidebar, then right click on `Steam Linux Runtime - Soldier` -> Properties... -> Betas -> pick `client_beta` from the dropdown in order to try out the beta build before it goes out to everybody.

**Comment by smcv** [comment]
If you find the `steamapps/common/SteamLinuxRuntime_soldier` directory in your Steam library, it has a file called `VERSIONS.txt` that indicates which versions of various components went into it. The duplicate ICDs should be fixed in pressure-vessel versions 0.20210105.0 or higher, which I think is still only in the beta branch.

**Comment by dylandn** [comment]
OK, I've switched the runtime to client_beta. Game still doesn't launch but updated both log files in the previous gist, https://gist.github.com/dylandn/1636a138d1c0b7d6edc59a1f45d3d50f

**Comment by smcv** [comment]
That's looking a lot better: it's correctly only finding one copy of your GPU now.

**Comment by smcv** [comment]
As for the other issues that are preventing RDR2 from running on your system, I think someone who knows how to debug Proton probably needs to look into those. So I'd be inclined to say that we leave this issue open until pressure-vessel >= 0.20210105.0 is in the default (non-beta) release channel, and then close it.

**Comment by kisak-valve** [comment]
Now that the identified Steam Linux Runtime - Soldier issue has a fix in beta, the next step would be to generate a new Proton log and continue the discussion on https://github.com/ValveSoftware/Proton/issues/3291 with the current game behavior you're seeing and the fresh log.

**Comment by HadetTheUndying** [comment]
So I have tried both things suggested and still no dice. I think Rockstar at this point tries to make their games intentionally frustrating to get launched on any platform you play on just so you'll want to make up for lost time and buy ingame money. I've also tried the latest git commits of mesa, no help.

**Comment by smcv** [comment]
> So I'd be inclined to say that we leave this issue open until pressure-vessel >= 0.20210105.0 is in the default (non-beta) release channel, and then close it

This happened a while ago. The beta and default release channels now both have 0.20210126.1.

@kisak-valve, can we close this now, and direct any further issues to new issue reports or Proton?
