### ISSUE TITLE
btdll fault when starting Ingnomia (709240)

### ISSUE THREAD

**Issue by comaldave** [ValveSoftware/steam-runtime#347]
I click the green PLAY button and get the `Preparing to Launch Ingnomia` dialogue.

The game does not start.

It does not work with `Proton Experimental` or `Proton 5.13-4` but it does work with `Proton 5.0-10`.

On the Steam Properties for the game under the `Compatibility` tab, check `Force the use of a specific Steam Play compatibility tool` and then select `Proton 5.0-10`

**Comment by kisak-valve** [comment]
Thanks @comaldave, sorry for ping-ponging your issue report around multiple issue trackers, but the last line of the extended diagnosics information in your system information has `CClientJobGatherRuntimeInformation: container read output failed` which tells us that Pressure Vessel encountered some kind of issue setting up the Steam Linux Runtime - Soldier container environment before Proton had a chance to run, hence the missing Proton log.

Proton 5.13 and newer run inside of this container environment.

---

Please could you show us a log of what pressure-vessel is thinking, and exactly what happens? You can do this without involving Proton (which should make things a bit simpler) like this:

```
cd /path/to/SteamLinuxRuntime_soldier
PRESSURE_VESSEL_VERBOSE=1 ./run -- steam-runtime-system-info --verbose 2>&1 | tee container.log
```

and then send container.log as a [gist](https://gist.github.com/). You can edit/censor the log if there's anything in it that you consider private, as long as it's obvious where it has been edited, for instance replacing your username with REDACTED.

The SteamLinuxRuntime_soldier directory will be in one of your Steam libraries. The most likely place is ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier if you haven't reconfigured the installation path.
(from https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-741037038)

**Comment by smcv** [comment]
@kisak-valve, do we have a **Needs info** label that we can put on issue reports like this one?

**Comment by kisak-valve** [comment]
Closing pending feedback.
