### ISSUE TITLE
Can't launch HotShot Racing (609920) - getcompatpath fails

### ISSUE THREAD

**Issue by popey** [ValveSoftware/steam-runtime#348]
#### Your system information

* Steam Runtime Version: steam-runtime_0.20201203.1
* Distribution (e.g. Ubuntu 18.04): 21.04 (pre-release
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/popey/58db16c771dd6e5a57261e7777402d3e
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: I believe so

#### Please describe your issue in as much detail as possible:

I was running Ubuntu 20.10, and upgraded to 21.04 pre-release this weekend. 
Hotshot Racing (609920) no longer launches
I have tried deleting my entire .steam folder and relaunching steam to re-get everything fresh.

Log at https://gist.github.com/popey/ba3ca4d6447bf2dfced179eb7e10a836
Container log at https://gist.github.com/popey/0d5df417a74d4b849d6bd088627f1b34

#### Steps for reproducing this issue:

1. Install Ubuntu 21.04
2. Install HotShot Racing
3. Attempts to launch then returns to steam

**Comment by TTimo** [comment]
- `/home/alan/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad`: we recommend you replace Ubuntu's steam package with Valve official package - see http://repo.steampowered.com/steam/ for details.

I see a lot of `Could not connect to X session manager: None of the authentication protocols specified are supported` in the steam log, but that might be a red herring.

A crash report was uploaded (c3b207bf-0cd1-4278-a6c9-603d82210116) (despite Ubuntu package trying to prevent - not sure how that happened but that's good for us in any case). It is the report for the install script problem:

```
GameAction [AppID 609920, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
```

That's the root cause. It might be a problem in Steam client.

- Is the game installed under the default Steam Library under `~/.steam/` or elsewhere?

- Can you provide your compat logs: `~/.steam/steam/logs/compat_log*`

GL is not working in the soldier container (both 32 and 64 bit), I'm not sure that's a root cause either but that will probably be an issue later.

- Can you upload a full report of Help > System Information so we see the diagnostic for all the runtimes for comparison?

**Comment by popey** [comment]
Thanks for the prompt response.

> Is the game installed under the default Steam Library under ~/.steam/ or elsewhere?

Yes. `~/.steam/debian-installation/steamapps/common/Hotshot Racing`

> Can you provide your compat logs: ~/.steam/steam/logs/compat_log*

Here you go: https://gist.github.com/popey/c550be18672b038d1840517ff84c98c4

> Can you upload a full report of Help > System Information so we see the diagnostic for all the runtimes for comparison?

I provided that in the original post near the top. Is this insufficient or did I do it wrong? https://gist.github.com/popey/58db16c771dd6e5a57261e7777402d3e

I am indeed using the deb from Ubuntu. 

I clicked your link to http://repo.steampowered.com/steam/ and it's got a broken link to http://repo.steampowered.com/steam/archive/stable/steam.gpg (404). So I'll just `apt install steam_latest.deb` for now. Thanks for the suggestion.

I nuked the `~/.steam` folder, installed the `steam_latest.deb` and re-downloaded the game & proton. It dies in the same way.

**Comment by TTimo** [comment]
This looks like a Proton problem now, the `getcompatpath` stopped working:

```
[2021-01-16 21:04:35] GetCompatibilityToolCommandLineInternal: '/home/alan/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --deploy=soldier --suite=soldier --verb=getcompatpath -- '/home/alan/.steam/debian-installation/steamapps/common/Proton 5.13'/proton getcompatpath 
[2021-01-16 21:04:43] Foreign install path for AppID 609920: Z:\home\alan\.steam\debian-installation\steamapps\common\Hotshot Racing
[2021-01-16 21:04:43] Foreign install path for common redist for AppID 609920: Z:\home\alan\.steam\debian-installation\steamapps\common\Steamworks Shared

[2021-01-16 23:13:07] GetCompatibilityToolCommandLineInternal: '/home/alan/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --deploy=soldier --suite=soldier --verb=getcompatpath -- '/home/alan/.steam/debian-installation/steamapps/common/Proton 5.13'/proton getcompatpath 
[2021-01-16 23:13:09] Foreign install path for AppID 609920: 
[2021-01-16 23:13:09] Foreign install path for common redist for AppID 609920:
```

Are those two log times of working and not working between the 18 to 21 upgrade?

PS: ty for pointing out the 404 on the gpg file. Our .deb are signed, if you are able to install you probably have the key already. We'll fix the 404

**Comment by popey** [comment]
No, I upgraded late on the 15th. So any logs from before the 16th were on 20.10, and 16th onwards are on 21.04. If you need logs from a working run, I can dig them out of a backup from prior to the 16, if that helps?

**Comment by TTimo** [comment]
> No, I upgraded late on the 15th. So any logs from before the 16th were on 20.10, and 16th onwards are on 21.04. If you need logs from a working run, I can dig them out of a backup from prior to the 16, if that helps?

Sorry I missed it. No we don't need 16. There are a lot of errors such as `"messages" : "Unknown option: signal\nUnknown option: kill-after\nUsage:\n\ttimeout [-t timelimit] [-m memlimit] [-x hertz] command [arguments ...]\n\nDied at /home/alan/bin/timeout line 29.\n"` - that may be a new problem with 21. I'll get more eyes to look at this.

**Comment by popey** [comment]
Oh my god, you've just identified the issue. It is entirely my fault. The `/home/alan/bin/timeout` is a perl script which appears in the path before `/usr/bin/timeout`. As soon as I move that out the way, the game launches! How incredibly embarrassing. I mean, no idea why it worked on 20.10! But this is sorted for me, even if there's other issues here.

![20210117195204_1](https://user-images.githubusercontent.com/1841272/104854252-8833d300-58fd-11eb-8eae-c92c0ab6ad17.jpg)

**Comment by TTimo** [comment]
ok!

**Comment by smcv** [comment]
> I see a lot of Could not connect to X session manager: None of the authentication protocols specified are supported in the steam log, but that might be a red herring.

FYI: yes this is a red herring. It's because the container setup code (borrowed from Flatpak) connects us to the host system's X11 display, but does not set up ICE, XSMP and other more obscure X11-related protocols.

**Comment by smcv** [comment]
> see http://repo.steampowered.com/steam/

Please use https://repo.steampowered.com/steam/ (one day we should probably make the http version redirect to https), otherwise you won't have a trust path.

**Comment by smcv** [comment]
> it's got a broken link to http://repo.steampowered.com/steam/archive/stable/steam.gpg (404)

Fixed.
