### ISSUE TITLE
Proton does not start at all - no Logs

### ISSUE THREAD

**Issue by I-R** [ValveSoftware/steam-runtime#350]
# Compatibility Report
- Little Nightmares
- 424840

## System Information
- GPU: GeForce GTX 1050 (Mobile) 
- Driver/LLVM version: 4.6.0 NVIDIA 450.102.04 / Mesa Intel(R) HD Graphics 630 (KBL GT2)
- Kernel version: 5.8.0-38-generic
- Link to full system information report as [Gist](https://gist.github.com/): Ubuntu 20.04
- Proton version: Experimental + 5.13-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

No Logs Produced

reimann@Anor:~$ PROTON_LOG=1 steam steam://rungameid/424840
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/reimann/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad steam://rungameid/424840
[2021-01-18 08:34:30] Startup - updater built Jan 16 2021 01:26:56
[2021-01-18 08:34:30] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
[2021-01-18 08:34:31] Loading cached metrics from disk (/home/reimann/.steam/debian-installation/package/steam_client_metrics.bin)
[2021-01-18 08:34:31] Using the following download hosts for Public, Realm steamglobal
[2021-01-18 08:34:31] 1. https://steamcdn-a.akamaihd.net, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-01-18 08:34:31] 2. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 0, source = 'baked in'
[2021-01-18 08:34:31] Verifying installation...
[2021-01-18 08:34:31] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy

## Symptoms 
I start the game - the Button turns to blue 'X Cancel' then 'X Stop' for a couple of seconds, thats all. No logs produced, but a crash report under /tmp/dumps 

Game is installed on same drive as OS, ext4

## Reproduction

Tried reinstall, tried successor 'Little Nightmares II' with same behaviour. From ProtonDB, i know, that both should run.

**Comment by kisak-valve** [comment]
Hello @I-R, the fact that no Proton log was generated hints that this is a Pressure Vessel issue. Starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment, and that's setup by Pressure Vessel. Let's treat this is a Pressure Vessel issue until there's a stronger indication the issue is elsewhere.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the information requested there.

**Comment by smcv** [comment]
> You need to disable runtime

Please don't advocate this as a general solution. At best, it's a temporary workaround. Official Proton 5.13+ binaries are designed to be run in the Steam Linux Runtime - soldier container environment, and Valve cannot support using them in other environments. If you're very lucky, they might accidentally work when not using the container, but that doesn't mean they will still work tomorrow.

To solve this properly for everyone, without everyone needing to copy/paste around workarounds, we need the information requested above.

For Vulkan specifically, part of the solution is likely to involve factors outside our control (we're waiting for a new release of the Vulkan loader library with fixes that we provided) so please be patient. We'll get there, but this stuff is *not* simple.

**Comment by I-R** [comment]
Hi,

thanks for all your help. First of all - it works!

When getting the Logs with STEAM_LINUX_RUNTIME_LOG=1, i also added the __VK_LAYER_NV_optimus=NVIDIA_only to the startup command. My former setup only had been 
`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia %command% -onethreaddid `
Now with 
`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only%command% -onethreaddid `
It`s up and running - i only have to transfer my save-game, now..

Best regards!
