### ISSUE TITLE
Installing/Running proton non-steam game ?

### ISSUE THREAD

**Issue by inkhey** [ValveSoftware/steam-runtime#351]
#### Your system information

* Steam Runtime Version: ?
* Distribution (e.g. Ubuntu 18.04): Debian 10
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  
* Have you checked for system updates?: [Yes/No] ?
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] ?

#### Please describe your issue in as much detail as possible:

Sorry, if my question seems dumb or if this is not the correct place to ask for, but as i am struggling to run Red dead redemption 2 (non steam version), i ask myself if there any solution to both install and run a non-steam game through the same runtime as normal proton game.

I do try non-steam game feature of steam with proton on it, but don't success to make something working. I can start the launcher (but it's far from instant and "play" button stay green), to reinstall game (as it doesn't see the already installed version with lutris) into some "Program File" dir that point in fact in an obscure directory here : `/home/me/.steam/steam/steamapps/compatdata/3682439891/pfx`, and game start but no windows.
I also  don't success to get any log from it, seems like i didn't understood something with the parameters.

it seems to me more logical and probably more successful to be able to do all action in the same correct runtime, as my game is running on steam official version, if properly installed the same way there should be very few difference that cause issue.

**Comment by kisak-valve** [comment]
Hello @inkhey, since the game's launcher works in the scenario you've described, this doesn't read like a Steam runtime issue. We're tracking issues with games with Proton in the Proton issue tracker, and one issue per unoffically supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-763189149.
