### ISSUE TITLE
bwrap: No permissions to creating new namespace on Arch

### ISSUE THREAD

**Issue by richardwolfe4991** [ValveSoftware/steam-runtime#356]
When trying to run games with Proton 5.13, the game immediately crashes upon hitting the play button in steam. If I revert back to 5.0-10, all my games work fine. 

I tried deleting the folders in compatdata/[appid] for each game, and I noticed that on 5.0-10 it recreates the pfx folder for the wine prefix as well as other files, but on 5.13 no pfx folder or any other files are created inside of the game's compatdata/[appid] folder. This appears to be affecting my entire library and not any specific games. Any help would be appreciated!

**Comment by kisak-valve** [comment]
Thanks, your system information ends with `CClientJobGatherRuntimeInformation: container read output failed` which tells us that you've encountered a Pressure Vessel issue of some kind. Starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment, and that's setup by Pressure Vessel.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and attach your findings in a [gist](https://gist.github.com) or as a file.

**Comment by richardwolfe4991** [comment]
Hello, I was unable to upload the resulting log file, but I have added it to a gist linked here:

https://gist.github.com/richardwolfe4991/4639506951b4fc36a0a8aefe6fcffc73

**Comment by kisak-valve** [comment]
We've seen `bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.` before with https://github.com/ValveSoftware/steam-runtime/issues/320#issuecomment-74248182. Please confirm you're using a hardened kernel build, then add the `bubblewrap-suid` package and retest.

**Comment by richardwolfe4991** [comment]
After reading #320, I found that I did not have any "bubblewrap" at all installed on my system. First, I tried the normal "bubblewrap" and that did not fix my issue, but as you said, after I installed "bubblewrap-suid" Proton 5.13 launches games now without any problems. Thank you so much!

**Comment by kisak-valve** [comment]
Glad to hear it's working for you, closing.
