### ISSUE TITLE
Age of Empires II: Definitive Edition (813780) doesn't run with the new runtime enabled

### ISSUE THREAD

**Issue by EmmerichFrog** [ValveSoftware/steam-runtime#358]
#### Your system information

* Steam Runtime Version: Soldier
* Arch
* Link to your full system information (Help -> System Information) in a Gist: [system info](https://gist.github.com/EmmerichFrog/55fd25547b8ea6c86b320aff662d532e)
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
With the soldier runtime enabled the game displays the splash screen and an empty windows and then crashes. The game works with the runtime disabled (like this flightlessmango/MangoHud#369 (comment)). Tested with both proton 5.13 and proton-experimental. The attached log was made with experimental

runtime log with steam run with the `STEAM_LINUX_RUNTIME_LOG=1` variable set: [slr-app813780-s8181650f82930add.log](https://github.com/ValveSoftware/steam-runtime/files/5882064/slr-app813780-s8181650f82930add.log)
proton log: [steam-813780.log](https://github.com/ValveSoftware/Proton/files/5873842/steam-813780.log)

#### Steps for reproducing this issue:

1. select proton 5.13 or proton-experimental as compatibility tool
2. launch the game
3. the game doesn't launch as described above

EDIT: forgot to add that I'm using both the steam client beta and soldier runtime beta, I don't know if it's obvious with the logs

**Comment by kisak-valve** [comment]
Hello @EmmerichFrog, can you also share a Proton log from the working scenario that just barely gets further than the failing log?

In particular, I'd like to see if `err:winediag:WS_getaddrinfo Failed to resolve your host name IP` appears in that log.

Another possible line of interest from the log: `E0126 14:28:47.388000000   288 server_secure_chttp2.cc:81] {"created":"@1611667727.388000000","description":"OS Error","file":"C:\CA\repos\vcpkg\buildtrees\grpc\src\f1b4c24419-dd45943f9a.clean\src\core\lib\iomgr\resolve_address_windows.cc","file_line":96,"os_error":"Unable to retrieve error string","syscall":"getaddrinfo","wsa_error":11001}`

**Comment by smcv** [comment]
One thing that jumps out at me:

```
18:38:51.461527: pressure-vessel-wrap[5046]: Vulkan ICD #0 at /home/REDACTED/Documenti/scripts/radeon_icd.x86_64.json: /home/REDACTED/Documenti/mesa-git/mesa/_build/src/amd/vulkan/libvulkan_radeon.so
18:38:51.461560: pressure-vessel-wrap[5046]: Vulkan ICD #1 at /home/REDACTED/Documenti/scripts/radeon_icd.i686.json: /home/REDACTED/Documenti/mesa-git/mesa/_build_32/src/amd/vulkan/libvulkan_radeon.so
```

You're using a locally-compiled Vulkan ICD directly from the build directory, without having installed it "properly". This might work, but equally might not, and is not really something we can support (you might have *anything* in there). Can you re-test this using a system-wide-installed Mesa stack from your distribution?

(This *might* be fine, but it's an extra variable that is unique to your system and will not match what happens for other Arch users.)

**Comment by EmmerichFrog** [comment]
@kisak-valve here is a log with the runtime disabled, stopped as soon as I got the loading screen. Between this and the first log I changed nothing outside of disabling the runtime.

[steam-813780.log](https://github.com/ValveSoftware/steam-runtime/files/5882904/steam-813780.log)

@smcv here are the same logs using my distro mesa. Just to be clear, the setup I'm using with a local mesa version works correctly with proton + the runtime with other games

[steam-813780-stock_mesa.log](https://github.com/ValveSoftware/steam-runtime/files/5882908/steam-813780-stock_mesa.log)
[slr-app813780-s3c9417f07df4063-stock_mesa.log](https://github.com/ValveSoftware/steam-runtime/files/5882909/slr-app813780-s3c9417f07df4063-stock_mesa.log)

**Comment by kisak-valve** [comment]
Thanks, there's no getaddrinfo error in the second log, so it might be a relevant hint.

**Comment by EmmerichFrog** [comment]
I just tried the game again with proton experimental and the runtime enabled and it works correctly.

The game was still broken until 1-2 months ago, but since the game got a big update yesterday with the new dlc, I have no idea if it got fixed by some proton/runtime update or accidentally with the update.

I assume you can close the issue, unless you might be interested in some other logs.

**Comment by kisak-valve** [comment]
Closing per the last comment.
