### ISSUE TITLE
Proton won't launch any games with mesa 21.0.0-rc4 and Runtime Soldier enabled (Mesa Device Select and MangoHud Vulkan Layers related)

### ISSUE THREAD

**Issue by Samsagax** [ValveSoftware/steam-runtime#365]
Hello. I was testing some suggestions for making Cyberpunk 2077 run a little better but encountered this issue:

Installing mesa v21.0 (or mesa-git 21.1-devel) will render all Proton games useless. The behaviour is always the same: enter to game in the Library, hit Launch, and it hangs in "Launching..." forever. A dump is generated in `/tmp/dumps` and the corresponding USER_log.txt reports the dmp file is uploaded.

Games I tried:
- Relicta (with Proton 5.13-5 and -6rc2, Proton Experimental, Proton 5.21-GE, Proton 6.1-GE)
- Cyberpunk 2077 (Proton 5.13, Proton Experimental and 5.21-GE)

Things I tried with proton versions:
- `vulkaninfo` works and reports my setup and even `vkcube` works fine:
````
Device Properties and Extensions:
=================================
GPU0:
VkPhysicalDeviceProperties:
---------------------------
        apiVersion     = 4202664 (1.2.168)
        driverVersion  = 88080483 (0x5400063)
        vendorID       = 0x1002
        deviceID       = 0x73bf
        deviceType     = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName     = AMD RADV SIENNA_CICHLID (ACO)
````
- adding `PROTON_LOG=1` doesn't produce a log.
- starting with clean steam runtime (I've run `steam-runtime --reset` and reconfigured steam)
- as soon as I come back to mesa 20.3 the issue disappears and I can play my proton games no problem with any version.

My setup:
- Ryzen 5 5600x
- 16Gb RAM
- Radeon RX 6900 XT
- ArchLinux with linux-zen kernel `5.10.15-zen1`
- mesa version `21.1.0_devel.134967.44a76ba16df` with radeon Vulkan drivers (radv).
- Steam launched in Big Picture mode on top of steam-compositor-plus

Steps to reproduce in my setup:
- Select "Library"
- Select game
- go to "Your game"
- hit "Play"

What I expect:
Game launches and plays

What happens:
Screen dims a little, the button says "Launching" and the box next to it says "Preparing to launch <game>". No input makes it go away and regain control. Have to got to a tty by `Ctrl+Alt+F2` and then reboot or restart the Display manager by issuing `systemctl restart lightdm.service`.

I'm willing to help troubleshoot this issue but can't figure out where to start. Any halo will be greatly appreciated.

Edit: native Linux games work perfectly with mesa 21 as Dirt 4 for example

**Comment by kisak-valve** [comment]
Hello @Samsagax, starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment and Pressure Vessel sets up this environment. Since there's no Proton log generated, that hints that there was some kind of issue with Pressure Vessel before Proton got a chance to start.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share a Steam Linux Runtime log along with your system information from Steam in a [gist](https://gist.github.com).

**Comment by Samsagax** [comment]
As requested:
- [System Information](https://gist.github.com/Samsagax/7d4b73e7e7328200319a181b0f9bbb43) taken by `lshw` as Big Picture doesn't provide a mean to get this information.
- [Steam Runtime log](https://gist.github.com/Samsagax/291bb3e1638ab42f7d5e0ce0649a7d0a) after hitting Play in the game page and waiting a couple minutes.

**Comment by Samsagax** [comment]
Today I tested bypassing the runtime entirely by means described [in this comment](https://github.com/flightlessmango/MangoHud/issues/369#issuecomment-709902078) and the game works great. So I think the Runtime is the culprit.
Anything I can help.

**Comment by smcv** [comment]
> System Information taken by lshw as Big Picture doesn't provide a mean to get this information

Please switch from Big Picture mode into desktop mode (you should be able to do this with Alt+Enter) to get the system info.

Or, if you can't do that, another way to get the information we need is:

```
~/.steam/steam/ubuntu12_32/steam-runtime/run.sh steam-runtime-system-info >ld_library_path_runtime.txt
/path/to/SteamLinuxRuntime_soldier/_v2-entry-point --suite=soldier -- steam-runtime-system-info >soldier.txt 2>soldier.log
```

and then share `ld_library_path_runtime.txt`, `soldier.txt` and `soldier.log`.

`lshw` is not what we want: the report that appears in System Information includes a lot of Steam-specific and container-runtime-specific information that we can't get any other way.

It would be useful to collect that information with both Mesa 20.3 (which you say works fine, even with the soldier container runtime) and Mesa 21 (which you say only works *without* the soldier container runtime), so that we can compare them and see what goes wrong in Mesa 21. Please make it as obvious as possible which log is which!

**Comment by Samsagax** [comment]
> Or, if you can't do that, another way to get the information we need is:
> 
> ```
> ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh steam-runtime-system-info >ld_library_path_runtime.txt
> /path/to/SteamLinuxRuntime_soldier/_v2-entry-point --suite=soldier -- steam-runtime-system-info >soldier.txt 2>soldier.log
> ```
> 
> and then share `ld_library_path_runtime.txt`, `soldier.txt` and `soldier.log`.

I see. Indeed I can't exit Big Picture mode as my setup doesn't have a desktop. Thanks for this info and commands. As side note this method is not listed in the [official Steam support page](https://support.steampowered.com/kb_article.php?ref=4840-QWJX-0408), should be updated with those commands. Will do with both Mesa 21-devel and Mesa 20.3, on the game "Relicta" as my version of Cyberpunk is not from Steam, and report back.

**Comment by Samsagax** [comment]
Ok. Here is what I tested on the game Relicta:
- Installed mesa 20.3 from official Arch repositories and Vulkan driver (radeon) with their corresponding lib32 packages as well.
- Set Proton Play version to latest 5.13-6.
- Reboot PC and verify the game launches fine.
- Take system-info and logs.
- Then install mesa 21.0.0-rc4 compiling from mesa git with corresponding lib32 package.
- Reboot PC and verify the game doesn't launch (exhibits the described behavior in first comment)
- Take system-info and logs.
- Install mesa 21.1-devel (master branch from git) with corresponding lib32 package.
- Reboot the PC and test the game (this time it worked!).
- Take system-info and logs.

Interestingly enough the game launches and plays fine with latest master branch, but tagged 21.0.0-rc4 doesn't.

[Here is the gist with each file](https://gist.github.com/Samsagax/01d8c834d363c64b5298e6aa13913864). The ones called `soldier*.log` came up empty so can't be uploaded

**Comment by kisak-valve** [comment]
Hello @Samsagax, it looks like steam-runtime-system-info wasn't able to sanity check the graphics driver because it wasn't run in an X session. The mesa build with trouble has lavapipe while the other two mesa builds don't. Switch back to mesa 21.0.0 rc4, confirm the issue again, then temporarily disable lavapipe with something like `sudo mv /usr/share/vulkan/icd.d/lvp_icd.x86_64.json /usr/share/vulkan/icd.d/lvp_icd.x86_64.json.disabled` and see if that has an effect.

**Comment by Samsagax** [comment]
> Hello @Samsagax, it looks like steam-runtime-system-info wasn't able to sanity check the graphics driver because it wasn't run in an X session.

Would setting the `DISPLAY` variable to a running X session be of help here? Like setting it to `DISPLAY=:0`. That's how I managed to run all my Vulkan tests on this machine.

> The mesa build with trouble has lavapipe while the other two mesa builds don't. Switch back to mesa 21.0.0 rc4, confirm the issue again, then temporarily disable lavapipe with something like `sudo mv /usr/share/vulkan/icd.d/lvp_icd.x86_64.json /usr/share/vulkan/icd.d/lvp_icd.x86_64.json.disabled` and see if that has an effect.

Unfortunately is has no effect on the game.

**Comment by smcv** [comment]
> The ones called soldier*.log came up empty so can't be uploaded

That's fine, that just means the container tool isn't producing any warnings.

**Comment by smcv** [comment]
> Would setting the DISPLAY variable to a running X session be of help here?

In general, whenever we ask for diagnostic tool output, we want it to come from an environment as close as possible to the environment in which you're running Steam and games - otherwise we can't know how much of the diagnostic tool's output is still going to be true for Steam, and how much is going to be different.

If you're running Steam under a special noninteractive window manager or compositor, it would be useful to be able to log in under a more standard environment (like an ordinary desktop environment) where you're able to bring up a terminal, and see whether the bug you're reporting is still reproducible there. If it is, then doing any further testing in that desktop environment is going to be a lot easier.

**Comment by smcv** [comment]
One thing I notice from these logs is that the two working configurations don't have `libVkLayer_MESA_device_select.so`, and the failing configuration does.

Another thing I notice is that you have MangoHUD.

This makes me wonder whether it's the same issue as https://github.com/ValveSoftware/steam-runtime/issues/363#issuecomment-774381965 - perhaps you could test that by disabling either the device selection layer, or MangoHUD?

**Comment by Samsagax** [comment]
> In general, whenever we ask for diagnostic tool output, we want it to come from an environment as close as possible to the environment in which you're running Steam and games - otherwise we can't know how much of the diagnostic tool's output is still going to be true for Steam, and how much is going to be different.
>
> If you're running Steam under a special noninteractive window manager or compositor, it would be useful to be able to log in under a more standard environment (like an ordinary desktop environment) where you're able to bring up a terminal, and see whether the bug you're reporting is still reproducible there. If it is, then doing any further testing in that desktop environment is going to be a lot easier.

Ironically I am running steam big picture inside steamos-compositor with lightdm set to autologin my user (really love this console-style experience, honestly). I don't really know how much it would change if I install a full DE and start steam inside to how I'm running my games now.

This are the things I can do and won't change my setup too much:
- Install a terminal emulator that can run inside the compositor (I run it in a tty or ssh session with `DISPLAY` variable set to `:0`) and there run the commands you mentioned. I can test it with xterm.
- Run the commands directly in the tty or ssh session with `DISPLAY` variable set to `:0`. That's what I've done in my last comment.

**Comment by Samsagax** [comment]
> One thing I notice from these logs is that the two working configurations don't have `libVkLayer_MESA_device_select.so`, and the failing configuration does.
> 
> Another thing I notice is that you have MangoHUD.
> 
> This makes me wonder whether it's the same issue as [#363 (comment)](https://github.com/ValveSoftware/steam-runtime/issues/363#issuecomment-774381965) - perhaps you could test that by disabling either the device selection layer, or MangoHUD?

Will test and report back

**Comment by Samsagax** [comment]
My findings with mesa compiled today (version 21.0.0-rc5):
- Having the device selection layer enabled and Mangohud disabled the game runs fine.
- Having the device selection layer disabled and MangoHud enabled the game runs fine
- Having both layers enabled the game won't run with the Steam Linux Runtime enabled.

Seems to be the same issue.

**Comment by Samsagax** [comment]
Another finding. In some games (Cyberpunk 2077 GOG version, probably others) the Mesa Overlay layer must be disabled (additionally to Mesa Device Selection, MangoHud is enabled and works) like so:
`# mv /usr/share/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json /usr/share/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json.disabled`

**Comment by smcv** [comment]
> the Mesa Overlay layer must be disabled

What do you mean by "must be disabled", in terms of the traditional bug reporting template: what you did; what you expected to happen; what actually happened?

If I'm understanding you correctly, it's something like this?

* Steps to reproduce
    * Mesa 21.0.0-rc5 (?)
    * Which version of Steam?
    * Which version of SteamLinuxRuntime_soldier?
    * Have MangoHud (which version?) enabled
    * Have the Mesa overlay layer enabled
    * Do you set any special environment variables?
    * Don't disable any layers by renaming their JSON manifests (?)
    * Run Cyberpunk 2077 GOG version
        * How? Are you running it via Steam as a "non-Steam game" and forcing it to use a Proton compatibility tool, or what?
* Expected result
    * The game runs successfully
    * MangoHud is visible
* Actual result
    * No graphics from the game are shown
    * Steam shows "Launching..." forever, until the game is killed (?)
    * What messages appear in SteamLinuxRuntime_soldier's `slr-*.log`?
    * What messages appear in Proton's log, if any?
    * What messages appear on Steam's stdout/stderr?

and you also have a workaround for this particular issue:

* Steps to reproduce
    * Disable the Mesa overlay layer by renaming `VkLayer_MESA_overlay.json` to `VkLayer_MESA_overlay.json.disabled`
    * Everything else the same as above
* Expected result
    * The game runs successfully
    * MangoHud is visible
* Actual result
    * As expected

I can't see what you see - the only information I have access to is what you tell me - so I'm unlikely to be able to solve this without your help.

**Comment by Samsagax** [comment]
You are absolutely right @smcv. I apologize for not being verbose about the test I made. I know I can't expect you to support this but the same behavior is shown and some things are related. I appreciate the effort you are putting to this and Linux gaming in general as there is a brighter future there.
As stated, my setup tries to emulate what a Steam Machine would have been:

Hardware specs (but that can be gathered from previous gist):
 - Ryzen 5 5600x
 - 16Gb RAM
 - Radeon RX 6900 XT

Software setup:
 - ArchLinux (rolling release) with linux-zen kernel (version `5.10.16-zen1-1-zen` as of this writing)
 - Steam (beta client) launched in Big Picture mode on top of [steam-compositor-plus](https://github.com/gamer-os/steamos-compositor-plus) as an auto-login session for LightDM ([steamos-session script](https://github.com/gamer-os/steamos-compositor-plus/blob/master/usr/bin/steamos-session))

For this case (CP 2077 GOG version) the game is installed by means of [`wyvern`](https://git.sr.ht/%7Enicohman/wyvern/) in a non-hidden directory inside `$HOME` (this is as per the game can't handle directories [that begin with a dot `.`](https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-776676602)). Then it is added to Steam client by means of a "non-steam game shortcut" and forced to use a proton version (i tested 5.13-6, 5.21-GE-1, 6.1-GE-2) with a [steam-tweaks](https://github.com/gamer-os/steam-tweaks) yaml file.

First test that led me to this issue:
Mesa 20.3 (as official ArchLinux package) with Proton 5.13-6, MangoHud (version 0.6.1) installed and enabled, no other environmental variables set in the games properties ("Launch options" is empty). The game works with no issues (aside from [performance](https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-776282151)). MangoHud works with the game as expected.
[Proton and soldier logs](https://gist.github.com/Samsagax/af97cda4f9706a17beae02085701ae5b)

Then I tried different Proton versions (5.21-GE-1 and 6.1-GE-2) they both work with Mesa 20.3. Runtime Soldier is enabled at all times. The game works and MangoHud too. For the purposes of these test I'll be using 5.13-6 but deleted pfx for a clean start each time.

Then was time to experiment with Mesa 21. I installed `mesa-git` package forcing to checkout [`mesa-21.0.0-rc5` tag](https://gitlab.freedesktop.org/mesa/mesa/-/commits/mesa-21.0.0-rc5). Then set Proton version to 5.13-6 (steam official) and the game hangs past "Launching..." with a standby screen (the one with 3 vertical bars that wave). To recover form that, I switch to a TTY and restart lightdm. The game seems not to run on Runtime Soldier.
[Soldier and Proton Log](https://gist.github.com/Samsagax/f648a82c1afa675c4f59955e62c3241f)

Two workarounds that i tested and succeeded:
If the Runtime is bypassed by adding
````
shift 4
exec "${@}"
````
at the beginning of `.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point` file then the game launches and runs with MangoHud with no issue. Soldier does not produce a log
[Proton Log](https://gist.github.com/210a5e7deceb074b5d7c2f0cdb1a9c20)

Also If both Mesa layers (device selection and overlay) are disabled like so:
````
# mv /usr/share/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json /usr/share/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json.disabled
# mv /usr/share/vulkan/implicit_layer.d/VkLayer_MESA_device_select.json /usr/share/vulkan/implicit_layer.d/VkLayer_MESA_device_select.json.disabled
````
the game launches with the Runtime enabled (commenting the likes that bypass it) and MangoHud works.
[Soldier and Proton Log](https://gist.github.com/f40685f15a607c6e8505fd6e19b972df)

**Comment by smcv** [comment]
> For this case (CP 2077 GOG version) the game is installed by means of wyvern in a non-hidden directory inside $HOME (this is as per the game can't handle directories that begin with a dot .). Then it is added to Steam client by means of a "non-steam game shortcut" and forced to use a proton version (i tested 5.13-6, 5.21-GE-1, 6.1-GE-2) with a steam-tweaks yaml file.

Are you able to reproduce an equivalent bug with a smaller number of unsupported addons?

For example, is there a game that is available from Steam, uses DXVK under Proton, doesn't need any special setting and exhibits the same problem?

Life Is Strange (32-bit) and Life Is Strange 2 (64-bit) make quite good test games: each has a free version (the first chapter), and they're available as native Linux games but can be forced to run as Windows games under Proton by forcing a specific Proton version as the compatibility tool.

**Comment by kisak-valve** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/commit/38ce8d4d00c2b0e567b6dd36876cf171acb1dbc7 potentially helps with this issue as well.

**Comment by Samsagax** [comment]
> https://gitlab.freedesktop.org/mesa/mesa/-/commit/38ce8d4d00c2b0e567b6dd36876cf171acb1dbc7 potentially helps with this issue as well.

This solved all issues, will test @smcv's suggestion next.

**Comment by Samsagax** [comment]
> > For this case (CP 2077 GOG version) the game is installed by means of wyvern in a non-hidden directory inside $HOME (this is as per the game can't handle directories that begin with a dot .). Then it is added to Steam client by means of a "non-steam game shortcut" and forced to use a proton version (i tested 5.13-6, 5.21-GE-1, 6.1-GE-2) with a steam-tweaks yaml file.
> 
> Are you able to reproduce an equivalent bug with a smaller number of unsupported addons?
> 
> For example, is there a game that is available from Steam, uses DXVK under Proton, doesn't need any special setting and exhibits the same problem?
> 
> Life Is Strange (32-bit) and Life Is Strange 2 (64-bit) make quite good test games: each has a free version (the first chapter), and they're available as native Linux games but can be forced to run as Windows games under Proton by forcing a specific Proton version as the compatibility tool.

Ok. Here is my test:
Installed "Life is Strange", unmodified mesa 21.0.0-rc5, Mangohud 0.6.1. Set it to force to use Proton 5.13-6. Hit PLAY.
Instead of playing the game hangs in "Launching...".
Proton didn't produce a log.
[Soldier log](https://gist.github.com/e49e02911c21ee497276f651ae76325c)

Then I disabled both mesa layers and try again. This time the game launches fine with Mangohud.
[Soldier and Proton logs](https://gist.github.com/f2d534ea61630540679b3b64741a77a2)

Then I re-enabled both Mesa layers and tested "Life is Strange 2". Same result as before, the game hangs in "Launching...". Proton did not produce a log.
[Soldier log](https://gist.github.com/e848fdb643392f31ef4fa04421224b99)

Then disabling both Mesa layers tried again and the game works fine with Mangohud enabled.
[Soldier and Proton logs](https://gist.github.com/ef09983d37423481aec97e527420d5da)

And finally, patched mesa 21.0.0-rc5 with what @kisak-valve suggested and the issue is gone. Both games work.
[Soldier and Proton logs](https://gist.github.com/a29cc24177d907578ef65ac8b69ee8a6)

**Comment by smcv** [comment]
> https://gitlab.freedesktop.org/mesa/mesa/-/commit/38ce8d4d00c2b0e567b6dd36876cf171acb1dbc7 potentially helps with this issue as well.

This is not something we can directly fix through the Steam Runtime, but I've contacted a Mesa maintainer to try to make sure that change gets into all the affected branches.

It's possible that there will eventually be a solution for this in the Vulkan-Loader. If there is, we can deploy *that* through the Steam Runtime.

**Comment by Samsagax** [comment]
Hope that patch gets accepted upstream. Meanwhile iĺl be using it as a workaround.

**Comment by Samsagax** [comment]
Good news, everyone. Compiled mesa 21.0 release today and the issue seems to be gone. I think we can close this issue for now. Thanks @kisak-valve and @smcv for your effort and guidance.

**Comment by smcv** [comment]
We're hoping Mesa 20.3.5 will also have the change that avoids this issue, but that version has not yet been released.

**Comment by jlanzobr** [comment]
This exact bug impacts me as well on Mesa 21.0.1 on Arch Linux with an AMD Radeon 6800. The workarounds mentioned by Samsagax resolve the issue.

**Comment by smcv** [comment]
> We're hoping Mesa 20.3.5 will also have the change that avoids this issue

It has now been released, and it does include that change.

@jlanzobr writes:
> This exact bug impacts me as well on Mesa 21.0.1

In general it's usually better to open a new issue than to reopen a closed issue, because if one issue number gets reused for a different root cause that needs different fixes, then tracking which versions have which fixes gets very confusing.

Please report a separate issue with [full details](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information), including the versions of Vulkan-Loader (libvulkan), Mesa and MangoHud that you are using. Mesa 21.0.1 is meant to already include the changes that avoided this particular root cause, so you might be experiencing something different that has the same symptoms.

Life Is Strange (32-bit) and Life Is Strange 2 (64-bit) make good test games for this sort of thing: each has a free version (the first chapter) that can be used to confirm whether the same issue is present on different systems, and they're available as native Linux games but can be forced to run as Windows games under Proton by forcing a specific Proton version as the compatibility tool. It would be useful if you could confirm whether you see the same thing with one of these games when forcing it to use Proton.

> The workarounds mentioned by Samsagax resolve the issue

Several different workarounds have been described in this issue report, so in the new issue please be specific about which workarounds you have tried, which ones were successful, and which ones were unsuccessful.
