### ISSUE TITLE
steam-runtime soldier doesnt work with a symlink at /var/tmp

### ISSUE THREAD

**Issue by farmboy0** [ValveSoftware/steam-runtime#368]
#### Your system information

* Steam Runtime Version:  0.20210208.0
* Distribution (e.g. Ubuntu 18.04):  Gentoo
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
 https://gist.github.com/farmboy0/16f79f8c08e6062bb1cf5365963499ce#file-steam-system-information
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] No, the compat tool is Proton 5.13

#### Please describe your issue in as much detail as possible:

This seems to be some recent change as Proton 5.13 worked for me like a month ago.
But now when running any game the steam-runtime will show this error:
bwrap: Can't make symlink at /var/tmp: File exists

If I remove the link and replace it with a bind mount Proton will work again.
I was having this link in place for several years so this should be a regression.

The steam-runtime-system-info would also show this error when run on the cmdline.
In steam's System Information it would just never complete.

#### Steps for reproducing this issue:

1. Make /var/tmp a symlink to /tmp
2. Run any game with Proton 5.13
3.

**Comment by smcv** [comment]
I think I can see why this is happening.

I would recommend using bind-mounts in preference to symlinks, particularly for system directories like `/var/tmp`, but we can probably rearrange the code in pressure-vessel to cope with `/var/tmp` being a symlink.

**Comment by smcv** [comment]
The next beta should resolve this (tested by setting up symlinks `/var -> VAR` and `/VAR/tmp -> TMP`, with `/VAR/TMP` as the actual temp directory).

**Comment by smcv** [comment]
This should be fixed in today's beta update. [Instructions for trying the beta, if you are not already](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#using-a-beta-or-an-older-version)

Please check `SteamLinuxRuntime_soldier/VERSIONS.txt` after updating: it should say that you have pressure-vessel version 0.20210309.0+srt1. With that version, the `PRESSURE_VESSEL_GRAPHICS_PROVIDER=/` workaround should become unnecessary.

**Comment by smcv** [comment]
0.20210309.0 has been released as the production version, so this should now be fixed even without using the beta.

**Comment by kisak-valve** [comment]
Closing per the last comment.
