### ISSUE TITLE
30xx (1029210) crashes straight to desktop

### ISSUE THREAD

**Issue by Cytomax55** [ValveSoftware/steam-runtime#375]
Protondb.com is convinced the game runs so i must be doing something wrong
https://www.protondb.com/app/1029210

#### Your system information

* Steam Runtime Version:  (I thinks is correct) soldier_0.20210208.0 
* (located /home/$USER/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/)

* Distribution: Manjaro KDE 5.10.18-1

* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
https://gist.github.com/Cytomax55/73c21f0517270a5696c478e108e018a8

* Have you checked for system updates?: YES

* Are you using the Steam Linux Runtime compatibility tool?: Steam Linux Runtime Soldier

#### Please describe your issue in as much detail as possible:
I run the game and it crashes straight to desktop with this error

First Pop Up
D3D Error
ERROR'D -- shader file not found or shader compilation failed. Maybe try running as admin?

i click Okay

Then a 2nd Popup

D3D Error
d3d->createDevice failed. 20xx will now exit :(

If you are using the Steam Linux Runtime compatibility tool, please
provide the information requested here:

running WITHOUT any launch options
https://gist.github.com/Cytomax55/f3c69fb5b9ba326c8325beecc5f62031

running WITH PROTON_NO_FSYNC=1 %command%
https://gist.github.com/Cytomax55/3d1670a369de11c85ea41c80d9d461bc

#### Steps for reproducing this issue:

1. Run the game with any proton version

**Comment by kisak-valve** [comment]
Hello @Cytomax55, in general, feedback for 30XX being run with Proton should go to https://github.com/ValveSoftware/Proton/issues/4632. However, your system information ends with `CClientJobGatherRuntimeInformation: container read output failed`, and that does hint that there is an issue with running Pressure Vessel on your system.

It looks like your system would be affected by #303 and #365. Please give them a read. In particular, https://github.com/ValveSoftware/steam-runtime/issues/303#issuecomment-783461878 and the comment after it.

**Comment by Cytomax55** [comment]
> Hello @Cytomax55, in general, feedback for 30XX being run with Proton should go to [ValveSoftware/Proton#4632](https://github.com/ValveSoftware/Proton/issues/4632). However, your system information ends with `CClientJobGatherRuntimeInformation: container read output failed`, and that does hint that there is an issue with running Pressure Vessel on your system.
> 
> It looks like your system would be affected by #303 and #365. Please give them a read. In particular, [#303 (comment)](https://github.com/ValveSoftware/steam-runtime/issues/303#issuecomment-783461878) and the comment after it.

ty for the information, 
I noticed i have 2 Steam Linux Runtimes
Steam Linux Runtime
Steam Linux Runtime - Soldier

which one do i change to beta?

**Comment by kisak-valve** [comment]
Steam Linux Runtime - Soldier is used with Proton.

**Comment by Cytomax55** [comment]
I changed

Steam Linux Runtime - Soldier to Steam Linux Runtime - Soldier Beta

Steam > Settings > Account > Steam Beta Update

It still crashes the exact same way with the exact same error message


Now i am on pressure-vessel version 0.20210203.0+srt1



First Pop Up
D3D Error
ERROR'D -- shader file not found or shader compilation failed. Maybe try running as admin?

i click Okay

Then a 2nd Popup

D3D Error
d3d->createDevice failed. 20xx will now exit :(


https://gist.github.com/Cytomax55/b7e3635c609b367ffab77bdca4762e06


Let me know what you think i have no idea what the logs mean

Thanks in Advance

**Comment by smcv** [comment]
If this is still a problem after today's updates to soldier, please provide new logs. You can use either the production version or the beta, but please say which.

Please get all of these logs from the same system state. It's best if you update soldier, then completely exit from Steam, then relaunch Steam with the environment variables set.

* Help -> System Information
* *Steam Linux Runtime - soldier* log from running Steam with `STEAM_LINUX_RUNTIME_LOG=1` (`slr-app1029210-(something).log`)
* Proton log from running Steam with `PROTON_LOG=1` (`steam-1029210.log`)

It would also be useful to know whether other games work in Proton on your system. [Floating Point](https://store.steampowered.com/app/302380/Floating_Point/) and [Life is Strange episode 1](https://store.steampowered.com/app/319630/Life_is_Strange__Episode_1/) are examples of free games that we often use for testing. By default, Steam will install their native Linux versions, but if you change the compatibility tool in their properties to Proton 5.13-6, Steam will switch to the Windows version and run it in Proton.

**Comment by smcv** [comment]
@kisak-valve, please could you label this as needing more info?

**Comment by kisak-valve** [comment]
Closing pending feedback.
