### ISSUE TITLE
Since system update no game starts

### ISSUE THREAD

**Issue by cmdr19** [ValveSoftware/steam-runtime#378]
Good day,

I'm trying to start Doom Eternal.
It always worked, it worked 1-2 weeks ago.
Recently I tried to run 3 different games (Doom Eternal, Deadlight, Beyond Dlue), different proton version, they all failed. 

I'm on 5.13-6 proton, Doom Eternal is stuck at "preparing to launch" and "launching" status, but nothing happens, game not starts
It is just "play' button appears again

![2021-03-09_20-36](https://user-images.githubusercontent.com/80351839/110514633-8ece1200-8118-11eb-83d1-bae1d5dbb72f.png)

System informations
[System Information.txt](https://github.com/ValveSoftware/steam-runtime/files/6110459/System.Information.txt)

Steam client logs
[slr-app782330-sa4fbc16331337b8.log](https://github.com/ValveSoftware/steam-runtime/files/6110461/slr-app782330-sa4fbc16331337b8.log)

Proton client logs
[steam-782330.log](https://github.com/ValveSoftware/steam-runtime/files/6110489/steam-782330.log)

**Comment by kisak-valve** [comment]
Hello @cmdr19, it looks like your system would be affected by https://gitlab.freedesktop.org/mesa/mesa/-/issues/4396. Please update mesa git to at least https://gitlab.freedesktop.org/mesa/mesa/-/commit/fb1100d718fbee07dc294e1ede20a084cda423b9.

**Comment by cmdr19** [comment]
I tried to start steam with command `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam` , and it fix problem. And i have to run steam with terminal. 

Maybe i am asking the wrong person, but how should i update mesa-git to [this](https://gitlab.freedesktop.org/mesa/mesa/-/commit/fb1100d718fbee07dc294e1ede20a084cda423b9) version? I have mesa-git from AUR, and there last update was at 03.03.2021

**Comment by RyuzakiKK** [comment]
> Maybe i am asking the wrong person, but how should i update mesa-git to [this](https://gitlab.freedesktop.org/mesa/mesa/-/commit/fb1100d718fbee07dc294e1ede20a084cda423b9) version? I have mesa-git from AUR, and there last update was at 03.03.2021

The `-git` packages on AUR always grabs the latest version when you compile them. Given that the necessary commit has already being merged in master, if you install, and compile, again `mesa-git` you should get the latest development version with the fix included.

**Comment by cmdr19** [comment]
Thank you, it's really works =)
