### ISSUE TITLE
"Error starting pressure-vessel container" with Proton 5.13 on Solus

### ISSUE THREAD

**Issue by Staudey** [ValveSoftware/steam-runtime#380]
#### Your system information

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): Solus 4.2
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/Staudey/2ce56dad3eaea95a5898c09dd7f6fffe
  
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: YEs

#### Please describe your issue in as much detail as possible:

Trying to launch any game using the Proton 5.13 "Steam play compatibility tool" on Solus results in the status of the game changing to "Running" for a few second, and then it silently closing again. No window is created at any point. Proton versions up to 5.0-10 work fine.

Launching steam with the "STEAM_LINUX_RUNTIME_LOG=1 STEAM_LINUX_RUNTIME_VERBOSE=1 PROTON_LOG=1" parameters and trying to launch the game "b" results in the following log: https://gist.github.com/Staudey/349752388edaf007382ee222d1bd4570

I've browsed through other issues (for Steam Runtime, Proton, Pressure Vessel) and saw some possibly related things, but since all of this is going over my head a bit I created this issue report so someone can hopefully point me in the right direction.

Note: Since Solus uses the "Linux Steam Integration" tool by default I tried disabling the "Use native runtime" setting there, but this had no effect on this issue. I also tried the newest Steam Linux Runtime - Solder beta, and disabling Mango HUD, since those were mentioned in the known issues.

#### Steps for reproducing this issue:

1. Launch Steam on Solus
2. Install e.g. the free game "b"
3. Try to launch it without specifying a Proton version (this will run it with Proton 5.13-6 at the moment)
4. Observe that the status changes to "Launching..." then "Running" and then the game silently closes

**Comment by smcv** [comment]
In your log, unfortunately something seems to be failing without an error message. `pressure-vessel-wrap` uses `execve()` to replace itself with a long `/usr/bin/bwrap` command-line, and then the next thing we see is the wrapper script `_start-container-in-background` reporting `Error starting pressure-vessel container`. I would have expected to see an error message from `bwrap` before that...

What version of `/usr/bin/bwrap` does Solus have? (For example `/usr/bin/bwrap --version` would tell us which upstream version it's based on, although would not tell us whether Solus applies any special patches.)

If you do this while running Steam from a terminal, do you get any interesting messages appearing on that terminal?

Do other games running under Proton work? https://store.steampowered.com/app/302380/Floating_Point/ is an example of a game that is very small and is known to work in the container - it will be installed as a native Linux game by default, but you can force Steam to install the Windows version instead by selecting the Proton 5.13-6 compatibility tool in the game's properties.

**Comment by smcv** [comment]
> Note: Since Solus uses the "Linux Steam Integration" tool by default I tried disabling the "Use native runtime" setting there, but this had no effect on this issue. I also tried the newest Steam Linux Runtime - Solder beta, and disabling Mango HUD, since those were mentioned in the known issues.

The log you provided seems to have come from the normal (non-beta) branch. If you can show us a similar log from the beta, that might give us a bit more information?

To reduce the number of variables, it would probably be good to keep "Linux Steam Integration" disabled, and keep Mango HUD disabled.

> `LD_AUDIT=/usr/$LIB/liblsi-intercept.so`
> `LD_PRELOAD=/usr/$LIB/liblsi-redirect.so`

This could be anywhere between "completely harmless" and "very bad". We can't really support arbitrary `LD_PRELOAD` and `LD_AUDIT` modules - any time there's a module that changes how libraries are loaded, it could be breaking our assumptions, or we could be breaking its assumptions, or both.

**Comment by smcv** [comment]
```
  "runtime" : {
    "path" : null,
    "version" : null,
    "issues" : [
      "disabled"
    ]
  },
```

It probably doesn't affect this particular issue much (if at all), but we cannot support systems where the Steam Runtime is disabled (sometimes referred to as a "native runtime"). As you can see from the System Information log, disabling the Steam Runtime means that lots of libraries that are expected to be present, such as `libtiff.so.4`, will fail to load. Native Linux games on Steam are allowed to assume that these libraries are present, and will not work in your "native runtime".

**Comment by Staudey** [comment]
Hello @smcv,
First of all thank you for the detailed response(s)! Here are further details, as requested:

> What version of /usr/bin/bwrap does Solus have? (For example /usr/bin/bwrap --version would tell us which upstream version it's based on, although would not tell us whether Solus applies any special patches.)

Solus has version 0.4.1 of bubblewrap; there doesn't seem to be extra patches applied, but the option "--with-priv-mode=setuid" is used for the configure script, see [here](https://dev.getsol.us/source/bubblewrap/browse/master/package.yml)

> Do other games running under Proton work?[...]

No, all games I've tried fail in the same way with Proton 5.13; Floating Point included

> If you can show us a similar log from the beta, that might give us a bit more information?
To reduce the number of variables, it would probably be good to keep "Linux Steam Integration" disabled, and keep Mango HUD disabled.

Here is a log with "Linux Steam Integration" disabled, the beta branch of the Soldier Runtime installed and Mango HUD disabled, again using the game "b" as an example: https://gist.github.com/Staudey/c578b5c7930c20c6f70b1e6a2a5f6a56

and here the System Information output with "Linux Steam Integration" disabled: https://gist.github.com/Staudey/a7bbb6408275a6ecec885085131f8406

**Comment by smcv** [comment]
Thanks, those give us some more info but nothing really jumps out at me. I'm finding it weird that we don't see an error message in your log. We get:

```
20:10:48.989904: pressure-vessel-wrap[7836]: D: Replacing self with bwrap...
20:10:49.048073: _start-container-in-background[7821]: Error starting pressure-vessel container
```

but if it's failing at this point, then I would usually expect to see something more like this:

```
20:10:48.989904: pressure-vessel-wrap[7836]: D: Replacing self with bwrap...
bwrap: Some error message here
20:10:49.048073: _start-container-in-background[7821]: Error starting pressure-vessel container
```

Does Flatpak work on this system? That would help to check whether there's a problem with `bwrap` (pressure-vessel's use of `bwrap` is very similar to Flatpak's).

**Comment by Staudey** [comment]
Yes, Flatpak works on my system. Just tried the Flatpak game "Aqueducts" to make sure and it launched just fine.
Anything else I can dig into, or try to get logs from?

**Comment by smcv** [comment]
> Anything else I can dig into, or try to get logs from?

Before doing any of these, check that you're confident that you can undo them and get back to a supported situation, including reinstalling the affected packages if necessary (I don't know how to do that in Solus's package manager).

One thing you could try is changing the permissions of `/usr/bin/bwrap` so it is *not* setuid root (`chmod 0755 /usr/bin/bwrap` or similar). Solus is installing it setuid root, but it isn't clear to me why this has been done. The only reason to make it setuid root is if your kernel restricts the ability for unprivileged users to create new namespaces (like Debian 10 and RHEL 7) - but as far as I can tell from the information on `dev.getsol.us`, the Solus kernel seems to have full support for unprivileged user namespaces (like Debian 11, Fedora, Ubuntu) so it doesn't need this?

Another thing you could try doing is: rename `/usr/bin/bwrap` to `/usr/bin/bwrap.real`, and replace it with this shell script:

```
#!/bin/bash
set -eu
echo "$0[$$]: called with arguments $(printf '%q ' "$@")" >&2
e=0
/usr/bin/bwrap.real "$@" || e="$?"
echo "$0[$$]: exit status $e" >&2
exit "$e"
```

and then retry launching a game, and see whether you get new messages appearing in the log between `D: Replacing self with bwrap` and `Error starting pressure-vessel container` (you should).

**Comment by Staudey** [comment]
> One thing you could try is changing the permissions of /usr/bin/bwrap so it is not setuid root (chmod 0755 /usr/bin/bwrap or similar).

Oh wow, this actually fixes it, thanks! I will report this on the Solus bug tracker and try to find out whether that configure option for bubblewrap is (still) necessary. I'll close this issue since this seems like something that should be fixed on Solus' side.
Thank you again for the great support!

**Comment by smcv** [comment]
If a setuid bwrap doesn't work, that's still a bug *somewhere*: having bwrap setuid root is the configuration that is *meant* to work on any kernel (although it's only really necessary on e.g. Debian 10, so it's probably regression-prone).

We run a lot of simpler bwrap commands while setting up the container, so your setuid bwrap can't be *completely* broken: it's only failing with the final, complicated command-line.

**Comment by smcv** [comment]
> I will report this on the Solus bug tracker and try to find out whether that configure option for bubblewrap is (still) necessary

Please could you drop a link here when you've done that? I'm an upstream contributor to bubblewrap and might be able to give more context if people need it.

**Comment by Staudey** [comment]
> If a setuid bwrap doesn't work, that's still a bug somewhere

Okay, so to get more data I changed the setuid bit back again, and tried the "replace bwrap with shell script" method you described above
Here is the log created: https://gist.github.com/Staudey/121770a1d800f52e0820fc243855d9b4

New output: 
```
01:07:28.555484: pressure-vessel-wrap[27631]: D: Replacing self with bwrap...
/usr/bin/bwrap[27631]: called with arguments --args 32 /run/pressure-vessel/pv-from-host/bin/pressure-vessel-adverb --generate-locales --fd 12 --terminate-timeout=2\,000000 --exit-with-parent --subreaper --pass-fd=3 --pass-fd=30 --shell=none --terminal=none --verbose -- /home/thomas/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/pressure-vessel-launcher --verbose --lock-env-from-fd 30 --info-fd=3 --socket-directory=/tmp/SteamPVSockets.6GSOR5/SteamLinuxRuntime.56e0318393c2a004 
/usr/bin/bwrap[27631]: exit status 132
01:07:28.622683: _start-container-in-background[27623]: Error starting pressure-vessel container
```

> Please could you drop a link here when you've done that? I'm an upstream contributor to bubblewrap and might be able to give more context if people need it.

Sure thing. For now I just added a comment to the existing issue about Proton 5.13 not working here: https://dev.getsol.us/T9406#182736

**Comment by smcv** [comment]
> exit status 132

That's probably `SIGILL`, which seems a weird thing to happen.

Are you running Steam under some sort of container or LSM confinement?

**Comment by smcv** [comment]
If an executable is crashing, can you get a backtrace from it? (Maybe Solus has `coredumpctl` available?)

**Comment by Staudey** [comment]
> Are you running Steam under some sort of container or LSM confinement?

Not that I'm aware of. Solus uses the files from here in its package: https://repo.steampowered.com/steam/pool/steam/s/steam/
and that is what I'm running. As far as I can see there is nothing added in terms of confinement.

> Maybe Solus has coredumpctl available?

It has. I'll have to see how to go about getting a backtrace as soon as I find the time.

**Comment by Staudey** [comment]
@smcv Hello again, sorry for the long silence; I've been pretty busy with work and other stuff.
By now I have to admit that I have no idea how I would best go about getting a backtrace inside of pressure-vessel. Could you perhaps point me in the right direction?

**Comment by smcv** [comment]
> By now I have to admit that I have no idea how I would best go about getting a backtrace inside of pressure-vessel. Could you perhaps point me in the right direction?

The crash you were seeing in `bwrap` is before it entered the container environment (I think?) so there is not really anything pressure-vessel-specific here. I'd recommend talking to your distribution's support channels, if it has them. What you're looking for is the Solus equivalent of <https://wiki.debian.org/HowToGetABacktrace>.

**Comment by Staudey** [comment]
> The crash you were seeing in bwrap is before it entered the container environment (I think?) so there is not really anything pressure-vessel-specific here

Oh yes, that's true. I think I can handle that then. Will report back as soon as I have something interesting.
