### ISSUE TITLE
Eternal Return: Black Survival

### ISSUE THREAD

**Issue by GentooCool** [ValveSoftware/steam-runtime#387]
# Compatibility Report
- Name of the game with compatibility issues: Eternal Return: Black Survival
- Steam AppID of the game: 1049590

## System Information
- GPU: GTX 2070 Super
- Driver/LLVM version: Nvidia 460.39 / LLVM 11.1.0
- Kernel version:  5.4.97
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/GentooCool/e4dc193cc1cf431f543255709a6b1cf1
- Proton version: 5.13.-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Previously game was wonky -- crashed to desktop often while in lobby -- but for the most part, I could play entire matches. Worked with Proton 5.13 and with Proton 6.2GE 

However, after the game's Mar 24 update, nothing works. Most Proton versions won't even load the game. The closest to success is unchecking "force specific Proton version". The game will load, get past splash screens, and right when it reaches the main lobby, will crash to desktop. 

I've attached my log file. Hope you could help, and appreciate all Valve has been doing for gaming on Linux! You guys rock!

## Reproduction
-Attempt A: force version Proton 5.13: game won't load. Steam goes from Play -> Stop -> Play again.
-Attempt B: UNcheck specific Proton version: game will load, gets past splash screens, then crashes to desktop.

[steam-1049590.log](https://github.com/ValveSoftware/Proton/files/6214003/steam-1049590.log)

**Comment by kisak-valve** [comment]
So, there's two parts to this issue report. First, there's an apparent change in game behavior which sounds like a game update induced regression. I've transferred a copy of this issue report to https://github.com/ValveSoftware/Proton/issues/4653 for that feedback.

Second, your system information ends with `CClientJobGatherRuntimeInformation: container read output failed` which hints that there's an issue with running Pressure Vessel on your system. Proton 5.13 and newer uses Pressure Vessel to setup and use the Steam Linux Runtime - Soldier container environment. Instead of telling you to open a new issue report from scratch, I've transferred this issue report to the ValveSoftware/steam-runtime issue tracker to ponder that issue instead of needing to re-write what you're seeing from scratch.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and attach a Steam Linux Runtime - Soldier log to this issue report.

Instead of

**Comment by GentooCool** [comment]
Ran Steam using these variables: STEAM_LINUX_RUNTIME_VERBOSE=1 PRESSURE_VESSEL_VERBOSE=1 CAPSULE_DEBUG=all G_MESSAGES_DEBUG=all STEAM_LINUX_RUNTIME_LOG=1 steam

Log attached (**'Soldier' runtime w/ Steam client beta**). Sorry, everything is contained in one log, since I couldn't separate them out. I ran attempts in this order: 

- Attempt A: launch game using Proton 5.13.6 -- game doesn't load
- Attempt B: launch game using Proton experimental -- game doesn't load
- Attempt C: trying to load game with Proton 5.10.0 -- game loads, gets past splash, crashes to desktop

[slr-app1049590-s60f3afb5642ea4e8.log](https://github.com/ValveSoftware/steam-runtime/files/6216271/slr-app1049590-s60f3afb5642ea4e8.log)

**Comment by kisak-valve** [comment]
`bwrap: Can't mkdir /usr/lib64/gconv: Read-only file system` in the log hints that this might be related to #300 / #328.

Maybe try adapting the troubleshooting instructions at https://github.com/ValveSoftware/steam-runtime/issues/300#issuecomment-728993249.

**Comment by GentooCool** [comment]
Wow, you helped me fix it. Let me know how I can buy you a coffee or how I can contribute in some other way. 

Reading through those linked bug reports got my gears turning, since why can't bwrap find a directory that already exists. Then running some of the LS commands (output below), made me go...huh that's weird, why don't those directories even exist in the Soldier runtime container. It confirmed to me it was probably that bug where it didn't unpack the new runtime properly, but Steam never told me this! I've also reinstalled Steam, reinstalled the game etc, and it never told me anything was missing. My only guess is that when the game updated, it borked something.

Then I went to my Steam library, right clicked on the Soldier runtime > Properties > Betas.  Switched it to "use with Steam client beta"--odd that this wasn't already set, since under Steam -> Settings -> Account, it shows I'm opted into the beta. Changing this setting in Soldier reinstalled the missing runtime files. "Verify integrity of tool files" showed 100% validated. 

Now the game successfully launches under Proton 5.13.6.  **YOU ROCK!**


> env LANG=C ls -ld /lib /lib32 /lib64 /usr/lib /usr/lib32 /usr/lib64 /usr/lib/gconv /usr/lib32/gconv /usr/lib64/gconv
> 
> _ls: cannot access '/lib32': No such file or directory
> ls: cannot access '/usr/lib32': No such file or directory
> ls: cannot access '/usr/lib32/gconv': No such file or directory
> drwxr-xr-x  11 root root   4096 Mar 10 17:23 /lib
> drwxr-xr-x   6 root root   4096 Mar 16 19:36 /lib64
> drwxr-xr-x  42 root root  24576 Mar 25 22:39 /usr/lib
> drwxr-xr-x   2 root root  12288 Mar 10 17:23 /usr/lib/gconv
> drwxr-xr-x 125 root root 126976 Mar 25 22:45 /usr/lib64
> drwxr-xr-x   2 root root  12288 Mar 10 17:23 /usr/lib64/gconv_
> 
> 
> cd ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier
> ls -ld soldier/files/lib32 soldier/files/lib64 soldier/files/lib
>
> _ls: cannot access 'soldier/files/lib32': No such file or directory
> ls: cannot access 'soldier/files/lib64': No such file or directory
> ls: cannot access 'soldier/files/lib': No such file or directory_

**Comment by kisak-valve** [comment]
Glad to hear you got it going again. Closing in favor of #300.
