### ISSUE TITLE
libibus-1.0.so.5 missing in Scout (Metro Exodus, Linux version)

### ISSUE THREAD

**Issue by dpanter** [ValveSoftware/steam-runtime#399]
#### Your system information
- Steam Runtime Version: 0.20210415.0
- Distribution: Siduction (Debian sid based). Can't gather system information in Steam as it crashes when I try, however it's not critical for this bug report. Short: 5.12.0-rc7, Mesa-git 21.2, KDE Plasma 5.20.5, RX6900XT
- Have you checked for system updates?: Yes
- Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:
Game doesn't start, error message in logs about missing **libibus-1.0.so.5**
`error while loading shared libraries: libibus-1.0.so.5: cannot open shared object file: No such file or directory`

**libibus-1.0.so.5.0.524** is installed on my system and I can see that **libibus-1.0.so.5.0.519** exists in Soldier.

#### Steps for reproducing this issue:
1. Start Metro Exodus using SLR

Logs:
[Steam terminal output](https://gist.github.com/dpanter/fdae5042089e1156337b89de71ce26fb)

[slr-app412020-t20210419T192741.log](https://github.com/ValveSoftware/steam-runtime/files/6337988/slr-app412020-t20210419T192741.log)

**Comment by smcv** [comment]
If Metro Exodus requires `libibus-1.0.so.5`, then it must have not been compiled in the recommended scout runtime environment. scout only has the older version `libibus-1.0.so.0`.

This looks like a game bug. There is no guarantee that a game that was compiled against `libibus-1.0.so.5` will work in any particular environment - although on your system without using SLR, right now, it would work by luck.

> Can't gather system information in Steam as it crashes when I try

This might indicate a wider problem with Steam or your system. The old way to get an equivalent log is:

```
~/.steam/root/ubuntu12_32/steam-runtime/run.sh steam-runtime-system-info > srsi.log
```

**Comment by dpanter** [comment]
Thanks Simon, there's indeed all kinds of interesting problems with Metro Exodus at the moment.
Not sure what's going on with the client crashing (both stable and beta) but I noticed another Debian user mention the same thing. Anyway here's the system info, collected old style. [srsi.log](https://github.com/ValveSoftware/steam-runtime/files/6338178/srsi.log)

**Comment by smcv** [comment]
> Mesa Gallium driver 21.2.0-devel

This seems pretty close to the edge...

**Comment by dpanter** [comment]
> This looks like a game bug. There is no guarantee that a game that was compiled against `libibus-1.0.so.5` will work in any particular environment - although on your system without using SLR, right now, it would work by luck.

I think you are correct, and the game runs with Soldier. Same specs as earlier, launched game via Steam beta client.
`...../SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/run-in-soldier %command%`


Didn't get a log for it but here's the [terminal output](https://gist.github.com/dpanter/724892226899f33935b1690b31fb71ab) anyway.

Guess this issue can be closed?

**Comment by smcv** [comment]
> I think you are correct, and the game runs with Soldier

This is not something that is supported, and you are not meant to need to do it. At the moment, all native Linux games on Steam are meant to be compiled against Steam Runtime 1 'scout'. soldier is not 100% compatible with scout (for example it doesn't have `libibus-1.0.so.0` available) so if a game was correctly compiled against scout, then trying to run it in a soldier container will fail.

However, if it works for you, as a workaround for a game that wasn't compiled in the intended way, then... great?

In future, I'm hoping that the Steam client will get a way for game developers to flag their game as needing soldier (or a newer runtime, when we have one). If that feature is added, then games that were flagged as needing soldier will *always* run in a soldier container, never scout or a future runtime.
