### ISSUE TITLE
How to find out the latest version of the Runtime?

### ISSUE THREAD

**Issue by abbradar** [ValveSoftware/steam-runtime#40]
We package and use Steam for NixOS in a special way, essentially building our own runtime replacing some libraries with our own updated versions. We use `http://media.steampowered.com/client/runtime/steam-runtime-release_${version}.tar.xz` as a source, but we don't (and can't due to checksums) use `latest` as a version. The only way we've found to get current latest release is:

1. Download `latest` archive.
2. Look at the version file/directory name (currently `2014-04-15`).

Is there any simpler way?

**Comment by scottlu** [comment]
The way the runtime is distributed has changed. Read more about it here:

https://github.com/ValveSoftware/steam-runtime

Look on that page for the build-runtime.py script.

**Comment by abbradar** [comment]
Thanks, I've built Runtime successfuly myself. For our purposes, though, it would be nice to have a URL from which steam downloads the prebuilt runtime, to save time and bandwidth of users.

**Comment by abbradar** [comment]
I think we are finally settled -- we now have an infrastructure for updating and assembling runtime in Nix.
