### ISSUE TITLE
Proton completely or partially stopped working after updating the system

### ISSUE THREAD

**Issue by ICaxapI** [ValveSoftware/steam-runtime#404]
#### System information

* Steam Runtime Version:  steam-runtime_0.20210422.0
* Distribution: Manjaro Linux
* [Full system information](https://gist.github.com/ICaxapI/135db4e80a94a4384a3054b952ff29a3)
* Have you checked for system updates?: **_Yes_**
* Are you using the Steam Linux Runtime compatibility tool?: **_Yes_**

### Foreword
Hey! I got a problem with a lot of games after updating my system. Those games that run always have no sound, but most simply do not start. Before updating my system, everything was fine and there were definitely no problems with the games listed below.
Moreover, if I use other Proton interpretations (like PortProton, for example) - I do not face any of the above problems. I tried all versions of Proton, and none of them worked, but for some reason the most detailed startup logs were obtained when using **Proton Experemental**, so I will give all the logs further using this version.
Note that this is only a problem with Proton. Native games run fine, like everything else in the system.
### Some details
When I launch any of the games, I get similar error logs that keep repeating in one form or another when launching other games.
For example, the error log 100% associated with the lack of sound in the game is:
> ALSA lib dlmisc.c: 287: (snd1_dlobj_cache_get) Cannot open shared library /usr/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so ((null): libgpg-error.so.0: cannot open shared object file: No such file or directory)
-- From log of from The Binding of Isaac: Repentance (App ID | 1426300)

Also has the form in other cases:
> ALSA lib dlmisc.c: 287: (snd1_dlobj_cache_get) Unable to open shared library /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so ((null): libgpg-error.so.0: unable to shared object file : No such file or directory)
-- From log of Generation Zero (App ID | 704270)

Games that refuse to start at all also have an error above, and a mention of DINPUT8.dll / order to check the DX9 installation:
>Gamepad_init fatal error: Couldn't load DINPUT8.dll

>Input [Error]: Could not find DirectInput! You must install the DirectX 9 runtime!

### Extra info
Yes, I definitely have these libraries on my system (see ldconfig -v below) and I tried to reinstall them, and older versions. I also created symlinks for the alsa libraries, which seem to be trying to load from the wrong place. None of this worked. I also have all the necessary packages in my system, but if you need to clarify one specific one, do not hesitate to ask.
However, I have been trying to solve this problem for more than one day, and have looked through many different solutions to similar problems on the net. Here are just a few of them (Nothing helped):
[Linux here--nice looking game but no sound...](https://steamcommunity.com/app/218090/discussions/0/828925849177856756/?l=french)
[Steam searches for libasound_module_pcm_pulse.so at the wrong location](https://github.com/ValveSoftware/steam-for-linux/issues/1199) --Not about the proton, here they tried to launch native games, I have no problems with that

--
[sudo ldconfig -v](https://pastebin.com/RFmkziaC)
[Complete list of packages affected by the update](https://pastebin.com/J01YNt3k) (Rolling back these packages to a previous version did not give a positive result)

### Game launch logs
All games below ran perfectly and had no issues prior to the update.
For some reason, with the environment variable STEAM_LINUX_RUNTIME_LOG to 1 set, there are not some log lines that are issued during normal startup from a terminal emulator, therefore the following logs were written without this parameter. But in the end I will attach a logs with this parameter for each of them.

[Full unedited run log The Binding of Isaac: Repentance](https://pastebin.com/HwvYP8cw) - Doesn't start at all
[slr-app250900-s300fa0f435fa857a.log](https://github.com/ValveSoftware/steam-runtime/files/6408793/slr-app250900-s300fa0f435fa857a.log)

[Full unedited run log Generation Zero](https://pastebin.com/hvh9HAbW) - Runs without sound
[slr-app704270-sf25f9f4e913aedf5.log](https://github.com/ValveSoftware/steam-runtime/files/6408794/slr-app704270-sf25f9f4e913aedf5.log)

[Full unedited run log Portal: reloaded](https://pastebin.com/cXaWyqHq) - Runs without sound
[slr-app1255980-s701185e3bef21894.log](https://github.com/ValveSoftware/steam-runtime/files/6408796/slr-app1255980-s701185e3bef21894.log)

[Full unedited run log Doom: Eternal](https://pastebin.com/Du4dhUT7) - Runs without sound
[slr-app782330-se8750967368f8eb8.log](https://github.com/ValveSoftware/steam-runtime/files/6408795/slr-app782330-se8750967368f8eb8.log)

[Full unedited run log Warframe](https://pastebin.com/zULtYKFk) - The main game does not start at all, the launcher starts, but no sound.
[slr-app230410-s457c4450a6a4573c.log](https://github.com/ValveSoftware/steam-runtime/files/6408792/slr-app230410-s457c4450a6a4573c.log)

**Comment by kisak-valve** [comment]
Hello @ICaxapI, looking at the diagnostic information, there indeed is something off with `libgpg-error.so.0` and it's not alsa related. However, that issue is inside the Steam Linux Runtime - Soldier container environment, not the host system and manipulating system packages shouldn't have an effect. I'd expect for it to be a symlink in `<Steam Library Folder>/steamapps/common/SteamLinuxRuntime_soldier/var/deploy-0.20210415.0/files/lib/x86_64-linux-gnu`.

Maybe try adapting https://github.com/ValveSoftware/steam-runtime/issues/300#issuecomment-728993249 and see if it has an effect?

**Comment by ICaxapI** [comment]
Yes, it really helped! After the done manipulations, everything worked again. **Thank you so much!**
