### ISSUE TITLE
Checksum / ISO validation activation servers down?

### ISSUE THREAD

**Issue by cashmerefly** [ValveSoftware/steam-runtime#406]
I wasn't really sure where to put this, but I recently acquired some very old retail games  (DVD discs) with a Steam logo (NBA 2K9 and Top Gun), and they are supposed to activate using some ancient checksum / iso validiation through Valve's servers (no retail CD key printed).

However, this is not working. Are these servers sunset for the time being? I'm running the latest version of Steam and tested activating on several drives and systems.

**Comment by kisak-valve** [comment]
Hello @cashmerefly, this doesn't sound related to the Steam runtime or Steam for Linux. Your best chance for this to be evaluated by the right folks is to use [Steam Support](https://help.steampowered.com/).
