### ISSUE TITLE
Guacamelee! Gold Edition (214770) doesn't launch

### ISSUE THREAD

**Issue by DanMan** [ValveSoftware/steam-runtime#409]
#### Your system information

* Steam Runtime Version: steam-runtime_0.20210422.0
* Distribution (e.g. Ubuntu 18.04): Fedora 33
* [Link to your full system information](https://gist.github.com/DanMan/df94fe2dc319aad76fc097c2f90e6329/a75201dff250134bf8df58f01aae106ebca44565)
* Have you checked for system updates?: [Yes]
* Are you using the Steam Linux Runtime compatibility tool?: [Yes]

#### Please describe your issue in as much detail as possible:
Game doesn't launch at all.

Tried to set `STEAM_LINUX_RUNTIME_LOG=1` but then steam wouldn't even launch.

#### Steps for reproducing this issue:

1. Launch Steam
2. Enable "Steam Linux Runtime" for the game
3. Launch game

Result in terminal:

```
Loaded Config for Local Selection Path for App ID 214770, Controller 4: /home/redacted/.local/share/Steam/steamapps/workshop/content/241100/1481661525/960843370970787542_legacy.bin
GameAction [AppID 214770, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 214770, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 214770, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 214770, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 214770, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 214770, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 214770 "", ProcID 36505, IP 0.0.0.0:0
ERROR: ld.so: object '/home/redacted/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 214770
>>> Adding process 36505 for game ID 214770
GameAction [AppID 214770, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
pid 36509 != 36506, skipping destruction (fork without exec?)
GameAction [AppID 214770, ActionID 2] : LaunchApp changed task to Completed with ""
pressure-vessel-adverb[36695]: E: Failed to execute child process "/mnt/games/linux/steamlib/steamapps/common/Guacamelee/game" (Permission denied)
Game removed: AppID 214770 "", ProcID 36505 
Uploaded AppInterfaceStats to Steam
Exiting app 214770
No cached sticky mapping in ActivateActionSet.No cached sticky mapping in ActivateActionSet.
```

I've deleted some duplicate lines for brevity.

**Comment by smcv** [comment]
> Tried to set STEAM_LINUX_RUNTIME_LOG=1 but then steam wouldn't even launch

That's strange. What, exactly, did you do, and what output or messages do you get? Please walk me through the steps you used?

If you completely exit from Steam, and then run it in a terminal with:

```
user@host:~$ STEAM_LINUX_RUNTIME_LOG=1 steam
```

then that should work. If it doesn't, that's a separate bug in something, unrelated to Guacamelee not working (but we might have to solve it before we can find out why Guacamelee can't launch).

**Comment by smcv** [comment]
```
pressure-vessel-adverb[36695]: E: Failed to execute child process "/mnt/games/linux/steamlib/steamapps/common/Guacamelee/game" (Permission denied)
```

What type of filesystem is this on - ext4, btrfs, xfs, ntfs-3g, other?

What does `ls -l /mnt/games/linux/steamlib/steamapps/common/Guacamelee/game` output?

If writing the log is broken for some reason, you might be able to get more information about what is going on by running Steam with `STEAM_LINUX_RUNTIME_VERBOSE=1` in the environment, and looking at Steam's output in the terminal. I'll be particularly interested in any line mentioning `bwrap` or `/mnt/games/linux/steamlib/steamapps/common/Guacamelee`, and other lines that are close to those.

From your comments in #267 and #255, do I understand correctly that the "Steam Linux Runtime" compat tool is working fine for some games, but not for this one specifically?

**Comment by DanMan** [comment]
It's an ext4 partition with a secondary Steam library on it (my main one). `game` is a small shell script that my user has `rw` permissions on:

```
#!/bin/sh
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":./lib32
exec ./game-bin $*
```

Steam does  launch when using `STEAM_LINUX_RUNTIME_VERBOSE`, so I was able to capture [this log](https://gist.github.com/DanMan/d9d2975fefd1aefff25fc77ac7737c4b).

I'm able to run various games successfully through the "Steam Linux Runtime", yes. I'll make an extra bug report on the logging issue.

**Comment by DanMan** [comment]
Ok, I feel stupid now. Setting the execute bit on both the script and the binary made it work.

**Comment by smcv** [comment]
> Process hangs on exit though

Is this a Unity game? If so, not exiting seems like it might be the same thing as Shadowrun Returns in #371.

**Comment by DanMan** [comment]
I don't think it's a [Unity game](https://en.wikipedia.org/wiki/List_of_Unity_games). It also hangs on exit without using PV, which I should have mentioned, sorry. So probably not PV related.
