### ISSUE TITLE
Games crash pulseaudio in Ubuntu 15.10

### ISSUE THREAD

**Issue by Edupop** [ValveSoftware/steam-runtime#41]
After half a minute at most after launching a game, pulseaudio will crash and automatically restart. (Error in pa_malloc()) The error is due to an incompatibility in the libraries steam-runtime ships with.

Deleting the contents of 
~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/alsa-lib/
(and ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/alsa-lib/ if applicable)
Fixes the bug. Although, to be honest, I'm deleting all the libraries at this point.

An additional replication difficulty may be that some games work fine unless I have my phone connected via Bluetooth as an audio source, i.e. Grim fandango remastered and massive chalice.  Others always crash. Borderlands 2, Creeper world 3. 

Consider this an extension of #13

**Comment by GNUletik** [comment]
This bug also appears in Transistor (at launch).
cf. http://steamcommunity.com/app/237930/discussions/2/492379159714114412/?tscn=1449161202#c492379439672614794

**Comment by Edupop** [comment]
While I cannot comment on the state of library conflicts, the Bluetooth problem has been fixed upstream in pulse 7.0
(ppa:ubuntu-audio-dev/pulse-testing)
