### ISSUE TITLE
GTA V launching issues across multiple Proton versions

### ISSUE THREAD

**Issue by joshsheedy** [ValveSoftware/steam-runtime#428]
# Compatibility Report
- Name of the game with compatibility issues: GTA V
- Steam AppID of the game:jsheedy

## System Information
- GPU: 1050ti
- Driver/LLVM version: 460.80
- Kernel version: 5.8.0-59-generic ValveSoftware/Proton#66-Ubuntu SMP Thu Jun 17 00:46:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/joshsheedy/6cfdfe8b7bcc498b475ef0cf802a6de2
- Proton version: All versions available

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

  This file is not getting create with PROTON_LOG=1  , or I am just unable to find it.

## Symptoms 
When you attempt to launch the game it will fail immediately 

## Reproduction
1. click play button
2. select Play GTA 5
3. click play button

**Comment by kisak-valve** [comment]
Hello @joshsheedy, in the Proton issue tracker, we're using one issue per unofficially supported game title, however, `pressure-vessel-wrap[49357]: E: None of the supported CPU architectures are common to the host system and the container (tried: x86_64-linux-gnu, i386-linux-gnu)` in your log and `CClientJobGatherRuntimeInformation: container read output failed` at the end of your system information indicates an issue with Steam Linux Runtime - Soldier, which is a container environment used by Proton 5.13 and newer, so I've transferred your issue report to the steam-runtime issue tracker.

I suspect that you've encountered #300. Please try opting into the `client_beta` beta branch of `Steam Linux Runtime - Soldier` which you can find by searching for the runtime in Steam's Library view. If that doesn't help, then please adapt https://github.com/ValveSoftware/steam-runtime/issues/300#issuecomment-728993249 and share the details here.

**Comment by joshsheedy** [comment]
@kisak-valve After the removal and re-install of Steam Linux Runtime - Soldier.  The game starts without issue.  This can be closed.  Thanks
