### ISSUE TITLE
How to instruct Steam to use look up libraries in game folder before Steam runtime?

### ISSUE THREAD

**Issue by mropert** [ValveSoftware/steam-runtime#430]
Hello,

My game relies on TBB 2020u3, which is quite more recent than the Ubuntu 12 version provided in the Steam Runtime.
How can I instruct Steam to use my game binary folder before Steam Runtime in library search path?

**Comment by TTimo** [comment]
In order to ensure that your game runs on all Linux distributions where Steam runs, I think the best approach is to compile and statically link the appropriate version of TBB with your game binaries.

**Comment by mropert** [comment]
I'm afraid Intel does not provide a static version of TBB and recommends against trying to build one yourself.

**Comment by TTimo** [comment]
If you can't statically link, a dynamic version that you bundle with your game binaries would be ok. You will need to use a launch script and prepend `$(pwd)` (the directory with your dynamic dependencies) to the passed in `LD_LIBRARY_PATH` (don't replace/modify the set of paths though .. just prepend yours ..)

**Comment by mropert** [comment]
Alright, we went for that solution in the end.
