### ISSUE TITLE
Don't Starve Together (322330) always crashes on first launch with home isolation enabled

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#433]
#### Your system information

* Steam Runtime Version: 0.20210630.0
* Distribution (e.g. Ubuntu 18.04): Fedora 34
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/Newbytee/d5f1e9f6a127137741248002bd50ad85
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`? [VERSIONS.txt](https://github.com/ValveSoftware/steam-runtime/files/6864985/VERSIONS.txt)

#### Please describe your issue in as much detail as possible:

When Don't Starve Together is run for the first time with home isolation enabled, the game will crash with the following error:

![image](https://user-images.githubusercontent.com/4428753/126703636-668cbd6a-7bb3-4ed0-9fcc-e6dcd5d68d4a.png)

If you cannot see pictures for one reason or another, it transcribes to this:

WARNING!
Unable to write to files in the config directory.
Please make sure you have permission for your Klei save folder.

Exit Game
Get More Help

Rev. 470691 LINUX_STEAM

(end of transcription)

Log: [slr-app322330-t20210722T221901.log](https://github.com/ValveSoftware/steam-runtime/files/6865018/slr-app322330-t20210722T221901.log)
version.txt: [version.txt](https://github.com/ValveSoftware/steam-runtime/files/6865039/version.txt)

Worth noting is that I have not tested whether this is reproducible without home isolation if the game has never been ran outside Pressure Vessel.

#### Steps for reproducing this issue:

1. Run Don't Starve Together (322330) with home isolation enabled (`PRESSURE_VESSEL_SHARE_HOME=0`)
2. Observe that it crashes with an error saying that the configuration directory isn't writeable

Since this only reproduces on the first launch, to reproduce it again you have to remove `~/.var/app/com.steampowered.App322330/`

**Comment by smcv** [comment]
Interesting. Would you mind capturing a new log with `STEAM_LINUX_RUNTIME_VERBOSE=1` in the environment? That will give us a larger log with more details about exactly how we're setting up the container.

> Worth noting is that I have not tested whether this is reproducible without home isolation if the game has never been ran outside Pressure Vessel.

Perhaps you could try this?

* Rename `~/.klei` to `~/saved-.klei`
* Run Don't Starve Together *without* using Steam Linux Runtime
* Check whether it fails in the same way
* If `~/.klei` has been created, delete it
* Rename or copy `~/saved-.klei` back to `~/.klei`

Or you could try using Steam Linux Runtime but `PRESSURE_VESSEL_SHARE_HOME=1` (the default).

Another interesting thing to try would be:

* Delete `~/.var/app/com.steampowered.App322330/`
* `mkdir -p ~/.var/app/com.steampowered.App322330/.klei`
* Run Don't Starve Together with Steam Linux Runtime and `PRESSURE_VESSEL_SHARE_HOME=0`

or even

* Delete `~/.var/app/com.steampowered.App322330/`
* `mkdir -p ~/.var/app/com.steampowered.App322330/.klei/DoNotStarveTogether`
* Run Don't Starve Together with Steam Linux Runtime and `PRESSURE_VESSEL_SHARE_HOME=0`

**Comment by Newbytee** [comment]
> Perhaps you could try this?

Seems to be a game bug. I can reproduce this even when not using Pressure Vessel if I get rid of `~/.klei`. Apologies for not testing this before reporting.

**Comment by smcv** [comment]
> Seems to be a game bug.

That's what I suspected, thanks for confirming (and reporting to Klei).
