### ISSUE TITLE
Legion TD2 game won't start with Proton 5.13 onwards

### ISSUE THREAD

**Issue by TheDamnedKirai** [ValveSoftware/steam-runtime#437]
# Compatibility Report
- Name of the game with compatibility issues: Legion TD2
- Steam AppID of the game: 469600

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia-driver-470
- Kernel version: 5.8.0-63
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/TheDamnedKirai/9bf31e44c5e52702fe2582c15dfec99c
- Proton version: 5.13.6 / 6.3-5 / Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 No logs are created, it seems the crash happens earlier

## Reproduction
You install the game, you click on play then it just doesn't start, it doesn't even creates log with `PROTON_LOG=1 %command%` so it's really hard to troubleshoot. The strange thing is that it seems that is not downloading the required environment (DirectX and so on) with proton Version 5.13 onwards.

I've tested the following things:
- I am able to start it with Proton 5.0, but then the game won't connect to the Steam network so it's unplayable.
- The way I have found to correctly run this game is run it via Lutris and Wine Steam (Lutris 6.13-2), with that combination, no problems are given.

**Comment by kisak-valve** [comment]
Hello @TheDamnedKirai, starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment, and pressure vessel is what sets up that environment. The symptoms you've described read more like pressure vessel is hitting an issue of some sort rather than an issue with Proton. Let's evaluate this as a pressure vessel issue until there's a stronger indication the issue is elsewhere.

Can you let Steam finish gathering the extended diagnostics section of its system information, and update your gist?

**Comment by TheDamnedKirai** [comment]
Updated the GIST link:

Noticed the following things in the output:


"scout runtime container" is not installed.
CClientJobGatherRuntimeInformation: container read output failed


Thanks!

**Comment by kisak-valve** [comment]
Thanks, that confirms there is an issue with Pressure Vessel. Can you give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested info.

Do you have Proton installed in a secondary Steam Library? If you do, what filesystem are you using with that partition?

**Comment by TheDamnedKirai** [comment]
You nailed it, the problem was this:

I was having another steam library on another Drive (the NTFS windows one), removing that steam library from the list solved the problem. Now also Proton 6.3 is downloading the environment and thegame works flawlessly. 

Could you please also remove my borked report? Thanks!!
