### ISSUE TITLE
Last couple versions of Soldier break Proton - insists my GPU does not support DirectX 10/out of date

### ISSUE THREAD

**Issue by omgthegreenranger** [ValveSoftware/steam-runtime#442]
#### Your system information

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): Arch KDE Plasma 5
* System Information: [Gist](https://gist.github.com/omgthegreenranger/6ad34e4195c4bfe46b28ce6cf121ab86): 
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Proton - current and Experimental
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: 

> * depot	0.20210809.22			# Overall version number
> pressure-vessel	0.20210809.1			
> scripts	v0.20210806.0-0-g21006f2			# Entry point scripts, etc.
> soldier	0.20210806.0	soldier	0.20210806.0	# soldier_platform_0.20210806.0/

#### Please describe your issue in as much detail as possible:
I have been running on Previous_release branch of soldier until tonight, as the current version would crash all proton games, but now that the new version released, I am unable to do so.

When running any Proton game (in this case, Star Trek Online), the game will load up and then stop, claiming that "support for my video card has ended," and that it does not support DirectX Hardware Feature 10.

Note that this was not an issue for any games in the previous_release branch released before today; the current Soldier (and client_beta) does the same thing.

[slr-app9900-t20210809T212846.log](https://github.com/ValveSoftware/steam-runtime/files/6958335/slr-app9900-t20210809T212846.log)
[slr-latest.log](https://github.com/ValveSoftware/steam-runtime/files/6958336/slr-latest.log)
[slr-non-steam-game-t20210809T212819.log](https://github.com/ValveSoftware/steam-runtime/files/6958337/slr-non-steam-game-t20210809T212819.log)
[steam-9900.log](https://github.com/ValveSoftware/steam-runtime/files/6958342/steam-9900.log)

**Comment by kisak-valve** [comment]
Most likely an AMDVLK-related issue.

**Comment by omgthegreenranger** [comment]
Well ain't that a pain! Removing amdvlk and switching to radv solved it, apparently. Appreciate it!
