### ISSUE TITLE
You must provide the code for the changes you made on some libraries

### ISSUE THREAD

**Issue by Xodetaetl** [ValveSoftware/steam-runtime#45]
I've read [here](http://jorgen.tjer.no/post/2014/05/28/steam-runtime-without-steam/) that some of the libs were patched to remove runtime dependencies on absolute paths. The article points to a `patches` folder in this repo but it's gone.

**Comment by proglo** [comment]
I'm sorry if I'm confused but this is not personally addressed to me is it? I do not believe I revised the libraries yet this message seems directed to me personally, though it doesn't make sense to be. Excuse my confusion and thank you for clarifying.

**Comment by Xodetaetl** [comment]
This is addressed to the owner of the repo, Valve. ;)

**Comment by thesbros** [comment]
They may not be doing that anymore. [This](https://github.com/ValveSoftware/steam-runtime/tree/1a9c7173fc2092a7214eacdd0ffcbff3c5afe1e5/patches) is the last commit with the `patches` directory for reference.

**Comment by Xodetaetl** [comment]
I'm sure they are, the runtime wouldn't work without these patches. They just made us download the modified packages instead of building them locally as the next commit title says.

**Comment by Plagman** [comment]
The patches are maintained in the source package repository now; you can access it there:

http://repo.steampowered.com/steamrt/

**Comment by Xodetaetl** [comment]
:+1:
