### ISSUE TITLE
soldier = 0.20210817.0 not working on openSUSE Tumbleweed for several games

### ISSUE THREAD

**Issue by priand1** [ValveSoftware/steam-runtime#452]
#### Your system information

* Steam Runtime Version: 0.20210629.0 and 0.20210817.0
* Distribution (e.g. Ubuntu 18.04): openSUSE Tumbleweed 20210817
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  
My [system information](https://gist.github.com/priand1/df2db421094762a1a14e184585fd9eee)
* Have you checked for system updates?: [Yes/No] Yes, everything is uptodate
* What compatibility tool are you using?: Proton 6.3-6
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
* VERSIONS.txt [soldier_previous](https://gist.github.com/priand1/596f8e239cd8298350cfd4955e8cc5cf)
* VERSIONS.txt [soldier_beta](https://gist.github.com/priand1/b1cb835f2fa1eb3671063c479e847956)

#### Please describe your issue in as much detail as possible:

With steam-runtime soldier = 0.20210817.0 several proton games stopped working on openSUSE Tumbleweed.
These are:
- Call of Duty: Advanced Warfare
- GTA V
- HALO MCC started with and without EAC
- Hitman 2
- Mafia Definitive Edition
- Mafia III Definitive Edition
- Sniper Ghost Warrior 3
- Sniper Ghost Warrior Contracts
- Tom Clancy's Ghost Recon Wildlands
- Wolfenstein II: The New Colossus

I am using Wolfenstein II (650500) as a representative.

Symptoms: When starting Wolfenstein II it immediately terminates and the start button turns green again. This behaviour is also shown by the other games in the above list.

Workaround: The workaround for me was to downgrade steam-runtime soldier from 
version 0.20210817.0 to 
version 0.20210629.0.
I found the inspiration for this workaround in [issue 431](https://github.com/ValveSoftware/steam-runtime/issues/431)

After downgrading steam-runtime soldier to version 0.20210629.0 all games started working again.

Proton logs for Wolfenstein II (650500):
Proton log with soldier_previous [version 0.20210629.0](https://gist.github.com/priand1/7ded59a5859a32f124218fcf72002558)
Proton log with soldier_beta [version 0.20210817.0](https://gist.github.com/priand1/1f50df960b3d738f2eb7763fde5b17f6)

#### Steps for reproducing this issue:

1. Let steam update soldier_beta to version 0.20210817.0
2. Try to start the games mentioned in the list above -> they fail to start
3. Downgrade soldier to soldier_previous version 0.20210629.0 -> all games starting again

**Comment by smcv** [comment]
There is an intermediate version between "previous release" and "beta": the default version (not a beta). Please try Properties -> Betas -> None (which I think should say `depot 0.20210723.18` and `soldier 0.20210719.0` in `VERSIONS.txt` at the moment), and report whether that works or fails, with a log. That will narrow down where the regression might have taken place.

> Proton log with soldier_previous version 0.20210629.0
> Proton log with soldier_beta version 0.20210817.0

Thanks for these, but they are not Proton logs: they are Steam Linux Runtime logs.

From these, it looks like the Steam Linux Runtime brings up the container successfully, but then either Proton or the actual game fails to start. I think it would be useful if you can get a Proton log too: you can do this by running Steam or the game with `PROTON_LOG=1` in the environment (see [Proton documentation](https://github.com/ValveSoftware/Proton/#runtime-config-options)). Logs will appear in your home directory by default, named `steam-650500.log` for game ID 650500.

It would probably also be useful if you can get a more detailed `slr-app650500*.log` by running Steam or the game with `STEAM_LINUX_RUNTIME_VERBOSE=1` in the environment.

**Comment by priand1** [comment]
> > Proton log with soldier_previous version 0.20210629.0
> > Proton log with soldier_beta version 0.20210817.0
> 
> Thanks for these, but they are not Proton logs: they are Steam Linux Runtime logs.
> 

My apologies! I corrected my error. You can now find the specified logs from the links.

I ran steam with `STEAM_LINUX_RUNTIME_VERBOSE=1 STEAM_LINUX_RUNTIME_LOG=1` and installed the default runtime_soldier. With this version Wolfenstein II is starting correctly. These are the logs:

[Soldier default versions.txt](https://gist.github.com/priand1/f898bec8c1b6d3cfe18327fdc9085500)
[Soldier default runtime log](https://gist.github.com/priand1/22acae553afb0d12d3acb9b2e8326010)
[Proton Wolfenstein 650500 with soldier default log ](https://gist.github.com/priand1/a7b298d543c3a3c36529d28121d35ee0)

After that I again installed soldier_beta. Wolfenstein is not starting as described in the OP. These are the logs:

[Soldier beta versions.txt](https://gist.github.com/priand1/b1cb835f2fa1eb3671063c479e847956)
[Soldier beta runtime log](https://gist.github.com/priand1/694a77d84f810b1484f04686f44d2017)
[Proton Wolfenstein 650500 with soldier beta log](https://gist.github.com/priand1/1f50df960b3d738f2eb7763fde5b17f6)

**Comment by kisak-valve** [comment]
`INFO: SDL_INIT_AUDIO failed: Audio target 'pulse' not available` looks like a line of interest from the second Proton log.

**Comment by smcv** [comment]
OK, so this is a regression between depot 0.20210723.18 and 0.20210818.24. I'm guessing this is going to be to do with changes made in pressure-vessel, either the changes to fix #224 (tracked as T14481 internally) or #435 (T29490 internally).

You could confirm this as follows:

* Install the default branch of soldier
* Copy `SteamLinuxRuntime_soldier/pressure-vessel/` somewhere else
* Upgrade to the beta branch
* Delete `SteamLinuxRuntime_soldier/pressure-vessel/`
* Replace it with the one from the default branch

**Comment by smcv** [comment]
The other thing that seems plausible is that it might be a regression caused by upgrading SDL from 2.0.14 to 2.0.16.

**Comment by smcv** [comment]
Good catch, @kisak-valve. Quoting a bit more:

```
INFO: SDL_INIT_AUDIO failed: Audio target 'pulse' not available
5096.176:0108:01a4:trace:seh:dispatch_exception code=c0000005 flags=0 addr=00007FD0D0AEC69C ip=00007FD0D0AEC69C tid=01a4
5096.176:0108:01a4:trace:seh:dispatch_exception  info[0]=0000000000000000
5096.176:0108:01a4:trace:seh:dispatch_exception  info[1]=0000000000000000
5096.176:0108:01a4:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
```

I'm not a Proton or Wine expert, but this looks to me like the absence of an audio device is causing a null pointer dereference.

@priand1, you have `SDL_AUDIODRIVER=pulse` specified in your environment. If you unset that (letting SDL do whatever it does by default) does that help?

**Comment by smcv** [comment]
I think `SDL_AUDIODRIVER=pulse` might also be wrong: the SDL audio driver for PulseAudio is called `pulseaudio`.

**Comment by kisak-valve** [comment]
For what it's worth, `SDL_AUDIODRIVER=pulse` was a thing for SDL 1.2 (https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html).

**Comment by priand1** [comment]
Guys, the problem is solved.
You pointed it out correctly, the setting `SDL_AUDIODRIVER=pulse` was the culprit. 

There is a post on the openSUSE factory mailing list mentioning this wrongly set variable [here.](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/DR7XYXLCTCN3Z6EBANKNG6SPGDSRLHHU/)

So, the first thing I tried was setting the variable to `SDL_AUDIODRIVER=pulseaudio` and all of the above games started with soldier_beta.

Many thanks for your help it is very much appreciated.

Even though this issue had nothing to do with steam-runtime I find it interesting to know that an environment variable, of which I had never thought that it could become such a big problem as preventing games from starting if it is not correctly set, would be the cause of the symptom in the first post.

What is also interesting is the fact, that this problem first startet with soldier_beta even though the wrong setting was also present when soldier_previous and soldier_default were installed.
If you need anything from me, like some more logs with the variable set back to `SDL_AUDIODRIVER=pulse`, just let me know.

**Comment by kisak-valve** [comment]
Glad to hear you got it working.

This sounds like something for the [upstream SDL](https://github.com/libsdl-org/SDL) devs to check if the stricter env variable behavior is intended or a regression.

**Comment by smcv** [comment]
> What is also interesting is the fact, that this problem first startet with soldier_beta even though the wrong setting was also present when soldier_previous and soldier_default were installed.

Older releases had SDL 2.0.14, with very loose validation for the driver environment variables. soldier has 2.0.16, with stricter validation.

> So, the first thing I tried was setting the variable to SDL_AUDIODRIVER=pulseaudio and all of the above games started with soldier_beta.

I would recommend not setting that environment variable at all, unless there is a specific reason why you need to override the default automatic selection. SDL should (and does!) have reasonable defaults without needing to set this variable; on my system it chooses PulseAudio without needing extra help.

The same applies to most package-specific environment variables, in fact. Debian even has [a policy for this](https://www.debian.org/doc/debian-policy/ch-opersys.html#environment-variables) and I'm sure we're not the only distribution to do so.

**Comment by priand1** [comment]
Thanks to both of you for your hints. I will take a look at this.

**Comment by smcv** [comment]
Today's beta update for "Steam Linux Runtime - soldier" has a backport of [an SDL commit](https://github.com/libsdl-org/SDL/commit/3261f7f6ceaaa435a3aca0252b2f7126eeae1bb2) which makes `SDL_AUDIODRIVER=pulse` an alias for `SDL_AUDIODRIVER=pulseaudio`, avoiding the problem.

I would still recommend not setting the environment variable at all - that will give you SDL's default behaviour, trying several possible backends in a preference order, which is more likely to continue to do the right things in future than forcing it to use a particular backend.

To check which version you have, look at `SteamLinuxRuntime_soldier/VERSIONS.txt`. The version that fixes this issue is `depot 0.20210907.26` or later.

**Comment by priand1** [comment]
Thanks @smcv, the new default for openSUSE Tumbleweed  is now to not set the `SDL_AUDIODRIVER` variable at all. This is working well, as you suggested.

**Comment by smcv** [comment]
> Today's beta update for "Steam Linux Runtime - soldier" has a backport of [an SDL commit](https://github.com/libsdl-org/SDL/commit/3261f7f6ceaaa435a3aca0252b2f7126eeae1bb2) which makes `SDL_AUDIODRIVER=pulse` an alias for `SDL_AUDIODRIVER=pulseaudio`, avoiding the problem.

In the latest Steam update (2021-09-13, 1631572918), both beta and general-availability, the version of SDL in the `scout` runtime has received the same change.
