### ISSUE TITLE
AMDVLK fails to initialize with: Failed to find GPUs with Vulkan support! in Soldier

### ISSUE THREAD

**Issue by konkode** [ValveSoftware/steam-runtime#453]
The new update of Quake (2310) crashes to desktop unless soldier is bypassed by adding `shift 2` at the start of `_v2-entry-point`.

The same behavior occurs when running Turok (405820) under Proton. Turok has a native Linux version which works without issue.
Both of these games were re-released by Night Dive Studios and use their Kex Engine.

#### Your system information

* Steam Runtime Version: **0.20210630.0**
* Distribution: **KDE Neon (Ubuntu 20.04)**
* Link to your full system information: **[Steam Sysinfo](https://gist.github.com/konkode/d0392322b5bb9dad9ebfc61e049d0455#file-steam_sysinfo)**
  
* Have you checked for system updates?: **Yes, fully current system and Steam Runtime**
* What compatibility tool are you using?: **Proton 6.3, Experimental, all other stable versions, and several GE builds.**
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: **[VERSIONS.txt](https://gist.github.com/konkode/d0392322b5bb9dad9ebfc61e049d0455#file-versions-txt)**

#### Please describe your issue in as much detail as possible:

**[SLR debug log for Quake on Proton 6.3](https://gist.github.com/konkode/d0392322b5bb9dad9ebfc61e049d0455#file-slr-app2310-proton6-3-6-log)**

Fresh installation of Quake with no prior compatdata would load a black screen and crash with the error popup below. Same result on all available versions of Proton except for 5.0-10 and 4.11-13.
![](https://media.discordapp.net/attachments/857280090810613771/878706494240084018/unknown.png)

Testing Turok with Experimental and 6.3 yielded familiar results with a slightly different error message, but still referring to `rhi`:

**[SLR debug log for Turok on Proton 6.3](https://gist.github.com/konkode/d0392322b5bb9dad9ebfc61e049d0455#file-slr-app405820-proton6-3-6-log)**

![](https://media.discordapp.net/attachments/434833177845039116/879165636805267506/unknown.png)

I was able to get Proton Experimental and Proton 6.3-6 working with both games by inserting these lines after the shebang in Soldier's `_v2-entry-point` script:

```bash
shift 2
exec "${@}"
```

#### Steps for reproducing this issue:
 1. Install Quake
 2. Switch to Proton 6.3 or Experimental
 3. Click `Play Quake`
 4. Change the `_v2-entry-point` script as noted above and try again.

OR

 1. Install Turok
 2. Force use of Proton 6.3 or Experimental and wait for download of the Windows game.
 3. Click `Play Turok`
 4. Change the `_v2-entry-point` script as noted above and try again.

#### For further testing, the same engine is [used in](https://www.nightdivestudios.com/kex-dev/):

 * Turok 2 (405830)
 * System Shock: Enhanced Edition (410710)
 * Blood: Fresh Supply (1010750)

**Comment by konkode** [comment]
I just confirmed the same behavior in Turok 2. Same issue, same error, same workaround with the edit to Soldier's `_v2-entry-point`.

![](https://cdn.discordapp.com/attachments/853130811581530145/879178674191081512/unknown.png)

Two of the games display their engine version numbers:

Quake: Kex Engine 4.0 (bastet)
Turok 2: Kex Engine 3.4 (Horus)

**Comment by kisak-valve** [comment]
Hello @konkode, it should be noted that running Proton versions that were built to be run inside the Steam Linux Runtime - Solder container environment (Proton 5.13 and newer) outside of the intended runtime is not recommended and unsupported.

That said, there's a good chance that your issue is related to AMDVLK, similar to #442.

**Comment by konkode** [comment]
Thank you @kisak-valve. Removing AMDVLK did indeed resolve the issue in both games. 

I never use AMDVLK except for troubleshooting purposes, when it's set manually as a launch option. I did notice Soldier seemed to want to load it before any of the others. Maybe because of the different path?

**Comment by smcv** [comment]
Steam's diagnostic tool is getting the same behaviour as the games themselves when it runs inside the container:

```
        "x11/vulkan" : {
          "messages" : [
            "Failed to find GPUs with Vulkan support!"
          ],
```

Presumably AMDVLK needs some extra files or devices that we are not copying into the container?

> I did notice Soldier seemed to want to load it before any of the others

When the diagnostic tool runs a small Vulkan program, it is being told that accessing the AMD GPU via some driver whose version number is "2.0.18" is the only Vulkan device available:

```
      "graphics-details" : {
        "x11/vulkan" : {
          "renderer" : "Radeon RX 570 Series",
          "version" : "1.2.182 (device 0x1002:0x67df) (driver 2.0.193)",
          "devices" : [
            {
              "name" : "Radeon RX 570 Series",
              "api-version" : "1.2.182",
              "driver-version" : "2.0.193",
              "vendor-id" : "0x1002",
              "device-id" : "0x67df",
              "type" : "discrete-gpu"
            }
          ]
        },
```

That doesn't look like a Mesa version number, so I think it must be AMDVLK or some other AMD-specific thing? If you don't intend to be using this as your Vulkan implementation, then you will need to try harder to turn it off.

The container runtime tries hard to preserve whatever order it saw ICDs and GPUs enumerated by the "real" system, to maximize the chance that that if you have successfully got the "real" system to behave the way you want it to (whatever that means), the container will behave in that same way.

**Comment by smcv** [comment]
You would probably find that this issue is not specific to Kex Engine games: it probably affects any Windows/Direct3D game running under recent Proton (because recent versions of Proton implement Direct3D by using Vulkan), and might also affect any native Linux game that uses Vulkan (such as Valve's Artifact).

In your system info, we are seeing the AMDVLK driver listed first, followed by Mesa software rendering and Mesa Intel, and finally Mesa's "Radeon" driver for the AMD GPU:

```
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/etc/vulkan/icd.d/amd_icd32.json",
        "library_path" : "/usr/lib/i386-linux-gnu/amdvlk32.so",
        "api_version" : "1.2.182",
        "issues" : [
        ]
      },
      {
        "json_path" : "/etc/vulkan/icd.d/amd_icd64.json",
        "library_path" : "/usr/lib/x86_64-linux-gnu/amdvlk64.so",
        "api_version" : "1.2.182",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/lvp_icd.i686.json",
        "library_path" : "/usr/lib/i386-linux-gnu/libvulkan_lvp.so",
        "api_version" : "1.1.182",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.x86_64.json",
        "library_path" : "/usr/lib/x86_64-linux-gnu/libvulkan_intel.so",
        "api_version" : "1.2.182",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/lvp_icd.x86_64.json",
        "library_path" : "/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so",
        "api_version" : "1.1.182",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.i686.json",
        "library_path" : "/usr/lib/i386-linux-gnu/libvulkan_intel.so",
        "api_version" : "1.2.182",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json",
        "library_path" : "/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so",
        "api_version" : "1.2.182",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.i686.json",
        "library_path" : "/usr/lib/i386-linux-gnu/libvulkan_radeon.so",
        "api_version" : "1.2.182",
        "issues" : [
        ]
      }
    ],
```

We can also see that there is an AMDVLK-specific "switchable graphics layer" being loaded, which is presumably what is disabling all other possible Vulkan drivers so that only AMDVLK is used:

```
    "implicit_layers" : [
      {
        "json_path" : "/etc/vulkan/implicit_layer.d/amd_icd32.json",
        "name" : "VK_LAYER_AMD_switchable_graphics_32",
        "description" : "AMD switchable graphics layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.182",
        "implementation_version" : "1",
        "library_path" : "/usr/lib/i386-linux-gnu/amdvlk32.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/etc/vulkan/implicit_layer.d/amd_icd64.json",
        "name" : "VK_LAYER_AMD_switchable_graphics_64",
        "description" : "AMD switchable graphics layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.182",
        "implementation_version" : "1",
        "library_path" : "/usr/lib/x86_64-linux-gnu/amdvlk64.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/usr/share/vulkan/implicit_layer.d/VkLayer_MESA_device_select.json",
        "name" : "VK_LAYER_MESA_device_select",
        "description" : "Linux device selection layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.73",
        "implementation_version" : "1",
        "library_path" : "libVkLayer_MESA_device_select.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/home/kon/.local/share/vulkan/implicit_layer.d/steamfossilize_i386.json",
        "name" : "VK_LAYER_VALVE_steam_fossilize_32",
        "description" : "Steam Pipeline Caching Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.136",
        "implementation_version" : "1",
        "library_path" : "/home/kon/.steam/debian-installation/ubuntu12_32/libVkLayer_steam_fossilize.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/home/kon/.local/share/vulkan/implicit_layer.d/steamfossilize_x86_64.json",
        "name" : "VK_LAYER_VALVE_steam_fossilize_64",
        "description" : "Steam Pipeline Caching Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.136",
        "implementation_version" : "1",
        "library_path" : "/home/kon/.steam/debian-installation/ubuntu12_64/libVkLayer_steam_fossilize.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/home/kon/.local/share/vulkan/implicit_layer.d/steamoverlay_i386.json",
        "name" : "VK_LAYER_VALVE_steam_overlay_32",
        "description" : "Steam Overlay Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.136",
        "implementation_version" : "1",
        "library_path" : "/home/kon/.steam/debian-installation/ubuntu12_32/steamoverlayvulkanlayer.so",
        "issues" : [
        ]
      },
      {
        "json_path" : "/home/kon/.local/share/vulkan/implicit_layer.d/steamoverlay_x86_64.json",
        "name" : "VK_LAYER_VALVE_steam_overlay_64",
        "description" : "Steam Overlay Layer",
        "type" : "GLOBAL",
        "api_version" : "1.2.136",
        "implementation_version" : "1",
        "library_path" : "/home/kon/.steam/debian-installation/ubuntu12_64/steamoverlayvulkanlayer.so",
        "issues" : [
        ]
      }
    ]
  },
```

If you look in `/etc/vulkan/implicit_layer.d/amd_icd32.json` and `/etc/vulkan/implicit_layer.d/amd_icd64.json`, you should find that there is an environment variable listed in a `disable_environment` block, which you can use to turn off the layer. I think it's `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1`, but I don't currently have an AMDVLK system.

[This commit to one of the components of AMDVLK might be relevant](https://github.com/GPUOpen-Drivers/xgl/commit/ec89b84f0b8a83aa2b29ed25cfd741c90f9e2688). Please make sure your version of AMDVLK is up to date.

**Comment by konkode** [comment]
@smcv is correct and I do not play enough video games. It was a bug in AMDVLK's switchable graphics layer which seems to have been introduced in 2021.Q3.2. Crashes with Soldier were resolved in AMDVLK 2021.Q3.4, but everything including `vkcube` still uses AMDVLK unless `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1` is set.

**Brief timeline of events**

**January 20:** Install AMDVLK. RADV remains default. ✔
**July 9:** AMDVLK updates to 2021.Q3.1 ✔
**July 14:** Happily play a D3D11 game under Proton 6.3 ✔
**July 23:** AMDVLK updates to 2021.Q3.2 ❌
**August 11:** AMD releases 2021.Q3.4 on Github but not their official Ubuntu repository. I stay on 2021.Q3.2 ❌
**August 22:** I try to play Quake ❌
**Today:** I update to 2021.Q3.4. Crashes are gone, but AMDVLK is still default. Must disable switchable gfx to get RADV. ✔


The only Vulkan game I played this month was inexplicably set to use Proton 5.0-10, so I didn't encounter the issue until now.

**Comment by kisak-valve** [comment]
Thanks @konkode, that aligns with the issue fixed in https://github.com/GPUOpen-Drivers/xgl/commit/ec89b84f0b8a83aa2b29ed25cfd741c90f9e2688. Closing as not-our-bug.
