### ISSUE TITLE
Proton games do not start: opendir(/): Permission denied

### ISSUE THREAD

**Issue by hanadrizz** [ValveSoftware/steam-runtime#454]
Games tried: Guilty Gear Strive | Trackmania Nations Forever

GG-ST- has a platinum grade on ProtonDB, but I can't start any game on Steam that uses Proton.

Ubuntu 20.04.3 LTS
CPU: AMD Ryzen 3 1300X (4) @ 3.500GH
GPU: NVIDIA GeForce GTX 1050 Ti
Logs: https://pastebin.com/36fHMmAM
What happens is that I click "Play", the little box that says "starting Guilty Gear" appears for a slight bit, the button turns blue and then the box closes and button turns back to the Play button

**Comment by kisak-valve** [comment]
Hello @hanadrizz, `pressure-vessel-wrap[24306]: E: opendir(/): Permission denied` in your log looks abnormal, and hints that there's a issue with Pressure Vessel setting up the Steam Linux Runtime - Soldier container environment for Proton to run in.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested information.

**Comment by hanadrizz** [comment]
[Console log](https://pastebin.com/8hbYNxCP)
[SteamLinuxRuntime_soldier/var/slr-latest.log](https://pastebin.com/YtFk7fsq)

**Comment by RyuzakiKK** [comment]
The SteamLinuxRuntime log strangely stops after the initial pressure-vessel version print.

@hanadrizz Can you please run Steam with `STEAM_LINUX_RUNTIME_LOG=1 STEAM_LINUX_RUNTIME_VERBOSE=1 steam` and post again the `slr-latest.log`?

Please also include your full system information, it's explained in the first few lines here how to get it https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information

**Comment by smcv** [comment]
This looks bad:

```
pressure-vessel-wrap[25471]: E: opendir(/): Permission denied
```

@kisak-valve or @hanadrizz, please could you change the issue title to "Proton games do not start: opendir(/): Permission denied" so we don't get people with unrelated issues commenting on this one?

**Comment by hanadrizz** [comment]
> 
> 
> This looks bad:
> 
> ```
> pressure-vessel-wrap[25471]: E: opendir(/): Permission denied
> ```
> 
> @kisak-valve or @hanadrizz, please could you change the issue title to "Proton games do not start: opendir(/): Permission denied" so we don't get people with unrelated issues commenting on this one?

Doneso, can't respond to the person above just yet cause im still in school, but got this really quick edit done

**Comment by smcv** [comment]
Thanks, that'll help - otherwise anyone else who has an unrelated issue breaking all Proton games would jump in here and cause confusion.

When you are able to respond in more detail: what are the permissions on your root directory `/` and the directories it contains? (`ls -l /` in a terminal would tell you.)

I *think* the only reason we would get `opendir(/): Permission denied` is if the root directory `/` is something like `drwx--x--x` instead of the usual `drwxr-xr-x`.

We need to be able to list all the subdirectories of the root directory to make the container runtime work (the exact action we need to take to start the container depends on your OS distribution and how they do filesystem layout), and there is normally nothing confidential (or even interesting!) in the root directory, so it's harmless for it to be readable by everyone.

**Comment by hanadrizz** [comment]
> Hello @hanadrizz, `pressure-vessel-wrap[24306]: E: opendir(/): Permission denied` in your log looks abnormal, and hints that there's a issue with Pressure Vessel setting up the Steam Linux Runtime - Soldier container environment for Proton to run in.
> 
> Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested information.

[Full System Information](https://pastebin.com/Zs4Hgcsf)
[slr-latest.log](https://pastebin.com/45zNHUiN)



> Thanks, that'll help - otherwise anyone else who has an unrelated issue breaking all Proton games would jump in here and cause confusion.
> 
> When you are able to respond in more detail: what are the permissions on your root directory `/` and the directories it contains? (`ls -al /` in a terminal would tell you.)
> 
> I _think_ the only reason we would get `opendir(/): Permission denied` is if the root directory `/` is something like `drwx--x--x` instead of the usual `drwxr-xr-x`.
> 
> We need to be able to list all the subdirectories of the root directory to make the container runtime work (the exact action we need to take to start the container depends on your OS distribution and how they do filesystem layout), and there is normally nothing confidential (or even interesting!) in the root directory, so it's harmless for it to be readable by everyone.

[ls -al](https://pastebin.com/kL71jzn9)

adding the / gets a "permission denied"

[sudo ls -al /](https://pastebin.com/NLE0QdJC)

drwx--x--x is something i notice indeed, how do I solve this issue?

**Comment by RyuzakiKK** [comment]
> [ls -al](https://pastebin.com/kL71jzn9)
> 
> adding the / gets a "permission denied"
> 
> [sudo ls -al /](https://pastebin.com/NLE0QdJC)
> 
> drwx--x--x is something i notice indeed, how do I solve this issue?

As @smcv guessed, your `/` doesn't allow listing from users different from the root.

You should be able to change it with: `sudo chmod 755 /`

**Comment by hanadrizz** [comment]
> > [ls -al](https://pastebin.com/kL71jzn9)
> > adding the / gets a "permission denied"
> > [sudo ls -al /](https://pastebin.com/NLE0QdJC)
> > drwx--x--x is something i notice indeed, how do I solve this issue?
> 
> As @smcv guessed, your `/` doesn't allow listing from users different from the root.
> 
> You should be able to change it with: `sudo chmod 755 /`

Unfortunately I'm a bit of an idiot and, through a friend not being clear enough before I got this message, I executed **sudo chmod -R 755 /** which completely fucked up all my permissions.

I'll take this as a sign to actually pack up my computer's Ubuntu and move to Manjaro, which I already had planned to do. Thanks for all the help though, and I'll refer back to this if I notice the same error happening.

Have a nice day!
