### ISSUE TITLE
Library pinning fails if zenity is not installed

### ISSUE THREAD

**Issue by 414n** [ValveSoftware/steam-runtime#458]
#### Your system information

* Steam client version (build number or date): 1630453407 (Aug 31 2021, 20:58:17)
* Distribution (e.g. Ubuntu): Slackware64 14.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam system information: [gist](https://gist.github.com/414n/34891616266f2d4e4489173e8bbee632)

#### Please describe your issue in as much detail as possible:

After installing the latest beta client update today and restarting Steam, I was greeted with completely black UI elements, specifically the "main" elements in every section of the application.

These are screenshot of the issue, taken for the "Store" and "Library" sections, but the others are the same:

![image](https://user-images.githubusercontent.com/11655692/131752202-cf7d5a8f-cbc0-4799-bcee-de3af4243abd.png)
![image](https://user-images.githubusercontent.com/11655692/131752264-493f3aca-8cd8-4ba0-867f-ad7469d84b48.png)

Menu items and secondary windows (like the "Settings" window) work ok.
Big Picture mode also works and is now the only way I have to see something in Steam.

Before restarting steam, I saw in the [incoming changes](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2956038687124632735) that there was a fix for issue ValveSoftware/steam-for-linux#7935, which should fix a really similar issue for users with a system-wide freetype-2.11.x library. This is clearly not my case, as my system sports freetype-2.6.3, but maybe the fix applied for ValveSoftware/steam-for-linux#7935 broke something for previous freetype versions.

When launching steam from the terminal, i can see a bunch of `src/vgui2/vgui_surfacelib/FontManager.cpp (287) : Assertion Failed: descs.Count() >= 1` messages. Don't know if this can be relevant or not.

#### Steps for reproducing this issue:

1. start the aforementioned client beta version

**Comment by smcv** [comment]
> should fix a really similar issue

The symptom is the same: `steamwebhelper` doesn't start up, so none of the UI that's implemented as HTML appears.

However, the *root cause* is likely to be completely different.

**Comment by 414n** [comment]
> @414n, please could you run Steam from a terminal (Konsole, xterm or equivalent) and put the output in a gist?

Sure, here is the [gist](https://gist.github.com/414n/6b5ee479d6ad284f8a90fb596511d6e9). I also added what happens when closing the client in patch form.

> The UI and games probably worked for you before by pure luck

:sweat_smile:
Good to know

**Comment by smcv** [comment]
Sorry, I'd forgotten that the beta now has a log file for the `steamwebhelper`. What's in `~/.steam/steam/logs/steamwebhelper.log`?

**Comment by smcv** [comment]
```
/mnt/storage/Steam/ubuntu12_32/steam-runtime/setup.sh: riga 421: zenity: comando non trovato
```

I'm guessing that's "command not found". This *might* be relevant: Steam normally expects that [zenity](https://gitlab.gnome.org/GNOME/zenity) is installed, so there might have been a regression in `setup.sh` for the case where it isn't. (Or it might be irrelevant, hard to say.)

**Comment by 414n** [comment]
I think I've found the issue.

I was just looking at that file (sorry, didn't save it before testing :facepalm: ) and found a couple or error messages involving zenity (which is not installed on my system). If my memory does not fail me they where something like this (I'm fairly sure about the line numbers):

 - `echo: broken pipe at line 77`
 - another error on line 421

After installing zenity, the runtime got updated and the web ui showed up correctly.

I agree, there may have been a regression on managing zenity-less systems inside that script.

**Comment by smcv** [comment]
> After installing zenity, the runtime got updated and the web ui showed up correctly.

Right, something is definitely not as it should be. What is *meant* to happen is that in this situation, `${STEAM_ZENITY}` gets set to the empty string, which means we skip the `| zenity` part... but apparently that's not happening correctly?

**Comment by 414n** [comment]
Well, this is interesting: if I remove the `pinned_libs_*` directories and run steam without zenity installed, they are not recreated and the steam client starts normally now.
If I install zenity, then they get recreated successfully.
I think this means that the setup script never runs correctly on my system without zenity.

I added some echo statements to stderr both in `ubuntu12_32/steam-runtime/setup.sh` and `ubuntu12_32/steam-runtime/run.sh` to confirm the contents of the `STEAM_ZENITY` variable, and it is indeed set to `zenity` instead of being empty when the scripts are run.
I guess this is due to this block at the start of the `steam.sh` bootstrap script:
```sh
# Prefer host zenity binary if available
export SYSTEM_ZENITY="$(which zenity 2>/dev/null)"
if [ -z ${SYSTEM_ZENITY} ]; then
        export STEAM_ZENITY="zenity"
else
        export STEAM_ZENITY="${SYSTEM_ZENITY}"
fi
```
This always sets the variable to `zenity` if no zenity is found on the path, so `STEAM_ZENITY` won't ever be empty.
This same block is more or less repeated both in `ubuntu12_32/steam-runtime/run.sh` and `ubuntu12_32/steam-runtime/setup.sh`, with the difference that in `setup.sh`, if the variable is not set when the script is called (but this is never true, all the tests I've done had it already set), then it could be set to the empty string if zenity is not found in PATH.

Forcing STEAM_ZENITY to empty in the `setup.sh` script solves the issue without zenity installed -- the  `pinned_libs_*` directories are correctly recreated.

**Comment by RyuzakiKK** [comment]
@414n Nice debugging, this seems to be indeed the issue. `steam.sh` always sets the `STEAM_ZENITY` environment variable to either the host full path or to `zenity` as a fallback.
This information is then used in `setup.sh`, where we assume to have a working zenity if `STEAM_ZENITY` is set. `setup.sh` is launched with `set -e`, meaning that the execution will be stopped as soon as a command exits with a non-zero status.
And in the line 421 of `setup.sh`:
`pin_newer_runtime_libs "$top" | "${STEAM_ZENITY}" [...]` fails and the entire execution of `setup.sh` is aborted.

**Comment by 414n** [comment]
I've performed some additional tests to find a less invasive solution.
At first I tried to put a `export -n STEAM_ZENITY` statement before each invocation of either `setup.sh` or `run.sh` scripts in the `steam.sh` bootstrap script, but those changes were not persistent and seemed not effective.
Instead, I resorted to resetting the `STEAM_ZENITY` variable in both scripts by adding a `unset STEAM_ZENITY` statement before each "zenity evaluation block" in each script, restoring what were presumably the original assumptions of those blocks.
After this, I can confirm that the setup script works correctly when no zenity is present, recreating both pinned lib dirs.

**Comment by smcv** [comment]
We have a solution in progress that should address this for people who don't have zenity installed, while still working as intended (progress bar appearing) for people who do.

**Comment by smcv** [comment]
@kisak-valve, now that we know the root cause for this one, please retitle to "library pinning fails if zenity is not installed"?

**Comment by HippoPenguin** [comment]
Thanks, I installed the missing zenity package from my system and that fixed the issue on Slackware.

**Comment by smcv** [comment]
This issue now affects the general availability branch of Steam, not just the beta. This is a harm-minimization thing: more distributions were broken by #7935 than by this issue, because most distributions treat `zenity` as a dependency of their Steam packages, so fixing #7935 was prioritized higher than fixing this issue.

Workaround: Install `zenity`.

A future release is likely to make `zenity` non-essential again, but installing it anyway is recommended: some games and some other parts of the Steam UI probably rely on it.

**Comment by junguler** [comment]
i was going crazy searching as to how to fix this, thanks for suggesting installing zenity, well i guess you learn a new thing every day.

**Comment by uoil** [comment]
It seems steam is failing to update without zenity on antiX as well. Installing the package fixes the black screen and allows the updates to go through as normal.

**Comment by smcv** [comment]
> It seems steam is failing to update without zenity on antiX as well

This is not distribution-specific, and we do not need a comprehensive list of distributions where zenity is not always installed. Any installation that has Steam but not zenity will be affected by this issue.

**Comment by smcv** [comment]
> A future release is likely to make `zenity` non-essential again

In the latest Steam update (2021-09-13, 1631572918), both beta and general-availability, it should work without `zenity` again. Functionality will be reduced (you won't get a progress bar or any indication of progress while the Steam Runtime is set up).

> installing it anyway is recommended: some games and some other parts of the Steam UI probably rely on it.

This is still true.

**Comment by 414n** [comment]
I can confirm that the fix works :+1: 

Thank you everyone!
