### ISSUE TITLE
Cannot run Proton > 5.0-x

### ISSUE THREAD

**Issue by Pistos** [ValveSoftware/steam-runtime#465]
I've been successfully running Steam on Linux for over a year now.  I am able to play games with native Linux versions, as well as some Windows games via Proton.  My issue, however, is that I always have to specify Proton version 5.0-xx for the Windows games.  If I try to use 5.13-xx or 6.x-xx , the game will briefly attempt to start up, and then close/fail.  The green "> PLAY" button turns briefly to the blue "X STOP" button, but then quickly back to "> PLAY" in about 1 second.  It doesn't seem to matter what game I do this with, they all act the same.  Some example titles: Cook, Serve, Delicious 3; Homeworld: Deserts of Kharak; Cat Quest II.

In the console/terminal, when I start up the app, there are maybe a 20-30 of the usual lines of output (which are seen even when a game successfully starts up), and then it gets to trying to start up a few processes for the game, but then it just dies.  For example, see the following snippet, where it shows "Adding process" a few times, and then suddenly "Game removed....ProcID blah" and "Exiting app"

```
>>> Adding process 4587 for game ID 1000030
>>> Adding process 4588 for game ID 1000030
Game removed: AppID 1000030 "", ProcID 4586 
Uploaded AppInterfaceStats to Steam
Exiting app 1000030
No cached sticky mapping in ActivateActionSet.
```

When I add `PROTON_LOG=1`, there is no apparent increase in verbosity in the terminal.  Also, it does not generate the expected `~/steam-######.log` file.

When I switch the Proton version to 5.0-xx (e.g. 5.0-10), only then does it generate the `steam-281610.log` (for Homework: Deserts of Kharak).

Could use some help debugging this issue.  I've been going along fine so far with 5.0-xx, but I fear that it's only a matter of time when newer games will not work with 5.0, and will only work with 5.13+ or 6.x.

**Comment by kisak-valve** [comment]
Hello @Pistos, starting with Proton 5.13, Proton is run inside the `Steam Linux Runtime - Soldier` container environment, and Pressure Vessel is what sets up that environment. The symptoms you've described reads like you've encountered some issue with Pressure Vessel.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the information requested here.

Hello @CStafford-14, the behavior you've described reads like it's unrelated to what @Pistos has described.

**Comment by Pistos** [comment]
@kisak-valve Thanks for your response!  Here's my System Information: https://gist.github.com/Pistos/030bbd335685224e1e567df0e7540026

I already have `STEAM_LINUX_RUNTIME_LOG=1` set before running `steam`.

And now that I've collected this info, I see the clear error:

```
bwrap: Failed to make / slave: Invalid argument
```

and I have seen that before, except in the normal terminal (which is running `steam`).  So I guess it's buried in a log file instead now, which is why I didn't see it.  I will now try a few things, as mentioned in

* https://wiki.gentoo.org/wiki/Talk:Steam/Client_troubleshooting#bwrap_.28bubblewrap.29_issues
* https://wiki.gentoo.org/wiki/Talk:Steam#User_namespace_kernel_builtin_required_for_proton

I'm hesitant to just enable user namespaces, as I've read that this could open up a security problem.  I'll try the bind mount first.

Thanks!

**Comment by Pistos** [comment]
After doing the bind mount (`mount -o bind $chroot_dir $chroot_dir`), I now see this in the `....../var/*.log` file:

```
bwrap: Can't find source path /tmp/.X11-unix/X0: No such file or directory
```

**Comment by Pistos** [comment]
Solved with

```
mount --bind /tmp/.X11-unix "${chroot_dir}/tmp/.X11-unix"
```

before `chroot`ing into the chroot.

Thanks for your help!

**Comment by F8ER** [comment]
> Solved with
> 
> ```
> mount --bind /tmp/.X11-unix "${chroot_dir}/tmp/.X11-unix"
> ```
> 
> before `chroot`ing into the chroot.
> 
> Thanks for your help!

Why chrooting is even required? It looks more like a workaround than solution. Was Steam running chrooted when the issue appeared?

**Comment by Pistos** [comment]
@F8ER Yes, I have been running Steam in a chroot on purpose from day one.

**Comment by F8ER** [comment]
> @F8ER Yes, I have been running Steam in a chroot on purpose from day one.

May I ask what was the purpose?

**Comment by farmall1125** [comment]
I know this is ancient, but I'm having the exact same issue. I'm not a guru by any means. If I wanted to replicate your steps, in what order do I do this? Here is my current log, but ultimately it seems to be pointing the same permission issue. ANY help is welcome.

**Comment by Pistos** [comment]
@farmall1125 Your log seems to talk about not being able to connect to the X server. Perhaps it has to do with `xhost`, as described https://wiki.gentoo.org/wiki/Steam#Chroot .
