### ISSUE TITLE
Monster hunter world and apparently other games do not start or show only a black screen.

### ISSUE THREAD

**Issue by Matias-Louzao-Ataria** [ValveSoftware/steam-runtime#479]
#### Your system information

* Steam Runtime Version: 0.20211027.0 soldier 0.20211027.0
* Distribution: Arch Linux (Up to date)
* Link to your full system information: 
 https://gist.github.com/Matias-Louzao-Ataria/6b5277fc5905f68759580ee0909b010d
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Proton older and proton 5.13+
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: depot 0.20211028.32

#### Please describe your issue in as much detail as possible:
A week earlier I tried playing Monster hunter world and got only a black screen, tried with older versions and even proton experimental as well as 3.6-8 but nothing change even when it was working earlier.
Maybe this link could be of some help: https://github.com/ValveSoftware/Proton/issues/5340 this issue is where I found that more people where having similar issues.

I only did get the game to work using proton-tkg-5.8,(performance is not good at all), but it was working with all the other official ones I tried.

I also found that the steam client is unable to close itself once it's told to exit.

depot	0.20211028.32
pressure-vessel	0.20211027.0
scripts	v0.20210917.0-0-g1cf127d
soldier	0.20211027.0	soldier	0.20211027.0

#### Steps for reproducing this issue:

1. Open steam
2. Try running Monster hunter world
3.  Only a black screen shows up.

logs and other files like the versions.txt file:
[slr-app582010-t20211208T234050.log](https://github.com/ValveSoftware/steam-runtime/files/7680955/slr-app582010-t20211208T234050.log)
[VERSIONS.txt](https://github.com/ValveSoftware/steam-runtime/files/7680958/VERSIONS.txt)
[steam-582010.log](https://github.com/ValveSoftware/steam-runtime/files/7680964/steam-582010.log)

Best regards!

**Comment by smcv** [comment]
If Proton 3.6-8 didn't help, then this might not be a pressure-vessel problem, because versions of Proton older than 5.13 do not use pressure-vessel.

**Comment by smcv** [comment]
> I also found that the steam client is unable to close itself once it's told to exit

This is not the bug tracker for the Steam client. Please report this as a separate issue on <https://github.com/ValveSoftware/steam-for-linux/issues>.

**Comment by smcv** [comment]
This looks more like a game-specific Proton issue with MHW than a container runtime issue.

Please try a game that is known to work successfully under Proton, such as The Expendabros (linked above). If that works but MHW does not, then this is more likely to be a Proton issue.

**Comment by kisak-valve** [comment]
Closing pending feedback.
