### ISSUE TITLE
steamwebhelper does not render (crashes, only shows black) on GNU Guix

### ISSUE THREAD

**Issue by podiki** [ValveSoftware/steam-runtime#480]
#### Your system information

* Steam Runtime Version: steam-runtime_0.20211102.0
* Distribution: GNU Guix
* Link to your full system information: [SysInfo Gist](https://gist.github.com/podiki/d1b2216a2c6833d986a9bc3b22713cdd)
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name   Version         Runtime Runtime_Version Comment
depot   0.20211028.32                   # Overall version number
pressure-vessel 0.20211027.0                    
scripts v0.20210917.0-0-g1cf127d                        # Entry point scripts, etc.
soldier 0.20211027.0    soldier 0.20211027.0    # soldier_platform_0.20211027.0/
```

#### Please describe your issue in as much detail as possible:
Steam doesn't display any content in main window besides menus, so all web (embedded Chrome) content is just black. Internet access is fine for downloading games, or in small or Big Picture mode which display correctly (don't use steamwebhelper presumably?).

I'm aware a similar sounding issue has come up repeatedly in the last couple of months, in other cases related to fontconfig versions or missing libraries. Here I'm not seeing any output to indicate that as a cause. This was also reported in the Nonguix package [at this issue](https://gitlab.com/nonguix/nonguix/-/issues/139) earlier on September 10th, but that was before my rewrite to use an `ld.so.cache` and have it running pressure-vessel and current Proton. Perhaps useful to note that before that issue there were no reported problems in this area, though the package then was using `LD_LIBRARY_PATH` instead.

The problem appears to be in steamwebhelper, but none of the verbose outputs or debugging I've tried has given me much useful information.

- [This gist](https://gist.github.com/podiki/0d4a9852cc0f7ed853e7b2646861bd3e) has the Steam, steamwebhelper, and cef logs when just opening Steam and trying to load the main store screen.
- For comparison, [this other gist](https://gist.github.com/podiki/ac9d705a6e23139f5a9701bddadac20a) has logs running Flatpak Steam for comparison (less verbose logging).

The main difference I see is that the lines
```
[1211/061432.492321:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
...
[1211/061433.612562:INFO:crash_reporting.cc(269)] Crash reporting enabled for process: renderer
```
do not appear when running non-Flatpak Steam. So my guess it that the sandbox and/or rendering process is failing (no surprise on the rendering failing), but no idea what is going wrong. It uploads a crash log but I don't see that locally anywhere (`/dev/fd/4` doesn't help).

Any idea or steps I can try to further debug? What does steamwebhelper or libcef need to function beyond what Steam and pressure-vessel need from the host?

#### Steps for reproducing this issue:

1. Start Steam on Guix (uses FHS container, see more at #478 for this setup)
2. Observe black where web content should be.

EDIT: Forgot to note that the logs from the failure (non-Flatpak Steam) are with all GPU interface options and smooth scrolling off. I've tried with them on as well, which has the same black rendering instead of expected content.

Also forgot the `syslog` message:
`Dec 13 00:28:30 localhost vmunix: [95056.072180] traps: ThreadPoolForeg[7667] trap invalid opcode ip:7f875a3e6643 sp:7f87435d3390 error:0 in libcef.so[7f8759bb0000+6f56000]`

**Comment by smcv** [comment]
> ```
> Dec 13 00:28:30 localhost vmunix: [95056.072180] traps: ThreadPoolForeg[7667] trap invalid opcode ip:7f875a3e6643 sp:7f87435d3390 error:0 in libcef.so[7f8759bb0000+6f56000]
> ```

This is almost certainly the `steamwebhelper` crashing, which is one way to cause the black screen symptom.

Can you get a backtrace, perhaps by using `systemd-coredump` or `corekeeper` or some equivalent thing?

**Comment by podiki** [comment]
Guix doesn't use `systemd` so I'll have to see the easiest way to get the full backtrace when I have time later today. In the meantime, I do have the coredump from another computer (Guix on top of Arch, but pretty sure there isn't a functional difference for the crash) via `systemd-coredump`. (There may be some minor differences here, like maybe not setting up for it to gzip and send the crash to Steam, but otherwise is the same package.)

Here is the coredump: [steamwebhelper.coredump.tar.gz](https://github.com/ValveSoftware/steam-runtime/files/7713465/steamwebhelper.coredump.tar.gz)

And below is the summary from the `journalctl`:
```
Dec 09 19:17:50 azazel systemd-coredump[254621]: [🡕] Process 254545 (steamwebhelper) of user 1000 dumped core.
                                                 
                                                 Found module /home/john/.local/share/Steam/ubuntu12_64/steamwebhelper with build-id: e69700b8133034af8086383a3eceba7842e07cf8
                                                 Found module /home/john/.local/share/Steam/ubuntu12_64/libminigbm.so with build-id: e2a99b94888bfefe2322217766fb4f4d331f6f1b
                                                 Found module /home/john/.local/share/Steam/ubuntu12_64/libSDL2-2.0.so.0 with build-id: 9958c337f121f3b76b908f5375507edfad42a8ca
                                                 Found module /home/john/.local/share/Steam/ubuntu12_64/libcef.so with build-id: 2aa8544fae633aa6049631bc673190c343c4789b
                                                 Found module /gnu/store/jawarkca8jl3japfz6j00ps5wvwhdb91-glibc-for-fhs-2.33/lib/ld-2.33.so without build-id.
                                                 Found module linux-vdso.so.1 with build-id: 21f54a7973875d5754f43db6afff2d13e5604665
                                                 Found module libnss_files.so.2 without build-id.
                                                 Found module libLLVMBitstreamReader.so.11 without build-id.
                                                 Found module libLLVMAsmParser.so.11 without build-id.
                                                 Found module libLLVMTextAPI.so.11 without build-id.
                                                 Found module libLLVMDebugInfoMSF.so.11 without build-id.
                                                 Found module libLLVMDebugInfoDWARF.so.11 without build-id.
                                                 Found module libLLVMDemangle.so.11 without build-id.
                                                 Found module libLLVMRemarks.so.11 without build-id.
                                                 Found module libLLVMDebugInfoCodeView.so.11 without build-id.
                                                 Found module libLLVMMCParser.so.11 without build-id.
                                                 Found module libLLVMBitReader.so.11 without build-id.
                                                 Found module libLLVMAggressiveInstCombine.so.11 without build-id.
                                                 Found module libLLVMLinker.so.11 without build-id.
                                                 Found module libLLVMInstrumentation.so.11 without build-id.
                                                 Found module libLLVMIRReader.so.11 without build-id.
                                                 Found module libLLVMFrontendOpenMP.so.11 without build-id.
                                                 Found module libLLVMBitWriter.so.11 without build-id.
                                                 Found module libLLVMVectorize.so.11 without build-id.
                                                 Found module libLLVMMIRParser.so.11 without build-id.
                                                 Found module libLLVMAMDGPUUtils.so.11 without build-id.
                                                 Found module libLLVMObject.so.11 without build-id.
                                                 Found module libLLVMBinaryFormat.so.11 without build-id.
                                                 Found module libLLVMProfileData.so.11 without build-id.
                                                 Found module libLLVMCodeGen.so.11 without build-id.
                                                 Found module libLLVMSelectionDAG.so.11 without build-id.
                                                 Found module libLLVMGlobalISel.so.11 without build-id.
                                                 Found module libLLVMCFGuard.so.11 without build-id.
                                                 Found module libLLVMAsmPrinter.so.11 without build-id.
                                                 Found module libLLVMMCDisassembler.so.11 without build-id.
                                                 Found module libdrm_nouveau.so.2 without build-id.
                                                 Found module libdrm_amdgpu.so.1 without build-id.
                                                 Found module libelf.so.1 with build-id: 18427992266b7cb4200e41b2ef5df3a69dde29c6
                                                 Found module libdrm_radeon.so.1 without build-id.
                                                 Found module libLLVMSupport.so.11 without build-id.
                                                 Found module libLLVMAMDGPUInfo.so.11 without build-id.
                                                 Found module libLLVMCore.so.11 without build-id.
                                                 Found module libLLVMMC.so.11 without build-id.
                                                 Found module libLLVMAMDGPUDesc.so.11 without build-id.
                                                 Found module libLLVMAMDGPUAsmParser.so.11 without build-id.
                                                 Found module libLLVMAnalysis.so.11 without build-id.
                                                 Found module libLLVMTransformUtils.so.11 without build-id.
                                                 Found module libLLVMInstCombine.so.11 without build-id.
                                                 Found module libLLVMScalarOpts.so.11 without build-id.
                                                 Found module libLLVMTarget.so.11 without build-id.
                                                 Found module libLLVMipo.so.11 without build-id.
                                                 Found module libLLVMAMDGPUCodeGen.so.11 without build-id.
                                                 Found module libLLVMAMDGPUDisassembler.so.11 without build-id.
                                                 Found module libLLVMRuntimeDyld.so.11 without build-id.
                                                 Found module libLLVMExecutionEngine.so.11 without build-id.
                                                 Found module libLLVMMCJIT.so.11 without build-id.
                                                 Found module libLLVMX86Info.so.11 without build-id.
                                                 Found module libLLVMX86Desc.so.11 without build-id.
                                                 Found module libLLVMX86CodeGen.so.11 without build-id.
                                                 Found module libLLVMX86Disassembler.so.11 without build-id.
                                                 Found module libLLVMCoroutines.so.11 without build-id.
                                                 Found module iris_dri.so with build-id: 0bcb494e7a931cef360f8549ef7d1cac1edb0375
                                                 Found module libpng16.so.16 without build-id.
                                                 Found module libbz2.so.1.0 without build-id.
                                                 Found module libxcb-render.so.0 without build-id.
                                                 Found module libblkid.so.1 without build-id.
                                                 Found module libfreetype.so.6 without build-id.
                                                 Found module libfontconfig.so.1 without build-id.
                                                 Found module libgthread-2.0.so.0 without build-id.
                                                 Found module libresolv.so.2 without build-id.
                                                 Found module libmount.so.1 without build-id.
                                                 Found module libz.so.1 without build-id.
                                                 Found module libgmodule-2.0.so.0 without build-id.
                                                 Found module libpcre.so.1 without build-id.
                                                 Found module libffi.so.7 without build-id.
                                                 Found module libxcb-xfixes.so.0 without build-id.
                                                 Found module libxshmfence.so.1 without build-id.
                                                 Found module libxcb-sync.so.1 without build-id.
                                                 Found module libxcb-present.so.0 without build-id.
                                                 Found module libxcb-shm.so.0 without build-id.
                                                 Found module libXxf86vm.so.1 without build-id.
                                                 Found module libxcb-dri2.so.0 without build-id.
                                                 Found module libxcb-glx.so.0 without build-id.
                                                 Found module libdrm.so.2 without build-id.
                                                 Found module libglapi.so.0 without build-id.
                                                 Found module libbsd.so.0 without build-id.
                                                 Found module libXdmcp.so.6 without build-id.
                                                 Found module libXau.so.6 without build-id.
                                                 Found module libgcc_s.so.1 without build-id.
                                                 Found module libasound.so.2 without build-id.
                                                 Found module libdbus-1.so.3 without build-id.
                                                 Found module libexpat.so.1 without build-id.
                                                 Found module libgio-2.0.so.0 without build-id.
                                                 Found module libXfixes.so.3 without build-id.
                                                 Found module libxcb-dri3.so.0 without build-id.
                                                 Found module libxcb.so.1 without build-id.
                                                 Found module libX11-xcb.so.1 without build-id.
                                                 Found module libglib-2.0.so.0 without build-id.
                                                 Found module libgobject-2.0.so.0 without build-id.
                                                 Found module libc.so.6 without build-id.
                                                 Found module libstdc++.so.6 without build-id.
                                                 Found module libGL.so.1 without build-id.
                                                 Found module libXdamage.so.1 without build-id.
                                                 Found module libXext.so.6 without build-id.
                                                 Found module libX11.so.6 without build-id.
                                                 Found module librt.so.1 without build-id.
                                                 Found module libpthread.so.0 without build-id.
                                                 Found module libdl.so.2 without build-id.
                                                 Found module libm.so.6 without build-id.
                                                 Stack trace of thread 2049:
                                                 #0  0x00007fb0808bcd12 n/a (/home/john/.local/share/Steam/ubuntu12_64/libcef.so + 0x5249d12)
                                                 #1  0x00007fb0808a512e n/a (/home/john/.local/share/Steam/ubuntu12_64/libcef.so + 0x523212e)
                                                 #2  0x00007fb07e05903a n/a (/home/john/.local/share/Steam/ubuntu12_64/libcef.so + 0x29e603a)
                                                 #3  0x00007fb07e16988c n/a (/home/john/.local/share/Steam/ubuntu12_64/libcef.so + 0x2af688c)
                                                 #4  0x00007fb07e166bea n/a (/home/john/.local/share/Steam/ubuntu12_64/libcef.so + 0x2af3bea)
                                                 #5  0x00007fb07f56eb1c n/a (/home/john/.local/share/Steam/ubuntu12_64/libcef.so + 0x3efbb1c)
                                                 #6  0x00007fb07cf9247d n/a (/home/john/.local/share/Steam/ubuntu12_64/libcef.so + 0x191f47d)
                                                 #7  0x00000000004b5e7a n/a (/home/john/.local/share/Steam/ubuntu12_64/steamwebhelper + 0xb5e7a)
```

**Comment by smcv** [comment]
The `steamwebhelper` is unusual because it uses its own miniature version of the `LD_LIBRARY_PATH`-based Steam Runtime, which is not the same as the one used to run Steam itself:

* Steam, native Linux games by default, Proton 5.0 and older: Steam Runtime 1 'scout' via `~/.steam/root/ubuntu12_32/steam-runtime`
* `steamwebhelper`: Steam Runtime 1½ 'heavy' via `~/.steam/root/ubuntu12_64/steam-runtime-heavy`
* Proton 5.13+, native Linux games in `Steam Linux Runtime`: Steam Runtime 2 'soldier' via `SteamLinuxRuntime_soldier` and pressure-vessel

In fact, you can see this in your log:

```
steamwebhelper.sh[403]: Runtime for steamwebhelper: defaulting to /home/john/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
```

The path of execution for this stuff goes:

* Steam binary
    * `ubuntu12_64/steamwebhelper.sh`
        * `ubuntu12_64/steam-runtime-heavy.sh`
            * `ubuntu12_64/steam-runtime-heavy/setup.sh`
            * `ubuntu12_64/steam-runtime-heavy/run.sh`
                * `ubuntu12_64/steamwebhelper` binary

If you run Steam with `STEAM_RUNTIME_VERBOSE=1` in the environment, you'll get a bit more information.

The goal is that `steamwebhelper` runs with a `LD_LIBRARY_PATH` that has, in this order:

* `steam-runtime-heavy/pinned_libs_*`, containing symlinks to any library in the `heavy` runtime that is strictly newer than your (Guix) system libraries
* your (Guix) system libraries
* the libraries from the `heavy` runtime

To make that happen, `ubuntu12_64/steam-runtime-heavy/setup.sh` populates `ubuntu12_64/steam-runtime-heavy/pinned_libs_*/` with symlinks, and then `ubuntu12_64/steam-runtime-heavy/run.sh` sets up the `LD_LIBRARY_PATH`.

If the resulting `LD_LIBRARY_PATH` is wrong, then crashes are likely. `setup.sh` and `run.sh` both rely on `/sbin/ldconfig -Xnv` giving us a list of system libraries and system library directories, which seems like something that might not work as expected on Guix.

**Comment by podiki** [comment]
Thanks for explaining (yet another runtime/container!), a few questions so I hope I can debug:

1. I assume `steam-runtime-heavy` is expected for steamwebhelper. It is a different runtime than e.g. soldier/pressure-vessel and I see `LD_LIBRARY_PATH` is used instead. Any clues why this won't work if seeing and capturing libraries in pressure-vessel does? I understand it is a different process, but wondering what is going wrong if that's the problem (`/sbin/ldconfig` exists and is used in pressure-vessel too, right?).
2. I don't see anything in the `pinned_libs_` directories, is that unusual?
3. I've tried adding more available libraries to the container for Steam, with no differences. And I'm not seeing any output giving me a hint that something is missing. Perhaps it is a version conflict somewhere? I've tried strace on steamwebhelper but didn't get any clues there (I can try that again and provide output)

Anything else I can try or look at that will let me know what's going wrong? Thanks for your help!

**Comment by smcv** [comment]
> It is a different runtime than e.g. soldier/pressure-vessel

Yes, the `LD_LIBRARY_PATH`-based scout and heavy runtimes are a completely different (and much older) implementation, which doesn't use containers.

This means they can work on systems where a container runtime can't (like older versions of Flatpak, or machines where creating a new user namespace is administratively prohibited like older versions of RHEL), but they don't work on some systems where the container runtime does - which might include NixOS and Guix. If you had to use any hacks or workarounds to make the scout runtime work (those might involve setting the `STEAM_RUNTIME` environment variable), then similar hacks or workarounds might be needed for heavy.

> `/sbin/ldconfig` exists and is used in pressure-vessel too, right?

I don't know whether `/sbin/ldconfig` exists in your FHS-style container: it's your FHS-style container, not mine.

pressure-vessel tries several possible paths for ldconfig, but I think the `LD_LIBRARY_PATH`-based runtimes do not.

pressure-vessel also uses `ldconfig`, but it uses it very differently: capsule-capture-libs reads the ldconfig cache directly from C code, and then runs ldconfig to build its own new ldconfig cache inside the container, whereas the `LD_LIBRARY_PATH`-based runtimes screen-scrape the output of `/sbin/ldconfig -Xnv`.

Try running `/sbin/ldconfig -Xnv` on your Arch system (or anything else vaguely FHS-like, such as Debian or Fedora) while *not* in the Guix environment. Your goal should be to get a similar result inside the Guix environment.

> I don't see anything in the `pinned_libs_` directories, is that unusual?

That's normal for `heavy`. Those directories will only be non-empty if one of the few libraries included in `heavy` is strictly newer than the corresponding library on your host system.

**Comment by podiki** [comment]
> If you had to use any hacks or workarounds to make the scout runtime work (those might involve setting the `STEAM_RUNTIME` environment variable), then similar hacks or workarounds might be needed for heavy.

I'm not using any workarounds but maybe this is showing something is needed. But only steamwebhelper uses the heavy runtime? Anything easy to test in heavy as well that might be useful?

Perhaps trying other things with the `run.sh` and `start.sh` scripts will give me something helpful.

> > `/sbin/ldconfig` exists and is used in pressure-vessel too, right?
> 
> I don't know whether `/sbin/ldconfig` exists in your FHS-style container: it's your FHS-style container, not mine.

The first part was a statement (`/sbin/ldconfig` exists and runs in the FHS container). But you answered the second part question of how it is used in the different runtimes which all seems fine on my end, but will investigate if the output is expected.

> Try running `/sbin/ldconfig -Xnv` on your Arch system (or anything else vaguely FHS-like, such as Debian or Fedora) while _not_ in the Guix environment. Your goal should be to get a similar result inside the Guix environment.

This doesn't output anything for me, but that would be because of the `-n` option (only process given directory): what directory should this run for? Within `ubuntu12_64/steam-runtime-heavy`?

**Comment by smcv** [comment]
Sorry, that should have said `/sbin/ldconfig -XNv` (capital N: don't rebuild the cache).

**Comment by smcv** [comment]
> But only steamwebhelper uses the heavy runtime?

Yes, which unfortunately makes it awkward to test (it doesn't have the `steam-runtime-system-info` diagnostic tool either).

**Comment by podiki** [comment]
Thanks. Okay, that's a huge list (since my Arch machine contains a lot of extra libraries of course). I'll see if adding any of those missing packages to the FHS-like container helps. Perhaps I should compare versus the Flatpak runtime, guessing that would be less.

On the other hand, if it is a missing library, I would think that would come up in some output. I should try an strace or maybe gdb, although my earlier tries with strace did not show any failing library calls. Maybe a version incompatibility instead?

Does the heavy runtime still allow `LD_LIBRARY_PATH` from the host to take priority or is it only through `ldconfig`? Just wondering if that will give me a shortcut to try (quicker to make a whole lot of libraries available for me).

**Comment by smcv** [comment]
> Okay, that's a huge list

The specific libraries do not all need to be there, but the general format of the output does. (In particular, it should be finding key libraries like GLib, Pango and libX11).

> Does the heavy runtime still allow `LD_LIBRARY_PATH` from the host to take priority or is it only through `ldconfig`?

It should put the host `LD_LIBRARY_PATH` first, same as scout (since 914de96).

**Comment by smcv** [comment]
> I'll see if adding any of those missing packages to the FHS-like container helps

The libraries that are included in heavy (see `steam-runtime-heavy/lib/x86_64-linux-gnu` and `steam-runtime-heavy/usr/lib/x86_64-linux-gnu`) would be a good place to start.

A few of them, like `libpng12.so.0`, won't typically be available under that SONAME on more modern systems, but most of them will be installed on non-minimal desktop systems in practice, so the code path where we genuinely use the version from heavy is not going to be well-tested for those.

**Comment by podiki** [comment]
Well, I got it to work, but not sure the actual root cause yet. Running with

`LD_LIBRARY_PATH=/lib64:$HOME/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu steam`

does the trick. I had also added more libraries to the FHS container, but didn't do anything (they are still in there now, haven't yet figured out the minimal combination of everything).

It indeed needs both of those paths above, not just one, adding in others (like `/lib`) doesn't make a difference. I'm confused since `/lib64` in the FHS-like container is every that is in the ld cache and picked up by ldconfig (will double check). The `steam-runtime` path makes more sense if something is not available maybe, but shouldn't it fall back to there? Or perhaps it is how it is combined by `heavy` in the final `LD_LIBRARY_PATH`. I guess by checking the contents of `/lib64` and the `steam-runtime` above should yield some clues over what is missing or a version difference. Seems odd to me, but will hopefully become clearer once I do a detailed cross check...

**Comment by podiki** [comment]
I think what that means is that `/sbin/ldconfig -XNv` is not giving output that `heavy` likes, or probably is missing some library. I note that the first lines of output (in the FHS container) are:
```
/sbin/ldconfig: Can't stat /gnu/store/jawarkca8jl3japfz6j00ps5wvwhdb91-glibc-for-fhs-2.33/lib64: No such file or directory
/sbin/ldconfig: Can't stat /gnu/store/jawarkca8jl3japfz6j00ps5wvwhdb91-glibc-for-fhs-2.33/libx32: No such file or directory
```
I see that `lib64` and `libx32` are defaults from `glibc`'s `ldconfig.h`, namely `SYSDEP_KNOWN_INTERPRETER_NAMES` and a similar line for `libx32` also appears on Arch. Meanwhile `/etc/ld.so.conf` only contains two directories
```
/gnu/store/dm5n74f0mrbpmv3w99mkmd2di9jsm4vs-fhs-union-64-0.0/lib
/gnu/store/77dx2adb8k8ina3yrgs67q26xqk57s2s-fhs-union-32-0.0/lib
```
which exist and provide the rest of the output of `ldconfig`. I'm guessing that error is ignored by the runtime parsing of `ldconfig` output?

After those two error lines above, the output looks the way it should, just like on an Arch system basically. Except, of course, with `/gnu/store/...` directories it is searching as expected. I've also tried this where the paths are all internal to the container, so just `/lib`, `/lib64` etc. I didn't notice a difference but maybe didn't hit the right combination of factors together.

And ignoring that for the moment, `ldconfig` doesn't output some libraries which exist in there, most noticeably `libssl.so`. I'm not sure why that is, perhaps some configuration of `ldconfig` or some environment variable or ...? Something for me to look into.

Anyway, if `ldconfig` is not giving output that the `heavy` runtime can use it is not clear to me why. The only difference is the paths. Probably (?) a library is missing, though would have hoped for an explicit error of not finding a library. Giving Steam an `LD_LIBRARY_PATH` works around this problem, though not sure why the `steam-runtime` itself also needs to be in there (isn't that added by `heavy`?). Maybe keeping `LD_LIBRARY_PATH` is helpful for older (non Steam runtime) native games as well.

**Comment by podiki** [comment]
Fixed on my end.

I decided to ignore that `ldconfig` doesn't list some libraries I provide and just started adding everything that the `heavy` runtime has in it to the FHS container. This fixed the problem without any other changes. The missing dependency turned out to be `eudev` (an alternative udev that Guix uses, from Gentoo I believe) presumably for the `libudev` library. All the others I added, like `openssl` did not make a difference once I removed them.

Still surprised that nothing gave output indicating trying to load a library that didn't exist or some mismatch from using the version in `heavy`. In that regard `pressure-vessel` was easier to diagnose.

Thanks @smcv once again for the help! I learned more about how Steam works and found the path forward thanks to your questions and comments.

**Comment by smcv** [comment]
Because the `LD_LIBRARY_PATH`-based runtimes rely on `ldconfig` to find out your OS's library search path, we can only see the libraries that your FHS container copies/binds/symlinks/hard-links into a directory that is searched by your `ldconfig`, which I think in your case means `/gnu/store/*-fhs-union-*/lib`. For libraries elsewhere in `/gnu/store`, the runtime will behave as though that library didn't exist.

I assume your solution to this was to copy/bind/link a suitable version of libudev into `/gnu/store/*-fhs-union-*/lib`.

> ldconfig doesn't output some libraries which exist in there, most noticeably libssl.so

Each library has an ELF `DT_SONAME` header (it shows up as `SONAME` in objdump), and the only name that should appear in `ldconfig` output is the `DT_SONAME`. For example, `ldconfig` should output `libc.so.6`, `libz.so.1`, and `libssl.so.1.1` (or whatever version you have), but not `libc.so`, `libz.so` or `libssl.so`. That's normal.

The `SONAME` is also the filename that needs to appear in the library search path, typically as a symlink to a version-qualified name like `libz.so.1 -> libz.so.1.2.11`.

All (correctly implemented) runtime library lookups, whether for `DT_NEEDED` or `dlopen`, are done in terms of the `SONAME`.

> Still surprised that nothing gave output indicating trying to load a library that didn't exist

steamwebhelper is closed-source, so I can't know what libraries it needs, other than by inspecting the binary. In principle, heavy is meant to contain everything it needs, except for glibc and OpenGL drivers. In practice, there will be some set of "system" libraries that are expected to come from the OS, and apparently libudev is one of those.

> The missing dependency turned out to be eudev (an alternative udev that Guix uses, from Gentoo I believe) presumably for the libudev library

That does make sense. libudev is an important library for various things, and the IPC protocol between udevd and libudev is not guaranteed to be stable between versions (officially it's considered to be an implementation detail of each specific version). So it's possible that heavy's libudev is incompatible with your OS's udevd, which might result in an error that something inside steamwebhelper/CEF maybe doesn't handle correctly?

Or maybe steamwebhelper/CEF is loading libudev with dlopen, assuming that it's a newer version than the 2015 version that's in heavy, and that assumption isn't met if you don't include your system libudev in the FHS-style container?

Again, the versions of all the libraries in heavy are *meant* to be sufficient, so either of those is arguably a bug in steamwebhelper/CEF - but any reasonable OS will have a newer x86_64 version of libudev than heavy's, so it's a bug that would only happen in unusual environments like NixOS and Guix (which I should remind you are not officially supported).

For context, udev was originally its own independent project, but joined systemd in 2013 (which is why the systemd version number jumped from 44 to 183, to keep it higher than the last separate udev release) and subsequently started sharing lower-level code with other parts of systemd. It doesn't technically require systemd, but the way to get udev without systemd is to compile all of systemd, and then throw away the parts that are not needed by udev. This is straightforward in binary distributions like Debian that routinely split the results of compiling a single source package into multiple binary packages for installation, but more annoying in source-based distributions.

eudev is a fork of the pre-183 separate udev, used by distros that don't want to use systemd for whatever reason. It's compatible enough with systemd's udev that the libudev ABI is the same, but might not be 100% compatible on finer details (Steam has had issues in the past with systemd's udev and eudev not parsing our udev rules identically, although the current version should be OK with both).

**Comment by smcv** [comment]
It sounds as though the solution to this needs to happen on the Guix side (changing the build rules for the FHS container so that it includes libudev) rather than in Steam. Is that correct?

If so, then I think we can close this issue.

**Comment by podiki** [comment]
> Because the `LD_LIBRARY_PATH`-based runtimes rely on `ldconfig` to find out your OS's library search path, we can only see the libraries that your FHS container copies/binds/symlinks/hard-links into a directory that is searched by your `ldconfig`, which I think in your case means `/gnu/store/*-fhs-union-*/lib`. For libraries elsewhere in `/gnu/store`, the runtime will behave as though that library didn't exist.
> 
> I assume your solution to this was to copy/bind/link a suitable version of libudev into `/gnu/store/*-fhs-union-*/lib`.

Yes, understood. All libraries for the FHS container are in that `...fhs-union...` directory in the store, as well as linked from where you'd expect it in an FHS layout, like `/lib`. This way anything relying on hardcoded expected paths should also work. The `/gnu/store...` directories are coming up because I've generated the ld cache that way rather than run within the container. This hasn't caused any functional difference, but I might move to running it once the container is created to look even more `FHS`-like in the future.

Anyway, yes, the solution was to add the `libudev` into the collection of libraries.

> Each library has an ELF `DT_SONAME` header (it shows up as `SONAME` in objdump), and the only name that should appear in `ldconfig` output is the `DT_SONAME`. ...
> 
> ...
> 
> All (correctly implemented) runtime library lookups, whether for `DT_NEEDED` or `dlopen`, are done in terms of the `SONAME`.

I'm still not sure why (no version of) `libssl` was appearing in the `ldconfig` output. Possibly it was seeing something else that provides the same `SONAME` (not sure if that makes sense)? When `ldconfig` was pointed to just a directory with `libssl` and nothing else, it showed up in the output. But I don't know enough about what's happening under the hood to understand why. Hopefully not something I'll need to dig into since it seems to work anyway, probably just something I don't know about the mechanics.

> steamwebhelper is closed-source, so I can't know what libraries it needs, other than by inspecting the binary. In principle, heavy is meant to contain everything it needs, except for glibc and OpenGL drivers. In practice, there will be some set of "system" libraries that are expected to come from the OS, and apparently libudev is one of those.
> 
> > The missing dependency turned out to be eudev (an alternative udev that Guix uses, from Gentoo I believe) presumably for the libudev library
> 
> That does make sense. libudev is an important library for various things, and the IPC protocol between udevd and libudev is not guaranteed to be stable between versions (officially it's considered to be an implementation detail of each specific version). So it's possible that heavy's libudev is incompatible with your OS's udevd, which might result in an error that something inside steamwebhelper/CEF maybe doesn't handle correctly?

I was trying libraries that were in the `heavy` runtime directory. So either `libudev` from `heavy` wasn't being picked up for some reason, or a mismatch somewhere that really required the host version (seems to make sense, as you say).

> Or maybe steamwebhelper/CEF is loading libudev with dlopen, assuming that it's a newer version than the 2015 version that's in heavy, and that assumption isn't met if you don't include your system libudev in the FHS-style container?

Yeah, that could make sense.

> Again, the versions of all the libraries in heavy are _meant_ to be sufficient, so either of those is arguably a bug in steamwebhelper/CEF - but any reasonable OS will have a newer x86_64 version of libudev than heavy's, so it's a bug that would only happen in unusual environments like NixOS and Guix (which I should remind you are not officially supported).

Understood about no official support. Definitely could be an assumption of "there's a current `libudev` from the host that works" or maybe that there was no testing that using the version in `heavy` works, since it is old and every system would provide a workable `libudev` for that system.

(And thanks for the context around `udev` and `systemd`. It could be a future roadblock for non-`systemd` systems like Guix, as `udev` is needed quite widely.)

> It sounds as though the solution to this needs to happen on the Guix side (changing the build rules for the FHS container so that it includes libudev) rather than in Steam. Is that correct?
> 
> If so, then I think we can close this issue.

Correct, the solution comes from the Guix host side, making the FHS container more like what is expected on a real (FHS) distro. It works for me now as well as some others that have started testing it. I'll close this now.

On a side note, I think the Steam package for a Guix system is pretty feature complete. Some smaller issues with launching stuff on the host (via `xdg` but probably should use the portals) and I'm testing SteamVR right now. But Steam has all been working pretty smoothly now, so thanks again for the information and guidance! (For reference in case it is helpful for anyone else, that merge request is here: [[WIP] Steam on Nonguix](https://gitlab.com/nonguix/nonguix/-/merge_requests/140)
