### ISSUE TITLE
Proton >= 5.13 not working on Fedora

### ISSUE THREAD

**Issue by ignapk** [ValveSoftware/steam-runtime#481]
#### Your system information

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): Fedora 35
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  
  [System info](https://gist.github.com/ignapk/5055ea6243cb20136e42a122d0e18503)
* Have you checked for system updates?: [Yes/No] Yes
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton] Proton 5.13+ doesn't work, older Proton works, native linux games work
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?
```
steam-runtime_0.20210817.0
```
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name    Version        Runtime    Runtime_Version    Comment
depot    0.20211028.32            # Overall version number
pressure-vessel    0.20211027.0
scripts    v0.20210917.0-0-g1cf127d            # Entry point scripts, etc.
soldier    0.20211027.0    soldier    0.20211027.0    # soldier_platform_0.20211027.0/
```
#### Please describe your issue in as much detail as possible:

Some time ago launching games with proton greater or equal 5.13 stopped working. No such problem on other distribution (Arch linux). Example log: https://gist.github.com/ignapk/a53ef5b15a75570e146771380ba61c9c

#### Steps for reproducing this issue:

1. Try to launch game with proton 5.13 or newer
2. Observe game not launching

**Comment by RyuzakiKK** [comment]
Can you please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested info?

Your system info ends with: `CClientJobGatherRuntimeInformation: container read output failed`
This likely means that a problem occurs when Steam tries to set up the Steam Linux Runtime - Soldier container.

**Comment by ignapk** [comment]
[Output of STEAM_LINUX_RUNTIME_LOG=1 steam](https://gist.github.com/ignapk/28bdaf3fb3c15217febc07fbfdc07071)
I could not find slr-app*-*.log anywhere though :/

**Comment by RyuzakiKK** [comment]
By looking at the output that you posted it seems like you installed the Soldier runtime in `/mnt/821C5C5A1C5C4B75/gry/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier`. So you should find the slr log there, under the `var` directory.

**Comment by ignapk** [comment]
Output of `ls /mnt/821C5C5A1C5C4B75/gry/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/var`: (gist)[https://gist.github.com/ignapk/54490665a0ed892f3508473a89e33c61]
Does that mean that pressure-vessel is crashing on startup and doesn't produce any log, and therefore I should use the older method as described in https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#older-method ?

**Comment by ignapk** [comment]
If that's the case, here's pressure-vessel log obtained using the older method: [gist](https://gist.github.com/ignapk/0c476268b89895e08cbbb72b9b23e6b6)

**Comment by RyuzakiKK** [comment]
I'm still not sure why there isn't any trace of log from pressure-vessel.

Can you please try the following:
1. Open a terminal in `/mnt/821C5C5A1C5C4B75/gry/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier`, launch `PRESSURE_VESSEL_VERBOSE=1 ./run -- steam-runtime-system-info 2>&1 | tee container.log` and post the resulting `container.log`
2. Is `/mnt/821C5C5A1C5C4B75` a NTFS  drive? What happens if you move Steam Linux Runtime - Soldier to the Steam default home directory? You can do it from the Steam client, right click on Steam Linux Runtime - Soldier -> Properties -> Local Files -> Move install folder

**Comment by ignapk** [comment]
1. [container.log](https://gist.github.com/ignapk/1b804c184e5101b461dc08d04f694675)
2. The observable behaviour doesn't change if moved SLR-Soldier to default home directory, if you need any logs let me know which exactly

**Comment by ignapk** [comment]
I have managed to resolve this issue, but I can't say for sure which of the following things I did was the actual fix:
- removed all versions of proton, and SLRs
- tried to remove all external NTFS Steam libraries, but they would show up on steam restart
- completely uninstalled steam and removed all leftovers
- noticed there was system update that included nvidia drivers, so updated and rebooted
- installed steam without adding any external NTFS Steam libraries
- installed Floating Point, tested Proton 6.3 which now magically works
I don't have more time to debug this right now, and don't know which conclusions to draw - perhaps it was somehow related to https://github.com/ValveSoftware/steam-runtime/issues/434
