### ISSUE TITLE
Unable to launch any game

### ISSUE THREAD

**Issue by Awlexus** [ValveSoftware/steam-runtime#484]
#### Your system information

* Steam Runtime Version: 
```bash
$ pacman -Q steam
steam 1.0.0.74-1
```
* Distribution (e.g. Ubuntu 18.04): Arch Linux 5.15.10-arch1-1-vfio
* Link to your full system information: https://gist.github.com/Awlexus/b430fc7786eeea79fe3cab052f6a7184
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Proton 6.3.8
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20211209.37			# Overall version number
pressure-vessel	0.20211207.0			
scripts	v0.20211029.0-0-g2d89be4			# Entry point scripts, etc.
soldier	0.20211207.0	soldier	0.20211207.0	# soldier_platform_0.20211207.0/
```
#### Please describe your issue in as much detail as possible:
After performing an update of my packages I've been unable to launch any game. As soon as the game starts its process switches to a zombie state and no errors are displayed. 

I've created a log of what happens when I try to start a game with 
command used: `STEAM_LINUX_RUNTIME_LOG=1 PRESSURE_VESSEL_LOG=1 steam`
https://gist.github.com/Awlexus/a2f12e1d0ab43d5f7ac745f4929b3110

**Comment by kisak-valve** [comment]
Hello @Awlexus, Arch's AMDVLK package is broken https://github.com/GPUOpen-Drivers/AMDVLK/issues/265. This is not a Steam runtime issue.

Downgrade the AMDVLK package or switch to mesa/radv in the `vulkan-radeon` and `lib32-vulkan-radeon` packages.
