### ISSUE TITLE
chdir problem with steam non-native linux games

### ISSUE THREAD

**Issue by suchencjusz** [ValveSoftware/steam-runtime#488]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 20.04 5.13.0-28-generic
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Expect:
Games starts.

Did:
Did not start.

(Proton 6.3-8)

When I started steam in cli, this shows up:

```chdir /home/suchencjusz/.steam/debian-installation/steamapps/common/SlapshotRebound```

It onlt appears on non-native games, csgo, prison architect and portal 2 works fine.

#### Steps for reproducing this issue:

1. Press Play button on any game, either native or proton.
2. Game prepares to launch...
3. Play button goes green again, no game starts.

**Comment by kisak-valve** [comment]
Thanks @suchencjusz, starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment and Pressure Vessel is what sets up that environment. [`CClientJobGatherRuntimeInformation: container read output failed`](https://gist.github.com/suchencjusz/0aebfc40cdfeb5e84cd9397d1fa5084d#file-steam-L844) at the end of your system information tells us something's gone wrong there before Proton got a chance to start.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested information for a Steam runtime dev to ponder.

**Comment by suchencjusz** [comment]
The (logs):

```.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier```
https://gist.github.com/suchencjusz/88459e63d7aa56059a80bbb31c850af4

VERSIONS.txt are clear

**Comment by suchencjusz** [comment]
There is any chance to repair it??

**Comment by smcv** [comment]
This looks like the root cause:

```
SteamLinuxRuntime_soldier/_v2-entry-point: line 284: .../SteamLinuxRuntime_soldier/run: Success
```

which means something is failing to run `.../SteamLinuxRuntime_soldier/run`, **and** the error indicator `errno` is not getting set correctly.

**Comment by smcv** [comment]
> `VERSIONS.txt are clear`

What do you mean by this? Do you mean that `VERSIONS.txt` is an empty file (does not contain any text)?

**Comment by smcv** [comment]
> When I started steam in cli, this shows up:
>
> chdir /home/suchencjusz/.steam/debian-installation/steamapps/common/SlapshotRebound

This is not an error. It is normal for this message to appear for Proton games.

**Comment by suchencjusz** [comment]
- Yes, csgo works fine,
- I mean other games that are not native supported,
- verifying the proton utility did not work,
- `VERSIONS.txt` exists, but is empty,
- `run` exists, but is empty, (wtf)
veryfing the `Steam Linux Runtime - soldier` worked...... thanks <3
