### ISSUE TITLE
Recent STL that supports C++17 features

### ISSUE THREAD

**Issue by sgiraudot** [ValveSoftware/steam-runtime#489]
I'm trying to compile my game on the Steam Runtime, but I'm having a hard time considering the most recent compiler available is, from what I understood, `gcc-5` whose STL only has partial support of C++17 features. Is there a way to compile a program that requires C++17 _and_ make it work within the Steam Runtime?

**Comment by TTimo** [comment]
Hello @sgiraudot,

You can use `gcc-9`, which is the most recent gcc version available in the scout runtime.

See https://github.com/ValveSoftware/steam-runtime for details on how to obtain the latest sdk images.

**Comment by TTimo** [comment]
Oh you're right this is a bit outdated. I added a mention for gcc-9.
