### ISSUE TITLE
pressure-vessel-wrap - E: Unable to set mode of "./bin" in "[...]" fchmod: Operation not permitted

### ISSUE THREAD

**Issue by Blue-Beaker** [ValveSoftware/steam-runtime#491]
## System Information
- Distro: Kubuntu 21.10
- CPU:i5-4300y
- GPU: Inter HD Graphics 4200
```
glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 4200 (HSW GT2) (0xa1e)
    Version: 21.2.2
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 4200 (HSW GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.2.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 21.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 21.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

- Kernel version:5.13.0-28-generic
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/Blue-Beaker/f6cdbe0dfa9a958bd9fe226aec4be115
- Proton version: 5.13-6, 6.3-8, experimental

Proton doesn't leave a log.
## Symptoms 
When I launch any game with proton 5.13-6, 6.3-8, or proton experimental, it quits instantly and leave no logs.
Proton 5.0-10 and 4.11-13 works well.
## Reproduction
1. install a game, force it to use proton 5.13-6, 6.3-8 or proton experimental.
2. add PROTON_LOG=1 %command% to launch options.
3. the game quits immediately after launch, and leaves no log.
4. try to attach console by konsole -e PROTON_LOG=1 %command%, these appears:
```ERROR: ld.so: object '/home/blue-beaker/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/blue-beaker/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blue-beaker/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blue-beaker/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 42004 != 42001, skipping destruction (fork without exec?)
pressure-vessel-wrap[42001]: E: Unable to set mode of "./bin" in "/mnt/D/SteamLibrary(Linux)/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-PJEMH1/usr": fchmod: Operation not permitted

```

**Comment by Blue-Beaker** [comment]
> Hello @Blue-Beaker, starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment, and Pressure Vessel is what sets up that container environment. The error you're seeing looks like there's some kind of file permission issue blocking Pressure Vessel, so I've gone ahead and transferred this issue report.
> 
> What filesystem are you using with `/mnt/D/SteamLibrary(Linux)` and how is it mounted?
> 
> As a side note, the video drivers for Intel's Haswell generation provides an incomplete implementation of Vulkan, which makes your system unsupported by Proton. It's not relevant to the above issue, but you should be aware that graphical artifacts and/or crashes are expected even if this issue gets resolved.

It's NTFS and mounted with fstab params `defaults,umask=007,gid=46` . I'll replace it with the working mount params from my other PC and try again.
For graphics, I use `PROTON_USE_WINED3D=1` env and it works well before I reinstalled the system.

**Comment by Blue-Beaker** [comment]
remounted with `rw,user,auto,exec,nosuid,nodev,x-gvfs-show` instead, worked.
maybe proton should prompt the user, at least show the console log when run into this problem.

**Comment by smcv** [comment]
Today's beta releases work around this, to the extent that it's possible to do so (see https://github.com/ValveSoftware/steam-runtime/issues/434#issuecomment-1710491239).
