### ISSUE TITLE
No sound on steam games - Snap client for linux

### ISSUE THREAD

**Issue by WovichX** [ValveSoftware/steam-runtime#505]
# Compatibility Report
- Almost every steam game except Half-Life and Counter-Strike

## System Information
- GPU: Intel HD Graphics 5500 
- Driver/LLVM version: Mesa 21.3.8
- Kernel version: 5.13.0-41-generic
- Link to full system information report as [gist]: https://gist.github.com/WovichX/75440e53dfedb4de899617f0c61d45ff
- Proton version: Default by Steam, when I'm trying to select another version of proton, games are not launch or crashes after start.

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms 
If I launch most of the games there is no sound
The issue occurs on games downloaded from snap version of Steam client

## Reproduction
Launch game
Wait until it loads
Notice that in main menu no sound
Start gameplay
Notice that in gameplay phase also no sound

**Comment by kisak-valve** [comment]
Hello @WovichX, this reads like https://github.com/canonical/steam-snap/issues/3, and should be evaluated on the package maintainer's side if the most recent build of the snap package doesn't fix your issue.

If that's not the case, then this issue pondered from the Steam Linux Runtime - Soldier side before Proton. Starting with with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment, and that hasn't been extensively tested for quirks with Canonical's snap package.

> Proton version: Default by Steam, when I'm trying to select another version of proton, games are not launch or crashes after start.

There is no such thing as a default Proton version set by Steam for any game. At some point you've picked a specific Proton version to use with any game that does not claim to have a native Linux build.

Are you able to check if the snap packaging of Steam is newer than the fix which was put in for the linked issue report? If not, are you able to get a development variant of the snap and retest? If that doesn't help, then please list specific games you've used to test and also give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the information requested there.

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by alexnc01** [comment]
Myself, found that "Chrome", on my mixer, "Applications" tab, was muted, and I don't remember setting that this way. Inferred that "Chrome", there, was currently my Steam client. Then I set audio fader properly and both games and Steam client were promptly fixed. Kubuntu 20.04, Steam Play + Proton Experimental.
