### ISSUE TITLE
pressure vessel - failed to open radeonsi: libicuuc.so.69: unable to open shared object file: No such file or directory

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/steam-runtime#512]
#### Your system information

* Steam Runtime Version: steam-runtime_0.20220315.0
* Distribution: OpenMandriva Cooker 
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/AngryPenguinPL/51abd6ad7e46f51ea7586678c054b488/) 
  
* Have you checked for system updates?: [Yes]
* What compatibility tool are you using?: [Proton 6/7/Experimenta;]
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
-depot	0.20220509.53			# Overall version number
-pressure-vessel	0.20220420.0			
-scripts	v0.20220311.0-0-gae4cbed			# Entry point scripts, etc.
-soldier	0.20220509.0	soldier	0.20220509.0	# soldier_platform_0.20220509.0/

#### Please describe your issue in as much detail as possible:

64bit Proton games works but all 32-bit not. Terminal log show me:

> /Proton 7.0'/proton waitforexitandrun  '/steam/steamapps/common/The Witcher Enhanced Edition/System/witcher.exe'", ProcID 33416, IP 0.0.0.0:0
> libGL error: MESA-LOADER: failed to open radeonsi: libicuuc.so.69: unable to open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri, suffix _dri)
> libGL error: failed to load driver: radeonsi
> libGL error: MESA-LOADER: failed to open radeonsi: libicuuc.so.69: unable to open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri, suffix _dri)
> libGL error: failed to load driver: radeonsi
> libGL error: MESA-LOADER: failed to open swrast: libicuuc.so.69: unable to open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri, suffix _dri)
> libGL error: failed to load driver: swrast
> X Error of failed request:  BadValue (integer parameter out of range for operation)
>   Major opcode of failed request:  152 (GLX)
>   Minor opcode of failed request:  3 (X_GLXCreateContext)
>   Value in failed request:  0x0
>   Serial number of failed request:  267

I dont know what cause this issue. Because last time when I play 32-bit Proton game was about in april. Played Witcher1 and Dark Devotion and right now both not working. Trying also other 32-bit games and there is a same error. Worth to add that my system ship icu 71.1.

**Comment by kisak-valve** [comment]
Hello @AngryPenguinPL, from one perspective, the riddle here seems to figuring out why the system installed 32 bit libexslt.so.0, libxml2.so.2, and libxslt.so.1 are built against an older version of icu compared to the rest of the system. https://gist.github.com/AngryPenguinPL/51abd6ad7e46f51ea7586678c054b488/#file-gistfile1-txt-L2160-L2192

I think for the graphics stack, we care most about why `/lib/libxml2.so.2.9.12` isn't 2.9.14 to match the 64 bit variant.

From the other perspective, the riddle is that `libicuuc.so.69` isn't found even though you have https://gist.github.com/AngryPenguinPL/51abd6ad7e46f51ea7586678c054b488/#file-gistfile1-txt-L1890 bringing it into the container environment.

**Comment by AngryPenguinPL** [comment]
Yes, looks like this is my fault. In the distribution I'm using, after dropping i686 repo and moving to compat -m32bit version built on the x86_64 tree, apparently some packages have not been updated to the -m32bit. After they were forced to upgrade to -m32, x86 applications started working in Proton again.
Unfortunately, I still do not know what could really cause this state, because in April I had the same libraries, but the x86 games on Steam Proton worked.

Thanks for your help.
