### ISSUE TITLE
Can't open Apex Legends due to "compatibility tool configuration failed"

### ISSUE THREAD

**Issue by MogManek** [ValveSoftware/steam-runtime#514]
#### Your system information

* Steam Runtime Version: No idea how to check that, is it's steam client version it should be:
Built: Jun 7 2022 at 03:18:43
Steam API: v020
Steam package versions: 1654574690
* Distribution : POP OS 22.04 LTS
* Link to your full system information: https://gist.github.com/MogManek/635819999afcf9f4910b028ceccea39b
* Have you checked for system updates?: [Yes]
* What compatibility tool are you using?: [Proton 5.13+]
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: 
https://gist.github.com/MogManek/392ba1604bd1dc0424e1f313be60044b

#### Please describe your issue in as much detail as possible:
I've tried launching Apex Legends but i've occurred many issues like disk write error (which is not a problem anymore) but now i've ran into "compatibility tool configuration failed" Tried validating Steam Linux Runtime Soldier files but it did not find anything

#### Steps for reproducing this issue:

1. Open Steam
2. Launch Apex
3. This error pops up

**Comment by MogManek** [comment]
Hi! I've tried validanting files of Proton but no error whatsoever, every file got validated succesfully.
These are the logs:
COMPAT: https://gist.github.com/MogManek/5812cf03104531b4a37fb89fc713fc11
CONTENT: https://gist.github.com/MogManek/05aea94c8c945af600b2b4b8aad91f7b

I've checked my HD and it's 100% healthy.

**Comment by kisak-valve** [comment]
Hello @MogManek, what filesystem are you using with `/media/kacper/Gry2/STEAM`?

**Comment by MogManek** [comment]
BUT, my Vulkan shaders are processing for a very long time even though i've enabled them to process in background

**Comment by MogManek** [comment]
Another update: Ran some games on Proton but they run on very low fps

**Comment by smcv** [comment]
> I use NTFS and i have report that it was magically working, we'll see if it will still work. iirc what i did to fix it is that i used some commands to make NTFS root or something like that, not sure.

Putting your Steam library on NTFS can be made to work, but it's extremely sensitive to the mount options in use. I'd recommend a native Linux filesystem like ext4 or btrfs.

**Comment by smcv** [comment]
> my Vulkan shaders are processing for a very long time even though i've enabled them to process in background

"Processing Vulkan shaders" is a Steam client thing, not a Steam Runtime thing, so it's out of scope for `ValveSoftware/steam-runtime`.

**Comment by MogManek** [comment]
> Putting your Steam library on NTFS can be made to work, but it's extremely sensitive to the mount options in use. I'd recommend a native Linux filesystem like ext4 or btrfs.

I would not change filesystem because i use Windows and Linux + i have 2 hard drives with around 1,6TB of Storage which i don't want to redownload 

And now once again i'm having disk write issues but it's out of scope here and i'll do it myself
