### ISSUE TITLE
Steam can't / won't update or download games on Windows 11 after making Pop os able to use NTFS drive

### ISSUE THREAD

**Issue by MogManek** [ValveSoftware/steam-runtime#520]
#### Your system information

* Steam Runtime Version: 
Built: Jul 25 2022, at 15:34:46
Steam API: v020
Steam package versions: 1658797147

* Distribution (e.g. Ubuntu 18.04): None, using W11
* Link to your full system information: https://gist.github.com/MogManek/55b7de9052ae1a103459c811afdc1e01
* Have you checked for system updates?: [Yes]
* Have you checked for system updates?: [Yes]
* What compatibility tool are you using?: [None]

#### Please describe your issue in as much detail as possible:
Hello, i'm not sure if it's the right place to report this, but i could not find any better place, i am currently having problem with steam giving me disk write error whenever i try update / download game, all of this started happening after doing this: https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows
Now steam won't update or download any games, tries recommended fixed like clear steam download cache etc.

#### Steps for reproducing this issue:

1. Open steam
2. Update / Download game that is on one of my disks

**Comment by kisak-valve** [comment]
Hello @MogManek, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing a Steam library folder between OSes is unsupported and undefined / unexpected issues might occur. Sorry, but this is an unsupported scenario.

Having said that, you might have luck with mentioning your issue to [Steam Support](https://help.steampowered.com). The Steam for Windows client is not supported here (on Github).
