### ISSUE TITLE
Run native Linux games inside the sniper runtime inside CI

### ISSUE THREAD

**Issue by quyykk** [ValveSoftware/steam-runtime#525]
The scout runtime has the following two files: `steam-runtime.sh` and `steam-runtime.tar.xz`. Those are useful to run the game inside the Steam runtime to verify that everything works, especially inside CI.

I'm currently experimenting with the new sniper runtime, and I can't figure out how to do this anymore. Reading through the docs (across way too many sites) I found that the container runtime is the `*.Platform-*-runtime.tar.gz` file, but it seems like I have to turn this into a Flatpak/pressure-vessel manually? I also found the `steam-container-runtime.tar.gz` file that seems to include a couple of scripts to build the runtime. But that's not really ideal for CI I would think.

The alternative is to use the Docker image to run the game, which probably works but I'd rather use the actual runtime that gets shipped with the Steam client instead of the development SDK if that makes sense.

So how would I best achieve this? Is there anything I overlooked? I'm admittedly pretty new to container technology and runtimes in general. 

Thanks!

**Comment by TTimo** [comment]
Hello @quyykk,

The runtime comes with a lot fewer packages than the sdk (no compilers for one), so you are right it's a better idea to test with the runtime and not the sdk.

At Valve we use the docker sdk images exclusively to target the Steam for linux runtime. Then we use `Steam Linux Runtime - Soldier` or `Steam Linux Runtime - Sniper` to run the game (either directly via Steam, or by invoking the entry point manually).

Probably worth pointing out that scout can run both via the legacy LD_* environment variables and library pinning setup, and the new container setup. The newer runtimes only run as container, there is no `run.sh` and LD_* environment variables option for them.

**Comment by quyykk** [comment]
> Then we use Steam Linux Runtime - Soldier or Steam Linux Runtime - Sniper to run the game (either directly via Steam, or by invoking the entry point manually)

That is something I could do on my machine, but I can't install Steam on GitHub's CI runners. Is it simply not possible?

**Comment by RyuzakiKK** [comment]
> The alternative is to use the Docker image to run the game, which probably works but I'd rather use the actual runtime that gets shipped with the Steam client instead of the development SDK if that makes sense.

What you are looking for is the "Platform". The "SDK" is an image with extra packages useful for building and debugging games, instead the "Platform" is the more traditional runtime as shipped via the Steam client.

For example to enter a Sniper environment you can use the Docker image `registry.gitlab.steamos.cloud/steamrt/sniper/platform`

If instead you prefer to use the runtime without docker, you need to download the [steam-container-runtime.tar.gz](https://images.steamos.cloud/steamrt-sniper/published/latest-container-runtime-depot/steam-container-runtime.tar.gz) and the actual [Sniper runtime](https://images.steamos.cloud/steamrt-sniper/published/latest-container-runtime-depot/com.valvesoftware.SteamRuntime.Platform-amd64,i386-sniper-runtime.tar.gz).
Finally you need to place the extracted Sniper content in `steam-container-runtime/depot/sniper_platform_*/`.

After that you'll be able to run `steam-container-runtime/depot/run-in-sniper` to execute your command from inside a Sniper environment.

**Comment by quyykk** [comment]
> For example to enter a Sniper environment you can use the Docker image registry.gitlab.steamos.cloud/steamrt/sniper/platform

That sounds great! Unfortunately it seems like this image isn't public:

```bash
$ docker run --rm -it --entrypoint bash registry.gitlab.steamos.cloud/steamrt/sniper/platform
Unable to find image 'registry.gitlab.steamos.cloud/steamrt/sniper/platform:latest' locally
docker: Error response from daemon: Head "https://registry.gitlab.steamos.cloud/v2/steamrt/sniper/platform/manifests/latest": denied: access forbidden.
See 'docker run --help'.
```

The actual Sniper runtime is 1.1GB big, that is not something that can be downloaded or cached from the CI. But thank you for the instructions, I will try it locally.

**Comment by RyuzakiKK** [comment]
> Unfortunately it seems like this image isn't public

Yeah, sorry about that. Docker transparently used my previous authentication token and I didn't realize it wasn't publicly available.

I guess that the only option for now to use the Sniper platform runtime is probably to download the two `tar.gz` and then launch `run-in-sniper`.

**Comment by quyykk** [comment]
> I guess that the only option for now, to use the Sniper platform runtime, is probably to download the two tar.gz and then launch run-in-sniper.

Yes thank you that worked perfectly!

**Comment by TTimo** [comment]
The registry images should definitely be public, be it sdk or platform.

**Comment by smcv** [comment]
> If instead you prefer to use the runtime without docker, you need to download the steam-container-runtime.tar.gz and the actual Sniper runtime.

The links Ludovico mentioned point to a non-public location that requires authentication. The public versions of those links (same content, different location) are [steam-container-runtime.tar.gz](https://repo.steampowered.com/steamrt-images-sniper/snapshots/latest-container-runtime-depot/steam-container-runtime.tar.gz) and [the Sniper platform libraries](https://repo.steampowered.com/steamrt-images-sniper/snapshots/latest-container-runtime-depot/com.valvesoftware.SteamRuntime.Platform-amd64,i386-sniper-runtime.tar.gz).

I'm looking into making the Docker/Podman images public as well.

**Comment by quyykk** [comment]
> One option is to use the newly-public Platform OCI images.

Nice! I will try it out. 

> You will not get up-to-date graphics drivers in this environment, so running a full game will probably not have acceptable performance

That's fine because for CI we already use llvmpipe.

> although that will often indicate a bug in the game that would also prevent it from running on older LTS operating systems.

that sounds like an advantage to me!

**Comment by quyykk** [comment]
I can't start the game inside the Docker platform image:

```
error: XDG_RUNTIME_DIR not set in the environment.
(SDL message: "No available video device")
```

Is there no llvmpipe? Or did I mess something up?

**Comment by smcv** [comment]
> Please note that the Platform OCI images are less polished than the corresponding SDKs.
>
> ...
>
> Next time I refactor the build process that produces the SDKs, I might adjust it to export the Platforms a little bit earlier, so that they miss out on some of the more destructive bits of customization.

I've now done this. The latest Platform image (sniper beta 0.20230216.41810) is less cut-down than previous versions, and more like an ordinary Docker image like `debian:bullseye-slim`:

* permissions and file ownership are normal
* setuid binaries stay setuid
* `apt` and `dpkg` are included, so you can install more packages if you need to
* Essential-flagged packages like `login`, `mount` and `passwd` aren't removed
* `/etc` and `/var` have their normal contents, instead of optimizing for space
* `sudo` and `libcap2-bin` (`capsh` etc.) are added, making it Toolbx-friendly
* it's no longer merged-`/usr`, matching the behaviour of `debian:bullseye-slim`

This makes it *slightly* larger and more featureful than the real container runtime, but hopefully not in any ways that a game would notice (if your game runs `useradd` or `dpkg` then something has gone *horribly* wrong).

> I can't start the game inside the Docker platform image

It is still the case that if you want X11 or Wayland inside your container, it's up to you to make that happen, perhaps by using `docker run -v ...` to share your X11 or Wayland socket with the container payload, or perhaps by installing `xauth` and `xvfb` and using `xvfb-run` (or a Wayland equivalent) to give you an invisible X11 display.

This is not unique to sniper: whatever you'd need to do to get working X11 in a `debian:bullseye-slim` container, it's going to be essentially the same steps for sniper.

The SDK is the same as the Platform in this respect, too (but you might find the SDK easier to debug because it has more tools, and in particular `xvfb-run` is preinstalled there).

**Comment by smcv** [comment]
> The latest Platform image (sniper beta 0.20230216.41810 from `registry.gitlab.steamos.cloud/steamrt/sniper/platform:0.20230216.41810` or `registry.gitlab.steamos.cloud/steamrt/sniper/platform:beta`) is less cut-down than previous versions, and more like an ordinary Docker image like `debian:bullseye-slim`

This change has now reached `registry.gitlab.steamos.cloud/steamrt/sniper/platform:latest` as well, so I think we can close this now.
