### ISSUE TITLE
after i update my Archlinux , A problem appear

### ISSUE THREAD

**Issue by ruizhipeng** [ValveSoftware/steam-runtime#53]
`'Running Steam on arch rolling 64-bit'`
`'STEAM_RUNTIME is enabled automatically'`
`'Installing breakpad exception handler for appid(steam)/version(1459463254)'`
`'libGL error: unable to load driver: i965_dri.so'`
`'libGL error: driver pointer missing'`
`'libGL error: failed to load driver: i965'`
`'libGL error: unable to load driver: swrast_dri.so'`
`'libGL error: failed to load driver: swrast'`
 When i start the steam it will appear this problem if you have time please help me 
 Best wishes

**Comment by Celti** [comment]
Recent updates in Arch have broken compatibility with the Steam runtime. Either use a native runtime [as detailed on the Arch wiki](https://wiki.archlinux.org/index.php/Steam#Using_native_runtime) or use the Steam Beta Update channel, which *seems* to be unaffected.

**Comment by not83** [comment]
How will he opt into beta if he can't open steam?

**Comment by heftig** [comment]
Unfortunately, beta is affected, too.

See https://bugs.archlinux.org/task/48994 . This could be fixed in the Steam Runtime by upgrading libgcrypt.

**Comment by ruizhipeng** [comment]
So was there not a method to fix this issue？Or maybe just i didn't find it ,i guess. Anyway, thanks for your hard working and test ,and i'll support Mr.G and Valve ^_^

**Comment by ruizhipeng** [comment]
@heftig Thank you so much that help me to fixed the problem but i still suggest that steam-runtime can be customized by player.  Best Wishes for all your guys.

**Comment by NicoHood** [comment]
Only deleting the libgpg-error did not fully work for me, I had to use the trick in post 16 here:
https://forum.manjaro.org/t/steam-doesnt-launch/623/15

**Comment by tfhavingfun** [comment]
Having the same issue here on Arch. I know there are workarounds for this, but a real fix by the dev team would be much appreciated.

**Comment by VGerris** [comment]
It seems this is the same problem like with starting the Android emulator.
In that case, the issue was with an incompatible libstdc++.so.6.

That one was fixed by renaming that file in the directory it is in, then symlink to the system version:
`ln -s /usr/lib64/libstdc++.so.6`

I hope that helps, the error is not very clear.

**Comment by Nephyrin** [comment]
This has been fixed for a while.  If you are still encountering problems with Arch using the steam runtime, please open a new issue report.
