### ISSUE TITLE
Cannot play any game via Proton: Application tried to create a window, but no driver could be loaded.

### ISSUE THREAD

**Issue by hjeldin** [ValveSoftware/steam-runtime#534]
#### Your system information

* Steam Runtime Version: 
steam-runtime_0.20220802.0
* Distribution (e.g. Ubuntu 18.04): 
Ubuntu 22.04
* Link to your full system information (Help -> System Information) in a Gist: 
https://gist.github.com/hjeldin/5880122927c61f9c91afae6edba7b22b
* Have you checked for system updates?: [Yes/No] 
Yes
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton] 
Proton 7.0/6.3/5.0
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?
N/A
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20220804.66			# Overall version number
pressure-vessel	0.20220803.0			
scripts	v0.20220803.0-0-gbca628e			# Entry point scripts, etc.
soldier	0.20220803.0	soldier	0.20220803.0	# soldier_platform_0.20220803.0/
```

#### Please describe your issue in as much detail as possible:

Expected: 
being able to play all proton-compatible games i have in my library.
What's happening: 
Starting any game in my library that requires proton fails.

Logs and system info running Skyrim Special Edition (proton versions 5.0, 6.3, 7.0):

- Proton 5.0 - working: https://gist.github.com/hjeldin/f93ab89098cc26fea83fb78cd5d1302f
- Proton 5.0 - not working: https://gist.github.com/hjeldin/ce14acf39b181f76546b812c181f0dbd
- Proton 6.3 - not working: https://gist.github.com/hjeldin/997d0179b660eac42ce0930449b1167f
- Proton 7.0 - not working: https://gist.github.com/hjeldin/4d0abb370c77f80ed94e324acaa150fe

Apparently running Skyrim SE with proton 5.0 worked only once. Now that i rebooted it doesn't work anymore.

As already said, Skyrim isn't the only game that doesn't run. So far i've tried with Skyrim SE, Hardspace: Shipbreaker and Sea of Thieves.
Sid Meier's Civilization VI and X4: Foundations work, but those are linux native ports so they don't count.

I noticed that the issue started occurring after a system update and an install of lutris and its whole wine stack.

Possibly similar issue #533 

#### Steps for reproducing this issue (supposedly):

1. Install steam + any proton-enabled game
2. Run said game
3. Install lutris

**Comment by RyuzakiKK** [comment]
I can see that in Soldier there is:
```
 "overrides/lib/x86_64-linux-gnu/libvulkan.so.1 -> /opt/DECK/libvulkan.so.1",
```
What's the content of `/opt/DECK`? Do you have a manually compiled/installed Vulkan driver there?

**Comment by hjeldin** [comment]
I see, i did install [DECK](https://github.com/sfx101/deck) right when i was installing lutris but (wrongly) assumed it didn't matter.
Thanks!
Here's the listing of `/opt/DECK`:
```
hjeldin@jupiter:/opt/DECK$ ls -al
total 176388
drwxrwxr-x 5 root root      4096 set 20 15:11 .
drwxr-xr-x 7 root root      4096 set 21 10:11 ..
-rw-r--r-- 1 root root    141930 mar 10  2022 chrome_100_percent.pak
-rw-r--r-- 1 root root    208519 mar 10  2022 chrome_200_percent.pak
-rwsr-xr-x 1 root root     50656 mar 10  2022 chrome-sandbox
-rwxr-xr-x 1 root root 140257336 mar 10  2022 deck
-rw-r--r-- 1 root root  10413488 mar 10  2022 icudtl.dat
-rwxr-xr-x 1 root root    233960 mar 10  2022 libEGL.so
-rwxr-xr-x 1 root root   2837744 mar 10  2022 libffmpeg.so
-rwxr-xr-x 1 root root   7234312 mar 10  2022 libGLESv2.so
-rwxr-xr-x 1 root root   4168528 mar 10  2022 libvk_swiftshader.so
-rwxr-xr-x 1 root root   4426328 mar 10  2022 libvulkan.so.1
-rw-r--r-- 1 root root      1096 mar 10  2022 LICENSE.electron.txt
-rw-r--r-- 1 root root   5286034 mar 10  2022 LICENSES.chromium.html
drwxrwxr-x 2 root root      4096 set 20 15:11 locales
drwxrwxr-x 3 root root      4096 set 20 15:11 resources
-rw-r--r-- 1 root root   5093175 mar 10  2022 resources.pak
-rw-r--r-- 1 root root     48465 mar 10  2022 snapshot_blob.bin
drwxrwxr-x 2 root root      4096 set 20 15:11 swiftshader
-rw-r--r-- 1 root root    165677 mar 10  2022 v8_context_snapshot.bin
-rw-r--r-- 1 root root       107 mar 10  2022 vk_swiftshader_icd.json
```

Moving the folder away from /opt now allows me to launch all my games. Is there a specific reason why /opt should have precedence compared to /usr ? 
Should i be careful when installing applications into /opt?

**Comment by RyuzakiKK** [comment]
AFAICT the DECK installation guide tells you to do `sudo sh -c "echo '/opt/DECK/' >> /etc/ld.so.conf.d/deck.conf"`.
This will add `/opt/DECK` to the dynamic linker configuration.

[ld.so(8)](https://man7.org/linux/man-pages/man8/ld.so.8.html) (check the man page for more detailed info), when asked to load a library, will search in:
- `LD_LIBRARY_PATH`
- `DT_RUNPATH` (from the binary)
- ld.so configuration (usually `/etc/ld.so.conf` and `/etc/ld.so.conf.d/*`)
- `/lib` and `/usr/lib` (or `lib64` variant)

For this reason `/opt/DECK` will have the precedence compared to `/usr/lib`.

**Comment by hjeldin** [comment]
Alright, thanks everybody!
Can confirm that the issue was a rogue override of libvulkan in my ld.so.conf.d. Removing either the file or the override fixes the issue.
