### ISSUE TITLE
Games using Proton don't open while using cursor theme on GNOME

### ISSUE THREAD

**Issue by waw6** [ValveSoftware/steam-runtime#538]
## System Information
- GPU: NVIDIA GeForce GTX 1660 Ti
- Driver/LLVM version: nvidia-515-48-07
- Kernel version: 5.18.10-76051810-generic 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/waw6/57bd3f79e14db3db2f6df1a3c2755354
- Proton version: Experimental

[steam-238460.log](https://github.com/ValveSoftware/Proton/files/9205464/steam-238460.log)

## Symptoms 

Games using Proton don't open while using the Orchis theme for some unknown reason. Works with other themes. Native games, such as CSGO, work fine.

**Comment by Hayashi-Tensai** [comment]
@RyuzakiKK After removing the `Inherits=WindowsConcept11_Dark` line from the `index.theme` file steam proton is then able to launch the game

**Comment by RyuzakiKK** [comment]
Thanks for checking. This is definitely a cursor theme bug then.

Newer versions of libxcursor (e.g. bullseye 1.2.0-2) gracefully handle it by preventing the circular dependency to happen, while older versions (e.g. buster 1.1.15-2 or Scout 1.1.12-1ubuntu0.1+srt6) will enter an infinite loop and ultimately crash.

In theory we could backport bullseye's version of libxcursor1 into the Scout Steam runtime, but first we need to figure out if that's feasible and how much work it would require.

**Comment by smcv** [comment]
This is really a bug in the cursor theme, and the real solution is to fix the theme so it doesn't claim to inherit from itself (which is not something that makes sense to do). However, we can mitigate it by backporting the workaround in libXcursor.

Depending on the exact versions involved, this can affect the Steam client itself, Proton games, and/or native Linux games.

For the Steam client itself, the libXcursor workaround is queued up for inclusion in a future Steam beta. You can also avoid the problem by making sure your host system has *both* 64-bit and 32-bit libXcursor, version 1.2.0 or later, for instance `libxcursor1:amd64` and `libxcursor1:i386` in Debian/Ubuntu, or `libxcursor` and `lib32-libxcursor` in Arch. If you do, those should be used in preference to the one from the Steam Runtime.

Most native Linux games use the same libXcursor as the Steam client. Proton 5.0 or older also uses the same libXcursor as the Steam client.

For Proton >= 5.13, the libXcursor workaround is included in the `client_beta` branch of "Steam Linux Runtime - soldier". In the fixed versions, `SteamLinuxRuntime_soldier/VERSIONS.txt` will say `soldier 0.20221017.1` or later. This version will be copied to the default branch when it has had more testing.

Native Linux games via the "Steam Linux Runtime" compatibility tool use the same libXcursor as Proton >= 5.13. Dota 2 is run like this by default. Most other games only run like this if you specifically configure it.

**Comment by smcv** [comment]
> For the Steam client itself, the libXcursor workaround is queued up for inclusion in a future Steam beta

This has now been released in Steam beta 1666656302 (build date 2022-10-24 22:59:09).

**Comment by kisak-valve** [comment]
Closing as fixed.

**Comment by smcv** [comment]
> > For the Steam client itself, the libXcursor workaround is queued up for inclusion in a future Steam beta
> 
> This has now been released in Steam beta 1666656302 (build date 2022-10-24 22:59:09).

This was promoted to the default branch in or before build 1668654564 (2022-11-17).

> For Proton >= 5.13, the libXcursor workaround is included in the client_beta branch of "Steam Linux Runtime - soldier". In the fixed versions, SteamLinuxRuntime_soldier/VERSIONS.txt will say soldier 0.20221017.1 or later. This version will be copied to the default branch when it has had more testing.

This was promoted to the default branch today.
