### ISSUE TITLE
Cannot start dota from Steam launcher, but can start it from terminal

### ISSUE THREAD

**Issue by Zulgrib** [ValveSoftware/steam-runtime#540]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/Zulgrib/9caad59255ac9573592401b59e12790d): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
When starting dota from Steam launcher GUI, the game never shows anything on screen, Steam launcher doesn't detect the game is running and allow me to start again, no dota process found in htop.

When starting dota using "~/.steam/root/ubuntu12_64/steam-runtime-heavy/run.sh ./dota.sh" while being in dota's data directory, the game starts, uses vulkan api and has no performance or stability issues.

Why wouldn't steam gui be able to start the game ?

#### Steps for reproducing this issue:

1. Start steam
2. Clic library
3. Clic on dota
4. Clic green play button

**Comment by kisak-valve** [comment]
Hello @Zulgrib, Dota 2 is currently expect to be run in the Steam Linux Runtime - Soldier container environment, not Steam's Heavy runtime. This reads more like an issue with initializing that container than an issue with Dota 2 itself.

Can you re-check Steam's system information, let it finish gathering the extended diagnostics information, and update your gist? Also, please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the request information.

**Comment by smcv** [comment]
This is still waiting for more information. We can't do anything to solve the problem you reported without seeing a log.

**Comment by kisak-valve** [comment]
Closing pending feedback.
