### ISSUE TITLE
Manually reinstall steam-runtime?

### ISSUE THREAD

**Issue by MyLittleRobo** [ValveSoftware/steam-runtime#56]
I deleted some files by accident. How can I regenerate steam-runtime now?

**Comment by Tele42** [comment]
Hello @MyLittleRobo, among other things, ```steam --reset``` will unpack the steam runtime during the re-bootstrap of the steam client.

Note: This will reset your steam client as if it was a new install, but should leave the installed games alone.

**Comment by MyLittleRobo** [comment]
@Tele42 thanks for fast answer!
