### ISSUE TITLE
Current Soldier release breaks MangoHUD on NixOS/Guix

### ISSUE THREAD

**Issue by hw-lunemann** [ValveSoftware/steam-runtime#562]
#### Your system information

* Steam Runtime Version: current release
* Distribution (e.g. Ubuntu 18.04): NixOS
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/):  https://gist.github.com/hw-lunemann/9c29b64d8710d81cb338e8d2c43e2f08

* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20230123.89			# Overall version number
pressure-vessel	0.20230216.0	scout		# from local file
scripts	0.20230112.0			# Entry point scripts, etc.
soldier	0.20230117.0	soldier	0.20230117.0	# soldier_platform_0.20230117.0/
```

#### Please describe your issue in as much detail as possible:
Currently MangoHUD is broken on the current and beta release of Soldier.
Log of current Soldier (broken): https://gist.github.com/hw-lunemann/5d12b972f0a947a3f5ff1c446e7d0151
Log of previous Solder (working): https://gist.github.com/hw-lunemann/e18ab51141249d63ab44bf9fa70d89b9

The offending error seems to be: `111:51:57.315493: pressure-vessel-wrap[57602]: I: Unable to load library /nix/store/dz2hdxs2h9vqn1lqc17vk6523yqssymj-mangohud-0.6.8/$LIB/mangohud/libMangoHud.so: /home/REDACTED/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/libexec/steam-runtime-tools-0/x86_64-linux-gnu-inspect-library: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory`
#### Steps for reproducing this issue:

1. Add "mangohud %command%" to launch options of a proton game
2. launch the game

**Comment by Atemu** [comment]
Back reference to Nixpkgs issue: https://github.com/NixOS/nixpkgs/issues/213366

**Comment by RyuzakiKK** [comment]
Pressure-vessel now checks the libraries more thoroughly, and in order to do that its helper `*-inspect-library` now depends on `libelf`.

From your log it seems like `libelf` is missing from your system, or from the list of dependencies that Nix uses for Steam.

**Comment by hw-lunemann** [comment]
`libelf` should be properly installed since it's included in the NixOS steam package [here](https://github.com/NixOS/nixpkgs/blob/b3474d78ff4b760be751a83aef7d58c503e3e66d/pkgs/games/steam/fhsenv.nix#L146)

**Comment by smcv** [comment]
I think this issue is probably only visible in NixOS (and probably Guix too), rather than being generic across all Linux distributions. In other distributions, `libelf.so.1` is not guaranteed in theory, but in practice it will always be present in the default search path because Mesa pulls it in. However, on NixOS and Guix, "default search path" is not really a concept that exists.

@kisak-valve or @hw-lunemann, please could you retitle to "Current Soldier release breaks MangoHUD on NixOS/Guix"?

**Comment by smcv** [comment]
Is that definitely `libelf.so.1` from `elfutils` (not some other `libelf` - there have been two projects with that name), and does NixOS include it in the FHS-style search path in the bubblewrap environment that NixOS uses to run Steam?

**Comment by Atemu** [comment]
`tree` of an older `libelf`:

```
result/
├── include
│   ├── gelf.h
│   ├── libelf
│   │   ├── elf_repl.h
│   │   ├── gelf.h
│   │   ├── libelf.h
│   │   ├── nlist.h
│   │   └── sys_elf.h
│   ├── libelf.h
│   └── nlist.h
├── lib
│   ├── libelf.a
│   ├── libelf.so -> libelf.so.0.8.13
│   ├── libelf.so.0 -> libelf.so.0.8.13
│   ├── libelf.so.0.8.13
│   └── pkgconfig
│       └── libelf.pc
└── share
    └── locale
        └── de
            └── LC_MESSAGES
                └── libelf.mo

8 directories, 14 files
```

It doesn't have the so. That so is located in `elfutils.out`:

```
result/
├── lib
│   ├── libasm-0.188.so
│   ├── libasm.a
│   ├── libasm.so -> libasm.so.1
│   ├── libasm.so.1 -> libasm-0.188.so
│   ├── libdw-0.188.so
│   ├── libdw.a
│   ├── libdw.so -> libdw.so.1
│   ├── libdw.so.1 -> libdw-0.188.so
│   ├── libelf-0.188.so
│   ├── libelf.a
│   ├── libelf.so -> libelf.so.1
│   └── libelf.so.1 -> libelf-0.188.so
└── share
    └── locale
        ├── de
        │   └── LC_MESSAGES
        │       └── elfutils.mo
        ├── en@boldquot
        │   └── LC_MESSAGES
        │       └── elfutils.mo
        ├── en@quot
        │   └── LC_MESSAGES
        │       └── elfutils.mo
        ├── es
        │   └── LC_MESSAGES
        │       └── elfutils.mo
        ├── ja
        │   └── LC_MESSAGES
        │       └── elfutils.mo
        ├── pl
        │   └── LC_MESSAGES
        │       └── elfutils.mo
        └── uk
            └── LC_MESSAGES
                └── elfutils.mo

17 directories, 19 files
```

Looks like a bug on our side.

**Comment by smcv** [comment]
> This is going to be tricky to avoid

I have some ideas about possible routes, let's see what happens.

The root cause here is that we're sharing code between a diagnostic tool (for which we want to use libelf to get us more information) and functionally necessary stuff done by pressure-vessel (for which we want minimal dependencies for maximum robustness).

@hw-lunemann or @Atemu, are you able to keep a copy of the old Steam environment that reproduces this issue, so that you'll be able to re-test this if we're able to find a solution? I hear NixOS is good at that sort of thing :-)

As a pragmatic workaround in NixOS and Guix, the FHS-like environment should contain elfutils (`libelf.so.1`) and it doesn't need the old libelf (`libelf.so.0`).

**Comment by smcv** [comment]
> are you able to keep a copy of the old Steam environment that reproduces this issue?

Sorry, I should be clearer about this: what I'm asking you to keep a copy of is the FHS-like environment that NixOS uses to run Steam. You can let Steam itself, and all of its games and tools, continue to auto-upgrade.

**Comment by hw-lunemann** [comment]
@smcv Yes, NixOS is indeed very good at that sort of thing.

@Atemu is right, plugging `elfutils.out` into our FHS environment fixes this issue on NixOS!

**Comment by smcv** [comment]
> Yes, NixOS is indeed very good at that sort of thing.

Great, please keep the non-working FHS environment around for a while, and I'll comment here again if there's something to test.

**Comment by hw-lunemann** [comment]
Alright!

**Comment by Atemu** [comment]
@smcv The non-working FHSenv will be around for pretty much forever, or rather, you will always be able to *reproduce* it. That's core to how Nix works! ;)

The environment and all its dependencies are fully declared by a single revision of Nixpkgs, i.e. https://github.com/NixOS/nixpkgs/blob/28319deb5ab05458d9cd5c7d99e1a24ec2e8fc4b/pkgs/games/steam/fhsenv.nix

If you installed the Nix package manager beside your Linux system, you could get our broken `steam` by simply running `nix-shell -p steam -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/28319deb5ab05458d9cd5c7d99e1a24ec2e8fc4b.tar.gz --command steam`

(You will likely need https://github.com/guibou/nixGL to get your non-NixOS drivers wired up though.)

Thank you so much for your help in debugging this!

**Comment by 8836290** [comment]
The problem is.....it happens on Ubuntu LTS 22.04.1

![Screenshot from 2023-02-17 17-26-53](https://user-images.githubusercontent.com/58001454/219696751-6a8c7640-2cbc-448e-ba70-654b02462df1.png)

**Comment by 8836290** [comment]
> @8836290 Can you please run steam with `STEAM_LINUX_RUNTIME_LOG=1` like this:
> 
> ```
> STEAM_LINUX_RUNTIME_LOG=1 steam
> ```
> 
> Then launch a game with mangohud enabled and post the latest logfile from `~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var`?
> 
> More info here https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md

The provided folder does not exist in my system. Instead I provide the requested log file as it is found under :

 `/media/<user name here>/linuxgames/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/var/
`
[slr-app383120-t20230217T174235.log](https://github.com/ValveSoftware/steam-runtime/files/10768497/slr-app383120-t20230217T174235.log)

**Comment by hw-lunemann** [comment]
Your problem is unrelated to this issue and likely not a SteamLinuxRuntime issue unless the previous release of Soldier (search for soldier in your library, right click, properties, betas, select "previous_release").

Either way, make a new issue here or in the MangoHUD repo.

**Comment by 8836290** [comment]
> 
Previous release of Soldier fixes the horizontal layout of MangoHud...The issue appeared today AFTER an update of Steam Linux Runtime - Soldier as I noticed (I always keep an eye on steam downloads almost every day).

**Comment by RyuzakiKK** [comment]
@8836290 please open a new issue. Include your "Help -> System Information" info and a `slr-app*.log` with Soldier "previous_release" to be able to compare the two.

**Comment by hw-lunemann** [comment]
> > 
> 
> Previous release of Soldier fixes the horizontal layout of MangoHud...The issue appeared today AFTER an update of Steam Linux Runtime - Soldier as I noticed (I always keep an eye on steam downloads almost every day).

I believe this is a configuration problem on your end
```
[2023-02-17 17:42:37.754] [MANGOHUD] [error] [overlay_params.cpp:702] Unknown option 'horizontal'
```

**Comment by 8836290** [comment]
> > > 
> > 
> > 
> > Previous release of Soldier fixes the horizontal layout of MangoHud...The issue appeared today AFTER an update of Steam Linux Runtime - Soldier as I noticed (I always keep an eye on steam downloads almost every day).
> 
> I believe this is a configuration problem on your end
> 
> ```
> [2023-02-17 17:42:37.754] [MANGOHUD] [error] [overlay_params.cpp:702] Unknown option 'horizontal'
> ```


So , let me see if I understand correctly. 

1. I touched nothing on my system regarding any updates and mangohud parameters, with only update of  SteamLinuxRuntime - Soldier
2. An update to latest verison of  SteamLinuxRuntime - Soldier messes with a parameter of mangohud in fact ignoring it. Log file indicates that the parameter is "unknown"
3.Previous version of  SteamLinuxRuntime - Soldier restores fuctionality of said parameter. 

Obviously said parameter is known to previous version of  SteamLinuxRuntime - Soldier but not in latest. The above indicate that there is a configuration problem on my end!!! Could you please elaborate? 

Thank you

**Comment by Atemu** [comment]
@8836290 you have an entirely separate issue, please create a new GitHub issue and follow the template w.r.t. logs and other info.

**Comment by 8836290** [comment]
You are right it is not Solider. Fixed my issue with the help from MangoHud developers. Thank you for your help.

**Comment by cyberconan** [comment]
> You are right it is not Solider. Fixed my issue with the help from MangoHud developers. Thank you for your help.

I have the same problem in ArchLinux playing Tomb Raider with Proton+Mangohud, only is fixed after downgrade Steam Linux Runtime Soldier to previous release. Can you share the solution than Magohud developers gave you? Thanks!

**Comment by 8836290** [comment]
> > You are right it is not Solider. Fixed my issue with the help from MangoHud developers. Thank you for your help.
> 
> I have the same problem in ArchLinux playing Tomb Raider with Proton+Mangohud, only is fixed after downgrade Steam Linux Runtime Soldier to previous release. Can you share the solution than Magohud developers gave you? Thanks!

Totaly remove mangohud from your system. [Go to their github and manually download the latest version ](https://github.com/flightlessmango/MangoHud/releases/tag/v0.6.8) Uncompress and install from the directory via console.

**Comment by smcv** [comment]
This is an issue tracker, not a forum, and this issue is specific to NixOS and Guix and is already closed.

If you have having problems with MangoHUD on an OS that is neither NixOS nor Guix, then this is not an appropriate place to discuss them. If you believe you have encountered a bug in the *Steam Linux Runtime - soldier* container runtime, please open a **separate** issue with full details so that a developer can look into it.

**Comment by cyberconan** [comment]
Simon, it was just a post closing question, we know the rules that github didn't come up with yesterday... Have a nice day.

**Comment by smcv** [comment]
The fixed version of pressure-vessel is now available in the `client_beta` branch of `SteamLinuxRuntime_soldier` and no longer needs to be downloaded separately. It shows up as `pressure-vessel 0.20230227.0` or later in `VERSIONS.txt` and logs.

**Comment by hw-lunemann** [comment]
I'll test it tomorrow!

**Comment by hw-lunemann** [comment]
> I'll test it tomorrow!

Not quite "tomorrow" but it works!

**Comment by smcv** [comment]
Good to know. The version in the `client_beta` branch will be copied to the default branch when it has had some more testing, fixing this for everyone - most likely that will be next time we do a new beta.

For users of unusual distributions like NixOS/Guix, it might be a good idea to run the *Steam Linux Runtime - soldier* beta routinely. That will get you bug fixes sooner, and will also mean that if you find a regression, you can report the regression, and then work around it by rolling back from the beta to the default branch while we look for a solution.
