### ISSUE TITLE
libxcb needs updating to avoid hangs using MESA and separate GL/Windowing threads.

### ISSUE THREAD

**Issue by jwyatt-feral** [ValveSoftware/steam-runtime#57]
The version of libxcb included in the steam runtime does not appear to contain https://cgit.freedesktop.org/xcb/libxcb/commit/?id=be0fe56c3bcad5124dcc6c47a2fad01acd16f71a, which is the fix for https://bugs.freedesktop.org/show_bug.cgi?id=44198.

Under MESA drivers, if making GL calls (not GLX calls) and Xlib calls on separate threads, occasional hangs can happen. They do not happen if you LD_PRELOAD the Ubuntu 16.04's version of libxcb. Based on the related QT bugs, this appears to be the fix.

(Example trace of xcb calls before hang:

> (Thread 7ffea7fef700) Call 157650: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157650:  returned (xcb_generic_event_t_) 0xe172d80
> (Thread 7ffea7fef700) Call 157651: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157651:  returned (xcb_generic_event_t_) 0xe14eeb0
> (Thread 7ffea7fef700) Call 157652: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157652:  returned (xcb_generic_event_t_) 0
> (Thread 7ffea7fef700) Call 157653: xcb_send_request((xcb_connection_t_) 0xc2a6ac0, (int) 0, (iovec_) 0x7ffea7fed900, (<unknown> const_) 0x7fffe8694db0
> (Thread 7ffea7fef700) Call 157653:  returned (unsigned int) 21656
> (Thread 7ffea7fef700) Call 157654: xcb_flush((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffea7fef700) Call 157654:  returned (int) 1
> (Thread 7ffea7fef700) Call 157655: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157655:  returned (xcb_generic_event_t_) 0
> (Thread 7ffea7fef700) Call 157656: xcb_flush((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffea7fef700) Call 157656:  returned (int) 1
> (Thread 7ffea7fef700) Call 157657: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157657:  returned (xcb_generic_event_t_) 0
> (Thread 7ffea7fef700) Call 157658: xcb_send_request((xcb_connection_t_) 0xc2a6ac0, (int) 0, (iovec_) 0x7ffea7fed900, (<unknown> const_) 0x7fffe8694db0
> (Thread 7ffea7fef700) Call 157658:  returned (unsigned int) 21657
> (Thread 7ffea7fef700) Call 157659: xcb_flush((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffea7fef700) Call 157659:  returned (int) 1
> (Thread 7ffea7fef700) Call 157660: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157660:  returned (xcb_generic_event_t_) 0x7ffdcca5b180
> (Thread 7ffea7fef700) Call 157661: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157661:  returned (xcb_generic_event_t_) 0x7ffdcc98ea30
> (Thread 7ffea7fef700) Call 157662: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157662:  returned (xcb_generic_event_t_) 0
> (Thread 7ffea7fef700) Call 157663: xcb_flush((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffea7fef700) Call 157663:  returned (int) 1
> (Thread 7ffea7fef700) Call 157664: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157664:  returned (xcb_generic_event_t_) 0
> (Thread 7ffea7fef700) Call 157665: xcb_send_request((xcb_connection_t_) 0xc2a6ac0, (int) 0, (iovec_) 0x7ffea7fed900, (<unknown> const_) 0x7fffe8694db0
> (Thread 7ffea7fef700) Call 157665:  returned (unsigned int) 21658
> (Thread 7ffea7fef700) Call 157666: xcb_flush((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffea7fef700) Call 157666:  returned (int) 1
> (Thread 7ffea7fef700) Call 157667: xcb_poll_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffea7fef700) Call 157667:  returned (xcb_generic_event_t_) 0
> (Thread 7ffea7fef700) Call 157668: xcb_flush((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffea7fef700) Call 157668:  returned (int) 1
> (Thread 7ffea7fef700) Call 157669: xcb_wait_for_special_event((xcb_connection_t_) 0xc2a6ac0, (xcb_special_event_t_) 0x7ffe50f1c4e0
> (Thread 7ffff7fa7580) Call 157670: xcb_take_socket((xcb_connection_t_) 0xc2a6ac0, (return_socket_callback) 0x7fffeb5954f4, (void_) 0xc2a5610, (int) 0, (unsigned long_) 0x7fffffffc830
> (Thread 7ffff7fa7580) Call 157670:  returned (int) 1
> (Thread 7ffff7fa7580) Call 157671: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157671:  returned (xcb_generic_event_t_) 0x7ffdcca6d4f0
> (Thread 7ffff7fa7580) Call 157672: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157672:  returned (xcb_generic_event_t_) 0x7ffe527b1af0
> (Thread 7ffff7fa7580) Call 157673: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157673:  returned (xcb_generic_event_t_) 0x7ffdccabd6e0
> (Thread 7ffff7fa7580) Call 157674: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157674:  returned (xcb_generic_event_t_) 0x7ffe52347c80
> (Thread 7ffff7fa7580) Call 157675: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157675:  returned (xcb_generic_event_t_) 0x7ffdccb19e40
> (Thread 7ffff7fa7580) Call 157676: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157676:  returned (xcb_generic_event_t_) 0x7ffdd5afaf60
> (Thread 7ffff7fa7580) Call 157677: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157677:  returned (xcb_generic_event_t_) 0
> (Thread 7ffff7fa7580) Call 157678: xcb_connection_has_error((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157678:  returned (int) 0
> (Thread 7ffff7fa7580) Call 157679: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157679:  returned (xcb_generic_event_t_) 0
> (Thread 7ffff7fa7580) Call 157680: xcb_connection_has_error((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157680:  returned (int) 0
> (Thread 7ffff7fa7580) Call 157681: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157681:  returned (xcb_generic_event_t_) 0
> (Thread 7ffff7fa7580) Call 157682: xcb_connection_has_error((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157682:  returned (int) 0
> (Thread 7ffff7fa7580) Call 157683: xcb_poll_for_event((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157683:  returned (xcb_generic_event_t_) 0
> (Thread 7ffff7fa7580) Call 157684: xcb_connection_has_error((xcb_connection_t_) 0xc2a6ac0
> (Thread 7ffff7fa7580) Call 157684:  returned (int) 0
> (Thread 7ffff7fa7580) Call 157685: xcb_writev((xcb_connection_t_) 0xc2a6ac0, (iovec_) 0x7fffffffc2b0, (int) 3, (unsigned long) 1
> (Thread 7ffff7fa7580) Call 157685:  returned (int) 1
> (Thread 7ffff7fa7580) Call 157686: xcb_wait_for_reply((xcb_connection_t_) 0xc2a6ac0, (unsigned int) 21659, (xcb_generic_error_t__) 0x7fffffffc348
> (Thread 7ffea7fef700) Call 157669:  returned (xcb_generic_event_t_) 0x7ffdd5afaf60
> (Thread 7ffea7fef700) Call 157687: xcb_flush((xcb_connection_t*) 0xc2a6ac0
> (Thread 7ffea7fef700) Call 157687:  returned (int) 1

Call 157686 hangs. 0x7ffff7fa7580 is the thread using Xlib, 0x7ffea7fef700 is the thread using GL.)

**Comment by TTimo** [comment]
closing old bug. please advise if this is still an issue in latest beta client
