### ISSUE TITLE
Proton not starting

### ISSUE THREAD

**Issue by DisturbingShibboleth** [ValveSoftware/steam-runtime#570]
None of my proton games, including DS2:SotFS (log attached) seem to load any more. I'm getting the attached output in stdout when running steam via the terminal, but even when I run games with PROTON_LOG=1 %command% the log file isn't generated. I'm not sure what's causing this but it's crippling a large potion of my library. This occurs with all of the proton versions I've tried including 7, Proton experimental and bleeding edge - any help would be greatly appreciated. Cheers
[steam-stdout.txt](https://github.com/ValveSoftware/Proton/files/10870660/steam-stdout.txt)

**Comment by kisak-valve** [comment]
Hello @DisturbingShibboleth, starting with Proton 5.13, Proton is run inside of the Steam Linux Runtime - Soldier container environment. The fact that no Proton log is generated on request strongly hints that there was a snafu before Proton had a chance to run.

This looks like the line of interest to ponder:
`x86_64-linux-gnu-capsule-capture-libs: code 0: gelf_getehdr(/usr/lib/dri/iHD_drv_video.so): invalid file descriptor
pressure-vessel-wrap[26373]: E: Child process exited with code 1`

This should be part of Pressure Vessel setting up the container environment, so I've transferred this issue report to the steam-runtime issue tracker. Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested information.

**Comment by DisturbingShibboleth** [comment]
Hey @kisak-valve, thanks for taking a look at this so quickly. I've updated to the `client_beta` branch of `Steam Linux Runtime - Soldier` but no luck. From poking around the steam-runtime repo I've re-ran steam with the `PRESSURE_VESSEL_VERBOSE` flag via `PRESSURE_VESSEL_VERBOSE=1 steam 2>&1 | tee ~/pressure-vessel.log` and re-ran -
[pressure-vessel.log](https://github.com/ValveSoftware/steam-runtime/files/10872404/pressure-vessel.log). Anything useful in there?
Cheers again

**Comment by RyuzakiKK** [comment]
@DisturbingShibboleth it seems like libcapsule is failing while capturing `/usr/lib/dri/iHD_drv_video.so`.

Probably `CAPSULE_DEBUG=all` should give us more insight about what is failing.

Can you please:
- Create a new temporary empty directory: `mkdir /tmp/foo`
- Execute `CAPSULE_DEBUG=all ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/libexec/steam-runtime-tools-0/x86_64-linux-gnu-capsule-capture-libs --provider / --container /tmp/foo --dest /tmp/foo no-dependencies:even-if-older:if-exists:if-same-abi:path:/usr/lib/dri/iHD_drv_video.so 2> ccl.log`
- Upload the resulting `ccl.log`

**Comment by RyuzakiKK** [comment]
I just realized that you didn't share your "Help -> System Information" from the Steam client.

To run `x86_64-linux-gnu-capsule-capture-libs` directly as I suggested you need to have a host system that is not older than Soldier (similar to Debian 10).

Otherwise you could launch Steam with `CAPSULE_DEBUG=tool` (`all` is very verbose) and try to run a game.

To grab the log you can use ` STEAM_LINUX_RUNTIME_LOG=1` instead of manually redirecting Steam's output. More info in https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information

**Comment by DisturbingShibboleth** [comment]
Hi @RyuzakiKK, thanks for taking a look at this. I've attached the 
[ccl.log](https://github.com/ValveSoftware/steam-runtime/files/10888660/ccl.log) file as well as the captured capsule logs for Dark Souls 2 ([slr-app335300-t20230304T141009.log](https://github.com/ValveSoftware/steam-runtime/files/10888827/slr-app335300-t20230304T141009.log)) and Noita ([slr-app881100-t20230304T141013.log](https://github.com/ValveSoftware/steam-runtime/files/10888824/slr-app881100-t20230304T141013.log))

VERSIONS.txt:
```
>>> cat VERSIONS.txt
#Name   Version         Runtime Runtime_Version Comment
depot   0.20230228.42394                        # Overall version number
pressure-vessel 0.20230227.0    scout           # pressure-vessel-bin.tar.gz
scripts 0.20230227.0                    # from steam-runtime-tools
soldier 0.20230228.42394        soldier 0.20230228.42394        # soldier_platform_0.20230228.42394/
```

[system-info.txt](https://github.com/ValveSoftware/steam-runtime/files/10888843/system-info.txt)

**Comment by DisturbingShibboleth** [comment]
Turns out it was just the so file that was corrupted:
```
>>> file /usr/lib/dri/iHD_drv_video.so
/usr/lib/dri/iHD_drv_video.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, missing section header
s at 42915600
```
`pacman -Fy iHD_drv_video.so` traced it back down to the `community/intel-media-driver 23.1.0-1` package, and after reinstalling the file looks fine, and games now run again:
```
>>> file /usr/lib/dri/iHD_drv_video.so
/usr/lib/dri/iHD_drv_video.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=31f0c7a0b52991c77f23870a13676a4bf125d746, stripped
```

Should have thought to check that first!
Cheers for your help
