### ISSUE TITLE
Request: Activate sniper runtime flag on other branches for our app

### ISSUE THREAD

**Issue by OatmealDome** [ValveSoftware/steam-runtime#571]
We have been using the sniper runtime flag for some time now on a testing branch, and it's been working quite well. We're now preparing to submit our initial build to Valve for review, so we'd like to have the flag activated on our other branches.

Our app id is `1941680`.

The branches we'd like the flag to be activated on are:

- `default`
- `development`

Thanks!

**Comment by smcv** [comment]
@TTimo, this looks like one for you

**Comment by TTimo** [comment]
Handled via email.
