### ISSUE TITLE
Testing custom mesa builds and ICDs.

### ISSUE THREAD

**Issue by cheako** [ValveSoftware/steam-runtime#574]
https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/101

I'm looking for howto instructions.  If you feel like it's important, then start from nothing and tell me how to get steam, what version I should use, and what I should see in the logs.

Thanks.

**Comment by cheako** [comment]
https://github.com/ValveSoftware/steam-runtime/issues/573

**Comment by smcv** [comment]
> I'm looking for howto instructions

Sorry, this is an issue tracker for reporting and fixing bugs in the Steam Runtime, not a tutorial on compiling and using a self-built copy of Mesa.

Is there some procedure that you have tried, which leads to "the right thing" happening for ordinary Linux games in your distro, but "the wrong thing" happening for games that run in the Steam container runtime?

**Comment by cheako** [comment]
There is a question about what copy of the driver is used.  Most git commits don't explicitly print a message making their use known.  Pressure vessel adds a layer of complexity, making this ambiguous.

Could I drop the driver off in `${HOME}/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu` and be assured that this is the driver that's used?

**Comment by smcv** [comment]
> Could I drop the driver off in ${HOME}/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu and be assured that this is the driver that's used?

No, that's not what that directory is used for.

The design goal for pressure-vessel is that whatever graphics driver is used for ordinary Linux games and other programs outside Steam (like if you install the mesa-utils or vulkan-tools package), pressure-vessel should set up the games in the container to use that same driver. If you set the appropriate environment variables to use your self-built drivers outside Steam, then pressure-vessel should find them too.

If you are trying to find out what graphics driver pressure-vessel is providing to the game, getting a log with `STEAM_LINUX_RUNTIME_LOG=1` as described in https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information will tell you a lot about what it's thinking, particularly if you also set `STEAM_LINUX_RUNTIME_VERBOSE=1`.

The output from the diagnostic tools that are run by Steam's Help -> System Information can also provide useful information about what drivers have been found.

Those are primarily intended for Steam and Steam Runtime developers (they provide the information we'll need if you report a bug where pressure-vessel is doing the wrong thing), but the same information will be more directly useful to you if you are not sure which driver is in use, even if you're not reporting a bug.
