### ISSUE TITLE
Corrupt update files

### ISSUE THREAD

**Issue by tpruzina** [ValveSoftware/steam-runtime#59]
Since yesterday I was unable to finish downloading game updates (cs:go, dota), they all seem to fail prior completion. Tried wiping $HOME/.local/share/Steam and reinstalling but to no avail (games seem to finish downloading and then fail to install).

<pre>depotreconstruct.cpp (490) : Assertion Failed: pInfo->nNumWritesFinished > 0
Assert( Assertion Failed: pInfo->nNumWritesFinished > 0 ):depotreconstruct.cpp:490

Installing breakpad exception handler for appid(steam)/version(1476379980)
crash_20161014193954_30.dmp[1101]: Uploading dump (out-of-process)
/tmp/dumps/crash_20161014193954_30.dmp
crash_20161014193954_30.dmp[1101]: Finished uploading minidump (out-of-process): success = yes
crash_20161014193954_30.dmp[1101]: response: CrashID=bp-ea76164e-bf3d-4127-b2da-f3a342161014
crash_20161014193954_30.dmp[1101]: file ''/tmp/dumps/crash_20161014193954_30.dmp'', upload yes: ''CrashID=bp-ea76164e-bf3d-4127-b2da-f3a342161014''
</pre>

Steam info
<pre>
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.8.0-linus-master+
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 370.28
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1200
    Primary Display Size: 20.91" x 11.73"  (23.94" diag)
                                            53.1cm x 29.8cm  (60.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC1150
    
Memory:
    RAM:  16036 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  C
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  228804 Mb
    Largest Free Hard Disk Block:  90888 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Fri Oct 14 17:22:58 2016 GMT: file ''/tmp/dumps/crash_20161014192256_32.dmp'', upload yes: ''CrashID=bp-a4b30db6-188e-4952-8724-d40b52161014''
    Fri Oct 14 17:39:55 2016 GMT: file ''/tmp/dumps/crash_20161014193954_30.dmp'', upload yes: ''CrashID=bp-ea76164e-bf3d-4127-b2da-f3a342161014''
    Fri Oct 14 17:54:58 2016 GMT: file ''/tmp/dumps/crash_20161014195456_37.dmp'', upload yes: ''CrashID=bp-4e21ec74-c76e-4e51-b58a-9e3d22161014''
</pre>

![screen](https://cloud.githubusercontent.com/assets/1160582/19397702/2f712f6c-9249-11e6-920b-1edf2d8f0f0c.png)

Update: Dota2 eventually finished installing just fine, CS:GO came up with this:
![screen](https://cloud.githubusercontent.com/assets/1160582/19397944/67a6d2be-924a-11e6-8d09-e24bda4c9d4b.png)

I installed dota on my external steamlibrary though (instead of my root SSD), will try to put CS:GO in there as well to see if it only breaks on my SSD (F2FS filesystem with over 100GB free space).

**Comment by Tele42** [comment]
Likely a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/4660.

**Comment by tpruzina** [comment]
@Tele42 Indeed it is, I searched before posting yet failed to spot that one. Closing. Nice catch.
