### ISSUE TITLE
Yakuza Kiwami won't launch, stuck on loading screen

### ISSUE THREAD

**Issue by RudeRussian** [ValveSoftware/steam-runtime#591]
#### Your system information

* Steam Runtime Version: IDK
* Distribution: 6.2.0-76060200-generic POP OS
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Proton 5.13+ (that's what the steamlinuxruntime_soldier said)
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`? (couldn't find this txt file, but I did find the _soldier file)

* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`? (I just copy pasted what it gave me below)

#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20230425.48609			# Overall version number
pressure-vessel	0.20230418.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20230418.0			# from steam-runtime-tools
soldier	0.20230425.48609	soldier	0.20230425.48609	# soldier_platform_0.20230425.48609/

#### Please describe your issue in as much detail as possible:

I'd like to preface this and say I am a complete newbie, I probably need major hand holding and help for this, but any respone or guidence towards the right direction will be much appreciated! I am trying to run Yakuza Kiwami, which shows a platnium on ProtonDB so I'd thought it would work by just downloading like I did with Elden Ring, yet, it doesn't want to launch. I reseted, looked over proton DB, but for some reason the fixes that they suggested I couldn't get to work because I could not run the codes in the terminal that they suggested or download some files. Any help is appreciated really, do I just go over download something? Do I hit a setting in steam? New system even?? If someone can give me a link to a guide I can possibly go to, or tell me what to download, I would really appreciate it, thank you!

**Comment by kisak-valve** [comment]
Hello @RudeRussian, in general, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2403#issuecomment-1559803264.

**Comment by smcv** [comment]
> stuck on loading screen

To confirm: if a game gets far enough to show a game-specific loading screen, then that usually means the Steam Linux Runtime is working correctly. If SLR is causing failure to launch a game, then that will usually happen before anything from this specific game has a chance to run.

**Comment by RudeRussian** [comment]
Sorry for the confusion. What happens is that I click "launch" and the game either is 1. stuck on the "preparing to launch Yakuza Kiwami" steam screen or 2. Takes me to a black screen for a second, exits me out, and cancels the application so I have to click "launch" again. So far, I have not played a single second of the game, just a black screen when hitting launch before exiting out.

**Comment by RudeRussian** [comment]
Did a little more research online, it seems to be a problem with either my Vulkan shaders of which I have both intel and NVIDIA, or something is up with the steam library and SLR like you mentioned. Unfortunately idk how to disable the intel Vulkan shader as had other users previously, so any help would be appreciated :3

**Comment by ItsRogueRen** [comment]
OMG I'M NOT ALONE!

I had this suddenly happen to me out of no where a week or so ago and have been trying to find ANYONE with the same issue!

I've tried moving the game between my main /home directory and an SSD both of which give the same result, deleted shaders, deleted the game and reinstalled, verified installed files, swapped between the deb package and the flatpak package for Steam, all of which did nothing to solve the issue. Yakuza is the only game affected by this as everything else I have runs perfectly as before, and Yakuza runs perfectly on my Steam Deck. 

If this is a SRL issue, that would be one of the only thing I've been unable to try

**Comment by smcv** [comment]
@ItsRogueRen: We can't do much with "it doesn't work", so if you suspect a Steam Linux Runtime issue, please collect the information requested in https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information and open a new issue.

However, if other Proton games work and it is only Yakuza Kiwami that does not, then that would suggest a game-specific issue, which is more likely to be Proton than the Steam Linux Runtime. A more typical symptom for a Steam Linux Runtime problem would be that it affects all Proton 5.13+ games equally.

**Comment by ItsRogueRen** [comment]
> @ItsRogueRen: We can't do much with "it doesn't work", so if you suspect a Steam Linux Runtime issue, please collect the information requested in https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information and open a new issue.
> 
> However, if other Proton games work and it is only Yakuza Kiwami that does not, then that would suggest a game-specific issue, which is more likely to be Proton than the Steam Linux Runtime. A more typical symptom for a Steam Linux Runtime problem would be that it affects all Proton 5.13+ games equally.

Neither of these apply though. Yakuza is only affected on my PC and not my Steam Deck which is running the same Proton version. I even dual-booted the same distro on my SD and no issue. So that doesn't sound like a Proton issue

But also it is only Yakuza that's affected, all my other games are fine. So then it isn't a SRL issue?

There's already an issue for Yakiza Kiwami and I've posted there with a log for Proton

**Comment by ItsRogueRen** [comment]
> 

I would have thought that too if I didn't have hours of stream VODs of it running perfectly on my desktop. This issue is baffling in every way imaginable with no consistency to debug from

**Comment by ItsRogueRen** [comment]
> > 
> 
> I would have thought that too if I didn't have hours of stream VODs of it running perfectly on my desktop. This issue is baffling in every way imaginable with no consistency to debug from

UPDATE: Pop!_OS on my Steam Deck can no longer launch Yakuza Kiwami. That's now a total of 3 systems on Pop!_OS unable to run the game with the distro being the only consistent variable.

This is looking like a Pop!_OS specific issue. If anyone reading this has Yakuza Kiwami and Pop!_OS please help confirm this theory
