### ISSUE TITLE
Scaling is broken in newest version of steam runtime

### ISSUE THREAD

**Issue by spacemanspliff024** [ValveSoftware/steam-runtime#594]
#### Your system information

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): 
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  
* Have you checked for system updates?: [Yes/No]
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton]
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by spacemanspliff024** [comment]
Your system information
Steam Runtime Version: 1686779606
Steam Client Build Date:  Wed, Jun 14 15:18 UTC -06:00
Steam Web Build Date:  Wed, Jun 14 16:41 UTC -06:00
Steam API Version:  SteamClient020
Distribution (e.g. Ubuntu 18.04): Arch Manjaro 6.2.16-2
Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/spacemanspliff024/ef9d634faea6b1e254f61c5897c427e2.js):
Have you checked for system updates?: Yes
What compatibility tool are you using?: Proton 8.0
If you are using Steam Linux Runtime for native Linux games: What versions are listed in SteamLinuxRuntime/VERSIONS.txt?
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20230405.0			# Overall version number
LD_LIBRARY_PATH	-	scout	-	# see ~/.steam/root/ubuntu12_32/steam-runtime/version.txt
scripts	0.20230405.0			# from steam-runtime-tools

If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in SteamLinuxRuntime_soldier/VERSIONS.txt?
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20230509.49491			# Overall version number
pressure-vessel	0.20230509.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20230509.0			# from steam-runtime-tools
soldier	0.20230509.49491	soldier	0.20230509.49491	# soldier_platform_0.20230509.49491/
Please describe your issue in as much detail as possible: the steam window no longer scales correctly based on the option "scale text and icons to match monitor settings (requires restart)".  Either on or off, the window scales to the same amount.  My desktop is scaled to 150% in Manjaro display settings but steam appears to be renderings at 100%. 

Also, unrelated, the system information and steam runtime diagnostics crash steam on my machine, not sure why.

Steps for reproducing this issue: Updated to latest version of client, launched client, scaling had changed.  Togling the option dokes nothing to change the window.,

**Comment by kisak-valve** [comment]
Hello @spacemanspliff024, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9209. Closing as a duplicate.
