### ISSUE TITLE
Apple OSX 10.13.6 Blank windows; others no max and min.

### ISSUE THREAD

**Issue by djearthquake** [ValveSoftware/steam-runtime#595]
![Screenshot from 2023-06-16 07-43-19](https://github.com/ValveSoftware/steam-runtime/assets/6540695/df417afb-cf92-445b-bff5-14e39e70c56e)

[Friends list is completely blank.](https://github.com/ValveSoftware/steam-for-linux/issues/8665)

Steam is unable to be used on this OS.  The friends list is on the left.

Further comment:
 _I was working and gaming fine until this update. Send e-mail notice if you are going to obsolete thousands of dollars of software on a per customer basis next time. We already experienced this when Steam came out. Still got the receipts when I spent 2k on parts that were useless a week later._

**Comment by kisak-valve** [comment]
Hello @djearthquake, in general, support for the Steam for Mac client is not handled on Github. Please use [Steam Support](https://help.steampowered.com) for feedback related to the Steam for Mac client.
