### ISSUE TITLE
games built for deck libstdc++ do not work with steam-runtime libstdc++

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#597]
steam-runtime libstdc++.so.6.0.21

game demo built for deck: selaco

c++ ABI crash if selaco demo is run with the current steam-runtime libstdc++.so.6.0.21

I did replace steam-runtime libstdc++.6.0.21 with libstdc++.6.0.24 (gcc 7.3).
The selaco demo runs fine (like on deck).

But wait, I did replace the steam-runtime libstdc++.6.0.21 with a "default build" libstdc++.6.0.30 from gcc 12, and the selaco demo does _NOT_ run.

I think we all know how much c++ ABI is toxic (always has been, but glibc devs are no much more honest than c++ gcc devs).

All that should not exist, and with the "-static-libgcc -static-libstdc++" compilation/linking options, all those issues should be gone.

I told the selaco guys, but they stay silent and don't statically link their binaries with libstdc++ and libgcc.

How you want to sync system libs compat between the deck and the steam runtime?

**Comment by kisak-valve** [comment]
Hello @sylware, https://github.com/ValveSoftware/steam-runtime/issues/383#issuecomment-804864428 is no less valid here. There's nothing further to ponder on this compared to the older issue report.

**Comment by sylware** [comment]
To mitigate the issue, deck games should be run in the steam runtime.

**Comment by sylware** [comment]
many games and major game engines started to statically link their libstdc++ and libgcc making all those issues go away.

Valve should do the same for its binaries.
