### ISSUE TITLE
Run Valve Deck games into the Steam runtime.

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#598]
Deck games must be run into the steam runtime to ensure developers use the right versions of SDK tools.

**Comment by kisak-valve** [comment]
Hello @sylware, my understanding is that this happens as part of the Steam Deck verification process and Linux native games. Closing as invalid.

**Comment by sylware** [comment]
Didn't know that. This is very good news.

**Comment by sylware** [comment]
going to warn the selaco guys.
