### ISSUE TITLE
With Steam as a Snap app, cannot run Proton games with Steam library in /media

### ISSUE THREAD

**Issue by 8836290** [ValveSoftware/steam-runtime#602]
# Compatibility Report
- Name of the game with compatibility issues: Tested two : Empyrion - Galactic Survival and Craft The World
- Steam AppID of the game: 383120 and 248390

## System Information
- GPU: GTX-1070
- Driver/LLVM version:  nVidia Latest Production Branch Version:[535.86.05](https://www.nvidia.com/Download/driverResults.aspx/209261/en-us/)
- Kernel version: 6.2.11-x64v3-xanmod1
-  [Link to full system information report as gist](https://gist.github.com/8836290/c1fef5e976fcaa3d4132dd54da79bed0)
- Proton version: Any 8.0-2, Experimental 7.0-6

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

 No /steam-$APPID.log is created whatsoever 

## Symptoms 
Can not start any game with any steam proton versions 8, 7 or experimental.

**Comment by kisak-valve** [comment]
Please give #586 a read for the majority of the issue you're seeing.

**Comment by 8836290** [comment]
> Please give #586 a read for the majority of the issue you're seeing.

So if I understand by reading #586  do I have to uninstall the snap version of steam and just download and install the.deb version and try this one?

**Comment by smcv** [comment]
@kisak-valve, perhaps you could retitle this to something like:

```
With Steam as a Snap app, cannot run Proton games with Steam library in /media
```

to avoid this issue being mixed up with other issues with the same symptom?

This is likely to be "won't fix" (or more accurately "can't fix") unless someone from Canonical can help.

**Comment by 8836290** [comment]
> > So if I understand by reading #586 do I have to uninstall the snap version of steam and just download and install the.deb version and try this one?
> 
> Yes please. If that solves the issue, please report it to https://github.com/canonical/steam-snap.
> 
> The key log line seems to be this:
> 
> ```
> bwrap: Can't bind mount /oldroot/media/myrmidon/Linux Games/Steam Library/steamapps/common/SteamLinuxRuntime_sniper/var/tmp-9T0171/usr on /newroot/usr: Unable to mount source on destination: Permission denied
> ```
> 
> This is a fatal error for the container runtime: if Snap will not allow us to do the setup that the container runtime requires, then there is not really anything that the container runtime can do to resolve that.

I installed the .deb version and steam site and the games run properly now. Thank you. I think we can close this issue as solved here.

**Comment by robstarmcdonald** [comment]
If you guys are complaining about steam snap won't always let you do anything, there is the way to fix that.

Please watch this video https://www.youtube.com/watch?v=r9tiyjKrQJ4
