### ISSUE TITLE
cmake sysroot

### ISSUE THREAD

**Issue by noncopyable** [ValveSoftware/steam-runtime#603]
hello everyone.

is it possible to use scout-sdk-sysroot (which was set to /var/chroots/steamrt_scout_amd64) as a toolchain for cmake without a schroot session? or is there a workaround for cmake cross-compiling? i managed to compile for windows with mingw, so there has to be a way for linux :)

toolchain-file.cmake
---
set(CMAKE_SYSTEM_NAME Linux)

set(DA__ROOT /var/chroots/steamrt_scout_amd64/)
set(CMAKE_SYSROOT ${DA__ROOT})
set(CMAKE_FIND_ROOT_PATH ${DA__ROOT})

set(DA__COMP ${DA__ROOT}usr/bin/)
set(DA__C    ${DA__COMP}gcc-9)
set(DA__CXX  ${DA__COMP}g++-9)

message(STATUS "sysroot c   ${DA__C}")
message(STATUS "sysroot c++ ${DA__CXX}")
set(CMAKE_C_COMPILER   ${DA__C})
set(CMAKE_CXX_COMPILER ${DA__CXX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
---

this one was unable to resolve compilers. if i force the compiler resolution somehow the compilers still failing to compile cmake-test-program.

thank  you.

**Comment by TTimo** [comment]
Hello,

We recommend using the docker images for the scout sdk instead of the older (and mostly obsolete) chroot artifacts. The SDK comes with an updated cmake.
