### ISSUE TITLE
Unable to set mode of "./bin" in "[...]" fchmod: Operation not permitted

### ISSUE THREAD

**Issue by mdrokz** [ValveSoftware/steam-runtime#606]
#### Your system information

* Steam Runtime Version: 0.20230606.5162
* Distribution (e.g. Ubuntu 18.04): Nobara Linux 37
* Link to your full system information [System Info](https://gist.github.com/mdrokz/e8c2dd940abd4bcd42f8ad6d67254041)
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Proton Experimental

#### Please describe your issue in as much detail as possible:
Hi im trying to use Proton experimental and proton 8.3 but i get this error everytime i launch any game 

```
pressure-vessel-wrap[157738]: E: Unable to set mode of "./." in "/run/media/mdrokz/md_data/Steam-Games/steamapps/common/SteamLinuxRuntime_sniper/var/tmp-NYBD91/usr": fchmod: Operation not permitted
```

i have mounted my drive with the following parameters 

```
UUID=222E77E72E77B281   /run/media/mdrokz/md_data       auto    nosuid,nodev,nofail,uid=10
00,gid=1000,rw,user,exec,x-gvfs-show,umask=000    0       0
```

**Comment by smcv** [comment]
What user ID are you running Steam as? Is it 1000 or something else?

> `auto`

What filesystem is this? Is it NTFS?

> `umask=000`

Those permissions are dangerous: if this gives your Steam library 0777 (`rwxrwxrwx`) permissions, then any other user (including reduced-privilege system users, not just human users!) can overwrite games in your Steam library with arbitrary code that will be run next time you try to launch the game.

**Comment by mdrokz** [comment]
> What user ID are you running Steam as? Is it 1000 or something else?
> 
> > `auto`
> 
> What filesystem is this? Is it NTFS?
> 
> > `umask=000`
> 
> Those permissions are dangerous: if this gives your Steam library 0777 (`rwxrwxrwx`) permissions, then any other user (including reduced-privilege system users, not just human users!) can overwrite games in your Steam library with arbitrary code that will be run next time you try to launch the game.

yes im running it as 1000 and the file system is NTFS, oh i didnt know about the permissions i saw these permissions on a article they were needed to allow steam to run games from NTFS hard drives

**Comment by smcv** [comment]
If you have some space on a Linux filesystem (ext4, btrfs, xfs or similar), the easy fix is to have a Steam library on that filesystem (the one Steam creates by default is suitable), and [move](https://help.steampowered.com/en/faqs/view/4BD4-4528-6B2E-8327#move) the "Steam Linux Runtime - soldier" and "Steam Linux Runtime - sniper" compatibility tools into a library on that filesystem. You can still install the actual games, which are much larger, onto the NTFS drive if you need to.

Installing Proton onto a Linux filesystem is also more likely to work than having it on NTFS.

Alternatively, if you're using `ntfs-3g` to mount NTFS filesystems, it is possible (or was possible in the past) to set up mount options that make it possible for the compatibility tools to work from a NTFS location, but it is likely to take some trial and error. The `permissions` or `silent` mount options might be helpful. See the `ntfs-3g(8)` man page for details.

> i saw these permissions on a article they were needed to allow steam to run games from NTFS hard drives

`umask=000` means "I don't care about security, just let anyone do anything", which does make things work, but isn't safe.

If the `uid` and `gid` are set to the user who will run Steam, then a safer mask like 022 or 027 should be sufficient.

**Comment by mdrokz** [comment]
> If you have some space on a Linux filesystem (ext4, btrfs, xfs or similar), the easy fix is to have a Steam library on that filesystem (the one Steam creates by default is suitable), and [move](https://help.steampowered.com/en/faqs/view/4BD4-4528-6B2E-8327#move) the "Steam Linux Runtime - soldier" and "Steam Linux Runtime - sniper" compatibility tools into a library on that filesystem. You can still install the actual games, which are much larger, onto the NTFS drive if you need to.
> 
> Installing Proton onto a Linux filesystem is also more likely to work than having it on NTFS.
> 
> Alternatively, if you're using `ntfs-3g` to mount NTFS filesystems, it is possible (or was possible in the past) to set up mount options that make it possible for the compatibility tools to work from a NTFS location, but it is likely to take some trial and error. The `permissions` or `silent` mount options might be helpful. See the `ntfs-3g(8)` man page for details.
> 
> > i saw these permissions on a article they were needed to allow steam to run games from NTFS hard drives
> 
> `umask=000` means "I don't care about security, just let anyone do anything", which does make things work, but isn't safe.
> 
> If the `uid` and `gid` are set to the user who will run Steam, then a safer mask like 022 or 027 should be sufficient.

Oh i see let me try to do that and i will also fix the `umask` permission. I will comment here after moving the runtimes and see if it launches the game and i dont think im using ntfs-3g to mount the drives let me confirm it.

**Comment by mdrokz** [comment]
So i moved the the runtime & proton to the linux drive and it is working now the games launch with proton experimental & proton 8.3 i also fixed the umask permission. Thanks for all the help!
