### ISSUE TITLE
blkid looks to flood kernel with unaligned transfer and I/O errors to sr0

### ISSUE THREAD

**Issue by Katana-Steel** [ValveSoftware/steam-runtime#611]
#### Your system information

* Steam Runtime Version: 2 and later (don't have scout installed)
* Distribution (e.g. Ubuntu 18.04):  Gentoo
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  [my system](https://gist.github.com/Katana-Steel/e6c8a806fd4612404b3b5d0361c90853)
  [runtime diagnostic too](https://gist.github.com/Katana-Steel/1f717e3dae643eb68357bc5130b352ac)
* Have you checked for system updates?: yes
* What compatibility tool are you using?: Steam Linux Runtime and Proton 5.13+
* If you are using Steam Linux Runtime for native Linux games: soldier and sniper
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: proton 7, 8, and experimental

#### Please describe your issue in as much detail as possible:
on steam startup and whenever I run a game [dmesg is flooded with sr0 and sr1 errors](https://gist.github.com/Katana-Steel/6270600bc2d07272bed4b8e2a762fab4)
these seem similar to an issue [fixed in blkid by redhat](https://bugzilla.redhat.com/show_bug.cgi?id=1787973)

#### Steps for reproducing this issue:

1.  start steam with any dvd/bluray drive present
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Katana-Steel, this is behavior coming from wine which was inherited by Proton and previously evaluated at https://github.com/ValveSoftware/steam-for-linux/issues/8002#issuecomment-902279809.

This is not a Steam runtime issue.

**Comment by Katana-Steel** [comment]
just so I understand, these won't need an update based on the [RH bugzilla report: 1787973](https://bugzilla.redhat.com/show_bug.cgi?id=1787973) and has to be fixed in wine?
```
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-35UT91/usr/lib/i386-linux-gnu/libblkid.so.1.1.0
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-35UT91/usr/lib/x86_64-linux-gnu/libblkid.so.1.1.0
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20230605.51440/files/lib/i386-linux-gnu/libblkid.so.1.1.0
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20230605.51440/files/lib/x86_64-linux-gnu/libblkid.so.1.1.0
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/var/tmp-OZAP91/usr/lib/i386-linux-gnu/libblkid.so.1.1.0
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/var/tmp-OZAP91/usr/lib/x86_64-linux-gnu/libblkid.so.1.1.0
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/sniper_platform_0.20230718.55074/files/lib/i386-linux-gnu/libblkid.so.1.1.0
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/sniper_platform_0.20230718.55074/files/lib/x86_64-linux-gnu/libblkid.so.1.1.0
```

**Comment by kisak-valve** [comment]
Based on that assumption, you could do a quick test.

Proton 8.0 and Proton Experimental are run inside the Steam Linux Runtime - Sniper container environment. The Steam Linux Runtime - Sniper container environment contains util-linux_2.36.1-8+deb11u1 package to provide libblkid. This is newer than 2.35 where the linked bug report was resolved (https://github.com/util-linux/util-linux/commit/dc30fd4383e57a0440cdb0e16ba5c4336a43b290).

If libblkid in Steam Linux Runtime - Soldier was the root cause, then only Proton 5.13 to 7.0 would leave these log lines in dmesg. Proton 8.0 and newer shouldn't misbehave in the same manner and you can watch for that while starting a game with Proton 8.0 to use as a data point to reinforce the hypothesis.

**Comment by mathew2214** [comment]
i am also getting this issue. 
system info gist: https://gist.github.com/mathew2214/afb01ad1d775a87ec0b1762dc5c415bc
