### ISSUE TITLE
Can't set STEAM_COMPAT_MOUNTS for all games at once.

### ISSUE THREAD

**Issue by lucasew** [ValveSoftware/steam-runtime#619]
#### Your system information
https://gist.github.com/lucasew/ee0d1b50ed535a534e87fe27c6e326e4

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): 
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/): 
* Have you checked for system updates?: Yes

* What compatibility tool are you using?: Proton latest
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`?
```
#Name   Version         Runtime Runtime_Version Comment
depot   0.20230605.0                    # Overall version number
LD_LIBRARY_PATH -       scout   -       # see ~/.steam/root/ubuntu12_32/steam-runtime/version.txt
scripts 0.20230605.0                    # from steam-runtime-tools
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name   Version         Runtime Runtime_Version Comment
depot   0.20230808.56728                        # Overall version number
pressure-vessel 0.20230804.0    scout           # pressure-vessel-bin.tar.gz
scripts 0.20230804.0                    # from steam-runtime-tools
soldier 0.20230808.56728        soldier 0.20230808.56728        # soldier_platform_0.20230808.56728/
```

* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`?
```
#Name   Version         Runtime Runtime_Version Comment
depot   0.20230808.56699                        # Overall version number
pressure-vessel 0.20230804.0    scout           # pressure-vessel-bin.tar.gz
scripts 0.20230804.0                    # from steam-runtime-tools
sniper  0.20230808.56699        sniper  0.20230808.56699        # sniper_platform_0.20230808.56699/
```

#### Please describe your issue in as much detail as possible:

I am working on a tool to [backup and unify savegames across the system](https://github.com/lucasew/cloud-savegame). Kind of like Steam Cloud, but for any game that has the rule. One of it's features is backlinks. This creates a symlink on the game folder pointing to the unified repository.

By default Proton and the Steam Runtime allows the game to access it, but not write. I already found a fix for that using the `STEAM_COMPAT_MOUNTS` in the game launch options and it works nicely, but I have to do that with all the games.

Is there either some way to define this variable for all games at once or some script that gets sourced by the runtime that I can patch to set this variable at the right time so it can work out of the box?

I also tried launching steam on a terminal window with the variable behind, like `STEAM_COMPAT_MOUNTS=/home/lucasew/SavedGames steam`, but it didn't work.

Related issue: https://github.com/ValveSoftware/steam-runtime/issues/470

#### Steps for reproducing this issue:

1. Realise that you need to set an environment variable (in my case `STEAM_COMPAT_MOUNTS`) for all games.
2. Realise that there is no way to set it for all games at once.

**Comment by kisak-valve** [comment]
Hello @lucasew, this is functionally the same as https://github.com/ValveSoftware/steam-for-linux/issues/3453. Closing as a duplicate.
