### ISSUE TITLE
Steam Linux Runtime can't use Steam library below /etc

### ISSUE THREAD

**Issue by tintinmaster** [ValveSoftware/steam-runtime#621]
#### Your system information

* System information from steam in a [gist](https://gist.github.com/tintinmaster/9111b3c7a6e2359556da0c6feec80368): 
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
CS2 does not start after pressing play.
No change in Screen
[Console output](https://gist.github.com/tintinmaster/2b4a35ae1d3ff42219036050d6758c15).

#### Steps for reproducing this issue:

1. Press Play
2. ???
3. No Profit

**Comment by kisak-valve** [comment]
Hello @tintinmaster, `bwrap: Can't chdir to /etc/steam/steamapps/common/Counter-Strike Global Offensive: No such file or directory` is the key detail in your log.

Counter-Strike 2 is run in the Steam Linux Runtime 3.0 (Sniper) container environment and there's a handful of folders that can't sanely be used as Steam Library folders and setup in the container environment like #288. I expect /etc/* is another example of that and you should reconfigure the mount point you use with that secondary library folder location.

**Comment by tintinmaster** [comment]
Changed the mount point and now it starts 🥳
Only the sound is not working properly 😅 But there are already workarounds/solutions on the issue-tracker

**Comment by smcv** [comment]
> Counter-Strike 2 is run in the Steam Linux Runtime 3.0 (Sniper) container environment and there's a handful of folders that can't sanely be used as Steam Library folders and setup in the container environment like https://github.com/ValveSoftware/steam-runtime/issues/288. I expect /etc/* is another example of that

I confirm, `/etc` is not suitable for this use.

@kisak-valve, please could you retitle this to "Steam Linux Runtime can't use Steam library below /etc"? And after that we should probably close it as "won't fix".

**Comment by smcv** [comment]
https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/shared-paths.md?ref_type=heads is the reference for which paths get what treatment.

Ideally the Steam client should just not let you put a library below `/etc` or `/usr`, but the runtime does not have control over the client's behaviour, so that isn't something that can be fixed here. I've opened https://github.com/ValveSoftware/steam-for-linux/issues/10096 for that.
