### ISSUE TITLE
Counter-Strike: Source doesn't launch

### ISSUE THREAD

**Issue by NishiyamaPedro** [ValveSoftware/steam-runtime#625]
#### Your system information

* Steam Runtime Version: steam-runtime_0.20230919.60656
* Distribution: Artix Linux 
* Link to your full system information: https://gist.github.com/NishiyamaPedro/4e65b542c7baa9f852371c845f9ddcea
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`?
```
depot 0.20230605.0 # Overall version number
LD_LIBRARY_PATH - scout	- # see ~/.steam/root/ubuntu12_32/steam-runtime/version.txt
scripts 0.20230605.0 # from steam-runtime-tools
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
depot	0.20230921.60881			# Overall version number
pressure-vessel	0.20230919.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20230919.0			# from steam-runtime-tools
soldier	0.20230921.60881	soldier	0.20230921.60881	# soldier_platform_0.20230921.60881/
```
#### Please describe your issue in as much detail as possible:
When trying to open CSS with a fully update system it just crashes.
If you preload `libtcmalloc_minimal.so.4` from the system the crash does not happen.

Steam Runtime log: https://gist.github.com/NishiyamaPedro/5569f6d49597968ba1fc54a7a48a33be

#### Steps for reproducing this issue:

1. Try opening the CSS on an updated system.
2. Game crashes.

**Comment by kisak-valve** [comment]
Hello @NishiyamaPedro, this is not a Steam Linux Runtime issue and is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/5043.

Closing as a duplicate.
