### ISSUE TITLE
Using the sniper runtime on a branch

### ISSUE THREAD

**Issue by Pentarctagon** [ValveSoftware/steam-runtime#628]
Coming back to the later parts of the discussion from #508 - has there been any update on being able to choose to use the Sniper runtime from within Steamworks in some way?

**Comment by smcv** [comment]
@TTimo, this seems like a question for you.

**Comment by TTimo** [comment]
No this isn't exposed to dev partners at this time.

**Comment by Pentarctagon** [comment]
Alright, in that case can all of the Battle for Wesnoth branches be set to use the Sniper runtime?

**Comment by TTimo** [comment]
Ok this is done now.

**Comment by Pentarctagon** [comment]
Thanks!
