### ISSUE TITLE
[pressure vessel] /etc/asound.conf

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#631]
The provider /etc/asound.conf should be imported, because provider system integrators may have configured their software mixer PCM to be the canonical default in /etc/asound.conf, namely [jack/pulseaudio2(pipewire)/pulseaudio1] alsa PCM plugin.

**Comment by kisak-valve** [comment]
Hello @sylware, this issue is already being tracked at #344. See the response at https://github.com/ValveSoftware/steam-runtime/issues/344#issuecomment-754162862.

Closing as a duplicate.
