### ISSUE TITLE
Steam non-responsive after device sleep-wake up cycle

### ISSUE THREAD

**Issue by Gift-505** [ValveSoftware/steam-runtime#634]
#### Your system information

* Steam Runtime Version: 1702079146
* Distribution (Windows 11 23H2): 
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/): https://gist.github.com/Gift-505/aa5418e1de05a477846155c3cbe65b14
* Have you checked for system updates?: [Yes]
* What compatibility tool are you using?: [None]
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`? Not using Linux
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`? Not using Linux
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`? Not using Linux

#### Please describe your issue in as much detail as possible:
Whenever steam is running in the background (window closed) if the device goes to sleep and then wakes up, steam hangs and is not visible in background tasks. The only way this can be solved is to kill Steam in task manager and then launch Steam again. Interestingly, this doesn't seem to happen when the window is open while the device goes to sleep-

#### Steps for reproducing this issue:

1. Close steam to background
2. Put device to sleep
3. Wake device from sleep

**Comment by kisak-valve** [comment]
Hello @Gift-505, you've come across an issue tracker for a couple sets of common Linux runtime libraries for games to be developed against. The issues with the Steam for Windows client isn't tracked on Github.

Please report this issue to [Steam Support](https://help.steampowered.com).
