### ISSUE TITLE
CSGO 2 crashes on vulkan code with linux runtime 3 (sniper) . Linux mint 20.3 

### ISSUE THREAD

**Issue by personnumber3377** [ValveSoftware/steam-runtime#635]
#### Your system information

* Steam Runtime Version: 3.0 (sniper)
* Distribution (e.g. Ubuntu 18.04): Linux Mint 20.3
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/):  https://gist.github.com/personnumber3377/419c717c0fd235697f5fcbef3cae0442
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20230928.0			# Overall version number
LD_LIBRARY_PATH	-	scout	-	# see ~/.steam/root/ubuntu12_32/steam-runtime/version.txt
scripts	0.20230928.0			# from steam-runtime-tools
```

* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20231107.66294			# Overall version number
pressure-vessel	0.20231107.1	scout		# pressure-vessel-bin.tar.gz
scripts	0.20231107.1			# from steam-runtime-tools
soldier	0.20231107.66294	soldier	0.20231107.66294	# soldier_platform_0.20231107.66294/
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20231107.66301			# Overall version number
pressure-vessel	0.20231107.1	scout		# pressure-vessel-bin.tar.gz
scripts	0.20231107.1			# from steam-runtime-tools
sniper	0.20231107.66301	sniper	0.20231107.66301	# sniper_platform_0.20231107.66301/
```

#### Please describe your issue in as much detail as possible:
https://gist.github.com/personnumber3377/e7b12e3d7876f406b32d4e46dbb2c07c

If you are using Proton or one of the Steam Linux Runtime compatibility
tools, please provide the information requested here:
https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md
-->

#### Steps for reproducing this issue:

1. Start CSGO 2 with the sniper linux runtime.
2. Observe crash.
3.

**Comment by kisak-valve** [comment]
Hello @personnumber3377, the Intel Sandybridge generation GPU does not support Vulkan. You're seeing a hardware limitation instead of a Steam runtime issue. Sorry, but this isn't fixable without adding Vulkan capable hardware.

**Comment by personnumber3377** [comment]
Hi! I downloaded nvidia drivers for my linux PC and I still crash in the vulkan code section, except now I get a stacksmashing detected error instead of just a core dumped: https://gist.github.com/personnumber3377/4d73de606921dd615cc1c215b7fa261f 

Here is the steam diagnostic information: https://gist.github.com/personnumber3377/18a386f41f5ad02acbfd8eaf1fca1c2e

Here is the gdb output: https://gist.github.com/personnumber3377/ae76b06911170a16cfb9c781927fb36a

I have the nvidia gt 440 graphics card, but I am not sure that it supports this game. Is it possible to play cs2 with this setup or can I downgrade to an earlier version of counter strike to play?

**Comment by kisak-valve** [comment]
Hello again, an NVIDIA GT 440 is part of of the Fermi generation. There is no Vulkan driver support for the Fermi hardware generation.

Regarding stack smashing, that issue is being tracked at #420.

**Comment by personnumber3377** [comment]
So it's not possible to play cs2 with this configuration? Thanks for the quick responses!
