### ISSUE TITLE
Please enable sniper runtime flag for the "beta" and "releasecandidates" branches of DDraceNetwork (412220)

### ISSUE THREAD

**Issue by heinrich5991** [ValveSoftware/steam-runtime#654]
I was redirected here from https://gitlab.steamos.cloud/steamrt/steamrt/-/issues/29#note_136027:

Could you enable the sniper runtime flag for the "beta" and "releasecandidates" branches of DDraceNetwork (412220)? The current version of DDNet which I co-maintain doesn't launch on Steam with the upcoming release because it requires a newer libcurl than provided by the old SDK: https://github.com/ddnet/ddnet/issues/7917.

**Comment by smcv** [comment]
@TTimo ^

**Comment by TTimo** [comment]
this should be done now

**Comment by heinrich5991** [comment]
Works, thanks!

**Comment by heinrich5991** [comment]
@TTimo Could you enable sniper for the default branch as well?

**Comment by TTimo** [comment]
@heinrich5991 to clarify - do you want sniper by default everywhere? e.g. no branch selection just sniper. (that's usually where we'd recommend to go once you're happy with the testing)

**Comment by heinrich5991** [comment]
Yes, please.

sniper by default everywhere.

**Comment by TTimo** [comment]
done
