### ISSUE TITLE
Request: Activate sniper runtime flag for appid 2840300

### ISSUE THREAD

**Issue by rubenlg** [ValveSoftware/steam-runtime#655]
Could you please enable "sniper" for my game demo in the testing branch?

- I already built my game demo in the sniper docker instance. 
- I tested the demo with the [snipper run script](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/slr-for-game-developers.md#launching-non-steam-games-in-a-steam-linux-runtime-container) both on Ubuntu 23.10 as well as Ubuntu 18.04. On Ubuntu 18.04 in particular it only runs when initiated with the runtime, due to the glibc version (as expected).
- The app ID of the demo: 2840300 (Shadows of the Afterland Demo)
- The branch is called "test"

I plan to follow up quickly with another request for the default branch if it works well on the testing branch, which is the most likely outcome, in case you want to keep this issue open in the meantime.

Thank you!

**Comment by rubenlg** [comment]
Nevermind, I had a support request open for the same thing before I learned that requests had to be made through github, and someone named Jason already enabled sniper for both the demo and the full game, on the default branch. I tested and it's working, so this is done.

**Comment by TTimo** [comment]
Ah, the way it usually works is I pick these up here and forward them to Jason anyway.
