### ISSUE TITLE
Problem with installing or updating Dota 2(missing update files)

### ISSUE THREAD

**Issue by PenguiN560** [ValveSoftware/steam-runtime#67]
Hello, have a problem with installing Dota 2 at Gentoo ~amd64. Other games installing and updating without any problems, for example Portal 2, Dont Starve Together and some other tested games. Steam support gave this link for send this problem and try to get your help. 

What I try before:
1. Delete Dota 2 content from Steam, check clean in SteamLibrary folder and reinstall: fail
2. Check partition for errors - no errors, one more try to install: fail
3. Clear Download Cache, one more try to install: fail
4. $ steam --reset, one more try to install: fail
5. try to change region for downloading, one more try to install: fail
6. ???, one more try to install: fail
7. install from LiveUSB Ubuntu - ok. Reboot in my installed Gentoo - Success. It run and it work on my Gentoo, before came new update...
8. Try to update Dota2 on gentoo: fail...

So what libraries and what versions of it are needed for successful install or update Dota2, but not needed for other games, or what can be wrong? Repeat, all other games that i installed or updated are ok on my Gentoo. Problem detected only with missing update files Dota2

**Comment by kisak-valve** [comment]
Hello @PenguiN560, let's continue this at https://github.com/ValveSoftware/steam-for-linux/issues/4834.
