### ISSUE TITLE
steamwebhelper p-v-adverb: error while loading shared libraries: libdl.so.2

### ISSUE THREAD

**Issue by vochant** [ValveSoftware/steam-runtime#670]
#### System information

* Steam client version: 1.0.0.79 from apt
* Distribution: Ubuntu 22.04LTS (Updated from NOI Linux)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steams-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15263375/steams-logs.tar.gz)
* GPU: NV137 / Mesa Intel(R) UHD Graphics (ICL GT1)

#### Details
I installed steam from apt (and i got a same error when using the package from .deb file). When i try to run it, i will get a dialog shows "steamwebhelper is not responding." I tried to disable GPU Acceleration or disable Browser Sandboxing, but the problem still exists.

I confirm that there are no issues with system runtime libraries, whether it is 32-bit or 64 bit.

`steamwebhelper.log` shows that `pressure-vessel-adverb` cannot find `libdl.so.2`, but both `locate` and `whereis` can find it, and `ldd` shows nothing was not found.

#### Steps for reproducing this issue:

I don't know why it will happen on my computer, maybe you cannot reproduce it on your computer.

1. Install Steam Linux
2. Run it.

**Comment by vochant** [comment]
[webhelper.txt](https://github.com/ValveSoftware/steam-runtime/files/15263756/webhelper.txt)

**Comment by vochant** [comment]
@kisak-valve Do you need more informations like dump file?

**Comment by smcv** [comment]
> webhelper.txt

We'll probably need to see `steamwebhelper.log`, not `webhelper.txt` (but it's safest if you just attach both).

> with `STEAM_LINUX_RUNTIME_LOG=1`

Instead of `STEAM_LINUX_RUNTIME_LOG`, please use `STEAM_LINUX_RUNTIME_VERBOSE=1`.

**Comment by smcv** [comment]
> * Distribution: Ubuntu 22.04LTS

I cannot reproduce this issue on an Ubuntu 22.04 test system.

> (Updated from NOI Linux)

Switching between different distros in-place is not usually something that can be supported. The process of upgrading from NOI Linux to Ubuntu 22.04 might have left your system in an unusual state.

To be able to make any progress on this issue report, we will need to see a detailed log as requested in my previous comment.

**Comment by smcv** [comment]
@kisak-valve, is there a "needs info" label that you can attach to issues that are waiting for more info from the issue reporter?

**Comment by vochant** [comment]
Sorry, i cannot provide any more information because i reinstalled my system, and the problem hasn't happened again. About NOI Linux, strictly speaking, this is not an independent distribution, but simply an adjustment to Ubuntu of some software.

There is a backup before reinstalling the system: <https://pan.huang1111.cn/s/K28KsY>

The problem may arise during the system upgrade process, where an unexpected shutdown resulted in the coexistence of old and new versions of files, but the problem only occurred on a very small number of applications. I reinstalled NOI Linux and updated to Ubuntu 22.04LTS, but this problem hasn't happened again.

This is likely not a bug.
