### ISSUE TITLE
Worms W.M.D is unplayable on Steam Runtime

### ISSUE THREAD

**Issue by robstarmcdonald** [ValveSoftware/steam-runtime#671]
OS -> Ubuntu 24.04 LTS (Linux Kernel 6.8)
Steam runtime app -> Steam Linux runtime 1.0 (scout)

When I tried few workaround for this game as a Linux native, yes even I do some research here https://gist.github.com/sxiii/9d9b8435fd343b2024b16b8cbe86a69e to find a solution. Unfortunately, none of those workaround helped the game to be playable at all.

I hope this game on Linux native has Steamworks common redistributables to fix this problem.

It used to be playable on Linux natively just fine back in the day until later on, it's no longer playable and many people are complaining about it.

**Comment by smcv** [comment]
> Steam runtime app -> Steam Linux runtime 1.0 (scout)

If you *don't* force use of Steam Linux runtime 1.0 (scout), does it work?

Please attach information about your system and whatever logs you can obtain.

**Comment by smcv** [comment]
> I hope this game on Linux native has Steamworks common redistributables

I think you're confused about the role of the "Steamworks common redistributables" tool: it is a helper for Windows games (on Windows, or running on Linux via Proton) and is not involved with running native Linux games.

**Comment by smcv** [comment]
> It used to be playable on Linux natively just fine back in the day until later on, it's no longer playable

This could be a sign that the game developer compiled or packaged it in a way that happened to work work at the time on at least "most" systems, but was not future-proof. The Steam Runtime tries to provide a stable runtime environment for native Linux games, but it cannot work miracles.

> `export LD_LIBRARY_PATH="/usr/lib:/usr/local/lib"`

Is this part of a workaround that has been suggested by the community, or is it part of the original `Run.sh`?

If it's part of the original `Run.sh`, then that indicates that this title is intentionally bypassing the Steam Runtime (which is unsupportable).

**Comment by robstarmcdonald** [comment]
> > I hope this game on Linux native has Steamworks common redistributables
> 
> I think you're confused about the role of the "Steamworks common redistributables" tool: it is a helper for Windows games (on Windows, or running on Linux via Proton) and is not involved with running native Linux games.

I'm not confused.

**Comment by robstarmcdonald** [comment]
> > Steam runtime app -> Steam Linux runtime 1.0 (scout)
> 
> If you _don't_ force use of Steam Linux runtime 1.0 (scout), does it work?
> 
> Please attach information about your system and whatever logs you can obtain, with any local workarounds reverted (you might find it useful to reinstall the game or [verify integrity of the game files](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB). If you are starting from an unknown situation with unknown workarounds, it will be difficult to tell whether those workarounds are helping or whether they are making matters worse.

No, it won't work at all.

**Comment by robstarmcdonald** [comment]
I'm closing this due to found issues for Windows Version with Proton GE.

**Comment by robstarmcdonald** [comment]
I'm closing this, because I no longer need this to be fixed due to Windows version I found the way to fix the issues such as team 17 logo and Worms W.M.D logo on wmv based on mp4 code.

Go see me here https://steamcommunity.com/app/327030/discussions/0/4353369676737256686/
