### ISSUE TITLE
This is more like suggestion instead of issue - problem with GE-Proton solution is similar to umu-proton

### ISSUE THREAD

**Issue by rairay91** [ValveSoftware/steam-runtime#677]
When i run a game with native umu-proton the launcher automatically check for update for latest umu-proton release, if there is a new release umu download it and create a link umu-latest/umu-proton whatever to that version and delete old. Now my issue is that for working with ge-proton which is more uptodate and have more patches/fixes than umu-proton, i have to manage it manually. Umu download latest version automatically at first boot but keep older version and do not create a link to the latest ge-proton just like it does to latest umu-proton.
So at the end umu should also download and create GE-Proton link to the latest downloaded GE-Proton in the same directory as it does to the latest umu-proton and should delete older version unless i assigned umu to use a specific version of proton.
Why downloading latest version of ge-proton then creating a link to that in the same directory and deleting previous version is important?
Because it eliminates the overhead of managing this manually.
And to be honest keeping older version of ge-proton is not necessary because i haven't ever noticed if we need to keep older ge-proton. Even if there is a game that need old version of ge-proton, we can do it manually.

**Comment by kisak-valve** [comment]
Hello @rairay91, both of these are downstream forks of Proton. This feedback should be directed at the maintainers of the forks.
