### ISSUE TITLE
Using Vulkan in a Steam Runtime 3 (sniper) toolbox container fails with error message "Found no drivers!"

### ISSUE THREAD

**Issue by tillmann** [ValveSoftware/steam-runtime#678]
#### Your system information

* Steam Runtime Version: Steam Runtime 3 (sniper) BUILD_ID: 0.20240423.85483
* Distribution (e.g. Ubuntu 18.04): Fedora Linux 40.20240703.0 (Silverblue)
* Link to your full system information (Help -> Steam Runtime Diagnostics): https://gist.github.com/tillmann/e2b7b876373e632975d3b101df84d5d0 (probably only relevant for the hardware-specs?)
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* I try to follow https://gitlab.steamos.cloud/steamrt/sniper/sdk/-/blob/steamrt/sniper/README.md

#### Please describe your issue in as much detail as possible:

Using Vulkan in a Steam Runtime 3 (sniper) toolbox container fails with error message "Found no drivers!"

I create and enter a toolbx container like this:

```bash
podman pull registry.gitlab.steamos.cloud/steamrt/sniper/sdk
toolbox create -i registry.gitlab.steamos.cloud/steamrt/sniper/sdk sniper
toolbox enter sniper
```

I want to use Vulkan inside the container. To do a sanity check, I run `vulkaninfo`. I expect valid output similar to running (on the host)
```
flatpak install org.freedesktop.Platform.VulkanInfo
flatpak run org.freedesktop.Platform.VulkanInfo
```
(Output in this [Gist](https://gist.github.com/tillmann/ff41bbb595c6462f5dd911a0a833a417))

However, if I run `vulkaninfo` inside the toolbx-container above, I get the following: 

```
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:674:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```

I tried installing `mesa-vulkan-drivers` and rerun `vulkaninfo` inside the toolbx-container which gives the following:
```
WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /usr/lib/x86_64-linux-gnu/libvulkan_intel.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so supports Vulkan 1.1, but only supports loader interface version 1. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_MESA_device_select uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Driver /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so supports interface version 1 but still exposes VkSurfaceKHR create/destroy entrypoints (Policy #LDP_DRIVER_8)
amdgpu: unknown (family_id, chip_external_rev): (148, 10)
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Call to ICD 0's 'vkEnumeratePhysicalDevices' failed with error 0xfffffffd
ERROR at ./vulkaninfo/vulkaninfo.h:237:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
```

This feels like a major corner-case to me, but I also expected it to "just work"™. Is sniper simply too old for my gpu? If I wanted to adopt a container-centric linux-first development-environment do develop a game targeted to steam/steamdeck, would there be a more promising approach?

#### Steps for reproducing this issue:

0. Have podman and toolbx installed and possibly a fairly new gpu
1. `podman pull registry.gitlab.steamos.cloud/steamrt/sniper/sdk`
2. `toolbox create -i registry.gitlab.steamos.cloud/steamrt/sniper/sdk sniper`
3. `toolbox enter sniper`
4. `vulkaninfo`

**Comment by tillmann** [comment]
I think I just answered parts of my question. Running my baseline check using flatpak on (the oldest) branch 20.08 of org.freedesktop.Platform.VulkanInfo gives the exact same error message. 

The question for the more promising approach remains, would I have to wait for medic? A pointer towards a sensible approach would be much appreciated :)

**Comment by smcv** [comment]
https://partner.steamgames.com/doc/steamdeck/loadgames describes a recommended way to test games on Deck.

**Comment by tillmann** [comment]
Thanks a bunch! Great clarification. That's way more than I could have asked for!

I'll just close this. :+1:
