### ISSUE TITLE
ALSA with dsp - no sound in games run through proton and some native games

### ISSUE THREAD

**Issue by xeaal** [ValveSoftware/steam-runtime#681]
#### Your system information

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): Void Linux
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/): https://gist.github.com/xeaal/861117407632207081af724b7f5b2e4c
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime, Proton 5.13+
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`? -
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20240618.92327			# Overall version number
pressure-vessel	0.20240610.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20240610.0			# from steam-runtime-tools
soldier	0.20240618.92327	soldier	0.20240618.92327	# soldier_platform_0.20240618.92327/
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20240618.92328			# Overall version number
pressure-vessel	0.20240610.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20240610.0			# from steam-runtime-tools
sniper	0.20240618.92328	sniper	0.20240618.92328	# sniper_platform_0.20240618.92328/
```

#### Please describe your issue in as much detail as possible:
I am running Void Linux with pure ALSA for sound. I am also using a specific plugin - [dsp](https://github.com/bmc0/dsp), for systemwide eq (alsaequal is a no go, for several reasons). The problem I'm having is that with that plugin enabled I don't have sound in proton powered games (for example, Noita) and some native games as well (Descenders). Steam client also has no sound. In output it gives these errors:
```
ALSA lib pcm_ladspa.c:1509:(snd_pcm_ladspa_add_plugin) Unable to find or load plugin 'ladspa_dsp:epz' ID 0, path '/usr/lib/ladspa'
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
```
If I launch steam and a game the first thing the system launches I actually get the sound but then there is no sound anywhere else, alsa gives an error "device or resource is busy". It also probably doesn't use the plugin, but I wasn't able to actually check if equalizer is in effect in this case.
So it's obvious that the problem is game running in a container and thus not being able to load the plugin I'm using. Where do I have to put this plugin in SteamLinuxRuntime directory so that it can load it? Or how do I make /usr/lib/ladspa_dsp/ladspa_dsp.so visible to it without copying files?

Here are steam and proton logs:
https://gist.github.com/xeaal/94ebcefa66ff18acf4ba6434d22cc3bf
https://gist.github.com/xeaal/7c755eafe7f01dcdf9fae0ad1acb2016

For some reason `STEAM_LINUX_RUNTIME_LOG=1 steam` didn't create log in `/var/log` and `STEAM_LINUX_RUNTIME_VERBOSE=1 steam 2>&1 | tee ~/slr.log` only outputs a few lines (it doesn't normally, if steam is launched without these parameters), but you can see the error I pointed out previously in proton log.

#### Steps for reproducing this issue:

1. Use ALSA without PulseAudio or PipeWire
2. Use [dsp](https://github.com/bmc0/dsp) plugin
3. Run any game via proton

**Comment by smcv** [comment]
Sorry, loading plugins from the host system into the container's library stack is not supported. The whole point of the container is to give games a library stack that's predictable and does not vary with the host OS, but then that library stack has neither the necessary dependencies to load the host system's plugins, nor direct access to the plugins themselves.

PulseAudio (or pipewire-pulse providing a PulseAudio-compatible socket) is the recommended way to get audio out of the container. This runs the audio service (which does the actual audio device access) fully outside the container, and client programs communicate with it via a backwards- and forwards-compatible protocol, so the result is similar to an audio equivalent of X11 or Wayland.

ALSA dmix can also work in some cases, but it's not clear exactly how it works behind the scenes, and user-defined plugins like ladspa_dsp certainly will not work.
