### ISSUE TITLE
steamwebhelper: bwrap: Can't make symlink at /var/lib/dbus/machine-id: destination exists and is not a symlink

### ISSUE THREAD

**Issue by Panda-Code-Master** [ValveSoftware/steam-runtime#688]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16509729/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD : AMD Lucienne [Integrated]

#### Steps for reproducing this issue:

1. Download latest steam deb / install using steam-installer from apt 
2. launch steam 
3. get error for steam webhelper always crashing

**Comment by Panda-Code-Master** [comment]
> This looks like a Steam Linux Runtime issue (@kisak-valve, you could move it to https://github.com/ValveSoftware/steam-runtime/ if you want).
> 
> @Panda-Code-Master, we will need more information to be able to solve this. Please try running the updated version of Steam (the one that doesn't work) as:
> 
> ```
> STEAM_LINUX_RUNTIME_VERBOSE=1 steam
> ```
> 
> Let it try to start the `steamwebhelper` for a while (for instance wait until the error dialog pops up), then provide your `~/.steam/steam/logs/webhelper-linux.txt` as a Gist or attachment. It will contain environment variables, so if you have any environment variables with secret content (`GITHUB_TOKEN` or similar), please censor them by replacing their values with a placeholder like `xxxx`.
> 
> I was unable to reproduce the issue with either of the common configurations for `/var/lib/dbus/machine-id` (either a copy of `/etc/machine-id`, or a symlink to `/etc/machine-id`).

i did as told with ```STEAM_LINUX_RUNTIME_VERBOSE=1 steam```  here is the new logs 
[steam-logs.tar.gz](https://github.com/user-attachments/files/16531650/steam-logs.tar.gz)

**Comment by smcv** [comment]
Here's the culprit:

`pressure-vessel-wrap[44395]: D: 	'XDG_DATA_DIRS=/home/pranav/.local/share/flatpak/exports/share:/var/lib/:/var/local:/usr/local/share/:/usr/share/:/var/lib/flatpak/exports/share'`

This will make pressure-vessel try to make the host system's `/var/lib` and `/var/local` available inside the container, but then when it's time to set up `/var/lib/dbus/machine-id`, it can't do that. We should make the container runtime more robust against this, by making it refuse to do things that won't work.

Workaround: run Steam with `/var/lib` (and probably also `/var/local`) removed from your `XDG_DATA_DIRS`.

Why are those two directories in your `XDG_DATA_DIRS` to begin with? This is not a typical configuration for Debian.

**Comment by Panda-Code-Master** [comment]
https://github.com/ValveSoftware/steam-runtime/issues/688#issuecomment-2273942307 i tried that work around and it worked as for why it was there was it was required for flatpak to load desktop entries

**Comment by smcv** [comment]
Having `/var/lib/flatpak/exports/share` as an item in your `XDG_DATA_DIRS` is necessary for Flatpak users. It shouldn't trigger this issue, as far as I know.

Having `/var/lib` as an item in your `XDG_DATA_DIRS` is unusual, and that's what's triggering this issue. This shouldn't be necessary to make `.desktop` files load, unless you have `/var/lib/applications/*.desktop`?

**Comment by smcv** [comment]
> We should make the container runtime more robust against this, by making it refuse to do things that won't work

This is in progress, and will hopefully be part of a future beta.

**Comment by smcv** [comment]
> For the copy of the container runtime that is used for `steamwebhelper`, the same change is expected to be part of the next major update to the [Steam client beta](https://steamcommunity.com/groups/SteamClientBeta/announcements).

This is is included in the 2024-10-02 beta (1727910361).

**Comment by kisak-valve** [comment]
Closing per the last comment.
