### ISSUE TITLE
Proton versions past 7.0 don't work

### ISSUE THREAD

**Issue by NitroDIon** [ValveSoftware/steam-runtime#692]
So I went to go play a game that was using proton 9.0 and found that it wouldn't even launch it would just start and then immediately close and did some further test and found that this happened with every game in my library and found that with some more testing anything past version 7.0 wouldn't work even though this wasn't an issue a few days ago and I also made sure there wasn't any sort of updates that could have broke this over that time. As for my system it has an i7-10700k, RTX 3050, 16GB DDR4 and my graphics drivers are nvidia 550.107.02 and i'm running Linux Mint 21.3.
System Hardware Info: https://gist.github.com/NitroDIon/bc580b6815d1bef1b04fc163fb03b0b8
Steam Runtime System Info: https://gist.github.com/NitroDIon/bbc3aec0f921ff2fda9b263854aac068

**Comment by kisak-valve** [comment]
`<3>pressure-vessel-wrap[14429]: E: Could not create copy "./manifest.dpkg" from "/media/Shared_Drive/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/sniper_platform_0.20240806.97927/files/./manifest.dpkg" into "/media/Shared_Drive/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/var/tmp-6183T2/usr": renameat: Input/output error` in your runtime diagnostics makes this more of a Steam runtime issue than a Proton issue.

What filesystem are you using with /media/Shared_Drive/SteamLibrary?

This looks similar to #661 / https://github.com/ValveSoftware/steam-runtime/issues/587#issuecomment-1540095422.

**Comment by NitroDIon** [comment]
It's NTFS which sounds like I'm gonna have to try and uninstall it and reinstall on my home drive but what is a bit weird is that this only became an issue today and I've been running this system the exact same way for 2 years now

**Comment by NitroDIon** [comment]
I managed to reinstall the runtime (thankfully windows let me uninstall it) and now it all works thanks for the the help @kisak-valve i would never had thought the runtime would have been causing this issue really but guess i still have some things to learn.
