### ISSUE TITLE
Danganronpa 2: Goodbye Despair (413420) no longer launches under Steam Linux Runtime 1.0

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/steam-runtime#711]
#### Your system information

* Steam Runtime Version: 0.20241024.105847
* Distribution (e.g. Ubuntu 18.04): SteamOS
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/): https://gist.github.com/matte-schwartz/2eebed953c413dacc8aa887c0db1f02a
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime 1.0 (Scout)
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`? 
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20240806.0			# Overall version number
LD_LIBRARY_PATH	-	scout	-	# see ~/.steam/root/ubuntu12_32/steam-runtime/version.txt
scripts	0.20240806.0			# from steam-runtime-tools
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20241008.104209			# Overall version number
pressure-vessel	0.20240916.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20240916.0			# from steam-runtime-tools
soldier	0.20241008.104209	soldier	0.20241008.104209	# soldier_platform_0.20241008.104209/
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20241008.104210			# Overall version number
pressure-vessel	0.20240916.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20240916.0			# from steam-runtime-tools
sniper	0.20241008.104210	sniper	0.20241008.104210	# sniper_platform_0.20241008.104210/
```

#### Please describe your issue in as much detail as possible:
Danganronpa 2: Goodbye Despair (413420) closes after ~2 seconds after launching, before ever reaching the game. I tested on two separate systems (Steam Deck on SteamOS, ROG Ally on CachyOS) with fresh game installations, and both display the same behavior. 

Checking my journal logs shows:
```
Nov 15 22:04:29 steamdeck-oled steam[19782]: /run/media/deck/b74cd95d-a0ba-4c53-ae7f-707b32b0cef9/steamapps/common/Danganronpa 2 Goodbye Despair/Launcher: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by ./lib/librt.so.1)
```

The game does launch if I override Valve's default selection and instead choose to run the game under Proton.

#### Steps for reproducing this issue:

1. Launch Danganronpa 2: Goodbye Despair

**Comment by smcv** [comment]
According to https://steamdb.info/depot/413423/ the game has its own bundled copies of *lots* of libraries, most of which it should not.

In particular, the one that is causing the startup failure you are observing is that games released on Steam must not include their own `librt.so.1` (which is part of glibc): that makes them incompatible with any version of glibc other than the one the developer was using. Please report this to the game's developer/publisher as a game bug.

Deleting `lib/librt.so.1` would probably be a successful workaround for this (untested).

**Comment by matte-schwartz** [comment]
Sure, I can send a link to this issue to the developer's support email when I find one. 

Deleting `lib/librt.so.1` does get me a bit farther and shows the game launcher, but the launcher itself is bugged and appears without any text.

For now it seems best to just launch this game under Proton where both the launcher and the game appear to be working, but this needs further validation. In the meantime, perhaps it's worth re-evaluating it as a Steam Deck Verified title?

**Comment by smcv** [comment]
> Deleting `lib/librt.so.1` does get me a bit farther and shows the game launcher, but the launcher itself is bugged and appears without any text.

That also sounds unwelcome. Are there any interesting messages logged in `~/.steam/steam/logs/console-linux.txt` when attempting to launch this game?

> For now it seems best to just launch this game under Proton where both the launcher and the game appear to be working, but this needs further validation. In the meantime, perhaps it's worth re-evaluating it as a Steam Deck Verified title?

Neither of those is under my control, but I would be inclined to agree on both (preferring Proton for this particular title as a likely workaround, and re-evaluating its Steam Deck verified status).

I suspect that this game may have coincidentally worked on an older version of SteamOS (because of implementation details of the version of glibc in use being "close enough" to the expectations of the `librt.so.1` that it bundles), but then regressed after a more recent SteamOS update that upgraded the glibc version to one that is not compatible with the bundled `librt.so.1`.

**Comment by matte-schwartz** [comment]
Great, I appreciate the update!

I'll leave this open for the time being for tracking purposes, but I'll let you make the call on when this is closeable.

**Comment by matte-schwartz** [comment]
closed with https://steamdb.info/app/413420/history/?changeid=26430120
