### ISSUE TITLE
Tomb Raider failed to start because of wrong lib folder

### ISSUE THREAD

**Issue by guoyunhe** [ValveSoftware/steam-runtime#714]
#### Your system information

* Steam Runtime Version: 1.0
* Distribution (e.g. Ubuntu 18.04): openSUSE Tumbleweed
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/): https://gist.github.com/guoyunhe/e726f73b10a9b72d3f9fe766c5d04c7e
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`?
```
#Name   Version         Runtime Runtime_Version Comment
depot   0.20240806.0                    # Overall version number
LD_LIBRARY_PATH -       scout   -       # see ~/.steam/root/ubuntu12_32/steam-runtime/version.txt
scripts 0.20240806.0                    # from steam-runtime-tools
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name   Version         Runtime Runtime_Version Comment
depot   0.20241008.104209                       # Overall version number
pressure-vessel 0.20240916.0    scout           # pressure-vessel-bin.tar.gz
scripts 0.20240916.0                    # from steam-runtime-tools
soldier 0.20241008.104209       soldier 0.20241008.104209       # soldier_platform_0.20241008.104209/
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`?
```
#Name   Version         Runtime Runtime_Version Comment
depot   0.20241008.104210                       # Overall version number
pressure-vessel 0.20240916.0    scout           # pressure-vessel-bin.tar.gz
scripts 0.20240916.0                    # from steam-runtime-tools
sniper  0.20241008.104210       sniper  0.20241008.104210       # sniper_platform_0.20241008.104210/
```

#### Please describe your issue in as much detail as possible:

I believe that I have been playing this game with no problem two year ago. Recently I want to pick up this game again. However, it failed to start.

After some research, I found that the game install *.so files in wrong folder:

```
steamapps/common/Tomb Raider/lib/i686/
```

Which should have been:

```
steamapps/common/Tomb Raider/lib/
```

This is a very old game and hasn't been updated for a long time. I don't know if the game vendor should fix it or Steam Linux Runtime can be compatible with such a lib folder.

Currently my work around is:

```
cd "steamapps/common/Tomb Raider/lib/"
cp i686/* .
```

#### Steps for reproducing this issue:

1. Install Tomb Raider
2. Launch Tomb Raider
3. Enter the game

**Comment by kisak-valve** [comment]
Hello @guoyunhe, this issue is already being tracked at #613. Closing as a duplicate.

**Comment by guoyunhe** [comment]
@kisak-valve I saw #613 is marked as "wont-fix". Does it mean this problem will never get solved?
