### ISSUE TITLE
Steam Runtime creates import error for OpenCV in Python

### ISSUE THREAD

**Issue by naveenT1010** [ValveSoftware/steam-runtime#73]
When I try to run Unreal Engine with steamVR runtime, and I import OpenCV with Python in there, I get import error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libhogweed.so.4: undefined symbol: __gmpn_cnd_sub_n
```
I dont get this error if I am not using steam runtime.

#### Steps for reproducing this issue:
The simplest way to reproduce this error without Unreal Engine is
1.  run python with steamVR runtime:
```bash
$ .steam/steam/ubuntu12_32/steam-runtime/run.sh python
```
2. And then try to import cv2 (OpenCV library)
```python
import cv2
```

**Comment by kisak-valve** [comment]
Hello @naveenT1010, this error message is telling you that the steam runtime's libgmp is too old to be used with the system-built libhogweed.so.4. A couple choices are either move the steam runtime variant out of the way so that it falls through to the system variant of libgmp or LD_PRELOAD the system variant.

**Comment by naveenT1010** [comment]
Hi @kisak-valve can you please help me with the solution, I tried:
```bash
$ LD_PRELOAD='/usr/lib/x86_64-linux-gnu/libgmp.so.10' .steam/steam/ubuntu12_32/steam-runtime/run.sh python
```
but this is giving a new import error
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: p11_kit_uri_get_pin_value
```

**Comment by kisak-valve** [comment]
Looks simular to the other library, except with libp11-kit.so.

**Comment by naveenT1010** [comment]
Where can I find the steam's libgmp to move out of the path?

**Comment by kisak-valve** [comment]
Take a look in `~/.steam/steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu` for the 64 bit variant.

**Comment by naveenT1010** [comment]
Hi @kisak-valve I got it working with this:
```bash
LD_PRELOAD='/usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 /usr/lib/x86_64-linux-gnu/libstdc++.so.6' .steam/steam/ubuntu12_32/steam-runtime/run.sh python
```
Thanks alot for your help. :smiley: 
You can close this now.

**Comment by kisak-valve** [comment]
Closing per the last comment.
