### ISSUE TITLE
libstdc++ incompatible with updated systems.

### ISSUE THREAD

**Issue by Nolan-O** [ValveSoftware/steam-runtime#75]
The packaged version of libsdtc++ is incompatible with things using newer versions of libstdc++; the only specific case I know of right now are the mesa drivers. The result is that users of the mesa drivers cannot directly launch steam apps unless they are launching them through steam itself. This issue began occurring in the latest sdk update, and is confirmed by the fact that simply removing the libraries from the runtime allows non-steam booting to work.

Relevant issue: https://github.com/ValveSoftware/source-sdk-2013/issues/431

**Comment by kisak-valve** [comment]
Hello @Nolan-O, this issue is already being tracked at #34 and https://github.com/ValveSoftware/steam-for-linux/issues/4768. Closing as a duplicate.
