### ISSUE TITLE
Make all libraries Multi-Arch: same

### ISSUE THREAD

**Issue by smcv** [ValveSoftware/steam-runtime#78]
I've recently been experimenting with building a Flatpak runtime from the Steam Runtime packages (#54) so that it can be used to run the Steam client as a Flatpak app. Because the Steam client and some games are 32-bit-only, but some other games are 64-bit-only, the 64-bit version will need to be run in a runtime with multilib (`lib`, `lib64`) or multiarch (`lib/i386-linux-gnu`, `lib/x86_64-linux-gnu`) so that all game-related libraries can be parallel-installed in both 32- and 64-bit versions.

At the moment, the Steam Runtime uses separate `amd64/` and `i386/` pseudo-chroots and enables them with `LD_LIBRARY_PATH`, but that's a bit of a hack: they both contain identical `etc/` and `include/`, and nearly-identical `usr/share/`, differing only in non-functional files in `usr/share/doc/`.

No libraries in the Steam Runtime write directly to `lib` (which would collide between architectures), only to `lib/*-linux-gnu`. There are only a few libraries that write to `usr/lib` and not `usr/lib/*-linux-gnu`, namely:

* `libappindicator`
* `libindicator`
* `libvpx`
* `network-manager`
* `tbb`

So patching those 5 libraries is sufficient to make everything multi-arch-friendly, such that all the relevant libraries for both amd64 and i386 can be installed in a single chroot.

All of those libraries were subsequently made multi-arch-friendly in Debian and Ubuntu, so all that's needed here is to backport the relevant changes.

This change would also make it possible for the Steam client itself to merge `amd64/` and `i386/` into a single pseudo-chroot, but I have not tested this. `nvidia-cg-toolkit` would have to be excluded (#77) or installed for only one of the two architectures. Similarly, `zenity` would have to be installed for only one of the two architectures, presumably `i386` for widest applicability - or just omitted, because the Steam client depends on the host system to provide `zenity` anyway?

**Comment by smcv** [comment]
Here are dget'able source packages which implement this:

* https://people.collabora.com/~smcv/expires-201710/libappindicator_0.4.92-0ubuntu1.1+steamrt1.dsc
* https://people.collabora.com/~smcv/expires-201710/libindicator_0.5.0-0ubuntu1+steamrt1.dsc
* https://people.collabora.com/~smcv/expires-201710/libvpx_1.0.0-2.dsc
* https://people.collabora.com/~smcv/expires-201710/network-manager_0.9.4.0-0ubuntu4.2+steamrt2.dsc
* https://people.collabora.com/~smcv/expires-201710/tbb_4.0+r233-1+steamrt1.dsc

libvpx is a slightly newer version from Debian; the others are backports.

Diffs since previous versions of the relevant packages for review (cc @fledermaus):

* https://people.collabora.com/~smcv/expires-201710/libappindicator_0.4.92-0ubuntu1.1+steamrt1.diff.txt
* https://people.collabora.com/~smcv/expires-201710/libindicator_0.5.0-0ubuntu1+steamrt1.diff.txt
* https://people.collabora.com/~smcv/expires-201710/libvpx_1.0.0-2.diff.txt
* https://people.collabora.com/~smcv/expires-201710/network-manager_0.9.4.0-0ubuntu4.2+steamrt2.diff.txt
* https://people.collabora.com/~smcv/expires-201710/tbb_4.0+r233-1+steamrt1.diff.txt

**Comment by smcv** [comment]
There's one more to do: libvulkan1 also needs multiarchifying.

**Comment by smcv** [comment]
* https://people.collabora.com/~smcv/expires-201710/tbb_4.0+r233-1+steamrt2.dsc
* https://people.collabora.com/~smcv/expires-201710/vulkan_1.0.8.0+dfsg1-0ubuntu1+steamrt2.dsc

Debdiffs:

* https://people.collabora.com/~smcv/expires-201710/tbb_4.0+r233-1+steamrt2.diff.txt
* https://people.collabora.com/~smcv/expires-201710/vulkan_1.0.8.0+dfsg1-0ubuntu1+steamrt2.diff.txt

**Comment by fledermaus** [comment]
These seem reasonable - the gir files are not coinstallable but as discussed offline we don't need them to be, so that should be fine.

**Comment by smcv** [comment]
All these packages have been fixed in OBS, and should be in the next push to the public apt repositories.
