### ISSUE TITLE
Make Essential executables usrmerge-friendly

### ISSUE THREAD

**Issue by smcv** [ValveSoftware/steam-runtime#79]
While experimenting with building a Flatpak runtime from the Steam Runtime packages, I found that I had to work around some Essential packages in Ubuntu precise that ship both `/bin/foo` and /usr/bin/foo`:

* `coreutils` (`touch`)
* `debianutils` (`which`)

In later Debian/Ubuntu versions, those packages have been changed to ship only `/bin/foo`, and create a `/usr/bin/foo` symlink in `postinst` if it doesn't already exist.

It would be more straightforward to generate Flatpak runtimes from the Steam Runtime packages if the `steamrt` apt repository contained versions of `coreutils` and `debianutils` that have that change applied. This won't affect current Steam games, because the Steam Runtime doesn't include `coreutils` or `debianutils` anyway.

**Comment by smcv** [comment]
Source packages that implement the proposed change:

* https://people.collabora.com/~smcv/expires-201710/coreutils_8.13-3ubuntu3.3+steamrt1+srt1.dsc
* https://people.collabora.com/~smcv/expires-201710/debianutils_4.2.1ubuntu2+steamrt1+srt1.dsc

Diffs for review (cc @fledermaus):

* https://people.collabora.com/~smcv/expires-201710/coreutils_8.13-3ubuntu3.3+steamrt1+srt1.diff.txt
* https://people.collabora.com/~smcv/expires-201710/debianutils_4.2.1ubuntu2+steamrt1+srt1.diff.txt

**Comment by smcv** [comment]
In the SDK, kbd, less and libattr1-dev have the same issue.

**Comment by smcv** [comment]
More source packages:

* https://people.collabora.com/~smcv/expires-201710/attr_2.4.46-5ubuntu1+steamrt1.dsc
* https://people.collabora.com/~smcv/expires-201710/kbd_1.15.2-3ubuntu4+steamrt1.dsc
* https://people.collabora.com/~smcv/expires-201710/less_444-1ubuntu1+steamrt1.dsc

Debdiffs:

* https://people.collabora.com/~smcv/expires-201710/attr_2.4.46-5ubuntu1+steamrt1.diff.txt
* https://people.collabora.com/~smcv/expires-201710/kbd_1.15.2-3ubuntu4+steamrt1.diff.txt
* https://people.collabora.com/~smcv/expires-201710/less_444-1ubuntu1+steamrt1.diff.txt

**Comment by fledermaus** [comment]
debdiffs look sane, couldn't see any causes for concern there (other than pre-existing weirdness wrt lib vs libexec in packages, but that's no more broken than it was before).

**Comment by smcv** [comment]
All these packages have been fixed in OBS, and should be in the next push to the public apt repositories.
