### ISSUE TITLE
Can't build chroot on Ubuntu 17.10

### ISSUE THREAD

**Issue by codecat** [ValveSoftware/steam-runtime#81]
I get the following output when trying to build the amd64 chroot:

```
Bootstrap the chroot...
I: Retrieving InRelease 
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
E: Release signed by unknown key (key id 40976EAF437D05B5)
```

I tried adding the key to apt using:

```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
```

But this didn't seem to help. Any ideas?

**Comment by PeteLewisUnity** [comment]
I added `-no-check-gpg` to the `debootstrap` call and that seemed to unblock me. Not sure if this is the "best" solution but it is the simplest :)

**Comment by codecat** [comment]
That's definitely not the most secure solution, that's for sure :)

**Comment by PeteLewisUnity** [comment]
I absolutely agree. Use at your own risk :)

**Comment by mdiluz** [comment]
This still also occurs on Ubuntu 18.04, so would be good to resolve by default

**Comment by Plagman** [comment]
Do you want to send a merge request for that change? Seems harmless in isolation, and would get us closer to a real fix for this.

**Comment by PeteLewisUnity** [comment]
@Plagman PR for your review: https://github.com/ValveSoftware/steam-runtime/pull/85

**Comment by jwyatt-feral** [comment]
The precise packages are signed using a 1024D keys - these have been removed per https://bugs.launchpad.net/ubuntu/+source/ubuntu-keyring/+bug/1363482. Because they have been added to the ubuntu-archived-removed-keys keyring, attempting to add them via apt-key doesn't actually add them to the keyring.

**Comment by h1z1** [comment]
Curious given Valve includes their own key already why would this not be packaged in their official apt repo?

**Comment by redmcg** [comment]
> attempting to add them via apt-key doesn't actually add them to the keyring.

This is correct - `apt-key`, by default, adds the key to the keyring found at `/etc/apt/trusted.gpg`.

`debootstrap`, by default, will look in the keyring defined by the relevant distribution script at `/usr/share/debootstrap/scripts`. For example, on bionic, the keyring used is located at `/usr/share/keyrings/ubuntu-archive-keyring.gpg`:
```
$ grep keyring /usr/share/debootstrap/scripts/bionic 
keyring /usr/share/keyrings/ubuntu-archive-keyring.gpg
```
The solution provided by @jwyatt-feral in https://github.com/FeralInteractive/steam-runtime/commit/830a5afc62bfe262402a16d7cc8e4ac7fcd463c1 is what I think is the best solution (i.e. create and use a temp keyring).

**Comment by smcv** [comment]
I think a better still solution is to commit a copy of the known-good public key to this git repo, so that the key we trust is completely unambiguous (#100).
