### ISSUE TITLE
Please provide a 64-bit package for macOS

### ISSUE THREAD

**Issue by ShikiSuen** [ValveSoftware/steam-runtime#86]
Please provide a 64-bit Steam package this year, so that those of us on macOS don't have to install a bootcamp to run Steam when macOS 10.14 comes out in this October.

Reference: https://support.apple.com/en-ca/HT208436

**Comment by kisak-valve** [comment]
Again, please use the forums for feature requests for the Steam for Mac client. This issue tracker is for issues with the set of linux runtime libraries provided by the Steam for Linux client.

Closing as out-of-scope.

**Comment by ShikiSuen** [comment]
Forums are filled with idiots flooding your thread with their prejudices to the necessity of macOS 64bit client. https://steamcommunity.com/groups/SteamClientBeta/discussions/1/1354868867708319045/

**Comment by ShikiSuen** [comment]
If I were you, it is not bad to forward the opinion to the one who is responsible to the macOS 64-bit Steam client in your company.
