### ISSUE TITLE
Update to newer than Ubuntu 12

### ISSUE THREAD

**Issue by Lucretia** [ValveSoftware/steam-runtime#95]
As can be seen here, [Precise Pangolin 12.04](https://wiki.ubuntu.com/Releases), is 4 years old, please update to a newer OS, this will then get some newer base packages.

**Comment by nanonyme** [comment]
This will probably never happen. Games depend on 12.04 libraries

**Comment by nanonyme** [comment]
Not probable without a full redesign of how Steam runtime works. Games need these older libraries to run. They are closed source and cannot be recompiled

**Comment by TTimo** [comment]
Correct.
